/**
 * Bina Aşamaları Görsel Sistemi — Semantik Manifest ve Resolver
 * Tek doğruluk kaynağı (Single Source of Truth).
 */

export type BinaVisualMode =
  | "site-process"
  | "installed-component"
  | "technical-cutaway"
  | "project-visual";

export interface BinaVisualAsset {
  nodeId: string;
  slugPath: string;
  card: string;
  hero?: string;
  diagram?: string;
  altTr: string;
  visualPurpose: string;
  mode: BinaVisualMode;
  objectPosition?: string;
  version: number;
}

export const BINA_VISUALS: Record<string, BinaVisualAsset> = {
  "proje-hazirlik": {
    nodeId: "proje-hazirlik",
    slugPath: "proje-hazirlik",
    card: "/bina-asamalari/topics/proje-hazirlik.svg",
    altTr: "Proje & İzinler — Tasarım koordinasyonu, mimari maket ve çizim paftaları genel görünümü",
    visualPurpose: "Kullanıcı bu görsele baktığında tasarım koordinasyonu, mimari maket ve çizim paftaları genel görünümü durumunu net olarak anlamalı.",
    mode: "project-visual",
    version: 1,
  },
  "proje-hazirlik/mimari-proje": {
    nodeId: "mimari-proje",
    slugPath: "proje-hazirlik/mimari-proje",
    card: "/bina-asamalari/topics/mimari-proje.svg",
    altTr: "Mimari Proje — Mimari plan ve kesit geometrileri ile temiz bina kütlesi ilişkisi",
    visualPurpose: "Kullanıcı bu görsele baktığında mimari plan ve kesit geometrileri ile temiz bina kütlesi ilişkisi durumunu net olarak anlamalı.",
    mode: "project-visual",
    version: 1,
  },
  "proje-hazirlik/statik-proje": {
    nodeId: "statik-proje",
    slugPath: "proje-hazirlik/statik-proje",
    card: "/bina-asamalari/topics/statik-proje.svg",
    altTr: "Statik Proje — Taşıyıcı sistem şeması, kolon-kiriş aksları ve 3D yapısal çerçeve modeli",
    visualPurpose: "Kullanıcı bu görsele baktığında taşıyıcı sistem şeması, kolon-kiriş aksları ve 3d yapısal çerçeve modeli durumunu net olarak anlamalı.",
    mode: "project-visual",
    version: 1,
  },
  "proje-hazirlik/tesisat-projesi": {
    nodeId: "tesisat-projesi",
    slugPath: "proje-hazirlik/tesisat-projesi",
    card: "/bina-asamalari/topics/tesisat-projesi.svg",
    altTr: "Tesisat Projesi — Bina kesitinde mekanik tesisat boru güzergahları ve şaft koordinasyonu",
    visualPurpose: "Kullanıcı bu görsele baktığında bina kesitinde mekanik tesisat boru güzergahları ve şaft koordinasyonu durumunu net olarak anlamalı.",
    mode: "project-visual",
    version: 1,
  },
  "proje-hazirlik/elektrik-projesi": {
    nodeId: "elektrik-projesi",
    slugPath: "proje-hazirlik/elektrik-projesi",
    card: "/bina-asamalari/topics/elektrik-projesi.svg",
    altTr: "Elektrik Projesi — Elektrik tava hatları, ana dağıtım ve aydınlatma linyesi proje koordinasyonu",
    visualPurpose: "Kullanıcı bu görsele baktığında elektrik tava hatları, ana dağıtım ve aydınlatma linyesi proje koordinasyonu durumunu net olarak anlamalı.",
    mode: "project-visual",
    version: 1,
  },
  "proje-hazirlik/yapi-ruhsati": {
    nodeId: "yapi-ruhsati",
    slugPath: "proje-hazirlik/yapi-ruhsati",
    card: "/bina-asamalari/topics/yapi-ruhsati.svg",
    altTr: "Yapı Ruhsatı — Onaylı proje setleri ve inşaata başlama hazırlığı bağlamı",
    visualPurpose: "Kullanıcı bu görsele baktığında onaylı proje setleri ve inşaata başlama hazırlığı bağlamı durumunu net olarak anlamalı.",
    mode: "project-visual",
    version: 1,
  },
  "kazi-temel": {
    nodeId: "kazi-temel",
    slugPath: "kazi-temel",
    card: "/bina-asamalari/topics/kazi-temel.svg",
    altTr: "Kazı & Temel — Kazı platformu, iksa sistemleri ve temel hazırlığının genel saha bağlamı",
    visualPurpose: "Kullanıcı bu görsele baktığında kazı platformu, iksa sistemleri ve temel hazırlığının genel saha bağlamı durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/zemin-etudu": {
    nodeId: "zemin-etudu",
    slugPath: "kazi-temel/zemin-etudu",
    card: "/bina-asamalari/topics/zemin-etudu.svg",
    altTr: "Zemin Etüdü — Sondaj makinesi, karot numune sandıkları ve zemin araştırma operasyonu",
    visualPurpose: "Kullanıcı bu görsele baktığında sondaj makinesi, karot numune sandıkları ve zemin araştırma operasyonu durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/hafriyat": {
    nodeId: "hafriyat",
    slugPath: "kazi-temel/hafriyat",
    card: "/bina-asamalari/topics/hafriyat.svg",
    altTr: "Hafriyat — Ekskavatörün temel çukurunda kademeli kazı yapması ve kamyon yüklemesi",
    visualPurpose: "Kullanıcı bu görsele baktığında ekskavatörün temel çukurunda kademeli kazı yapması ve kamyon yüklemesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/iksa-sistemi": {
    nodeId: "iksa-sistemi",
    slugPath: "kazi-temel/iksa-sistemi",
    card: "/bina-asamalari/topics/iksa-sistemi.svg",
    altTr: "İksa Sistemi — Derin kazı çukurunu tutan betonarme iksa perdesi ve zemin katmanı ilişkisi",
    visualPurpose: "Kullanıcı bu görsele baktığında derin kazı çukurunu tutan betonarme iksa perdesi ve zemin katmanı ilişkisi durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "kazi-temel/iksa-sistemi/fore-kazik": {
    nodeId: "fore-kazik",
    slugPath: "kazi-temel/iksa-sistemi/fore-kazik",
    card: "/bina-asamalari/topics/fore-kazik.svg",
    altTr: "Fore Kazık — Döner delgi makinesi (fore kazık makinesi) ve donatı kafesi yerleşimi",
    visualPurpose: "Kullanıcı bu görsele baktığında döner delgi makinesi (fore kazık makinesi) ve donatı kafesi yerleşimi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/iksa-sistemi/ankrajli-iksa": {
    nodeId: "ankrajli-iksa",
    slugPath: "kazi-temel/iksa-sistemi/ankrajli-iksa",
    card: "/bina-asamalari/topics/ankrajli-iksa.svg",
    altTr: "Ankrajlı İksa — İksa perdesi yüzeyindeki çelik ankraj başlıkları ve zemine eğik uzanan kök ankrajlar",
    visualPurpose: "Kullanıcı bu görsele baktığında i̇ksa perdesi yüzeyindeki çelik ankraj başlıkları ve zemine eğik uzanan kök ankrajlar durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "kazi-temel/iksa-sistemi/palplans": {
    nodeId: "palplans",
    slugPath: "kazi-temel/iksa-sistemi/palplans",
    card: "/bina-asamalari/topics/palplans.svg",
    altTr: "Palplanş — Kilitli çelik palplanş perdelerinin vibro-çekiç ile zemine çakılması",
    visualPurpose: "Kullanıcı bu görsele baktığında kilitli çelik palplanş perdelerinin vibro-çekiç ile zemine çakılması durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/temel-turleri": {
    nodeId: "temel-turleri",
    slugPath: "kazi-temel/temel-turleri",
    card: "/bina-asamalari/topics/temel-turleri.svg",
    altTr: "Temel Türleri — Tekil sömel, sürekli temel ve radye plağın zemin üzerindeki izometrik yapısal kesiti",
    visualPurpose: "Kullanıcı bu görsele baktığında tekil sömel, sürekli temel ve radye plağın zemin üzerindeki izometrik yapısal kesiti durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "kazi-temel/temel-turleri/radye-temel": {
    nodeId: "radye-temel",
    slugPath: "kazi-temel/temel-turleri/radye-temel",
    card: "/bina-asamalari/topics/radye-temel.svg",
    altTr: "Radye Temel — Geniş alanlı radye temel donatı ağı, sehpa demirleri ve kolon filizleri",
    visualPurpose: "Kullanıcı bu görsele baktığında geniş alanlı radye temel donatı ağı, sehpa demirleri ve kolon filizleri durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/temel-turleri/grobeton": {
    nodeId: "grobeton",
    slugPath: "kazi-temel/temel-turleri/grobeton",
    card: "/bina-asamalari/topics/grobeton.svg",
    altTr: "Grobeton — Kazılmış temel tabanına temiz grobeton tabakasının serilmesi ve mastarlanması",
    visualPurpose: "Kullanıcı bu görsele baktığında kazılmış temel tabanına temiz grobeton tabakasının serilmesi ve mastarlanması durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/temel-turleri/temel-donati": {
    nodeId: "temel-donati",
    slugPath: "kazi-temel/temel-turleri/temel-donati",
    card: "/bina-asamalari/topics/temel-donati.svg",
    altTr: "Temel Donatısı — Radye temel alt ve üst donatı örgüsü, pas payı takozları ve bağ telleri",
    visualPurpose: "Kullanıcı bu görsele baktığında radye temel alt ve üst donatı örgüsü, pas payı takozları ve bağ telleri durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/temel-turleri/temel-betonlama": {
    nodeId: "temel-betonlama",
    slugPath: "kazi-temel/temel-turleri/temel-betonlama",
    card: "/bina-asamalari/topics/temel-betonlama.svg",
    altTr: "Temel Betonlama — Mobil beton pompası bomu ile temele sürekli taze beton dökümü ve yayılması",
    visualPurpose: "Kullanıcı bu görsele baktığında mobil beton pompası bomu ile temele sürekli taze beton dökümü ve yayılması durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kazi-temel/temel-turleri/temel-su-yalitimi": {
    nodeId: "temel-su-yalitimi",
    slugPath: "kazi-temel/temel-turleri/temel-su-yalitimi",
    card: "/bina-asamalari/topics/temel-su-yalitimi.svg",
    altTr: "Temel Su Yalıtımı — Temel altı ve perde duvar dışındaki bitümlü membran yalıtım katmanının sürekliliği",
    visualPurpose: "Kullanıcı bu görsele baktığında temel altı ve perde duvar dışındaki bitümlü membran yalıtım katmanının sürekliliği durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "kaba-insaat": {
    nodeId: "kaba-insaat",
    slugPath: "kaba-insaat",
    card: "/bina-asamalari/topics/kaba-insaat.svg",
    altTr: "Kaba İnşaat — Betonarme iskeletin yükseldiği şantiye: kolonlar, döşeme kalıpları ve kule vinç",
    visualPurpose: "Kullanıcı bu görsele baktığında betonarme iskeletin yükseldiği şantiye: kolonlar, döşeme kalıpları ve kule vinç durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/kalip-isleri": {
    nodeId: "kalip-isleri",
    slugPath: "kaba-insaat/kalip-isleri",
    card: "/bina-asamalari/topics/kalip-isleri.svg",
    altTr: "Kalıp İşleri — Endüstriyel çelik çerçeveli plywood kalıp panelleri ve teleskopik dikmeler",
    visualPurpose: "Kullanıcı bu görsele baktığında endüstriyel çelik çerçeveli plywood kalıp panelleri ve teleskopik dikmeler durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/kalip-isleri/kolon-kalibi": {
    nodeId: "kolon-kalibi",
    slugPath: "kaba-insaat/kalip-isleri/kolon-kalibi",
    card: "/bina-asamalari/topics/kolon-kalibi.svg",
    altTr: "Kolon Kalıbı — Düşey kolon kalıp paneli, çelik kuşaklar ve şakül ayar payandaları",
    visualPurpose: "Kullanıcı bu görsele baktığında düşey kolon kalıp paneli, çelik kuşaklar ve şakül ayar payandaları durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/kalip-isleri/kiris-kalibi": {
    nodeId: "kiris-kalibi",
    slugPath: "kaba-insaat/kalip-isleri/kiris-kalibi",
    card: "/bina-asamalari/topics/kiris-kalibi.svg",
    altTr: "Kiriş Kalıbı — Kiriş taban ve kanat kalıpları, döşeme bağlantısı ve alt taşıyıcı iskele",
    visualPurpose: "Kullanıcı bu görsele baktığında kiriş taban ve kanat kalıpları, döşeme bağlantısı ve alt taşıyıcı iskele durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/kalip-isleri/doseme-kalibi": {
    nodeId: "doseme-kalibi",
    slugPath: "kaba-insaat/kalip-isleri/doseme-kalibi",
    card: "/bina-asamalari/topics/doseme-kalibi.svg",
    altTr: "Döşeme Kalıbı — Geniş döşeme kalıp platformu, ana ve tali ahşap H20 kirişler ve teleskopik dikmeler",
    visualPurpose: "Kullanıcı bu görsele baktığında geniş döşeme kalıp platformu, ana ve tali ahşap h20 kirişler ve teleskopik dikmeler durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/kalip-isleri/kalip-sokumu": {
    nodeId: "kalip-sokumu",
    slugPath: "kaba-insaat/kalip-isleri/kalip-sokumu",
    card: "/bina-asamalari/topics/kalip-sokumu.svg",
    altTr: "Kalıp Sökümü — Betonu prizini almış kolon veya kiriş kanat kalıbının levyeyle dikkatle sökülmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında betonu prizini almış kolon veya kiriş kanat kalıbının levyeyle dikkatle sökülmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/donati-isleri": {
    nodeId: "donati-isleri",
    slugPath: "kaba-insaat/donati-isleri",
    card: "/bina-asamalari/topics/donati-isleri.svg",
    altTr: "Donatı İşleri — Nervürlü inşaat demirlerinin sahada bağlanması ve donatı hazırlığı",
    visualPurpose: "Kullanıcı bu görsele baktığında nervürlü inşaat demirlerinin sahada bağlanması ve donatı hazırlığı durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/donati-isleri/kolon-donati": {
    nodeId: "kolon-donati",
    slugPath: "kaba-insaat/donati-isleri/kolon-donati",
    card: "/bina-asamalari/topics/kolon-donati.svg",
    altTr: "Kolon Donatısı — Düşey kolon donatı kafesi, sıklaştırılmış etriyeler ve çirozlar",
    visualPurpose: "Kullanıcı bu görsele baktığında düşey kolon donatı kafesi, sıklaştırılmış etriyeler ve çirozlar durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/donati-isleri/kiris-donati": {
    nodeId: "kiris-donati",
    slugPath: "kaba-insaat/donati-isleri/kiris-donati",
    card: "/bina-asamalari/topics/kiris-donati.svg",
    altTr: "Kiriş Donatısı — Kiriş donatı kafesi, alt-üst boyuna demirler, etriyeler ve kolon düğüm noktası",
    visualPurpose: "Kullanıcı bu görsele baktığında kiriş donatı kafesi, alt-üst boyuna demirler, etriyeler ve kolon düğüm noktası durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/donati-isleri/doseme-donati": {
    nodeId: "doseme-donati",
    slugPath: "kaba-insaat/donati-isleri/doseme-donati",
    card: "/bina-asamalari/topics/doseme-donati.svg",
    altTr: "Döşeme Donatısı — Kalıp üzerine serilmiş çift doğrultulu döşeme donatı ağı ve mesnet pilyeleri/donatıları",
    visualPurpose: "Kullanıcı bu görsele baktığında kalıp üzerine serilmiş çift doğrultulu döşeme donatı ağı ve mesnet pilyeleri/donatıları durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/donati-isleri/pas-payi": {
    nodeId: "pas-payi",
    slugPath: "kaba-insaat/donati-isleri/pas-payi",
    card: "/bina-asamalari/topics/pas-payi.svg",
    altTr: "Pas Payı — Donatı demirinin kalıptan mesafesini sağlayan beton veya plastik pas payı takozunun net kesiti",
    visualPurpose: "Kullanıcı bu görsele baktığında donatı demirinin kalıptan mesafesini sağlayan beton veya plastik pas payı takozunun net kesiti durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "kaba-insaat/beton-isleri": {
    nodeId: "beton-isleri",
    slugPath: "kaba-insaat/beton-isleri",
    card: "/bina-asamalari/topics/beton-isleri.svg",
    altTr: "Beton İşleri — Hazır beton transmikseri, beton pompası besleme teknesi ve şantiye döküm hattı",
    visualPurpose: "Kullanıcı bu görsele baktığında hazır beton transmikseri, beton pompası besleme teknesi ve şantiye döküm hattı durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/beton-isleri/beton-sinifi": {
    nodeId: "beton-sinifi",
    slugPath: "kaba-insaat/beton-isleri/beton-sinifi",
    card: "/bina-asamalari/topics/beton-sinifi.svg",
    altTr: "Beton Sınıfı — Standart beton silindir ve küp basınç dayanım numuneleri ve agrega tane dağılım kesiti",
    visualPurpose: "Kullanıcı bu görsele baktığında standart beton silindir ve küp basınç dayanım numuneleri ve agrega tane dağılım kesiti durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "kaba-insaat/beton-isleri/beton-dokumu": {
    nodeId: "beton-dokumu",
    slugPath: "kaba-insaat/beton-isleri/beton-dokumu",
    card: "/bina-asamalari/topics/beton-dokumu.svg",
    altTr: "Beton Dökümü — Beton pompa hortumundan döşeme ve perde kalıbına taze betonun kontrollü serilmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında beton pompa hortumundan döşeme ve perde kalıbına taze betonun kontrollü serilmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/beton-isleri/vibrasyon": {
    nodeId: "vibrasyon",
    slugPath: "kaba-insaat/beton-isleri/vibrasyon",
    card: "/bina-asamalari/topics/vibrasyon.svg",
    altTr: "Vibrasyon — Dökülen taze betona daldırılan mekanik iğne vibratör ve hava kabarcıklarının yüzeye çıkışı",
    visualPurpose: "Kullanıcı bu görsele baktığında dökülen taze betona daldırılan mekanik iğne vibratör ve hava kabarcıklarının yüzeye çıkışı durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/beton-isleri/kur-islemi": {
    nodeId: "kur-islemi",
    slugPath: "kaba-insaat/beton-isleri/kur-islemi",
    card: "/bina-asamalari/topics/kur-islemi.svg",
    altTr: "Kür İşlemi — Yeni dökülmüş döşeme betonunun çatlamayı önlemek için su jetiyle ıslatılması ve nem kürü",
    visualPurpose: "Kullanıcı bu görsele baktığında yeni dökülmüş döşeme betonunun çatlamayı önlemek için su jetiyle ıslatılması ve nem kürü durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/beton-isleri/beton-testi": {
    nodeId: "beton-testi",
    slugPath: "kaba-insaat/beton-isleri/beton-testi",
    card: "/bina-asamalari/topics/beton-testi.svg",
    altTr: "Beton Testleri — Yapı laboratuvarında hidrolik pres cihazı arasına yerleştirilmiş beton küp basınç testi",
    visualPurpose: "Kullanıcı bu görsele baktığında yapı laboratuvarında hidrolik pres cihazı arasına yerleştirilmiş beton küp basınç testi durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "kaba-insaat/duvar-orme": {
    nodeId: "duvar-orme",
    slugPath: "kaba-insaat/duvar-orme",
    card: "/bina-asamalari/topics/duvar-orme.svg",
    altTr: "Duvar Örme — İskelet arasında duvarda harç yatağı üzerine blok yerleştirme ve şakül/ip kontrolü",
    visualPurpose: "Kullanıcı bu görsele baktığında i̇skelet arasında duvarda harç yatağı üzerine blok yerleştirme ve şakül/ip kontrolü durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/duvar-orme/tugla-duvar": {
    nodeId: "tugla-duvar",
    slugPath: "kaba-insaat/duvar-orme/tugla-duvar",
    card: "/bina-asamalari/topics/tugla-duvar.svg",
    altTr: "Tuğla Duvar — Düzgün derzli kırmızı delikli pişmiş kil tuğla duvar örgüsü ve harç birleşimi",
    visualPurpose: "Kullanıcı bu görsele baktığında düzgün derzli kırmızı delikli pişmiş kil tuğla duvar örgüsü ve harç birleşimi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/duvar-orme/ytong-gazbeton": {
    nodeId: "ytong-gazbeton",
    slugPath: "kaba-insaat/duvar-orme/ytong-gazbeton",
    card: "/bina-asamalari/topics/ytong-gazbeton.svg",
    altTr: "Ytong / Gazbeton — Beyaz hafif gazbeton blokların ince derz yapıştırıcısı ve dişli mala ile hassas örülmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında beyaz hafif gazbeton blokların ince derz yapıştırıcısı ve dişli mala ile hassas örülmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/duvar-orme/briket": {
    nodeId: "briket",
    slugPath: "kaba-insaat/duvar-orme/briket",
    card: "/bina-asamalari/topics/briket.svg",
    altTr: "Briket / Bims — Gri bims/briket bloklarla dış cephe veya bölme duvar örülmesi ve kilit derzler",
    visualPurpose: "Kullanıcı bu görsele baktığında gri bims/briket bloklarla dış cephe veya bölme duvar örülmesi ve kilit derzler durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/cati-iskeleti": {
    nodeId: "cati-iskeleti",
    slugPath: "kaba-insaat/cati-iskeleti",
    card: "/bina-asamalari/topics/cati-iskeleti.svg",
    altTr: "Çatı İskeleti — Binanın üst katında kalkan duvarlar üzerine oturan üçgen çatı taşıyıcı makas ve aşık karkası",
    visualPurpose: "Kullanıcı bu görsele baktığında binanın üst katında kalkan duvarlar üzerine oturan üçgen çatı taşıyıcı makas ve aşık karkası durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/cati-iskeleti/ahsap-cati": {
    nodeId: "ahsap-cati",
    slugPath: "kaba-insaat/cati-iskeleti/ahsap-cati",
    card: "/bina-asamalari/topics/ahsap-cati.svg",
    altTr: "Ahşap Çatı — Geleneksel emprenye ahşap çatı makası, mertek, aşık bağlantı detayı ve çelik bulonlar",
    visualPurpose: "Kullanıcı bu görsele baktığında geleneksel emprenye ahşap çatı makası, mertek, aşık bağlantı detayı ve çelik bulonlar durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "kaba-insaat/cati-iskeleti/celik-cati": {
    nodeId: "celik-cati",
    slugPath: "kaba-insaat/cati-iskeleti/celik-cati",
    card: "/bina-asamalari/topics/celik-cati.svg",
    altTr: "Çelik Çatı — Geniş açıklıklı çelik kafes makas sistemi, IPE/HEA profilleri ve cıvatalı montaj",
    visualPurpose: "Kullanıcı bu görsele baktığında geniş açıklıklı çelik kafes makas sistemi, ipe/hea profilleri ve cıvatalı montaj durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "kaba-insaat/cati-iskeleti/teras-cati": {
    nodeId: "teras-cati",
    slugPath: "kaba-insaat/cati-iskeleti/teras-cati",
    card: "/bina-asamalari/topics/teras-cati.svg",
    altTr: "Teras Çatı — Düz teras çatıda betonarme döşeme, eğim betonu, su yalıtımı ve ısı yalıtım katman kesiti",
    visualPurpose: "Kullanıcı bu görsele baktığında düz teras çatıda betonarme döşeme, eğim betonu, su yalıtımı ve ısı yalıtım katman kesiti durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "ince-isler": {
    nodeId: "ince-isler",
    slugPath: "ince-isler",
    card: "/bina-asamalari/topics/ince-isler.webp",
    altTr: "İnce İşler — Kaba inşaatı bitmiş gerçek iç mekanda sıva, asma tavan ve zemin kaplama aşamalarının ilerlemesi",
    visualPurpose: "Kullanıcı bu görsele baktığında kaba inşaatı bitmiş gerçek iç mekanda sıva, asma tavan ve zemin kaplama aşamalarının ilerlemesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/siva": {
    nodeId: "siva",
    slugPath: "ince-isler/siva",
    card: "/bina-asamalari/topics/siva.webp",
    altTr: "Sıva — İç mekan tuğla duvar yüzeyine çelik mala ile taze harç sıva uygulaması ve mastarlama",
    visualPurpose: "Kullanıcı bu görsele baktığında i̇ç mekan tuğla duvar yüzeyine çelik mala ile taze harç sıva uygulaması ve mastarlama durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/siva/ic-siva": {
    nodeId: "ic-siva",
    slugPath: "ince-isler/siva/ic-siva",
    card: "/bina-asamalari/topics/ic-siva.svg",
    altTr: "İç Sıva — Oda içinde ano çıtaları arasında iç sıvanın alüminyum mastarla düzeltilmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında oda içinde ano çıtaları arasında iç sıvanın alüminyum mastarla düzeltilmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/siva/dis-siva": {
    nodeId: "dis-siva",
    slugPath: "ince-isler/siva/dis-siva",
    card: "/bina-asamalari/topics/dis-siva.svg",
    altTr: "Dış Sıva — Bina dış cephesinde şantiye iskelesi üzerinde dış cephe kaba ve ince sıva uygulaması",
    visualPurpose: "Kullanıcı bu görsele baktığında bina dış cephesinde şantiye iskelesi üzerinde dış cephe kaba ve ince sıva uygulaması durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/siva/alci-siva": {
    nodeId: "alci-siva",
    slugPath: "ince-isler/siva/alci-siva",
    card: "/bina-asamalari/topics/alci-siva.svg",
    altTr: "Alçı Sıva — Duvara son kat perdah alçısı uygulaması ve saten pürüzsüzlüğünde beyaz yüzey",
    visualPurpose: "Kullanıcı bu görsele baktığında duvara son kat perdah alçısı uygulaması ve saten pürüzsüzlüğünde beyaz yüzey durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/alcipan": {
    nodeId: "alcipan",
    slugPath: "ince-isler/alcipan",
    card: "/bina-asamalari/topics/alcipan.webp",
    altTr: "Alçıpan & Asma Tavan — Galvaniz çelik C-U profilleri, taşyünü yalıtım dolgusu ve alçıpan levha montaj ilişkisi",
    visualPurpose: "Kullanıcı bu görsele baktığında galvaniz çelik c-u profilleri, taşyünü yalıtım dolgusu ve alçıpan levha montaj ilişkisi durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "ince-isler/alcipan/bolme-duvar": {
    nodeId: "bolme-duvar",
    slugPath: "ince-isler/alcipan/bolme-duvar",
    card: "/bina-asamalari/topics/bolme-duvar.svg",
    altTr: "Bölme Duvar — Oda bölmesinde çift tarafı alçı levha kaplı ses yalıtımlı hafif karkas duvar kesiti",
    visualPurpose: "Kullanıcı bu görsele baktığında oda bölmesinde çift tarafı alçı levha kaplı ses yalıtımlı hafif karkas duvar kesiti durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "ince-isler/alcipan/asma-tavan": {
    nodeId: "asma-tavan",
    slugPath: "ince-isler/alcipan/asma-tavan",
    card: "/bina-asamalari/topics/asma-tavan.svg",
    altTr: "Asma Tavan — Tavana çelik askı telleriyle bağlanan ana/tali taşıyıcı tavan karkası ve levha montajı",
    visualPurpose: "Kullanıcı bu görsele baktığında tavana çelik askı telleriyle bağlanan ana/tali taşıyıcı tavan karkası ve levha montajı durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "ince-isler/zemin-kaplamalari": {
    nodeId: "zemin-kaplamalari",
    slugPath: "ince-isler/zemin-kaplamalari",
    card: "/bina-asamalari/topics/zemin-kaplamalari.svg",
    altTr: "Zemin Kaplamaları — Tesviye edilmiş düzgün şap zemin üzerinde ilerleyen gerçek zemin kaplaması montajı",
    visualPurpose: "Kullanıcı bu görsele baktığında tesviye edilmiş düzgün şap zemin üzerinde ilerleyen gerçek zemin kaplaması montajı durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/zemin-kaplamalari/seramik-kaplama": {
    nodeId: "seramik-kaplama",
    slugPath: "ince-isler/zemin-kaplamalari/seramik-kaplama",
    card: "/bina-asamalari/topics/seramik-kaplama.svg",
    altTr: "Seramik — Zemine dişli mala ile çekilen yapıştırıcı harç üzerine seramik karo yerleşimi ve seviye takozları",
    visualPurpose: "Kullanıcı bu görsele baktığında zemine dişli mala ile çekilen yapıştırıcı harç üzerine seramik karo yerleşimi ve seviye takozları durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/zemin-kaplamalari/parke-kaplama": {
    nodeId: "parke-kaplama",
    slugPath: "ince-isler/zemin-kaplamalari/parke-kaplama",
    card: "/bina-asamalari/topics/parke-kaplama.svg",
    altTr: "Parke — Şilte altlık üzerine kilitli lamine/laminat parke panellerinin klik sistemiyle birbirine geçmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında şilte altlık üzerine kilitli lamine/laminat parke panellerinin klik sistemiyle birbirine geçmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/zemin-kaplamalari/mermer-kaplama": {
    nodeId: "mermer-kaplama",
    slugPath: "ince-isler/zemin-kaplamalari/mermer-kaplama",
    card: "/bina-asamalari/topics/mermer-kaplama.svg",
    altTr: "Mermer / Granit — Geniş formatlı doğal damarlı mermer plakanın harç yatağına teraziyle yerleştirilmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında geniş formatlı doğal damarlı mermer plakanın harç yatağına teraziyle yerleştirilmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/zemin-kaplamalari/epoksi-kaplama": {
    nodeId: "epoksi-kaplama",
    slugPath: "ince-isler/zemin-kaplamalari/epoksi-kaplama",
    card: "/bina-asamalari/topics/epoksi-kaplama.svg",
    altTr: "Epoksi — Beton zemin üzerine çekçek ve rulo ile uygulanan kendiliğinden yayılan parlak epoksi kaplama",
    visualPurpose: "Kullanıcı bu görsele baktığında beton zemin üzerine çekçek ve rulo ile uygulanan kendiliğinden yayılan parlak epoksi kaplama durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/duvar-kaplamalari": {
    nodeId: "duvar-kaplamalari",
    slugPath: "ince-isler/duvar-kaplamalari",
    card: "/bina-asamalari/topics/duvar-kaplamalari.svg",
    altTr: "Duvar Kaplamaları — İç mekan duvar yüzeyinde dekoratif bitiş kaplamasının hazırlanmış alt yüzeyle ilişkisi",
    visualPurpose: "Kullanıcı bu görsele baktığında i̇ç mekan duvar yüzeyinde dekoratif bitiş kaplamasının hazırlanmış alt yüzeyle ilişkisi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/duvar-kaplamalari/fayans": {
    nodeId: "fayans",
    slugPath: "ince-isler/duvar-kaplamalari/fayans",
    card: "/bina-asamalari/topics/fayans.svg",
    altTr: "Fayans — Banyo/ıslak hacim duvarında su yalıtımlı yüzeye dişli harçla döşenen duvar fayansı",
    visualPurpose: "Kullanıcı bu görsele baktığında banyo/ıslak hacim duvarında su yalıtımlı yüzeye dişli harçla döşenen duvar fayansı durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/duvar-kaplamalari/boya": {
    nodeId: "boya",
    slugPath: "ince-isler/duvar-kaplamalari/boya",
    card: "/bina-asamalari/topics/boya.svg",
    altTr: "Boya — Pürüzsüz astarlı duvara boya rulosu ile son kat mat iç cephe boyası uygulaması",
    visualPurpose: "Kullanıcı bu görsele baktığında pürüzsüz astarlı duvara boya rulosu ile son kat mat iç cephe boyası uygulaması durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/duvar-kaplamalari/duvar-kagidi": {
    nodeId: "duvar-kagidi",
    slugPath: "ince-isler/duvar-kaplamalari/duvar-kagidi",
    card: "/bina-asamalari/topics/duvar-kagidi.svg",
    altTr: "Duvar Kağıdı — Tutkallanmış duvara rulo duvar kağıdının hava kabarcığı bırakılmadan spatulayla yapıştırılması",
    visualPurpose: "Kullanıcı bu görsele baktığında tutkallanmış duvara rulo duvar kağıdının hava kabarcığı bırakılmadan spatulayla yapıştırılması durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/kapi-pencere": {
    nodeId: "kapi-pencere",
    slugPath: "ince-isler/kapi-pencere",
    card: "/bina-asamalari/topics/kapi-pencere.svg",
    altTr: "Kapı & Pencere — Duvar açıklığı, kör kasa, pencere/kapı ana kasası, montaj vidası ve poliüretan köpük yalıtımı",
    visualPurpose: "Kullanıcı bu görsele baktığında duvar açıklığı, kör kasa, pencere/kapı ana kasası, montaj vidası ve poliüretan köpük yalıtımı durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "ince-isler/kapi-pencere/dis-kapi": {
    nodeId: "dis-kapi",
    slugPath: "ince-isler/kapi-pencere/dis-kapi",
    card: "/bina-asamalari/topics/dis-kapi.svg",
    altTr: "Dış Kapı — Daire girişinde kör kasaya emniyetli montajı yapılmış sağlam çelik kapı ve pervaz birleşimi",
    visualPurpose: "Kullanıcı bu görsele baktığında daire girişinde kör kasaya emniyetli montajı yapılmış sağlam çelik kapı ve pervaz birleşimi durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "ince-isler/kapi-pencere/ic-kapi": {
    nodeId: "ic-kapi",
    slugPath: "ince-isler/kapi-pencere/ic-kapi",
    card: "/bina-asamalari/topics/ic-kapi.svg",
    altTr: "İç Kapı — Oda duvar boşluğuna monte edilen ahşap iç kapı kasası, pervazı ve menteşe detayı",
    visualPurpose: "Kullanıcı bu görsele baktığında oda duvar boşluğuna monte edilen ahşap iç kapı kasası, pervazı ve menteşe detayı durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "ince-isler/kapi-pencere/pencere": {
    nodeId: "pencere",
    slugPath: "ince-isler/kapi-pencere/pencere",
    card: "/bina-asamalari/topics/pencere.svg",
    altTr: "Pencere — Duvar açıklığında çok odacıklı yalıtımlı PVC/alüminyum pencere doğraması, çift cam ve denizlik",
    visualPurpose: "Kullanıcı bu görsele baktığında duvar açıklığında çok odacıklı yalıtımlı pvc/alüminyum pencere doğraması, çift cam ve denizlik durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "ince-isler/cati-kaplamasi": {
    nodeId: "cati-kaplamasi",
    slugPath: "ince-isler/cati-kaplamasi",
    card: "/bina-asamalari/topics/cati-kaplamasi.svg",
    altTr: "Çatı Kaplaması — Eğimli çatıda ahşap lata, su yalıtım örtüsü, OSB kaplama ve son kat kiremit/metal katman ilişkisi",
    visualPurpose: "Kullanıcı bu görsele baktığında eğimli çatıda ahşap lata, su yalıtım örtüsü, osb kaplama ve son kat kiremit/metal katman ilişkisi durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "ince-isler/cati-kaplamasi/kiremit": {
    nodeId: "kiremit",
    slugPath: "ince-isler/cati-kaplamasi/kiremit",
    card: "/bina-asamalari/topics/kiremit.svg",
    altTr: "Kiremit — Eğimli çatı latası üzerine kilitli kiremitlerin alttan üste doğru düzenli sıralarla dizilmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında eğimli çatı latası üzerine kilitli kiremitlerin alttan üste doğru düzenli sıralarla dizilmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/cati-kaplamasi/membran-cati": {
    nodeId: "membran-cati",
    slugPath: "ince-isler/cati-kaplamasi/membran-cati",
    card: "/bina-asamalari/topics/membran-cati.svg",
    altTr: "Membran — Teras çatıda şalümo aleviyle ısıtılarak zemine yapıştırılan arduvazlı bitümlü membran ruloları",
    visualPurpose: "Kullanıcı bu görsele baktığında teras çatıda şalümo aleviyle ısıtılarak zemine yapıştırılan arduvazlı bitümlü membran ruloları durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "ince-isler/cati-kaplamasi/metal-cati": {
    nodeId: "metal-cati",
    slugPath: "ince-isler/cati-kaplamasi/metal-cati",
    card: "/bina-asamalari/topics/metal-cati.svg",
    altTr: "Metal Çatı — Çatı konstrüksiyonu üzerine kenet robotu ile birleştirilen modern çinko/titanyum kenet metal panel",
    visualPurpose: "Kullanıcı bu görsele baktığında çatı konstrüksiyonu üzerine kenet robotu ile birleştirilen modern çinko/titanyum kenet metal panel durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "tesisat-isleri": {
    nodeId: "tesisat-isleri",
    slugPath: "tesisat-isleri",
    card: "/bina-asamalari/topics/tesisat-isleri.svg",
    altTr: "Tesisat İşleri — Binanın teknik şaftında ve tavanında düzenli ilerleyen mekanik boru ve elektrik tava hatları",
    visualPurpose: "Kullanıcı bu görsele baktığında binanın teknik şaftında ve tavanında düzenli ilerleyen mekanik boru ve elektrik tava hatları durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "tesisat-isleri/sihhi-tesisat": {
    nodeId: "sihhi-tesisat",
    slugPath: "tesisat-isleri/sihhi-tesisat",
    card: "/bina-asamalari/topics/sihhi-tesisat.svg",
    altTr: "Sıhhi Tesisat — Temiz su PPRC borularının kaynak makinesiyle füzyon kaynağı yapılarak döşenmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında temiz su pprc borularının kaynak makinesiyle füzyon kaynağı yapılarak döşenmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "tesisat-isleri/sihhi-tesisat/temiz-su": {
    nodeId: "temiz-su",
    slugPath: "tesisat-isleri/sihhi-tesisat/temiz-su",
    card: "/bina-asamalari/topics/temiz-su.svg",
    altTr: "Temiz Su — Teknik odada temiz su dağıtım kollektörü (manifoldu), vanalar ve hat ayrımı",
    visualPurpose: "Kullanıcı bu görsele baktığında teknik odada temiz su dağıtım kollektörü (manifoldu), vanalar ve hat ayrımı durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "tesisat-isleri/sihhi-tesisat/pis-su": {
    nodeId: "pis-su",
    slugPath: "tesisat-isleri/sihhi-tesisat/pis-su",
    card: "/bina-asamalari/topics/pis-su.svg",
    altTr: "Pis Su — Düşey atık su kolon borusu, çatal ve dirsek bağlantıları ve %2 akış eğimi",
    visualPurpose: "Kullanıcı bu görsele baktığında düşey atık su kolon borusu, çatal ve dirsek bağlantıları ve %2 akış eğimi durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "tesisat-isleri/elektrik-tesisati": {
    nodeId: "elektrik-tesisati",
    slugPath: "tesisat-isleri/elektrik-tesisati",
    card: "/bina-asamalari/topics/elektrik-tesisati.svg",
    altTr: "Elektrik Tesisatı — Tuğla duvar kanalı içine yerleştirilmiş spiral borular, kasa ve buat bağlantıları",
    visualPurpose: "Kullanıcı bu görsele baktığında tuğla duvar kanalı içine yerleştirilmiş spiral borular, kasa ve buat bağlantıları durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "tesisat-isleri/elektrik-tesisati/kablolama": {
    nodeId: "kablolama",
    slugPath: "tesisat-isleri/elektrik-tesisati/kablolama",
    card: "/bina-asamalari/topics/kablolama.svg",
    altTr: "Kablolama — Tavandaki delikli saç kablo tavası içinde düzenli sıralanmış yangına dayanıklı kablo demetleri",
    visualPurpose: "Kullanıcı bu görsele baktığında tavandaki delikli saç kablo tavası içinde düzenli sıralanmış yangına dayanıklı kablo demetleri durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "tesisat-isleri/elektrik-tesisati/pano-montaj": {
    nodeId: "pano-montaj",
    slugPath: "tesisat-isleri/elektrik-tesisati/pano-montaj",
    card: "/bina-asamalari/topics/pano-montaj.svg",
    altTr: "Pano Montajı — Teknik hacimde ana elektrik dağıtım panosu, modüler sigortalar, baralar ve düzenli kablo girişi",
    visualPurpose: "Kullanıcı bu görsele baktığında teknik hacimde ana elektrik dağıtım panosu, modüler sigortalar, baralar ve düzenli kablo girişi durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "tesisat-isleri/isitma-sogutma": {
    nodeId: "isitma-sogutma",
    slugPath: "tesisat-isleri/isitma-sogutma",
    card: "/bina-asamalari/topics/isitma-sogutma.svg",
    altTr: "Isıtma & Soğutma — Mekanik merkezde kazan/ısı pompası bağlantısı, sirkülasyon pompaları ve izolasyonlu borular",
    visualPurpose: "Kullanıcı bu görsele baktığında mekanik merkezde kazan/ısı pompası bağlantısı, sirkülasyon pompaları ve izolasyonlu borular durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "tesisat-isleri/isitma-sogutma/yerden-isitma": {
    nodeId: "yerden-isitma",
    slugPath: "tesisat-isleri/isitma-sogutma/yerden-isitma",
    card: "/bina-asamalari/topics/yerden-isitma.svg",
    altTr: "Yerden Isıtma — Döşeme üzerinde modülasyon paneli arasına döşenmiş kırmızı PEX serpantin boru ve şap katmanı",
    visualPurpose: "Kullanıcı bu görsele baktığında döşeme üzerinde modülasyon paneli arasına döşenmiş kırmızı pex serpantin boru ve şap katmanı durumunu net olarak anlamalı.",
    mode: "technical-cutaway",
    version: 1,
  },
  "tesisat-isleri/isitma-sogutma/klima-tesisat": {
    nodeId: "klima-tesisat",
    slugPath: "tesisat-isleri/isitma-sogutma/klima-tesisat",
    card: "/bina-asamalari/topics/klima-tesisat.svg",
    altTr: "Klima Tesisatı — VRF/klima iç ünite tavan montajı, izoleli bakır boru hattı ve şeffaf drenaj hattı",
    visualPurpose: "Kullanıcı bu görsele baktığında vrf/klima iç ünite tavan montajı, izoleli bakır boru hattı ve şeffaf drenaj hattı durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "tesisat-isleri/yangin-tesisati": {
    nodeId: "yangin-tesisati",
    slugPath: "tesisat-isleri/yangin-tesisati",
    card: "/bina-asamalari/topics/yangin-tesisati.svg",
    altTr: "Yangın Tesisatı — Tavanda kırmızı çelik yangın boru hattı ve aşağı sarkan pirinç sprinkler başlıkları",
    visualPurpose: "Kullanıcı bu görsele baktığında tavanda kırmızı çelik yangın boru hattı ve aşağı sarkan pirinç sprinkler başlıkları durumunu net olarak anlamalı.",
    mode: "installed-component",
    version: 1,
  },
  "peyzaj-teslim": {
    nodeId: "peyzaj-teslim",
    slugPath: "peyzaj-teslim",
    card: "/bina-asamalari/topics/peyzaj-teslim.svg",
    altTr: "Peyzaj & Teslim — Yapımı tamamlanmış modern bina, temiz çevre düzeni, yürüyüş yolları ve yeşil alanlar",
    visualPurpose: "Kullanıcı bu görsele baktığında yapımı tamamlanmış modern bina, temiz çevre düzeni, yürüyüş yolları ve yeşil alanlar durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "peyzaj-teslim/peyzaj-ve-cevre-duzenleme": {
    nodeId: "peyzaj-ve-cevre-duzenleme",
    slugPath: "peyzaj-teslim/peyzaj-ve-cevre-duzenleme",
    card: "/bina-asamalari/topics/peyzaj-ve-cevre-duzenleme.svg",
    altTr: "Peyzaj & Çevre Düzenleme — Bina çevresinde sert zemin bordür taşları ile bitkisel toprak alanının uyumlu düzenlenmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında bina çevresinde sert zemin bordür taşları ile bitkisel toprak alanının uyumlu düzenlenmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "peyzaj-teslim/peyzaj-ve-cevre-duzenleme/sert-zemin": {
    nodeId: "sert-zemin",
    slugPath: "peyzaj-teslim/peyzaj-ve-cevre-duzenleme/sert-zemin",
    card: "/bina-asamalari/topics/sert-zemin.svg",
    altTr: "Sert Zemin — Yaya yolunda kum yatağı üzerine beton kilit parke taşlarının tokmakla döşenmesi",
    visualPurpose: "Kullanıcı bu görsele baktığında yaya yolunda kum yatağı üzerine beton kilit parke taşlarının tokmakla döşenmesi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "peyzaj-teslim/peyzaj-ve-cevre-duzenleme/bitkisel-peyzaj": {
    nodeId: "bitkisel-peyzaj",
    slugPath: "peyzaj-teslim/peyzaj-ve-cevre-duzenleme/bitkisel-peyzaj",
    card: "/bina-asamalari/topics/bitkisel-peyzaj.svg",
    altTr: "Bitkisel Peyzaj — Bahçe alanında fidan dikimi, kök boğazı toprağı, damlama sulama borusu ve malç serimi",
    visualPurpose: "Kullanıcı bu görsele baktığında bahçe alanında fidan dikimi, kök boğazı toprağı, damlama sulama borusu ve malç serimi durumunu net olarak anlamalı.",
    mode: "site-process",
    version: 1,
  },
  "peyzaj-teslim/iskan-ruhsati": {
    nodeId: "iskan-ruhsati",
    slugPath: "peyzaj-teslim/iskan-ruhsati",
    card: "/bina-asamalari/topics/iskan-ruhsati.svg",
    altTr: "İskan Ruhsatı — Tüm imalatları bitmiş, oturuma ve kabule hazır tamamlanmış kusursuz bina girişi",
    visualPurpose: "Kullanıcı bu görsele baktığında tüm imalatları bitmiş, oturuma ve kabule hazır tamamlanmış kusursuz bina girişi durumunu net olarak anlamalı.",
    mode: "project-visual",
    version: 1,
  },
};

/**
 * Slug path veya node ID üzerinden görsel varlığını çözer.
 */
export function getBinaVisual(slugPathOrId: string): BinaVisualAsset | undefined {
  if (BINA_VISUALS[slugPathOrId]) {
    return BINA_VISUALS[slugPathOrId];
  }

  // slugPath içindeki son segmenti veya ID'yi ara
  const id = slugPathOrId.split("/").pop() || slugPathOrId;
  for (const key in BINA_VISUALS) {
    if (BINA_VISUALS[key].nodeId === id) {
      return BINA_VISUALS[key];
    }
  }

  return undefined;
}
