import { PHASE3_UPDATED_AT, phase3Lines, tbdyPhase3References, type DepremPhase3Override } from "./deprem-phase3-shared";

export const DEPREM_PHASE3_BOLUM17: DepremPhase3Override = {
  slug: "tbdy-bolum-17-basitlestirilmis-tasarim",
  description: "TBDY 2018 Bölüm 17'deki basitleştirilmiş tasarım kurallarının gerçek kapsamını; BKS, DTS-BYS, bodrum, taşıyıcı sistem, plan/açıklık/kat yüksekliği, düzensizlik, döşeme, temel ve malzeme koşullarıyla birlikte açıklar.",
  seoTitle: "TBDY Bölüm 17 Basitleştirilmiş Tasarım | Kapsam ve Ön Koşullar",
  seoDescription: "BKS=3, DTS-BYS sınırları, en fazla bir bodrum, 30 m plan, 3–7.5 m açıklık, 4 m kat yüksekliği, düzensizlik ve temel koşullarıyla Bölüm 17 rehberi.",
  updatedAt: PHASE3_UPDATED_AT,
  readTime: "12 dk",
  sections: [
    {
      id: "kapsam-kapisi",
      title: "Bölüm 17 genel bir kısa yol değil, koşullu ve isteğe bağlı bir tasarım yoludur",
      content: phase3Lines(
        "TBDY 17.1.1, basitleştirilmiş hesap ve tasarım kurallarını yalnız belirli **yerinde dökme betonarme** binalara açar. Binanın bodrumsuz veya en fazla bir bodrumlu olması, bina tabanının 3.3.1'e göre doğru tanımlanması, DTS–BYS sınırlarının ve 17.2 koşullarının birlikte sağlanması gerekir. Yöntemin kullanımı yapı sahibi ve projeden sorumlu mühendisin tercihine bağlıdır.",
        "",
        "| Kapsam girdisi | 17.1 SOURCE_VALUE |",
        "|---|---|",
        "| Yapım sistemi | Yerinde dökme betonarme |",
        "| Bodrum | Bodrumsuz veya bir bodrum kat |",
        "| DTS = 1 veya 2 | BYS ≥ 6 |",
        "| DTS = 3 veya 4 | BYS ≥ 7 |",
        "| Bina Kullanım Sınıfı | BKS = 3, konut veya işyeri |",
        "",
        "> [!warning] BYS sayısını kat sayısı sanmayın",
        "> `BYS ≥ 6` ifadesi “en az altı kat” demek değildir. BYS, TBDY Tablo 3.3'te DTS ve deprem hesabına esas bina yüksekliği HN üzerinden belirlenen sınıftır."
      ),
      subsections: [],
    },
    {
      id: "on-tasarim-ayrimi",
      title: "17.1.4: basitleştirilmiş kesin tasarım ile ön tasarım seçeneğini ayırın",
      content: phase3Lines(
        "17.1.4, Bölüm 17'nin sık atlanan ikinci kullanım biçimini tanımlar. Basitleştirilmiş yapısal çözümleme kullanılmasa bile belirli daha geniş DTS–BYS aralığındaki BKS=3 konut/işyeri binalarında 17.3 ve 17.4'teki boyutlandırma kuralları ile enkesit ve donatı alt sınırları **ön tasarım amacıyla** kullanılabilir.",
        "",
        "| Kullanım | DTS 1–2 | DTS 3–4 | Nihai hesap |",
        "|---|---:|---:|---|",
        "| 17.1.1 basitleştirilmiş hesap/tasarım | BYS ≥ 6 | BYS ≥ 7 | Bölüm 17 koşullarıyla |",
        "| 17.1.4 ön tasarım alt sınırları | BYS ≥ 5 | BYS ≥ 6 | Yönetmeliğin diğer ilgili bölümleri zorunlu |",
        "",
        "> [!regulation] Kesin tasarım sınırı",
        "> 17.1.4 kapsamındaki ön boyutlandırma değerlerini “Bölüm 17 ile kesin tasarım yapıldı” biçiminde yorumlamayın. Metin, bu binaların kesin tasarımında yürürlükteki ilgili standartlar ve TBDY'nin diğer bölümlerindeki hesap/tasarım kurallarını zorunlu tutar."
      ),
      subsections: [],
    },
    {
      id: "geometri-duzenlilik",
      title: "Plan, açıklık ve kat geometrisi için sıkı düzenlilik koşulları vardır",
      content: phase3Lines(
        "Bölüm 17'nin kolaylaştırılmış hesapları, düzenli bir taşıyıcı sistem geometrisi karşılığında izin verilir. Özellikle 17.2.4–17.2.9 koşulları bir ön kontrol tablosu halinde proje başında doğrulanmalıdır.",
        "",
        "| Kontrol | SOURCE_VALUE / koşul |",
        "|---|---|",
        "| Plan biçimi | Dikdörtgene yakın, ortogonal ve eksenleri sürekli |",
        "| Uzun plan kenarı | ≤ 30 m |",
        "| Uzun/kısa kenar oranı | ≤ 4 |",
        "| Açıklık | 3 m ≤ açıklık ≤ 7.5 m |",
        "| Her doğrultudaki açıklık sayısı | en az 2 |",
        "| Komşu açıklık farkı | uzun açıklığın ≤ 1/5'i |",
        "| Konsol | ≤ 2 m ve komşu açıklığın ≤ 1/3'ü |",
        "| Kat yüksekliği | ≤ 4 m |",
        "| Kat yükseklik değişimi | yüksek katın ≤ 1/5'i |",
        "",
        "17.2.7'ye göre **A2, A3, B1 ve B3 düzensizlikleri bulunmamalıdır**. 17.2.8 ayrıca kısmi bodrum hariç her katta kütle merkezi–rijitlik merkezi dışmerkezliğini ilgili dik plan boyunun 1/5'i ile sınırlar.",
        "",
        "> [!check] Perde yerleşimi",
        "> Taşıyıcı sistemde betonarme perdeler varsa her doğrultuda, kat kütle merkezinin iki tarafında en az birer tane olacak şekilde toplam en az iki dikdörtgen perde veya perde kolu bulunmalıdır."
      ),
      subsections: [],
    },
    {
      id: "sistem-doseme-temel",
      title: "Taşıyıcı sistem, döşeme ve temel türü serbest değildir",
      content: phase3Lines(
        "17.2.1 kapsamında yatay yük taşıyıcı sistem yalnız **süneklik düzeyi yüksek çerçevelerden** veya **süneklik düzeyi yüksek boşluksuz perdeler + süneklik düzeyi yüksek çerçevelerden** oluşabilir. DTS = 1 ve 2 için 17.2.13 süneklik düzeyi yüksek boşluksuz perde kullanımını zorunlu kılar.",
        "",
        "| Konu | Bölüm 17 koşulu |",
        "|---|---|",
        "| Kolon/perde enkesiti | bina yüksekliği boyunca küçültme yapılmaz |",
        "| Kiriş enkesiti | katlar veya aynı taşıyıcı eksen boyunca değiştirilmez |",
        "| Kirişli plak döşeme | kalınlık ≥ 150 mm |",
        "| Dişli/dolgulu (asmolen) döşeme plağı | kalınlık ≥ 70 mm + SDY çerçeve kirişi koşulları |",
        "| Yalnız çerçeveli sistem temeli | radye veya sürekli temel |",
        "| Perde + çerçeve sistemi temeli | radye temel |",
        "",
        "> [!engineering] DTS 1–2 dağılım notu",
        "> Bölüm 17 hesabında DTS=1 ve 2 perde+çerçeve sistemlerde toplam eşdeğer deprem yükünün tamamının süneklik düzeyi yüksek perdeler, %33'ünün ise süneklik düzeyi yüksek çerçeveler tarafından karşılandığı koşul gözetilir."
      ),
      subsections: [],
    },
    {
      id: "ozel-hesap-ve-malzeme",
      title: "Bölüm 17 kendi özel hesap kabullerini ve malzeme sınırlarını getirir",
      content: phase3Lines(
        "Basitleştirilmiş yöntemin bazı hükümleri genel Bölüm 4 akışından bilinçli olarak ayrılır. 17.2.12'ye göre bu bölümde tanımlanan hesap kuralları yalnız `G + Q + 0.2S ± Ed` ve `0.9G ± Ed` birleşimleri için düzenlenmiştir; **düşey deprem etkisi Ed(Z) hesaba katılmayabilir ve yatay deprem etkilerinde doğrultu birleştirmesi uygulanmaz**.",
        "",
        "17.2.17–17.2.19 ayrıca malzeme ve detay sınırları getirir: beton sınıfı **C25'ten düşük veya C50'den yüksek olamaz**; donatı çeliği B420C veya S420 dışına çıkamaz. Boyuna donatı kenetlenme ve bindirme boyu en az `50ϕ`, 90° kanca kenetlenmesi en az `25ϕ` alınır; perde kritik yüksekliği için bodrum durumuna bağlı minimum kat sayıları vardır.",
        "",
        "> [!warning] Genel TBDY kuralları tamamen devre dışı kalmaz",
        "> 17.2.2 açıkça, Bölüm 17 dışında kalan dayanıma göre tasarım, detaylandırma, geometrik, minimum ve üst sınır koşullarının Bölüm 7 ve yürürlükteki ilgili standart/yönetmeliklere tabi olduğunu belirtir. Basitleştirme yalnız tanımlanan kapsam içindedir."
      ),
      subsections: [],
    },
    {
      id: "kontrol-listesi",
      title: "Proje kontrol listesi",
      content: phase3Lines(
        "- Yapı yerinde dökme betonarme mi ve bodrumsuz/en fazla bir bodrumlu mu?",
        "- BKS gerçekten 3 ve kullanım konut veya işyeri mi?",
        "- DTS 1–2 için BYS ≥ 6 veya DTS 3–4 için BYS ≥ 7 koşulu sağlanıyor mu?",
        "- 17.2'de izin verilen süneklik düzeyi yüksek taşıyıcı sistemlerden biri kullanılıyor mu?",
        "- Plan uzun kenarı ≤30 m, oran ≤4 ve taşıyıcı eksenler ortogonal/sürekli mi?",
        "- Açıklıklar 3–7.5 m, kat yüksekliği ≤4 m ve konsol sınırları uygun mu?",
        "- A2, A3, B1 veya B3 düzensizliği var mı?",
        "- Perde kullanılıyorsa her doğrultuda kütle merkezinin iki tarafında gerekli perde düzeni sağlanıyor mu?",
        "- Döşeme kalınlığı ve temel türü 17.2.10–17.2.11 ile uyumlu mu?",
        "- Bölüm 17'ye özel yük birleşimi, düşey deprem ve doğrultu birleştirmesi kabulleri doğru uygulanmış mı?",
        "- Beton C25–C50 ve donatı B420C/S420 sınırlarında mı?",
        "- Yalnız 17.1.4 ön tasarım seçeneği kullanılıyorsa kesin tasarımın genel TBDY hükümleriyle tamamlanacağı açık mı?"
      ),
      subsections: [],
    },
  ],
  references: tbdyPhase3References("Bölüm 17; Madde 17.1–17.2"),
  keywords: ["TBDY 2018", "Bölüm 17", "basitleştirilmiş tasarım", "BKS 3", "BYS 6", "BYS 7", "30 m", "7.5 m", "4 m kat yüksekliği", "C25 C50"],
  tags: ["TBDY 2018", "Bölüm 17", "Basitleştirilmiş Tasarım", "Betonarme"],
};
