import type { DepremRolloutSpec } from "./deprem-rollout";

export const DEPREM_ROLLOUT_BATCH_6: readonly DepremRolloutSpec[] = [
  {
    slug: "yagmur-suyu-drenaji-ve-sizma-tesisi-hesabi",
    batch: 6,
    headline: "Yağmur Suyu Drenajı ve Sızdırma Tesisi",
    eyebrow: "YAĞIŞ · DRENAJ · DEŞARJ",
    steps: ["Yağış ve yüzey verisi", "Drenaj debisi ve güzergâh", "Sızdırma veya deşarj kararı"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "engelsiz-tekerlekli-sandalye-manevra-alani-koridor-genislikleri",
    batch: 6,
    headline: "Tekerlekli Sandalye Manevra Alanı ve Koridorlar",
    eyebrow: "MANEVRA · KORİDOR · NET ÖLÇÜ",
    steps: ["Manevra alanı", "Koridor net genişliği", "Dönüş ve geçiş sürekliliği"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "engelsiz-rampa-egimi-korkuluk-yuzey-standartlari",
    batch: 6,
    headline: "Engelsiz Rampalarda Eğim, Korkuluk ve Yüzey",
    eyebrow: "EĞİM · KORKULUK · YÜZEY",
    steps: ["Rampa geometrisi", "Korkuluk ve kenar koruması", "Kaymaz yüzey ve sahanlık"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "engelsiz-wc-asansor-kapi-boyutlari",
    batch: 6,
    headline: "Engelsiz WC, Asansör ve Kapı Boyutları",
    eyebrow: "WC · ASANSÖR · KAPI",
    steps: ["Islak hacim net alanı", "Asansör kabini ve önü", "Kapı net geçişi"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "engelsiz-yapi-ruhsatinda-uyum-kontrolu",
    batch: 6,
    headline: "Yapı Ruhsatında Erişilebilirlik Uyum Kontrolü",
    eyebrow: "GÜZERGÂH · PROJE · RUHSAT",
    steps: ["Kesintisiz erişilebilir güzergâh", "Net ölçü ve detay kontrolü", "Ruhsat eki proje uyumu"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "eurocode-ts-en-1990-yuk-kombinasyonlari-ve-guvenlik-katsayilari",
    batch: 6,
    headline: "TS EN 1990 Yük Birleşimleri ve Güvenlik Katsayıları",
    eyebrow: "ETKİ · KATSAYI · BİRLEŞİM",
    steps: ["Tasarım durumunu belirle", "Etki ve güvenlik katsayıları", "Yük birleşimini oluştur"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1991-1-1-hareketli-yukler-bolume-gore-degerler",
    batch: 6,
    headline: "TS EN 1991-1-1 Hareketli Yükler",
    eyebrow: "KULLANIM · KATEGORİ · YÜK",
    steps: ["Kullanım alanını belirle", "Yük kategorisini seç", "Karakteristik yükü uygula"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "eurocode-ts-en-1991-1-3-kar-yuku-hesabi-bolge-haritasi-ile",
    batch: 6,
    headline: "TS EN 1991-1-3 Kar Yükü Hesabı",
    eyebrow: "BÖLGE · ÇATI · KAR YÜKÜ",
    steps: ["Yer ve iklim girdileri", "Çatı biçimi ve katsayılar", "Tasarım kar yükü"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1991-1-4-ruzgar-yuku-hesabi-turkiye-bolgeleri",
    batch: 6,
    headline: "TS EN 1991-1-4 Rüzgâr Yükü Hesabı",
    eyebrow: "RÜZGÂR · ARAZİ · BASINÇ",
    steps: ["Rüzgâr ve arazi girdileri", "Yapı geometrisi ve katsayılar", "Basınç ve yük etkisi"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1992-1-1-ec2-ts-500-ile-karsilastirmali-analiz",
    batch: 6,
    headline: "TS EN 1992-1-1 ve TS 500 Karşılaştırması",
    eyebrow: "EC2 · TS 500 · TASARIM",
    steps: ["Kapsam ve tasarım kabulleri", "Malzeme ve güvenlik yaklaşımı", "Kesit ve detay sonuçları"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "akustik-ts-en-iso-12354-ile-yalitim-hesabi",
    batch: 6,
    headline: "TS EN ISO 12354 ile Ses Yalıtımı Hesabı",
    eyebrow: "HEDEF · ELEMAN · PERFORMANS",
    steps: ["Hedef akustik performans", "Ayırıcı eleman ve birleşimler", "Beklenen yerinde performans"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "asansor-boslugu-boyutlandirma-kapasite-alan-tablosu",
    batch: 6,
    headline: "Asansör Kuyusu Boyutlandırması ve Kapasite",
    eyebrow: "KAPASİTE · KABİN · KUYU",
    steps: ["Kapasite ve kullanım", "Kabin ve kapı ölçüleri", "Kuyu ve sahanlık yerleşimi"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
] as const;

export const DEPREM_ROLLOUT_BATCH_7: readonly DepremRolloutSpec[] = [
  {
    slug: "asansor-makine-daireli-ve-dairesiz-sistemler",
    batch: 7,
    headline: "Makine Daireli ve Dairesiz Asansör Sistemleri",
    eyebrow: "SİSTEM · HACİM · BAKIM",
    steps: ["Tahrik ve makine yerleşimi", "Kuyu ve üst boşluk gereksinimi", "Bakım ve erişim koşulları"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "asansor-guvenlik-aksesuarlari-ve-periyodik-bakim-zorunlulugu",
    batch: 7,
    headline: "Asansör Güvenlik Aksesuarları ve Periyodik Bakım",
    eyebrow: "GÜVENLİK · KONTROL · BAKIM",
    steps: ["Güvenlik bileşenlerini doğrula", "Periyodik kontrolü izle", "Bakım ve kayıt sürekliliği"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "asansor-deprem-sirasinda-otomatik-park-ozelligi",
    batch: 7,
    headline: "Asansörde Deprem Sırasında Otomatik Park",
    eyebrow: "ALGILAMA · PARK · GÜVENLİK",
    steps: ["Deprem sinyalini algıla", "Güvenli park senaryosunu çalıştır", "Yeniden devreye alma koşulunu doğrula"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "isg-santiye-guvenlik-plani-zorunlu-icerik",
    batch: 7,
    headline: "Şantiye Güvenlik Planının Zorunlu İçeriği",
    eyebrow: "RİSK · ORGANİZASYON · TEDBİR",
    steps: ["İş ve tehlike alanlarını tanımla", "Sorumluluk ve organizasyonu kur", "Tedbir ve acil durum planını belgele"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "isg-uzmani-gorevlendirme-tehlike-sinifi-isci-sayisi",
    batch: 7,
    headline: "İSG Uzmanı Görevlendirme Koşulları",
    eyebrow: "TEHLİKE · ÇALIŞAN · GÖREVLENDİRME",
    steps: ["Tehlike sınıfını belirle", "Çalışan sayısı ve kapsamı kontrol et", "Görevlendirme kararını uygula"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "isg-yuksekte-calisma-ve-iskele-guvenligi",
    batch: 7,
    headline: "Yüksekte Çalışma ve İskele Güvenliği",
    eyebrow: "ERİŞİM · DÜŞME · İSKELE",
    steps: ["Güvenli erişim ve platform", "Toplu/kişisel düşme önlemleri", "İskele kontrolü ve kullanım"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "isg-kazi-guvenligi-iksa-tasarimi-ve-kontrol",
    batch: 7,
    headline: "Kazı Güvenliği, İksa Tasarımı ve Kontrol",
    eyebrow: "KAZI · İKSA · SAHA",
    steps: ["Kazı ve çevre koşullarını tanı", "İksa ihtiyacını ve sistemi değerlendir", "Saha kontrolü ve deformasyonu izle"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "isg-beton-dokumunde-topraklama-ve-elektrik-guvenligi",
    batch: 7,
    headline: "Beton Dökümünde Topraklama ve Elektrik Güvenliği",
    eyebrow: "ENERJİ · TOPRAKLAMA · DÖKÜM",
    steps: ["Geçici elektrik tesisatını kontrol et", "Topraklama ve kaçak akım korumasını doğrula", "Döküm sırasında güvenli çalışma alanını sürdür"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "cevre-ced-zorunlulugu-proje-buyuklugu-esikleri",
    batch: 7,
    headline: "ÇED Gerekliliği ve Proje Büyüklüğü Eşikleri",
    eyebrow: "PROJE · EŞİK · ÇED",
    steps: ["Proje türü ve kapasitesini belirle", "İlgili eşik ve listeyi kontrol et", "ÇED süreci kararını belgeye bağla"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "cevre-insaat-atigi-yonetimi-yonetmeligi",
    batch: 7,
    headline: "İnşaat Atığı Yönetimi",
    eyebrow: "AYIRMA · DEPOLAMA · BERTARAF",
    steps: ["Atık türlerini kaynağında ayır", "Geçici depolamayı ve taşıma kaydını yönet", "Geri kazanım veya bertarafı doğrula"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "cevre-gurultu-ve-toz-santiye-yukumlulukleri",
    batch: 7,
    headline: "Şantiyede Gürültü ve Toz Yükümlülükleri",
    eyebrow: "GÜRÜLTÜ · TOZ · KONTROL",
    steps: ["Gürültü kaynakları ve çalışma saatleri", "Toz oluşumu ve yayılımı", "Azaltım ve izleme tedbirleri"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "cevre-yagmur-suyu-kirliligi-ve-santiye-filtrasyonu",
    batch: 7,
    headline: "Şantiye Yağmur Suyu Kirliliği ve Filtrasyon",
    eyebrow: "AKIŞ · KİRLİLİK · FİLTRE",
    steps: ["Yüzey akışını ve kirletici kaynağı tanı", "Tutma ve filtrasyon noktasını tasarla", "Deşarj ve bakım kontrolünü sürdür"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
] as const;

export const DEPREM_ROLLOUT_EXTRA_BATCHES: Readonly<Record<number, readonly DepremRolloutSpec[]>> = {
  6: DEPREM_ROLLOUT_BATCH_6,
  7: DEPREM_ROLLOUT_BATCH_7,
};
