import type { DepremRolloutSpec } from "./deprem-rollout";

export const DEPREM_ROLLOUT_BATCH_6: readonly DepremRolloutSpec[] = [
  {
    slug: "yagmur-suyu-drenaji-ve-sizma-tesisi-hesabi",
    batch: 6,
    headline: "Yağmur Suyu Drenajı ve Sızdırma Tesisi",
    eyebrow: "YAĞIŞ · DRENAJ · DEŞARJ",
    steps: ["Yağış ve yüzey verisi", "Drenaj debisi ve güzergâh", "Sızdırma veya deşarj kararı"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "engelsiz-tekerlekli-sandalye-manevra-alani-koridor-genislikleri",
    batch: 6,
    headline: "Tekerlekli Sandalye Manevra Alanı ve Koridorlar",
    eyebrow: "MANEVRA · KORİDOR · NET ÖLÇÜ",
    steps: ["Manevra alanı", "Koridor net genişliği", "Dönüş ve geçiş sürekliliği"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "engelsiz-rampa-egimi-korkuluk-yuzey-standartlari",
    batch: 6,
    headline: "Engelsiz Rampalarda Eğim, Korkuluk ve Yüzey",
    eyebrow: "EĞİM · KORKULUK · YÜZEY",
    steps: ["Rampa geometrisi", "Korkuluk ve kenar koruması", "Kaymaz yüzey ve sahanlık"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "engelsiz-wc-asansor-kapi-boyutlari",
    batch: 6,
    headline: "Engelsiz WC, Asansör ve Kapı Boyutları",
    eyebrow: "WC · ASANSÖR · KAPI",
    steps: ["Islak hacim net alanı", "Asansör kabini ve önü", "Kapı net geçişi"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "engelsiz-yapi-ruhsatinda-uyum-kontrolu",
    batch: 6,
    headline: "Yapı Ruhsatında Erişilebilirlik Uyum Kontrolü",
    eyebrow: "GÜZERGÂH · PROJE · RUHSAT",
    steps: ["Kesintisiz erişilebilir güzergâh", "Net ölçü ve detay kontrolü", "Ruhsat eki proje uyumu"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "eurocode-ts-en-1990-yuk-kombinasyonlari-ve-guvenlik-katsayilari",
    batch: 6,
    headline: "TS EN 1990 Yük Birleşimleri ve Güvenlik Katsayıları",
    eyebrow: "ETKİ · KATSAYI · BİRLEŞİM",
    steps: ["Tasarım durumunu belirle", "Etki ve güvenlik katsayıları", "Yük birleşimini oluştur"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1991-1-1-hareketli-yukler-bolume-gore-degerler",
    batch: 6,
    headline: "TS EN 1991-1-1 Hareketli Yükler",
    eyebrow: "KULLANIM · KATEGORİ · YÜK",
    steps: ["Kullanım alanını belirle", "Yük kategorisini seç", "Karakteristik yükü uygula"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "eurocode-ts-en-1991-1-3-kar-yuku-hesabi-bolge-haritasi-ile",
    batch: 6,
    headline: "TS EN 1991-1-3 Kar Yükü Hesabı",
    eyebrow: "BÖLGE · ÇATI · KAR YÜKÜ",
    steps: ["Yer ve iklim girdileri", "Çatı biçimi ve katsayılar", "Tasarım kar yükü"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1991-1-4-ruzgar-yuku-hesabi-turkiye-bolgeleri",
    batch: 6,
    headline: "TS EN 1991-1-4 Rüzgâr Yükü Hesabı",
    eyebrow: "RÜZGÂR · ARAZİ · BASINÇ",
    steps: ["Rüzgâr ve arazi girdileri", "Yapı geometrisi ve katsayılar", "Basınç ve yük etkisi"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1992-1-1-ec2-ts-500-ile-karsilastirmali-analiz",
    batch: 6,
    headline: "TS EN 1992-1-1 ve TS 500 Karşılaştırması",
    eyebrow: "EC2 · TS 500 · TASARIM",
    steps: ["Kapsam ve tasarım kabulleri", "Malzeme ve güvenlik yaklaşımı", "Kesit ve detay sonuçları"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "akustik-ts-en-iso-12354-ile-yalitim-hesabi",
    batch: 6,
    headline: "TS EN ISO 12354 ile Ses Yalıtımı Hesabı",
    eyebrow: "HEDEF · ELEMAN · PERFORMANS",
    steps: ["Hedef akustik performans", "Ayırıcı eleman ve birleşimler", "Beklenen yerinde performans"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "asansor-boslugu-boyutlandirma-kapasite-alan-tablosu",
    batch: 6,
    headline: "Asansör Kuyusu Boyutlandırması ve Kapasite",
    eyebrow: "KAPASİTE · KABİN · KUYU",
    steps: ["Kapasite ve kullanım", "Kabin ve kapı ölçüleri", "Kuyu ve sahanlık yerleşimi"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
] as const;

export const DEPREM_ROLLOUT_BATCH_7: readonly DepremRolloutSpec[] = [
  {
    slug: "asansor-makine-daireli-ve-dairesiz-sistemler",
    batch: 7,
    headline: "Makine Daireli ve Dairesiz Asansör Sistemleri",
    eyebrow: "SİSTEM · HACİM · BAKIM",
    steps: ["Tahrik ve makine yerleşimi", "Kuyu ve üst boşluk gereksinimi", "Bakım ve erişim koşulları"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "asansor-guvenlik-aksesuarlari-ve-periyodik-bakim-zorunlulugu",
    batch: 7,
    headline: "Asansör Güvenlik Aksesuarları ve Periyodik Bakım",
    eyebrow: "GÜVENLİK · KONTROL · BAKIM",
    steps: ["Güvenlik bileşenlerini doğrula", "Periyodik kontrolü izle", "Bakım ve kayıt sürekliliği"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "asansor-deprem-sirasinda-otomatik-park-ozelligi",
    batch: 7,
    headline: "Asansörde Deprem Sırasında Otomatik Park",
    eyebrow: "ALGILAMA · PARK · GÜVENLİK",
    steps: ["Deprem sinyalini algıla", "Güvenli park senaryosunu çalıştır", "Yeniden devreye alma koşulunu doğrula"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "isg-santiye-guvenlik-plani-zorunlu-icerik",
    batch: 7,
    headline: "Şantiye Güvenlik Planının Zorunlu İçeriği",
    eyebrow: "RİSK · ORGANİZASYON · TEDBİR",
    steps: ["İş ve tehlike alanlarını tanımla", "Sorumluluk ve organizasyonu kur", "Tedbir ve acil durum planını belgele"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "isg-uzmani-gorevlendirme-tehlike-sinifi-isci-sayisi",
    batch: 7,
    headline: "İSG Uzmanı Görevlendirme Koşulları",
    eyebrow: "TEHLİKE · ÇALIŞAN · GÖREVLENDİRME",
    steps: ["Tehlike sınıfını belirle", "Çalışan sayısı ve kapsamı kontrol et", "Görevlendirme kararını uygula"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "isg-yuksekte-calisma-ve-iskele-guvenligi",
    batch: 7,
    headline: "Yüksekte Çalışma ve İskele Güvenliği",
    eyebrow: "ERİŞİM · DÜŞME · İSKELE",
    steps: ["Güvenli erişim ve platform", "Toplu/kişisel düşme önlemleri", "İskele kontrolü ve kullanım"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "isg-kazi-guvenligi-iksa-tasarimi-ve-kontrol",
    batch: 7,
    headline: "Kazı Güvenliği, İksa Tasarımı ve Kontrol",
    eyebrow: "KAZI · İKSA · SAHA",
    steps: ["Kazı ve çevre koşullarını tanı", "İksa ihtiyacını ve sistemi değerlendir", "Saha kontrolü ve deformasyonu izle"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "isg-beton-dokumunde-topraklama-ve-elektrik-guvenligi",
    batch: 7,
    headline: "Beton Dökümünde Topraklama ve Elektrik Güvenliği",
    eyebrow: "ENERJİ · TOPRAKLAMA · DÖKÜM",
    steps: ["Geçici elektrik tesisatını kontrol et", "Topraklama ve kaçak akım korumasını doğrula", "Döküm sırasında güvenli çalışma alanını sürdür"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "cevre-ced-zorunlulugu-proje-buyuklugu-esikleri",
    batch: 7,
    headline: "ÇED Gerekliliği ve Proje Büyüklüğü Eşikleri",
    eyebrow: "PROJE · EŞİK · ÇED",
    steps: ["Proje türü ve kapasitesini belirle", "İlgili eşik ve listeyi kontrol et", "ÇED süreci kararını belgeye bağla"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "cevre-insaat-atigi-yonetimi-yonetmeligi",
    batch: 7,
    headline: "İnşaat Atığı Yönetimi",
    eyebrow: "AYIRMA · DEPOLAMA · BERTARAF",
    steps: ["Atık türlerini kaynağında ayır", "Geçici depolamayı ve taşıma kaydını yönet", "Geri kazanım veya bertarafı doğrula"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "cevre-gurultu-ve-toz-santiye-yukumlulukleri",
    batch: 7,
    headline: "Şantiyede Gürültü ve Toz Yükümlülükleri",
    eyebrow: "GÜRÜLTÜ · TOZ · KONTROL",
    steps: ["Gürültü kaynakları ve çalışma saatleri", "Toz oluşumu ve yayılımı", "Azaltım ve izleme tedbirleri"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "cevre-yagmur-suyu-kirliligi-ve-santiye-filtrasyonu",
    batch: 7,
    headline: "Şantiye Yağmur Suyu Kirliliği ve Filtrasyon",
    eyebrow: "AKIŞ · KİRLİLİK · FİLTRE",
    steps: ["Yüzey akışını ve kirletici kaynağı tanı", "Tutma ve filtrasyon noktasını tasarla", "Deşarj ve bakım kontrolünü sürdür"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
] as const;

export const DEPREM_ROLLOUT_BATCH_8: readonly DepremRolloutSpec[] = [
  {
    slug: "tbdy-bks-dts-bys-belirleme",
    batch: 8,
    headline: "BKS, DTS ve BYS'nin Birlikte Belirlenmesi",
    eyebrow: "BKS · DTS · BYS",
    steps: ["Kullanım amacı ve BKS", "SDS üzerinden DTS", "Bina yüksekliği üzerinden BYS"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "tbdy-performans-hedefleri-dd-sh-kh-go",
    batch: 8,
    headline: "DD Düzeyleri ve Performans Hedefleri",
    eyebrow: "DD · SH · KH · GÖ",
    steps: ["Bina kullanımını belirle", "DD düzeyini seç", "Performans hedefini eşleştir"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "tbdy-kutle-kaynagi-hareketli-yuk-katilimi",
    batch: 8,
    headline: "Kütle Kaynağı ve Hareketli Yük Katılımı",
    eyebrow: "SABİT YÜK · HAREKETLİ YÜK · KÜTLE",
    steps: ["Sabit yükleri topla", "Hareketli yük katılımını uygula", "Kat ve diyafram kütlesini doğrula"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "tbdy-rijit-yari-rijit-diyafram",
    batch: 8,
    headline: "Rijit ve Yarı Rijit Diyafram Seçimi",
    eyebrow: "DÖŞEME · DİYAFRAM · MODEL",
    steps: ["Boşluk ve geometriyi incele", "Rijit/yarı rijit kabulünü seç", "Ağ ve kuvvet aktarımını doğrula"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "tbdy-esdeger-deprem-yuku-uygulanma-sinirlari",
    batch: 8,
    headline: "Eşdeğer Deprem Yükü Yönteminin Sınırları",
    eyebrow: "DTS · BYS · YÖNTEM",
    steps: ["DTS ve BYS koşullarını kontrol et", "Düzensizlikleri değerlendir", "Analiz yöntemini kararlaştır"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "tbdy-yeterli-mod-modal-kutle-katilimi",
    batch: 8,
    headline: "Titreşim Modları ve Modal Kütle Katılımı",
    eyebrow: "MOD · KÜTLE · KATILIM",
    steps: ["X/Y modal katılımı oku", "Burulma modlarını incele", "Yeterli mod sayısına ulaş"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "tbdy-modal-taban-kesme-olceklendirme",
    batch: 8,
    headline: "Modal Taban Kesmesinin Ölçeklendirilmesi",
    eyebrow: "MODAL · TABAN KESME · ÖLÇEK",
    steps: ["Modal taban kesmesini belirle", "Referans alt sınırla karşılaştır", "Tepki büyüklüklerini tutarlı ölçekle"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "tbdy-yuzde-100-yuzde-30-birlesimi",
    batch: 8,
    headline: "%100–%30 Deprem Doğrultusu Birleşimi",
    eyebrow: "X · Y · BİRLEŞİM",
    steps: ["İki yatay doğrultuyu oluştur", "%100–%30 işaret birleşimlerini üret", "P-M-M ve kuvvet zarflarını kontrol et"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "tbdy-dusey-deprem-etkisi",
    batch: 8,
    headline: "Düşey Deprem Etkisinin Hesaba Katılması",
    eyebrow: "DÜŞEY DEPREM · ELEMAN · BİRLEŞİM",
    steps: ["Duyarlı elemanları belirle", "Düşey deprem etkisini tanımla", "Mesnet ve moment sonuçlarını kontrol et"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "tbdy-deprem-derzi-hesabi",
    batch: 8,
    headline: "Deprem Derji Hesabı ve Sürekliliği",
    eyebrow: "ÖTELENME · DERZ · ÇARPIŞMA",
    steps: ["Komşu blok ötelenmelerini karşılaştır", "Gerekli derz genişliğini belirle", "Temelden çatıya sürekliliği çöz"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "tbdy-bolum-17-basitlestirilmis-tasarim",
    batch: 8,
    headline: "TBDY Bölüm 17 Basitleştirilmiş Tasarım",
    eyebrow: "KAPSAM · DÜZENLİLİK · YÖNTEM",
    steps: ["Bina türü ve yükseklik sınırı", "Plan/düşey düzenlilik", "Yöntemin uygulanabilirlik kararı"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "tbdy-uygulama-esaslari-taslak-statusu",
    batch: 8,
    headline: "TBDY Uygulama Esasları Taslak Statüsü",
    eyebrow: "TASLAK · YÜRÜRLÜK · KAYNAK",
    steps: ["Resmî yayımlanma durumunu doğrula", "Taslak ve yürürlükteki metni ayır", "Proje raporunda sürüm/tarihi belirt"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
] as const;

export const DEPREM_ROLLOUT_BATCH_9: readonly DepremRolloutSpec[] = [
  { slug: "tbdy-betonarme-ozel-deprem-etriyesi-ciroz", batch: 9, headline: "Özel Deprem Etriyesi ve Çiroz Düzeni", eyebrow: "ETRİYE · ÇİROZ · SARILMA", steps: ["Kanca geometrisini doğrula", "Çirozları şaşırtmalı düzenle", "Boyuna çubukların yanal tutulmasını kontrol et"], referenceProfile: "preserve", visualLayout: "classification" },
  { slug: "tbdy-betonarme-kenetlenme-bindirme-manson-bolgeleri", batch: 9, headline: "Kenetlenme, Bindirme ve Manşon Bölgeleri", eyebrow: "EK · KONUM · BELGE", steps: ["Yasaklı uç bölgeleri işaretle", "Bindirme yığılmasını önle", "Manşon sınıfı ve deney belgesini doğrula"], referenceProfile: "preserve", visualLayout: "decision" },
  { slug: "tbdy-betonarme-kolon-kesit-eksenel-yuk-siniri", batch: 9, headline: "Kolon Kesiti ve Eksenel Yük Sınırı", eyebrow: "KESİT · EKSENEL YÜK · SÜNEKLİK", steps: ["Minimum kesit boyutunu kontrol et", "Eksenel yük oranını hesapla", "Sınır aşımında kesit veya sistemi revize et"], referenceProfile: "preserve", visualLayout: "decision" },
  { slug: "tbdy-betonarme-kolon-boyuna-donati-duzeni", batch: 9, headline: "Kolon Boyuna Donatı Düzeni", eyebrow: "ORAN · DAĞILIM · SÜREKLİLİK", steps: ["Minimum-maksimum donatı oranı", "Kesit çevresinde dengeli dağılım", "Kat geçişinde kenetlenme ve süreklilik"], referenceProfile: "preserve", visualLayout: "classification" },
  { slug: "tbdy-betonarme-kolon-sarilma-bolgeleri", batch: 9, headline: "Kolon Sarılma Bölgeleri", eyebrow: "UÇ BÖLGE · ETRİYE · SIKLAŞTIRMA", steps: ["Alt ve üst sarılma boylarını belirle", "İlk etriye ve aralıkları kontrol et", "Temel üstü ve bindirme koşullarını uygula"], referenceProfile: "preserve", visualLayout: "flow" },
  { slug: "tbdy-betonarme-kolon-kapasite-kesme", batch: 9, headline: "Kolonda Kapasite Tasarımına Göre Kesme", eyebrow: "MOMENT · KESME · KAPASİTE", steps: ["Uç moment kapasitelerini belirle", "Analiz ve kapasite kesmesini karşılaştır", "Enine donatı güvenliğini doğrula"], referenceProfile: "preserve", visualLayout: "flow" },
  { slug: "tbdy-betonarme-kiris-boyut-eksen-kacikligi", batch: 9, headline: "Kiriş Boyutları ve Eksen Kaçıklığı", eyebrow: "KESİT · EKSEN · BİRLEŞİM", steps: ["Kiriş boyut sınırlarını kontrol et", "Kolon çekirdeğine göre ekseni ölç", "Kaçıklıkta birleşim ve burulmayı çöz"], referenceProfile: "preserve", visualLayout: "comparison" },
  { slug: "tbdy-betonarme-kiris-mesnet-donati-surekliligi", batch: 9, headline: "Kiriş Mesnet Donatısı Sürekliliği", eyebrow: "MESNET · KENETLENME · DEVAM", steps: ["Pozitif-negatif donatıyı kontrol et", "Birleşimde kenetlenmeyi sağla", "Kesilen çubukların devam boyunu göster"], referenceProfile: "preserve", visualLayout: "flow" },
  { slug: "tbdy-betonarme-kiris-sarilma-bolgeleri", batch: 9, headline: "Kiriş Sarılma Bölgeleri", eyebrow: "PLASTİKLEŞME · ETRİYE · UÇ BÖLGE", steps: ["İki uçta sarılma bölgesini ölçülendir", "İlk etriye ve aralıkları doğrula", "Bindirmeleri plastikleşme bölgesinden uzaklaştır"], referenceProfile: "preserve", visualLayout: "classification" },
  { slug: "tbdy-betonarme-kiris-kapasite-kesme", batch: 9, headline: "Kirişte Kapasite Tasarımına Göre Kesme", eyebrow: "UÇ MOMENT · DÜŞEY YÜK · ETRİYE", steps: ["İki yön için uç moment kapasitesi", "Düşey yük ve kapasite kesmesini birleştir", "Etriye hesabını belirleyici kesmeye göre yap"], referenceProfile: "preserve", visualLayout: "flow" },
  { slug: "tbdy-betonarme-kusatilmamis-birlesim", batch: 9, headline: "Kuşatılmış ve Kuşatılmamış Birleşimler", eyebrow: "KİRİŞ · GEOMETRİ · KUŞATMA", steps: ["Kirişleri iki doğrultuda değerlendir", "Kuşatma geometrisini doğrula", "Kuşatılmamış birleşim kesmesini belirle"], referenceProfile: "preserve", visualLayout: "comparison" },
  { slug: "tbdy-betonarme-birlesim-kesme-guvenligi", batch: 9, headline: "Kolon-Kiriş Birleşim Kesme Güvenliği", eyebrow: "ÇEKİRDEK · KESME · DONATI", steps: ["Kiriş kuvvetlerinden birleşim kesmesini çıkar", "Birleşim alanı ve sınıfını seç", "Enine donatının çekirdek içi sürekliliğini göster"], referenceProfile: "preserve", visualLayout: "decision" },
] as const;

export const DEPREM_ROLLOUT_BATCH_10: readonly DepremRolloutSpec[] = [
  { slug: "tbdy-betonarme-perde-kolon-geometri-ayrimi", batch: 10, headline: "Perde ve Kolon Geometri Ayrımı", eyebrow: "KESİT · ORAN · SİSTEM", steps: ["Kesit boyut oranını kontrol et", "Perde sürekliliği ve doğrultusunu izle", "Gerçek perde katkısını sistemde doğrula"], referenceProfile: "preserve", visualLayout: "comparison" },
  { slug: "tbdy-betonarme-perde-kritik-yukseklik-uc-bolge", batch: 10, headline: "Perde Kritik Yüksekliği ve Uç Bölgeleri", eyebrow: "KRİTİK YÜKSEKLİK · UÇ BÖLGE · SARILMA", steps: ["Kritik perde yüksekliğini belirle", "Uç bölge gereksinimini kontrol et", "Kat geçişlerinde uç bölge sürekliliğini izle"], referenceProfile: "preserve", visualLayout: "classification" },
  { slug: "tbdy-betonarme-perde-govde-uc-donati", batch: 10, headline: "Perde Gövde ve Uç Bölgesi Donatısı", eyebrow: "GÖVDE · ÇİFT SIRA · UÇ BÖLGE", steps: ["Yatay-düşey minimum donatıyı kontrol et", "Çift sıra ve bağlantıları göster", "Uç bölgeyi etriye ve çirozla sar"], referenceProfile: "preserve", visualLayout: "classification" },
  { slug: "tbdy-betonarme-perde-moment-kesme-zarfi", batch: 10, headline: "Perde Moment ve Kesme Zarfları", eyebrow: "MOMENT · KESME · TASARIM ZARFI", steps: ["Moment zarfını kritik yükseklikte düzenle", "Kesme kuvvetini kapasite kurallarıyla kontrol et", "Kabuk sonuçlarını kesit kuvvetlerine dönüştür"], referenceProfile: "preserve", visualLayout: "flow" },
  { slug: "tbdy-betonarme-perde-bosluklari-modelleme", batch: 10, headline: "Perde Boşluklarının Modellenmesi", eyebrow: "BOŞLUK · AĞ · KUVVET YOLU", steps: ["Sürekli boşlukları modele aktar", "Boşluk köşelerinde ağ ve gerilmeyi incele", "Ara elemanı doğru taşıyıcı türde tanımla"], referenceProfile: "preserve", visualLayout: "decision" },
  { slug: "tbdy-betonarme-diyafram-toplayici-baslik", batch: 10, headline: "Diyafram, Toplayıcı ve Başlık Donatısı", eyebrow: "DİYAFRAM · TOPLAYICI · BAŞLIK", steps: ["Diyafram kuvvetlerini çıkar", "Toplayıcı bölgeleri tanımla", "Boşluk çevresi başlık donatısını detaylandır"], referenceProfile: "preserve", visualLayout: "flow" },
  { slug: "mevcut-bina-riskli-yapi-ve-bolum-15-farki", batch: 10, headline: "Riskli Yapı Tespiti ve Bölüm 15 Farkı", eyebrow: "AMAÇ · YÖNTEM · RAPOR", steps: ["Hukuki ve teknik amacı tanımla", "Doğru veri ve hesap yöntemini seç", "Rapor kapsamını açıkça belirt"], referenceProfile: "preserve", visualLayout: "comparison" },
  { slug: "mevcut-bina-bilgi-duzeyleri", batch: 10, headline: "Mevcut Binalarda Bilgi Düzeyleri", eyebrow: "BELGE · SAHA · KATSAYI", steps: ["Mevcut belgeleri değerlendir", "Geometri ve donatı tespit kapsamını doğrula", "Bilgi düzeyi katsayısını modelde belgele"], referenceProfile: "preserve", visualLayout: "classification" },
  { slug: "mevcut-bina-tasiyici-rolove-hasar-belgeleme", batch: 10, headline: "Taşıyıcı Rölöve ve Hasar Belgeleme", eyebrow: "ÖLÇÜM · HASAR · İZLENEBİLİRLİK", steps: ["Eleman boyut ve akslarını ölç", "Değişiklik ve boşlukları işaretle", "Hasarı kat-aks-fotoğraf ile ilişkilendir"], referenceProfile: "preserve", visualLayout: "flow" },
  { slug: "mevcut-bina-karot-beton-dayanimi", batch: 10, headline: "Karot ve Mevcut Beton Dayanımı", eyebrow: "NUMUNE · DENEY · DAYANIM", steps: ["Karot sayısını ve dağılımını belirle", "Güvenli numune yerlerini seç", "Deney sonuçlarını düzeltmelerle değerlendir"], referenceProfile: "preserve", visualLayout: "decision" },
  { slug: "mevcut-bina-donati-tespiti-korozyon", batch: 10, headline: "Donatı Tespiti ve Korozyon İncelemesi", eyebrow: "TARAMA · SIYIRMA · KOROZYON", steps: ["Tarama-sıyırma noktalarını dağıt", "Boyuna ve enine donatıyı kaydet", "Kesit kaybı ve pas payını belgele"], referenceProfile: "preserve", visualLayout: "classification" },
  { slug: "mevcut-bina-beklenen-dayanim-bilgi-katsayisi", batch: 10, headline: "Beklenen Dayanım ve Bilgi Katsayısı", eyebrow: "BETON · ÇELİK · KATSAYI", steps: ["Beklenen beton ve çelik dayanımını belirle", "Bilgi katsayısını kapasiteye uygula", "Kabulleri deney raporlarıyla izlenebilir kıl"], referenceProfile: "preserve", visualLayout: "comparison" },
] as const;

export const DEPREM_ROLLOUT_EXTRA_BATCHES: Readonly<Record<number, readonly DepremRolloutSpec[]>> = {
  6: DEPREM_ROLLOUT_BATCH_6,
  7: DEPREM_ROLLOUT_BATCH_7,
  8: DEPREM_ROLLOUT_BATCH_8,
  9: DEPREM_ROLLOUT_BATCH_9,
  10: DEPREM_ROLLOUT_BATCH_10,
};