import { phase3Lines, tbdyPhase3References, PHASE3_UPDATED_AT, type DepremPhase3Override } from "./deprem-phase3-shared";

export const DEPREM_PHASE3_TASARIM_SPEKTRUMU: DepremPhase3Override = {
  slug: "tbdy-tasarim-spektrumu-cizimi",
  description: "TBDY 2018 Denklem 2.2 ve 2.3'e göre yatay elastik tasarım spektrumunun SDS/SD1, TA/TB ve TL=6 s kullanılarak dört periyot bölgesinde nasıl kurulduğunu açıklar.",
  seoTitle: "TBDY 2018 Yatay Elastik Tasarım Spektrumu | Denklem 2.2–2.3",
  seoDescription: "SDS, SD1, TA, TB, TL=6 s ve Sae(T) bağıntılarıyla TBDY 2018 yatay elastik tasarım spektrumunun parça parça kurulması ve proje kontrolü.",
  updatedAt: PHASE3_UPDATED_AT,
  readTime: "12 dk",
  sections: [
    {
      id: "spektrum-girdi-zinciri",
      title: "Spektrum çizimi harita değerinden değil SDS ve SD1 tasarım katsayılarından başlar",
      content: phase3Lines(
        "TBDY 2018 yatay elastik tasarım spektrumunu çizerken ilk kontrol, hangi sayıların eğriye girdiğidir. Haritadan alınan `Ss/S1` doğrudan spektrum ordinatı değildir; yerel zemin katsayıları uygulandıktan sonra elde edilen `SDS` ve `SD1` kullanılır.",
        "",
        "Doğru zincir `DD düzeyi + proje konumu → Ss/S1 → FS/F1 → SDS/SD1 → TA/TB → Sae(T)` şeklindedir. ZF sınıfında ise standart FS/F1 yolu yerine Bölüm 16.5'e göre sahaya özel spektrum gerekir.",
        "",
        "> [!warning] Bozuk veya eski değişken adlarını modele taşımayın",
        "> `SDŞ`, `Sı` gibi encoding/isim bozuklukları teknik değişken değildir. Hesap ve raporda yönetmelikteki `SDS`, `SD1`, `TA`, `TB`, `TL` ve `Sae(T)` gösterimini tutarlı kullanın."
      ),
      subsections: [],
    },
    {
      id: "denklem-2-3",
      title: "Denklem 2.3: TA ve TB, SDS ile SD1 oranından hesaplanır; TL = 6 s sabittir",
      content: phase3Lines(
        "TBDY Denklem (2.3), yatay elastik tasarım spektrumunun iki temel köşe periyodunu tanımlar:",
        "",
        "```formula",
        "@label: TBDY Denklem (2.3) — yatay tasarım spektrumu köşe periyotları",
        "T_A = 0.2 S_D1 / S_DS",
        "T_B = S_D1 / S_DS",
        "@symbol: T_A | Spektrumun birinci köşe periyodu | s",
        "@symbol: T_B | Spektrumun ikinci köşe periyodu | s",
        "@symbol: S_D1 | 1.0 saniye periyot tasarım spektral ivme katsayısı | -",
        "@symbol: S_DS | Kısa periyot tasarım spektral ivme katsayısı | -",
        "```",
        "",
        "Metin gösterimiyle `TA = 0.2 SD1 / SDS` ve `TB = SD1 / SDS`. Uzun periyot geçiş periyodu ise yönetmelikte `TL = 6 s` olarak verilir. Bunlar SOURCE_VALUE kurallarıdır; yazılımın otomatik ürettiği köşe periyotları bu bağıntılarla çapraz kontrol edilmelidir.",
        "",
        "> [!check] Birim",
        "> SDS ve SD1 boyutsuz olduğu için TA ve TB saniye cinsinden periyot değeridir."
      ),
      subsections: [],
    },
    {
      id: "denklem-2-2",
      title: "Denklem 2.2: Sae(T) dört periyot bölgesinde farklı bağıntıyla hesaplanır",
      content: phase3Lines(
        "TBDY **Denklem (2.2)** yatay elastik tasarım spektral ivmesini `Sae(T)` dört parçalı olarak tanımlar:",
        "",
        "| Periyot bölgesi | Sae(T) bağıntısı | Davranış |",
        "|---|---|---|",
        "| 0 ≤ T ≤ TA | `Sae(T) = (0.4 + 0.6 T / TA) SDS` | Başlangıçtan platoya doğrusal yükseliş |",
        "| TA ≤ T ≤ TB | `Sae(T) = SDS` | Sabit ivme platosu |",
        "| TB ≤ T ≤ TL | `Sae(T) = SD1 / T` | Periyotla ters orantılı azalma |",
        "| TL ≤ T | `Sae(T) = SD1 TL / T²` | Uzun periyotta 1/T² azalma |",
        "",
        "Eğriyi yalnız birkaç noktayı serbestçe birleştirerek çizmek yerine her periyot aralığında kendi yönetmelik bağıntısını kullanın. Köşe noktalarında ifadeler birbirini sürekli biçimde karşılamalıdır.",
        "",
        "> [!engineering] Parça sınırları",
        "> T tam TA, TB veya TL değerindeyken komşu bağıntıların aynı ordinatı verdiğini kontrol etmek hem formül hem kod uygulaması için etkili bir birim testidir."
      ),
      subsections: [],
    },
    {
      id: "sayisal-ornek",
      title: "Sayısal kontrol örneği: SDS = 1.10 ve SD1 = 0.76 için köşe periyotları",
      content: phase3Lines(
        "Yerel zemin örneğindeki `SDS = 1.10` ve `SD1 = 0.76` değerlerini kullanalım:",
        "",
        "- `TA = 0.2 × 0.76 / 1.10 ≈ 0.138 s`.",
        "- `TB = 0.76 / 1.10 ≈ 0.691 s`.",
        "- `TL = 6 s`.",
        "- `TA ≤ T ≤ TB` aralığında spektrum platosu `Sae(T) = 1.10` olur.",
        "- Örneğin `T = 1.0 s`, TB ile TL arasında olduğundan `Sae(1.0) = SD1 / T = 0.76` olur.",
        "",
        "Bu örnek aritmetik kontrol içindir; gerçek projede SDS ve SD1 proje konumu, DD düzeyi ve zemin sınıfından yeniden üretilmelidir.",
        "",
        "> [!check] Köşe periyodu sırası",
        "> Pozitif SDS/SD1 için `TA = 0.2 TB` ilişkisi vardır. Hesap çıktısında TA'nın TB'den büyük görünmesi girdi veya formül hatasına işaret eder."
      ),
      subsections: [],
    },
    {
      id: "yazilim-model-aktarimi",
      title: "Analiz yazılımına aktarımda DD, sönüm, zemin ve birim bilgisi aynı spektrumla eşleşmelidir",
      content: phase3Lines(
        "Bir spektrum eğrisinin şekli doğru olsa bile yanlış DD düzeyi, yanlış yerel zemin sınıfı veya yanlış sönüm kabulü ile analiz girdisi hatalı olabilir. Standart TBDY spektrumu **%5 sönüm** için tanımlanır; farklı sönüm gerektiren özel sistemlerde ilgili yönetmelik hükümleri ayrıca uygulanır.",
        "",
        "Analiz programına kullanıcı tanımlı spektrum giriliyorsa periyot biriminin saniye, ordinat tanımının ise programın beklediği ivme/yerçekimi formatıyla uyumlu olduğu kontrol edilmelidir. Yönetmelik katsayılarını yazılımın kendi birim ölçeklemesiyle iki kez çarpmayın.",
        "",
        "> [!warning] Grafik benziyor diye kabul etmeyin",
        "> Spektrum QA'sı görsel benzerlikle bitmez; TA, TB, TL ve seçilmiş birkaç T noktasındaki sayısal Sae(T) değerleri bağımsız hesapla doğrulanmalıdır."
      ),
      subsections: [],
    },
    {
      id: "spektrum-kalite-kapisi",
      title: "Spektrum kalite kapısı: köşe noktaları, süreklilik ve kaynak girdileri birlikte test edilir",
      content: phase3Lines(
        "Minimum bağımsız kontrol seti şu noktaları içermelidir:",
        "",
        "| Kontrol noktası | Beklenen değer |",
        "|---|---|",
        "| T = 0 | `0.4 SDS` |",
        "| T = TA | `SDS` |",
        "| T = TB | `SDS = SD1 / TB` |",
        "| T = TL | `SD1 / TL` |",
        "| T > TL | `SD1 TL / T²` |",
        "",
        "Bu testler hem elle çizilen eğriyi hem Excel/kod/yazılım üretimini denetler. Ayrıca kaynak `Ss/S1`, kullanılan `FS/F1` ve nihai `SDS/SD1` değerleri rapor başında görünür tutulmalıdır.",
        "",
        "> [!engineering] Regresyon testi",
        "> Spektrum hesaplayan bir yazılım aracı geliştiriliyorsa TA, TB ve sınır noktaları için otomatik testler eklemek, parça geçişi hatalarını erken yakalar."
      ),
      subsections: [],
    },
    {
      id: "kontrol-listesi",
      title: "Proje kontrol listesi",
      content: phase3Lines(
        "- Spektrum girdisi olarak Ss/S1 yerine doğru SDS/SD1 değerleri kullanıldı mı?",
        "- `TA = 0.2 SD1 / SDS` ve `TB = SD1 / SDS` Denklem (2.3)'e göre doğrulandı mı?",
        "- `TL = 6 s` kullanıldı mı?",
        "- Denklem (2.2)'nin `0 ≤ T ≤ TA`, `TA ≤ T ≤ TB`, `TB ≤ T ≤ TL` ve `TL ≤ T` bölgeleri eksiksiz uygulandı mı?",
        "- `Sae(T) = SD1 / T` bölgesi doğru TB–TL aralığında mı?",
        "- T = 0, TA, TB ve TL sınırlarında spektrum sürekliliği kontrol edildi mi?",
        "- DD düzeyi, proje konumu, zemin sınıfı ve %5 sönüm kabulü spektrumla aynı mı?",
        "- Analiz yazılımındaki periyot ve ordinat birimleri bağımsız hesapla doğrulandı mı?",
        "- ZF sınıfında standart FS/F1 spektrumu yerine Bölüm 16.5 sahaya özel analiz kullanıldı mı?"
      ),
      subsections: [],
    },
  ],
  references: tbdyPhase3References("Bölüm 2; Madde 2.3.1–2.3.3, Denklem (2.2), Denklem (2.3) ve Şekil 2.1"),
  keywords: ["TBDY 2018", "tasarım spektrumu", "SDS", "SD1", "TA", "TB", "TL", "Sae(T)", "Denklem 2.2", "Denklem 2.3"],
  tags: ["TBDY 2018", "Tasarım Spektrumu", "SDS", "SD1", "Köşe Periyotları"],
};
