import type { DepremRolloutSpec } from "./deprem-rollout";

export const DEPREM_ROLLOUT_BATCH_6: readonly DepremRolloutSpec[] = [
  {
    slug: "yagmur-suyu-drenaji-ve-sizma-tesisi-hesabi",
    batch: 6,
    headline: "Yağmur Suyu Drenajı ve Sızdırma Tesisi",
    eyebrow: "YAĞIŞ · DRENAJ · DEŞARJ",
    steps: ["Yağış ve yüzey verisi", "Drenaj debisi ve güzergâh", "Sızdırma veya deşarj kararı"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "engelsiz-tekerlekli-sandalye-manevra-alani-koridor-genislikleri",
    batch: 6,
    headline: "Tekerlekli Sandalye Manevra Alanı ve Koridorlar",
    eyebrow: "MANEVRA · KORİDOR · NET ÖLÇÜ",
    steps: ["Manevra alanı", "Koridor net genişliği", "Dönüş ve geçiş sürekliliği"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "engelsiz-rampa-egimi-korkuluk-yuzey-standartlari",
    batch: 6,
    headline: "Engelsiz Rampalarda Eğim, Korkuluk ve Yüzey",
    eyebrow: "EĞİM · KORKULUK · YÜZEY",
    steps: ["Rampa geometrisi", "Korkuluk ve kenar koruması", "Kaymaz yüzey ve sahanlık"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "engelsiz-wc-asansor-kapi-boyutlari",
    batch: 6,
    headline: "Engelsiz WC, Asansör ve Kapı Boyutları",
    eyebrow: "WC · ASANSÖR · KAPI",
    steps: ["Islak hacim net alanı", "Asansör kabini ve önü", "Kapı net geçişi"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "engelsiz-yapi-ruhsatinda-uyum-kontrolu",
    batch: 6,
    headline: "Yapı Ruhsatında Erişilebilirlik Uyum Kontrolü",
    eyebrow: "GÜZERGÂH · PROJE · RUHSAT",
    steps: ["Kesintisiz erişilebilir güzergâh", "Net ölçü ve detay kontrolü", "Ruhsat eki proje uyumu"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "eurocode-ts-en-1990-yuk-kombinasyonlari-ve-guvenlik-katsayilari",
    batch: 6,
    headline: "TS EN 1990 Yük Birleşimleri ve Güvenlik Katsayıları",
    eyebrow: "ETKİ · KATSAYI · BİRLEŞİM",
    steps: ["Tasarım durumunu belirle", "Etki ve güvenlik katsayıları", "Yük birleşimini oluştur"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1991-1-1-hareketli-yukler-bolume-gore-degerler",
    batch: 6,
    headline: "TS EN 1991-1-1 Hareketli Yükler",
    eyebrow: "KULLANIM · KATEGORİ · YÜK",
    steps: ["Kullanım alanını belirle", "Yük kategorisini seç", "Karakteristik yükü uygula"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
  {
    slug: "eurocode-ts-en-1991-1-3-kar-yuku-hesabi-bolge-haritasi-ile",
    batch: 6,
    headline: "TS EN 1991-1-3 Kar Yükü Hesabı",
    eyebrow: "BÖLGE · ÇATI · KAR YÜKÜ",
    steps: ["Yer ve iklim girdileri", "Çatı biçimi ve katsayılar", "Tasarım kar yükü"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1991-1-4-ruzgar-yuku-hesabi-turkiye-bolgeleri",
    batch: 6,
    headline: "TS EN 1991-1-4 Rüzgâr Yükü Hesabı",
    eyebrow: "RÜZGÂR · ARAZİ · BASINÇ",
    steps: ["Rüzgâr ve arazi girdileri", "Yapı geometrisi ve katsayılar", "Basınç ve yük etkisi"],
    referenceProfile: "preserve",
    visualLayout: "flow",
  },
  {
    slug: "eurocode-ts-en-1992-1-1-ec2-ts-500-ile-karsilastirmali-analiz",
    batch: 6,
    headline: "TS EN 1992-1-1 ve TS 500 Karşılaştırması",
    eyebrow: "EC2 · TS 500 · TASARIM",
    steps: ["Kapsam ve tasarım kabulleri", "Malzeme ve güvenlik yaklaşımı", "Kesit ve detay sonuçları"],
    referenceProfile: "preserve",
    visualLayout: "comparison",
  },
  {
    slug: "akustik-ts-en-iso-12354-ile-yalitim-hesabi",
    batch: 6,
    headline: "TS EN ISO 12354 ile Ses Yalıtımı Hesabı",
    eyebrow: "HEDEF · ELEMAN · PERFORMANS",
    steps: ["Hedef akustik performans", "Ayırıcı eleman ve birleşimler", "Beklenen yerinde performans"],
    referenceProfile: "preserve",
    visualLayout: "decision",
  },
  {
    slug: "asansor-boslugu-boyutlandirma-kapasite-alan-tablosu",
    batch: 6,
    headline: "Asansör Kuyusu Boyutlandırması ve Kapasite",
    eyebrow: "KAPASİTE · KABİN · KUYU",
    steps: ["Kapasite ve kullanım", "Kabin ve kapı ölçüleri", "Kuyu ve sahanlık yerleşimi"],
    referenceProfile: "preserve",
    visualLayout: "classification",
  },
] as const;

export const DEPREM_ROLLOUT_EXTRA_BATCHES: Readonly<Record<number, readonly DepremRolloutSpec[]>> = {
  6: DEPREM_ROLLOUT_BATCH_6,
};
