import { TOOLS, type ToolDefinition } from "./tools-data";

export type ToolImplementationStatus =
  | "placeholder"
  | "implemented"
  | "verified"
  | "live";

export type ToolImplementationKind =
  | "dedicated-route"
  | "registry-rendered";

export interface ToolImplementationRecord {
  id: string;
  name: string;
  status: ToolImplementationStatus;
  kind: ToolImplementationKind;
  route: string;
  enginePath?: string;
  componentPath?: string;
  normativeReference?: string;
  tier: "A" | "B" | "C";
  hasDedicatedPage: boolean;
}

export const TOOL_REGISTRY: Record<string, ToolImplementationRecord> = {
  "donati-hesabi": {
    id: "donati-hesabi",
    name: "Donatı Hesabı",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/donati-hesabi",
    enginePath: "src/lib/rebar-calculations.ts",
    componentPath: "src/components/rebar-calculator.tsx",
    normativeReference: "TS 500 / TS 708",
    tier: "B",
    hasDedicatedPage: true,
  },
  "kolon-on-boyutlandirma": {
    id: "kolon-on-boyutlandirma",
    name: "Kolon Ön Boyutlandırma",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/kolon-on-boyutlandirma",
    enginePath: "src/lib/concrete-tools/column.ts",
    componentPath: "src/components/column-preliminary-sizing-calculator.tsx",
    normativeReference: "TS 500 Madde 7.4",
    tier: "A",
    hasDedicatedPage: true,
  },
  "kiris-kesiti": {
    id: "kiris-kesiti",
    name: "Kiriş Kesiti",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/kiris-kesiti",
    enginePath: "src/lib/concrete-tools/beam.ts",
    componentPath: "src/components/beam-section-calculator.tsx",
    normativeReference: "TS 500 Madde 7.1",
    tier: "A",
    hasDedicatedPage: true,
  },
  "doseme-kalinligi": {
    id: "doseme-kalinligi",
    name: "Döşeme Kalınlığı",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/doseme-kalinligi",
    enginePath: "src/lib/concrete-tools/slab.ts",
    componentPath: "src/components/slab-thickness-calculator.tsx",
    normativeReference: "TS 500 Madde 11.2",
    tier: "B",
    hasDedicatedPage: true,
  },
  "pas-payi": {
    id: "pas-payi",
    name: "Pas Payı",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/pas-payi",
    enginePath: "src/lib/concrete-tools/cover.ts",
    componentPath: "src/components/concrete-cover-calculator.tsx",
    normativeReference: "TS 500 / TS EN 1992-1-1",
    tier: "B",
    hasDedicatedPage: true,
  },
  "zimbalama-kontrolu": {
    id: "zimbalama-kontrolu",
    name: "Döşeme Zımbalama Kontrolü",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/zimbalama-kontrolu",
    enginePath: "src/lib/concrete-tools/punching.ts",
    componentPath: "src/components/punching-calculator.tsx",
    normativeReference: "TS 500 Madde 8.3",
    tier: "A",
    hasDedicatedPage: true,
  },
  "kiris-kesme-etriye": {
    id: "kiris-kesme-etriye",
    name: "Kiriş Kesme & Etriye Hesabı",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/kiris-kesme-etriye",
    enginePath: "src/lib/concrete-tools/shear-stirrup.ts",
    componentPath: "src/components/shear-stirrup-calculator.tsx",
    normativeReference: "TS 500 Madde 8.1",
    tier: "A",
    hasDedicatedPage: true,
  },
  "kenetlenme-boyu": {
    id: "kenetlenme-boyu",
    name: "Donatı Kenetlenme & Ek Boyu",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/kenetlenme-boyu",
    enginePath: "src/lib/concrete-tools/splice.ts",
    componentPath: "src/components/splice-calculator.tsx",
    normativeReference: "TS 500 Madde 9.1",
    tier: "A",
    hasDedicatedPage: true,
  },
  "taban-kesme-kuvveti": {
    id: "taban-kesme-kuvveti",
    name: "Eşdeğer Deprem Yükü",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/taban-kesme-kuvveti",
    enginePath: "src/lib/engineering/tbdy2018/base-shear.ts",
    componentPath: "src/components/seismic-base-shear-calculator.tsx",
    normativeReference: "TBDY 2018 Bölüm 4.7",
    tier: "A",
    hasDedicatedPage: true,
  },
  "duzensizlik-kontrolu": {
    id: "duzensizlik-kontrolu",
    name: "Düzensizlik Kontrolü",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/duzensizlik-kontrolu",
    enginePath: "src/lib/engineering/tbdy2018/irregularity.ts",
    componentPath: "src/components/irregularity-calculator.tsx",
    normativeReference: "TBDY 2018 Tablo 3.6",
    tier: "A",
    hasDedicatedPage: false,
  },
  "zemin-sinifi": {
    id: "zemin-sinifi",
    name: "Yerel Zemin Sınıfı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/zemin-sinifi",
    enginePath: "src/lib/engineering/tbdy2018/soil-class.ts",
    componentPath: "src/components/soil-class-calculator.tsx",
    normativeReference: "TBDY 2018 Tablo 16.1",
    tier: "B",
    hasDedicatedPage: false,
  },
  "deprem-periyot-hesabi": {
    id: "deprem-periyot-hesabi",
    name: "Ampirik Periyot & Elastik Spektrum",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/deprem-periyot-hesabi",
    enginePath: "src/lib/engineering/tbdy2018/period.ts",
    componentPath: "src/components/seismic-period-calculator.tsx",
    normativeReference: "TBDY 2018 Bölüm 4.8.4 & Bölüm 2",
    tier: "A",
    hasDedicatedPage: true,
  },
  "goreli-kat-otelemesi": {
    id: "goreli-kat-otelemesi",
    name: "Göreli Kat Ötelemesi (Drift)",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/goreli-kat-otelemesi",
    enginePath: "src/lib/engineering/tbdy2018/drift.ts",
    componentPath: "src/components/drift-calculator.tsx",
    normativeReference: "TBDY 2018 Bölüm 4.9 & Tablo 4.3",
    tier: "A",
    hasDedicatedPage: true,
  },
  "radye-temel-hesabi": {
    id: "radye-temel-hesabi",
    name: "Radye Temel Kalınlık & Zımbalama",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/radye-temel-hesabi",
    enginePath: "src/lib/concrete-tools/mat-foundation.ts",
    componentPath: "src/components/mat-foundation-calculator.tsx",
    normativeReference: "TS 500 / TBDY 2018 Bölüm 16",
    tier: "A",
    hasDedicatedPage: false,
  },
  "iksa-toprak-basinci": {
    id: "iksa-toprak-basinci",
    name: "İksa Perdesi Toprak Basıncı",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/iksa-toprak-basinci",
    enginePath: "src/lib/engineering/geotech/retaining-wall.ts",
    componentPath: "src/components/retaining-wall-calculator.tsx",
    normativeReference: "Rankine & Coulomb",
    tier: "A",
    hasDedicatedPage: true,
  },
  "sev-stabilitesi": {
    id: "sev-stabilitesi",
    name: "Şev Stabilitesi Güvenlik Katsayısı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/sev-stabilitesi",
    enginePath: "src/lib/engineering/geotech/slope-stability.ts",
    componentPath: "src/components/slope-stability-calculator.tsx",
    normativeReference: "Fellenius Dilim Yöntemi",
    tier: "A",
    hasDedicatedPage: false,
  },
  "celik-profil-secimi": {
    id: "celik-profil-secimi",
    name: "Çelik Profil Seçimi & Narinlik",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/celik-profil-secimi",
    enginePath: "src/lib/engineering/steel/profile-selection.ts",
    componentPath: "src/components/steel-profile-calculator.tsx",
    normativeReference: "ÇYTHYE 2018 / TS EN 1993-1-1",
    tier: "A",
    hasDedicatedPage: false,
  },
  "celik-birlestesi-hesabi": {
    id: "celik-birlestesi-hesabi",
    name: "Çelik Cıvata & Kaynak Hesabı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/celik-birlestesi-hesabi",
    enginePath: "src/lib/engineering/steel/connection.ts",
    componentPath: "src/components/steel-connection-calculator.tsx",
    normativeReference: "ÇYTHYE 2018 Bölüm 13",
    tier: "A",
    hasDedicatedPage: false,
  },
  "ahsap-eleman-hesabi": {
    id: "ahsap-eleman-hesabi",
    name: "Ahşap Kiriş & Dikme Taşıma Gücü",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/ahsap-eleman-hesabi",
    enginePath: "src/lib/engineering/timber/timber-member.ts",
    componentPath: "src/components/timber-member-calculator.tsx",
    normativeReference: "TS 647 / TS EN 1995-1-1",
    tier: "A",
    hasDedicatedPage: false,
  },
  "kalip-sokum-suresi": {
    id: "kalip-sokum-suresi",
    name: "Kalıp Söküm Süresi",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/kalip-sokum-suresi",
    componentPath: "src/app/araclar/kalip-sokum-suresi/page.tsx",
    normativeReference: "TS 500 / TS EN 13670",
    tier: "B",
    hasDedicatedPage: true,
  },
  "dis-cephe-yalitim-kalinligi": {
    id: "dis-cephe-yalitim-kalinligi",
    name: "Dış Cephe Yalıtım Kalınlığı",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/dis-cephe-yalitim-kalinligi",
    enginePath: "src/lib/ts825/calculator.ts",
    componentPath: "src/components/external-wall-insulation-calculator.tsx",
    normativeReference: "TS 825:2024",
    tier: "B",
    hasDedicatedPage: true,
  },
  "imar-hesaplayici": {
    id: "imar-hesaplayici",
    name: "İmar Hesaplayıcı",
    status: "verified",
    kind: "dedicated-route",
    route: "/kategori/araclar/imar-hesaplayici",
    enginePath: "src/lib/imar/calculator.ts",
    componentPath: "src/components/imar-calculator.tsx",
    normativeReference: "Planlı Alanlar İmar Yönetmeliği",
    tier: "B",
    hasDedicatedPage: true,
  },
  "beton-metraj-hesabi": {
    id: "beton-metraj-hesabi",
    name: "Şantiye Beton & Harç Metrajı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/beton-metraj-hesabi",
    enginePath: "src/lib/engineering/quantity/concrete-volume.ts",
    componentPath: "src/components/concrete-quantity-calculator.tsx",
    normativeReference: "ÇŞİDB Metraj Esasları",
    tier: "C",
    hasDedicatedPage: false,
  },
  "hafriyat-metraj-hesabi": {
    id: "hafriyat-metraj-hesabi",
    name: "Hafriyat & Kamyon Sefer",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/hafriyat-metraj-hesabi",
    enginePath: "src/lib/engineering/quantity/excavation.ts",
    componentPath: "src/components/excavation-quantity-calculator.tsx",
    normativeReference: "Toprak İşleri Kabarma Normları",
    tier: "C",
    hasDedicatedPage: false,
  },
  "pratik-donati-metraji": {
    id: "pratik-donati-metraji",
    name: "Pratik Demir Metrajı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/pratik-donati-metraji",
    enginePath: "src/lib/engineering/quantity/rebar-ratio.ts",
    componentPath: "src/components/rebar-quantity-calculator.tsx",
    normativeReference: "Şantiye Pursantaj Standartları",
    tier: "C",
    hasDedicatedPage: false,
  },
  "pratik-kalip-metraji": {
    id: "pratik-kalip-metraji",
    name: "Pratik Kalıp Metrajı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/pratik-kalip-metraji",
    enginePath: "src/lib/engineering/quantity/formwork-ratio.ts",
    componentPath: "src/components/formwork-quantity-calculator.tsx",
    normativeReference: "Şantiye Kalıp Katsayıları",
    tier: "C",
    hasDedicatedPage: false,
  },
  "duvar-metraji-hesabi": {
    id: "duvar-metraji-hesabi",
    name: "Duvar & Tuğla Metrajı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/duvar-metraji-hesabi",
    enginePath: "src/lib/engineering/quantity/masonry.ts",
    componentPath: "src/components/masonry-quantity-calculator.tsx",
    normativeReference: "TS EN 771 Blok Standartları",
    tier: "C",
    hasDedicatedPage: false,
  },
  "siva-boya-metraji": {
    id: "siva-boya-metraji",
    name: "Sıva & Boya Metrajı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/siva-boya-metraji",
    enginePath: "src/lib/engineering/quantity/plaster-paint.ts",
    componentPath: "src/components/plaster-paint-calculator.tsx",
    normativeReference: "TS 1481 Sarfiyat Normları",
    tier: "C",
    hasDedicatedPage: false,
  },
  "cati-kaplama-metraji": {
    id: "cati-kaplama-metraji",
    name: "Çatı & Ahşap Metrajı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/cati-kaplama-metraji",
    enginePath: "src/lib/engineering/quantity/roof-covering.ts",
    componentPath: "src/components/roof-covering-calculator.tsx",
    normativeReference: "Çatı Kaplama ve Eğim Geometrisi",
    tier: "C",
    hasDedicatedPage: false,
  },
  "seramik-fayans-metraji": {
    id: "seramik-fayans-metraji",
    name: "Seramik & Fayans Metrajı",
    status: "verified",
    kind: "registry-rendered",
    route: "/kategori/araclar/seramik-fayans-metraji",
    enginePath: "src/lib/engineering/quantity/tile-flooring.ts",
    componentPath: "src/components/tile-quantity-calculator.tsx",
    normativeReference: "TS EN 14411 / TS EN 12004",
    tier: "C",
    hasDedicatedPage: false,
  },
};

export function getToolImplementation(id: string): ToolImplementationRecord | undefined {
  return TOOL_REGISTRY[id];
}

export function isToolVerified(id: string): boolean {
  const tool = TOOL_REGISTRY[id];
  return tool ? tool.status === "verified" || tool.status === "live" : false;
}

export function isToolImplemented(id: string): boolean {
  const tool = TOOL_REGISTRY[id];
  return tool ? tool.status !== "placeholder" : false;
}
