import type { ToolDefinition } from "./tools-data";

export type ToolTier = "A" | "B" | "C";

export interface ToolVerificationEvidence {
  toolId: string;
  tier: ToolTier;
  enginePath: string;
  componentPath: string;
  engineTestFiles: string[];
  referenceFixtureSource?: string;
  hasAdversarialCoverage: boolean;
  hasBrowserSmokeCoverage: boolean;
  requiresNormativeSource: boolean;
  provenanceDocument?: string;
}

export const TOOL_EVIDENCE_REQUIREMENTS: Record<string, ToolVerificationEvidence> = {
  "donati-hesabi": {
    toolId: "donati-hesabi",
    tier: "B",
    enginePath: "src/lib/rebar-calculations.ts",
    componentPath: "src/components/rebar-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-existing.ts"],
    referenceFixtureSource: "TS 708 / TS 500",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "kolon-on-boyutlandirma": {
    toolId: "kolon-on-boyutlandirma",
    tier: "A",
    enginePath: "src/lib/concrete-tools/column.ts",
    componentPath: "src/components/column-preliminary-sizing-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-regression-baseline.ts"],
    referenceFixtureSource: "TS 500 Madde 7.4",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
    provenanceDocument: "docs/tools/corrections/column-rebar-mass.md",
  },
  "kiris-kesiti": {
    toolId: "kiris-kesiti",
    tier: "A",
    enginePath: "src/lib/concrete-tools/beam.ts",
    componentPath: "src/components/beam-section-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-regression-baseline.ts"],
    referenceFixtureSource: "TS 500 Madde 7.1",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "doseme-kalinligi": {
    toolId: "doseme-kalinligi",
    tier: "A",
    enginePath: "src/lib/concrete-tools/slab.ts",
    componentPath: "src/components/slab-thickness-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-regression-baseline.ts"],
    referenceFixtureSource: "TS 500 Madde 11.2",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "pas-payi": {
    toolId: "pas-payi",
    tier: "A",
    enginePath: "src/lib/concrete-tools/cover.ts",
    componentPath: "src/components/concrete-cover-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-regression-baseline.ts"],
    referenceFixtureSource: "TS EN 1992-1-1 / TS 500",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "zimbalama-kontrolu": {
    toolId: "zimbalama-kontrolu",
    tier: "A",
    enginePath: "src/lib/concrete-tools/punching.ts",
    componentPath: "src/components/punching-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-concrete-phase4.ts"],
    referenceFixtureSource: "TS 500 Madde 8.3 & TBDY 2018",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "kiris-kesme-etriye": {
    toolId: "kiris-kesme-etriye",
    tier: "A",
    enginePath: "src/lib/concrete-tools/shear-stirrup.ts",
    componentPath: "src/components/shear-stirrup-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-concrete-phase4.ts"],
    referenceFixtureSource: "TS 500 Madde 8.1 & TBDY 2018 7.4",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "kenetlenme-boyu": {
    toolId: "kenetlenme-boyu",
    tier: "A",
    enginePath: "src/lib/concrete-tools/splice.ts",
    componentPath: "src/components/splice-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-concrete-phase4.ts"],
    referenceFixtureSource: "TS 500 Madde 9.1 & 9.2",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "taban-kesme-kuvveti": {
    toolId: "taban-kesme-kuvveti",
    tier: "A",
    enginePath: "src/lib/engineering/tbdy2018/base-shear.ts",
    componentPath: "src/components/seismic-base-shear-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-existing.ts"],
    referenceFixtureSource: "TBDY 2018 Bölüm 4.7",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "duzensizlik-kontrolu": {
    toolId: "duzensizlik-kontrolu",
    tier: "A",
    enginePath: "src/lib/engineering/tbdy2018/irregularity.ts",
    componentPath: "src/components/irregularity-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-earthquake-geotech-phase5.ts"],
    referenceFixtureSource: "TBDY 2018 Tablo 3.6",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "zemin-sinifi": {
    toolId: "zemin-sinifi",
    tier: "A",
    enginePath: "src/lib/engineering/tbdy2018/soil-class.ts",
    componentPath: "src/components/soil-class-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-earthquake-geotech-phase5.ts"],
    referenceFixtureSource: "TBDY 2018 Tablo 16.1",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "deprem-periyot-hesabi": {
    toolId: "deprem-periyot-hesabi",
    tier: "A",
    enginePath: "src/lib/engineering/tbdy2018/period.ts",
    componentPath: "src/components/seismic-period-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-existing.ts"],
    referenceFixtureSource: "TBDY 2018 Madde 4.7.3 & Bölüm 2",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "goreli-kat-otelemesi": {
    toolId: "goreli-kat-otelemesi",
    tier: "A",
    enginePath: "src/lib/engineering/tbdy2018/drift.ts",
    componentPath: "src/components/drift-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-earthquake-geotech-phase5.ts"],
    referenceFixtureSource: "TBDY 2018 Madde 4.9.1 & Tablo 4.3",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "radye-temel-hesabi": {
    toolId: "radye-temel-hesabi",
    tier: "A",
    enginePath: "src/lib/concrete-tools/mat-foundation.ts",
    componentPath: "src/components/mat-foundation-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-concrete-phase4.ts"],
    referenceFixtureSource: "TS 500 / TBDY 2018 Bölüm 15",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "iksa-toprak-basinci": {
    toolId: "iksa-toprak-basinci",
    tier: "A",
    enginePath: "src/lib/engineering/geotech/retaining-wall.ts",
    componentPath: "src/components/retaining-wall-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-earthquake-geotech-phase5.ts"],
    referenceFixtureSource: "TBDY 2018 Bölüm 16.6 / Rankine & Coulomb",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "sev-stabilitesi": {
    toolId: "sev-stabilitesi",
    tier: "A",
    enginePath: "src/lib/engineering/geotech/slope-stability.ts",
    componentPath: "src/components/slope-stability-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-earthquake-geotech-phase5.ts"],
    referenceFixtureSource: "TBDY 2018 Bölüm 16.8 / Fellenius (OMS)",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "celik-profil-secimi": {
    toolId: "celik-profil-secimi",
    tier: "A",
    enginePath: "src/lib/engineering/steel/profile-selection.ts",
    componentPath: "src/components/steel-profile-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-steel-timber-phase6.ts"],
    referenceFixtureSource: "ÇYTHYE 2018 Bölüm 8",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "celik-birlestesi-hesabi": {
    toolId: "celik-birlestesi-hesabi",
    tier: "A",
    enginePath: "src/lib/engineering/steel/connection.ts",
    componentPath: "src/components/steel-connection-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-steel-timber-phase6.ts"],
    referenceFixtureSource: "ÇYTHYE 2018 Bölüm 13",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "ahsap-eleman-hesabi": {
    toolId: "ahsap-eleman-hesabi",
    tier: "A",
    enginePath: "src/lib/engineering/timber/timber-member.ts",
    componentPath: "src/components/timber-member-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-steel-timber-phase6.ts"],
    referenceFixtureSource: "TS EN 1995-1-1 (Eurocode 5)",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "kalip-sokum-suresi": {
    toolId: "kalip-sokum-suresi",
    tier: "B",
    enginePath: "src/lib/concrete-tools/stripping.ts",
    componentPath: "src/app/araclar/kalip-sokum-suresi/page.tsx",
    engineTestFiles: ["scripts/check-tools-existing.ts"],
    referenceFixtureSource: "TS 500 Madde 13.3",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "dis-cephe-yalitim-kalinligi": {
    toolId: "dis-cephe-yalitim-kalinligi",
    tier: "B",
    enginePath: "src/lib/ts825/calculator.ts",
    componentPath: "src/components/external-wall-insulation-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-existing.ts"],
    referenceFixtureSource: "TS 825:2024",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "imar-hesaplayici": {
    toolId: "imar-hesaplayici",
    tier: "B",
    enginePath: "src/lib/imar/calculator.ts",
    componentPath: "src/components/imar-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-existing.ts"],
    referenceFixtureSource: "Planlı Alanlar İmar Yönetmeliği",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: true,
  },
  "beton-metraj-hesabi": {
    toolId: "beton-metraj-hesabi",
    tier: "C",
    enginePath: "src/lib/engineering/quantity/concrete-volume.ts",
    componentPath: "src/components/concrete-quantity-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-quantity-phase7-8.ts"],
    referenceFixtureSource: "Geometrik Hacim & ÇŞB Poz Standartları",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: false,
  },
  "hafriyat-metraj-hesabi": {
    toolId: "hafriyat-metraj-hesabi",
    tier: "C",
    enginePath: "src/lib/engineering/quantity/excavation.ts",
    componentPath: "src/components/excavation-quantity-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-quantity-phase7-8.ts"],
    referenceFixtureSource: "Geometrik Prizma & Kabarma Katsayısı",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: false,
  },
  "pratik-donati-metraji": {
    toolId: "pratik-donati-metraji",
    tier: "C",
    enginePath: "src/lib/engineering/quantity/rebar-ratio.ts",
    componentPath: "src/components/rebar-quantity-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-quantity-phase7-8.ts"],
    referenceFixtureSource: "Yapı Yaklaşık Maliyet & Pursantaj İstatistikleri",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: false,
  },
  "pratik-kalip-metraji": {
    toolId: "pratik-kalip-metraji",
    tier: "C",
    enginePath: "src/lib/engineering/quantity/formwork-ratio.ts",
    componentPath: "src/components/formwork-quantity-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-quantity-phase7-8.ts"],
    referenceFixtureSource: "Kalıp Açınımı & Kat Katsayıları",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: false,
  },
  "duvar-metraji-hesabi": {
    toolId: "duvar-metraji-hesabi",
    tier: "C",
    enginePath: "src/lib/engineering/quantity/masonry.ts",
    componentPath: "src/components/masonry-quantity-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-quantity-phase7-8.ts"],
    referenceFixtureSource: "Tuğla/Gazbeton Birim Sarfiyat Standartları",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: false,
  },
  "siva-boya-metraji": {
    toolId: "siva-boya-metraji",
    tier: "C",
    enginePath: "src/lib/engineering/quantity/plaster-paint.ts",
    componentPath: "src/components/plaster-paint-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-quantity-phase7-8.ts"],
    referenceFixtureSource: "Sıva/Boya Yüzey & Tüketim Standartları",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: false,
  },
  "cati-kaplama-metraji": {
    toolId: "cati-kaplama-metraji",
    tier: "C",
    enginePath: "src/lib/engineering/quantity/roof-covering.ts",
    componentPath: "src/components/roof-covering-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-quantity-phase7-8.ts"],
    referenceFixtureSource: "Çatı Eğim Açınımı & Kiremit/Mahya Sarfiyatı",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: false,
  },
  "seramik-fayans-metraji": {
    toolId: "seramik-fayans-metraji",
    tier: "C",
    enginePath: "src/lib/engineering/quantity/tile-flooring.ts",
    componentPath: "src/components/tile-quantity-calculator.tsx",
    engineTestFiles: ["scripts/check-tools-quantity-phase7-8.ts"],
    referenceFixtureSource: "Kaplama Alanı & Kutu/Derz/Yapıştırıcı Normları",
    hasAdversarialCoverage: true,
    hasBrowserSmokeCoverage: true,
    requiresNormativeSource: false,
  },
};
