export type CalculationKind =
  | 'preliminary'
  | 'check'
  | 'classification'
  | 'quantity'
  | 'estimate';

export type ToolTier = 'A' | 'B' | 'C';

export interface ToolPublicMeta {
  id: string;
  title: string;
  shortDescription: string;
  calculationKind: CalculationKind;
  tier: ToolTier;
  scope: string[];
  limitations: string[];
  sourceLabels: string[];
}

export const TOOLS_PUBLIC_METADATA: Record<string, ToolPublicMeta> = {
  'donati-hesabi': {
    id: 'donati-hesabi',
    title: 'Donatı Hesabı',
    shortDescription: 'Çap ve adet girerek toplam donatı alanını ve eşdeğer seçenekleri hesaplayın.',
    calculationKind: 'preliminary',
    tier: 'B',
    scope: ['Donatı çubuk alanı', 'Eşdeğer alternatif donatı kombinasyonları', 'Teorik metretül ağırlık'],
    limitations: ['Yerleşebilirlik ve pas payı şantiye detay çizimi ile kontrol edilmelidir', 'Çatlak genişliği tahkiki içermez'],
    sourceLabels: ['TS 500', 'TS 708'],
  },
  'kolon-on-boyutlandirma': {
    id: 'kolon-on-boyutlandirma',
    title: 'Kolon Ön Boyutlandırma',
    shortDescription: 'Dikdörtgen kolonlar için ilk kesiti ve tasarım alanını kontrol edin.',
    calculationKind: 'preliminary',
    tier: 'A',
    scope: ['Eksenel yük kapasitesi Ac >= Nd / (0.6 * fck)', 'Minimum dikdörtgen boyut sınırları', 'Brüt beton alanı'],
    limitations: ['Ön boyutlandırmadır; P-M etkileşimi, iki eksenli eğilme ve 2. mertebe etkileri içermez', 'Nihai donatı ve etriye tasarımı yerine geçmez'],
    sourceLabels: ['TS 500 Madde 7.4', 'TBDY 2018'],
  },
  'kiris-kesiti': {
    id: 'kiris-kesiti',
    title: 'Kiriş Kesiti',
    shortDescription: 'Eğilme donatısı ve kesme kontrolünü TS 500 mantığıyla yapın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Basit donatılı eğilme momenti kapasitesi (Md)', 'Kesme kuvveti tahkiki (Vd <= Vmax)', 'Gerekli çekme donatısı As'],
    limitations: ['Md ve Vd harici yapısal analiz sonuçlarıdır', 'Çift donatılı kesit veya sehim sünekliği içermez'],
    sourceLabels: ['TS 500 Madde 7.1', 'TS 500 Madde 8.1'],
  },
  'doseme-kalinligi': {
    id: 'doseme-kalinligi',
    title: 'Döşeme Kalınlığı',
    shortDescription: 'Açıklık-kalınlık oranı ve minimum donatı aralığını ön kontrol edin.',
    calculationKind: 'preliminary',
    tier: 'B',
    scope: ['Tek ve çift doğrultuda çalışan plak döşeme kalınlığı', 'Sehim şartı ön kontrolü', 'Minimum h sınırları'],
    limitations: ['Nihai sehim integrali veya dinamik titreşim analizi yerine geçmez'],
    sourceLabels: ['TS 500 Madde 11.2'],
  },
  'pas-payi': {
    id: 'pas-payi',
    title: 'Pas Payı',
    shortDescription: 'Nominal beton örtüsünü ve pratik pas payını hesaplayın.',
    calculationKind: 'check',
    tier: 'B',
    scope: ['Çevre etki sınıfına göre minimum örtü (cmin)', 'Tolerans payı (Delta_cdev)', 'Nominal pas payı (cnom)'],
    limitations: ['Yangın dayanımı için özel tabak kalınlıkları haricen doğrulanmalıdır'],
    sourceLabels: ['TS EN 1992-1-1', 'TS 500'],
  },
  'zimbalama-kontrolu': {
    id: 'zimbalama-kontrolu',
    title: 'Döşeme Zımbalama Kontrolü',
    shortDescription: 'Mantar ve radye döşemelerde kolon çevresi zımbalama güvenliğini tahkik edin.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['d/2 kritik zımbalama çevresi (up)', 'Zımbalama kayma gerilmesi (tau_pd)', 'Beton zımbalama dayanımı (fctd)'],
    limitations: ['Yalnız iç kolon geometrisi için standart çevredir; kenar/köşe serbest kenar boşlukları haricen kontrol edilmelidir'],
    sourceLabels: ['TS 500 Madde 8.3', 'TBDY 2018'],
  },
  'kiris-kesme-etriye': {
    id: 'kiris-kesme-etriye',
    title: 'Kiriş Kesme / Etriye Hesabı',
    shortDescription: 'TS 500 kayma dayanımı (Vc + Vw) ve etriye sıklaştırma aralığını belirleyin.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Beton kesme katkısı Vc', 'Etriye kesme katkısı Vw', 'Sıklaştırma ve orta bölge maksimum aralık limitleri'],
    limitations: ['Gövde donatısı ve burulmalı kesme kombinasyonu haricen tahkik edilmelidir'],
    sourceLabels: ['TS 500 Madde 8.1', 'TBDY 2018 Bölüm 7.4'],
  },
  'kenetlenme-boyu': {
    id: 'kenetlenme-boyu',
    title: 'Donatı Kenetlenme / Bindirme',
    shortDescription: 'Çekme ve basınç donatıları için bindirmeli ek ve kenetlenme boyunu hesaplayın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Temel kenetlenme boyu lb', 'Tasarım kenetlenme boyu lbd', 'Bindirmeli ek boyu l0'],
    limitations: ['Kaynaklı ek veya manşonlu mekanik bağlantıları kapsamaz'],
    sourceLabels: ['TS 500 Madde 9.1', 'TS 500 Madde 9.2'],
  },
  'taban-kesme-kuvveti': {
    id: 'taban-kesme-kuvveti',
    title: 'Eşdeğer Deprem Yükü',
    shortDescription: 'Toplam eşdeğer taban kesme kuvveti Vt ve katlara dağılımını hesaplayın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['TBDY 2018 Eşdeğer Deprem Yükü Yöntemi', 'Kat yatay kuvvetleri Fi', 'Taban kesme alt sınırı kontrolü'],
    limitations: ['Bina yükseklik sınıfı ve düzensizlik kısıtlarına göre mod birleştirme gereksinimi kontrol edilmelidir'],
    sourceLabels: ['TBDY 2018 Bölüm 4.7'],
  },
  'duzensizlik-kontrolu': {
    id: 'duzensizlik-kontrolu',
    title: 'Bina Düzensizlik Kontrolleri',
    shortDescription: 'TBDY 2018 Bölüm 3.6 uyarınca A1, A2 ve B2 düzensizlik katsayılarını hesaplayın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['A1 Burulma düzensizliği (eta_bi)', 'A2 Döşeme süreksizlikleri boşluk oranı', 'B2 Yumuşak kat rijitlik farkı (eta_ki)'],
    limitations: ['Yalnız A1, A2 ve B2 kontrollerini yapar; A3, B1 ve B3 kontrolleri ayrı analiz gerektirir'],
    sourceLabels: ['TBDY 2018 Tablo 3.6'],
  },
  'zemin-sinifi': {
    id: 'zemin-sinifi',
    title: 'Yerel Zemin Sınıfı Tayini',
    shortDescription: 'Vs30, SPT-N60 veya cu verileriyle TBDY 2018 yerel zemin sınıfını belirleyin.',
    calculationKind: 'classification',
    tier: 'A',
    scope: ['TBDY 2018 Tablo 16.1 parametre eşleştirmesi', 'ZA, ZB, ZC, ZD, ZE zemin sınıfları', 'ZF özel araştırma uyarısı'],
    limitations: ['Sondaj logu ve geoteknik rapor yerine geçmez; tabakalanma özel değerlendirilmelidir'],
    sourceLabels: ['TBDY 2018 Bölüm 16.4'],
  },
  'deprem-periyot-hesabi': {
    id: 'deprem-periyot-hesabi',
    title: 'Deprem Periyodu / Spektrum',
    shortDescription: 'Ampirik hakim periyot ve TBDY 2018 elastik ivme spektrumunu hesaplayın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Ampirik hakim doğal titreşim periyodu Tp', 'Yatay elastik tasarım spektrumu Sae(T)', 'Karakteristik periyotlar TA ve TB'],
    limitations: ['3D modal analiz özdeğer periyotları ampirik periyodun yerini alır'],
    sourceLabels: ['TBDY 2018 Bölüm 4.7.3', 'TBDY 2018 Bölüm 2.3'],
  },
  'goreli-kat-otelemesi': {
    id: 'goreli-kat-otelemesi',
    title: 'Göreli Kat Ötelemesi',
    shortDescription: 'Deprem yükleri altında göreli kat ötelemesi ve ikinci mertebe göstergesini tahkik edin.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Etkin göreli kat ötelemesi delta_i', 'lambda * delta_i / h_i sınır kontrolü', 'İkinci mertebe gösterge değeri theta_i'],
    limitations: ['3D bina analizinden elde edilen kat deplasmanları girdi olarak verilmelidir'],
    sourceLabels: ['TBDY 2018 Bölüm 4.9'],
  },
  'radye-temel-hesabi': {
    id: 'radye-temel-hesabi',
    title: 'Radye Temel Kalınlık / Zımbalama',
    shortDescription: 'Zemin gerilmesi, ampatman konsol eğilmesi ve radye zımbalama ön tahkikini yapın.',
    calculationKind: 'preliminary',
    tier: 'A',
    scope: ['Ortalama zemin taban basıncı', 'Radye ön kalınlık kontrolü', 'Kritik kolon çevresi radye zımbalama tahkiki'],
    limitations: ['Winkler yay modeli veya plak sonlu elemanlar temeli yerine geçmez; ön boyutlandırmadır'],
    sourceLabels: ['TS 500', 'TBDY 2018'],
  },
  'iksa-toprak-basinci': {
    id: 'iksa-toprak-basinci',
    title: 'İksa Perdesi Toprak Basıncı',
    shortDescription: 'Rankine teorisiyle aktif ve pasif yanal toprak basıncı dağılımını hesaplayın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Rankine aktif (Ka) ve pasif (Kp) zemin katsayıları', 'Yanal basınç diyagramı', 'Bileşke zemin itkisi ve uygulama noktası'],
    limitations: ['Yeraltı suyu, kohezyon çatlağı veya kademeli ankraj analizlerini içermez; yalın Rankine durumudur'],
    sourceLabels: ['Rankine Teorisi', 'TS 7994'],
  },
  'sev-stabilitesi': {
    id: 'sev-stabilitesi',
    title: 'Şev Stabilitesi',
    shortDescription: 'Fellenius dilim yöntemiyle dairesel kayma yüzeyi güvenlik katsayısını hesaplayın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Fellenius (İsveç Dilim) yöntemi', 'Kaydırıcı ve tutucu moment dengesi', 'Güvenlik katsayısı Fs'],
    limitations: ['Tek daire kabulüdür; kritik kayma yüzeyi otomatik grid araması veya depremli durum içermez'],
    sourceLabels: ['Fellenius Dilim Yöntemi'],
  },
  'celik-profil-secimi': {
    id: 'celik-profil-secimi',
    title: 'Çelik Profil Seçimi / Kapasite',
    shortDescription: 'Çelik profillerde narinlik, basınç, eğilme ve kesme taşıma gücünü hesaplayın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Çift eksenli narinlik lambda_y, lambda_z', 'Basınç burkulma kapasitesi Nb,Rd', 'Eğilme Mc,Rd ve kesme Vc,Rd kapasiteleri'],
    limitations: ['Yanal burkulmalı eğilme (LTB) ve yerel levha burkulması sınıf 4 kontrolleri haricen yapılmalıdır'],
    sourceLabels: ['ÇYTHYE 2018', 'AISC 360-16'],
  },
  'celik-birlestesi-hesabi': {
    id: 'celik-birlestesi-hesabi',
    title: 'Çelik Cıvata / Kaynak',
    shortDescription: 'Kayma etkisindeki bulonlu ve köşe kaynaklı birleşimlerin dayanımını kontrol edin.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Bulon kesme ve ezilme dayanımı', 'Köşe kaynak dikişi dayanımı', 'Birleşim güvenliği kontrolü'],
    limitations: ['Moment aktaran birleşim, alın levhası veya çekme bulonu kombinasyonlarını içermez'],
    sourceLabels: ['ÇYTHYE 2018 Bölüm 13'],
  },
  'ahsap-eleman-hesabi': {
    id: 'ahsap-eleman-hesabi',
    title: 'Ahşap Kiriş Taşıma Gücü / Sehim',
    shortDescription: 'Eurocode 5 kurallarıyla ahşap kirişlerde eğilme, kayma ve sehim tahkiklerini yapın.',
    calculationKind: 'check',
    tier: 'B',
    scope: ['Tasarım dayanımları fm,d, fv,d (kmod, gammaM)', 'Basit kiriş eğilme ve kayma gerilmeleri', 'Anlık elastik sehim ve L/300 sınırı'],
    limitations: ['Yalnız yayılı yüklü basit kiriş modudur; dikme/kolon burkulması için özel genişletme gereklidir'],
    sourceLabels: ['TS EN 1995-1-1 (Eurocode 5)'],
  },
  'kalip-sokum-suresi': {
    id: 'kalip-sokum-suresi',
    title: 'Kalıp Söküm Süresi Hesabı',
    shortDescription: 'Ortalama sıcaklık ve çimento tipine göre tahmini minimum kalıp söküm süresini hesaplayın.',
    calculationKind: 'preliminary',
    tier: 'B',
    scope: ['Eleman türü (yan kalıp, döşeme altı, kiriş altı)', 'Ortalama ortam sıcaklığı etkisi', 'Çimento dayanım sınıfı çarpanı'],
    limitations: ['Tahmini süredir; şantiyede erken kalıp sökümü için gerçek beton basınç dayanım testi (karot/küp) esastır'],
    sourceLabels: ['TS 500 Madde 5.4', 'ACI 347R'],
  },
  'dis-cephe-yalitim-kalinligi': {
    id: 'dis-cephe-yalitim-kalinligi',
    title: 'Yalıtım Kalınlığı ve U Değeri',
    shortDescription: 'TS 825 derece-gün bölgelerine göre duvar U değerini ve gerekli yalıtım kalınlığını hesaplayın.',
    calculationKind: 'check',
    tier: 'A',
    scope: ['Bileşen katmanları ısıl direnci R = d / lambda', 'Toplam ısı geçirme katsayısı U', 'TS 825 bölge maksimum U sınır kontrolü'],
    limitations: ['Yalnız opak dış duvar içindir; pencere, çatı ve döşeme toplam bina enerji simülasyonu yerine geçmez'],
    sourceLabels: ['TS 825 Standardı'],
  },
  'imar-hesaplayici': {
    id: 'imar-hesaplayici',
    title: 'İmar Hesaplayıcı (TAKS/KAKS)',
    shortDescription: 'Parsel alanı, TAKS, KAKS ve çekme mesafelerine göre yapılaşma ön etüdü yapın.',
    calculationKind: 'preliminary',
    tier: 'B',
    scope: ['Taban alanı (TAKS)', 'Emsal inşaat alanı (KAKS)', 'Ön, yan ve arka bahçe çekme mesafeleri'],
    limitations: ['Ön fizibilitedir; ilgili belediyenin güncel imar planı notları, plan lejantı ve terkinler esastır'],
    sourceLabels: ['3194 Sayılı İmar Kanunu', 'Planlı Alanlar İmar Yönetmeliği'],
  },
  'beton-metraj-hesabi': {
    id: 'beton-metraj-hesabi',
    title: 'Beton Metrajı / Mikser Seferi',
    shortDescription: 'Eleman net hacimlerini toplayın; fire katsayısı ve mikser kapasitesine göre sipariş planlayın.',
    calculationKind: 'estimate',
    tier: 'C',
    scope: ['Temel, kolon, kiriş ve döşeme net beton hacmi', 'Şantiye döküm firesi payı', 'Tahmini transmikser sefer sayısı'],
    limitations: ['Yaklaşık sipariş tahminidir; pompa ve kalıp esneme kayıpları şantiye ölçümüyle teyit edilmelidir'],
    sourceLabels: ['Saha Pratiği', 'Çevre Şehircilik Standartları'],
  },
  'hafriyat-metraj-hesabi': {
    id: 'hafriyat-metraj-hesabi',
    title: 'Hafriyat Metrajı / Kamyon Seferi',
    shortDescription: 'Şevli temel kazısı prizmoid hacmini ve zemin kabarmasına göre kamyon sefer sayısını hesaplayın.',
    calculationKind: 'estimate',
    tier: 'C',
    scope: ['Prizmoid formülüyle şevli kazı hacmi', 'Zemin cinsine göre kabarma payı', 'Damperli kamyon sefer sayısı'],
    limitations: ['Yaklaşık kazı tahminidir; zemin etüt profili ve harita mühendisi kübajı esastır'],
    sourceLabels: ['Saha Pratiği', 'Karayolları Genel Müdürlüğü'],
  },
  'pratik-donati-metraji': {
    id: 'pratik-donati-metraji',
    title: 'Pratik Donatı (Demir) Metrajı',
    shortDescription: 'Yapı tipolojisi ve inşaat alanına göre ampirik kg/m² donatı sarfiyatını ve sipariş dağılımını hesaplayın.',
    calculationKind: 'estimate',
    tier: 'C',
    scope: ['Ampirik kg/m² donatı oranı', 'Tahmini toplam demir tonajı', 'Çap gruplarına göre sipariş dağılım yüzdeleri'],
    limitations: ['Yaklaşık ön keşif tahminidir; statik betonarme detay çizimleri pursantajı esastır'],
    sourceLabels: ['Saha Pratiği', 'İMO Yaklaşık Maliyet Bülteni'],
  },
  'pratik-kalip-metraji': {
    id: 'pratik-kalip-metraji',
    title: 'Pratik Kalıp / İskele Metrajı',
    shortDescription: 'Kat alanı ve açınım katsayısına göre kalıp yüzeyi, plywood ve iskele dikme adetlerini hesaplayın.',
    calculationKind: 'estimate',
    tier: 'C',
    scope: ['Kalıp açınım yüzeyi (m²)', 'Plywood plaka ihtiyacı', 'Teleskopik dikme ve iskele tahmini'],
    limitations: ['Yaklaşık keşif tahminidir; kalıp projesi ve kolon-kiriş yoğunluğu kontrol edilmelidir'],
    sourceLabels: ['Saha Pratiği', 'Çevre ve Şehircilik Bakanlığı'],
  },
  'duvar-metraji-hesabi': {
    id: 'duvar-metraji-hesabi',
    title: 'Duvar Metrajı Hesabı',
    shortDescription: 'Duvar ölçüleri ve kapı-pencere boşluklarına göre net duvar alanı, tuğla adedi ve harç miktarını hesaplayın.',
    calculationKind: 'estimate',
    tier: 'C',
    scope: ['Net duvar örme alanı', 'Tuğla / bims / gazbeton adet hesabı', 'Kaba harç sarfiyatı'],
    limitations: ['Yaklaşık metrajdır; ürün kırılma zayiatı ve derz kalınlığı şantiye uygulamasına göre değişir'],
    sourceLabels: ['ÇŞB Standart Pozları'],
  },
  'siva-boya-metraji': {
    id: 'siva-boya-metraji',
    title: 'Sıva ve Boya Metrajı Hesabı',
    shortDescription: 'Duvar ve tavan alanlarına göre kaba/ince sıva torba ihtiyacı ile astar ve boya sarfiyatını hesaplayın.',
    calculationKind: 'estimate',
    tier: 'C',
    scope: ['Sıva kuru harç torba sarfiyatı', 'Astar kova ihtiyacı', 'İki kat son kat boya kova hesabı'],
    limitations: ['Yaklaşık sarfiyattır; yüzey pürüzlülüğü ve boya markası TDS föyü esas alınmalıdır'],
    sourceLabels: ['ÇŞB Standart Pozları'],
  },
  'cati-kaplama-metraji': {
    id: 'cati-kaplama-metraji',
    title: 'Çatı Kaplama / Eğim Metrajı',
    shortDescription: 'Yatay izdüşüm ve eğim açısına göre gerçek çatı kaplama alanı, kiremit ve membran metrajını hesaplayın.',
    calculationKind: 'estimate',
    tier: 'C',
    scope: ['Eğim faktörü ile gerçek çatı alanı', 'Kiremit ve panel adet tahmini', 'Mahya ve su yalıtım membranı'],
    limitations: ['Yaklaşık keşiftir; saçak payları ve dere detayları çatı projesiyle doğrulanmalıdır'],
    sourceLabels: ['TS EN 490', 'ÇŞB Standartları'],
  },
  'seramik-fayans-metraji': {
    id: 'seramik-fayans-metraji',
    title: 'Seramik / Fayans Metrajı',
    shortDescription: 'Zemin ve duvar alanlarına göre seramik paket/kutu sayısı, yapıştırıcı ve derz dolgusunu hesaplayın.',
    calculationKind: 'estimate',
    tier: 'C',
    scope: ['Net kaplama alanı ve zayiat payı', 'Kutu / ambalaj yuvarlaması', 'Yapıştırıcı ve derz dolgusu torba ihtiyacı'],
    limitations: ['Kutu içi metrekare üretici serisine göre değişir; sipariş öncesi ürün kutusu teyit edilmelidir'],
    sourceLabels: ['TS EN 14411', 'ÇŞB'],
  },
};