import type { OfficialCostRow } from "./types";

export const OFFICIAL_UNIT_COST_SOURCE_2026 = {
  label: "2026 Yapı Yaklaşık Birim Maliyetleri Tebliği",
  localPdfPath: "/hesaplamalar/2026 yaklaşık brim maliyetleri.pdf",
  sourceUrl:
    "https://webdosya.csb.gov.tr/v2/yfk/2026/02/M-MARLIK-M-HEND-SL-K-TEBL-2026-20260204101544.pdf",
} as const;

export const OFFICIAL_UNIT_COSTS_2026: OfficialCostRow[] = [
  {
    yil: 2026,
    anaGrupKodu: "I",
    anaGrupAdi: "I. Sınıf Yapılar",
    altGrupKodu: "A",
    altGrupAdi: "A Grubu",
    sinifKodu: "I-A",
    sinifAdi: "I. Sınıf (A) Grubu Yapılar",
    m2BirimMaliyet: 2600,
    ornekYapilar: [
      "Basit hayvancılık ve basit tarım yapıları",
      "Çardaklar, gölgelikler ve üstü kapalı yanları açık dinlenme yapıları",
      "Plastik örtülü seralar",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "1/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "I",
    anaGrupAdi: "I. Sınıf Yapılar",
    altGrupKodu: "B",
    altGrupAdi: "B Grubu",
    sinifKodu: "I-B",
    sinifAdi: "I. Sınıf (B) Grubu Yapılar",
    m2BirimMaliyet: 3900,
    ornekYapilar: [
      "Basit padok ve küçükbaş hayvan ağılları",
      "Cam veya sert plastik örtülü seralar",
      "Kalıcı kullanımı olan yardımcı yapılar",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "1/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "I",
    anaGrupAdi: "I. Sınıf Yapılar",
    altGrupKodu: "C",
    altGrupAdi: "C Grubu",
    sinifKodu: "I-C",
    sinifAdi: "I. Sınıf (C) Grubu Yapılar",
    m2BirimMaliyet: 4200,
    ornekYapilar: [
      "Betonarme ve kâgir su depoları",
      "Elektrikli araç şarj istasyonları",
      "İstinat duvarları, palplanş ve ankrajlı perde",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "1/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "I",
    anaGrupAdi: "I. Sınıf Yapılar",
    altGrupKodu: "D",
    altGrupAdi: "D Grubu",
    sinifKodu: "I-D",
    sinifAdi: "I. Sınıf (D) Grubu Yapılar",
    m2BirimMaliyet: 4800,
    ornekYapilar: ["Güneş enerji santralleri (GES)"],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "1/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "II",
    anaGrupAdi: "II. Sınıf Yapılar",
    altGrupKodu: "A",
    altGrupAdi: "A Grubu",
    sinifKodu: "II-A",
    sinifAdi: "II. Sınıf (A) Grubu Yapılar",
    m2BirimMaliyet: 8100,
    ornekYapilar: [
      "Deniz iskeleleri",
      "Genel amaçlı depolar",
      "Tarımsal endüstri yapıları",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "2/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "II",
    anaGrupAdi: "II. Sınıf Yapılar",
    altGrupKodu: "B",
    altGrupAdi: "B Grubu",
    sinifKodu: "II-B",
    sinifAdi: "II. Sınıf (B) Grubu Yapılar",
    m2BirimMaliyet: 12500,
    ornekYapilar: [
      "Botanik, jeopark ve tema park yapıları",
      "Geçici kullanımı olan yapılar ve konteyner kentler",
      "Hangar yapıları ve kapalı pazar yerleri",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "2/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "II",
    anaGrupAdi: "II. Sınıf Yapılar",
    altGrupKodu: "C",
    altGrupAdi: "C Grubu",
    sinifKodu: "II-C",
    sinifAdi: "II. Sınıf (C) Grubu Yapılar",
    m2BirimMaliyet: 15100,
    ornekYapilar: [
      "Bağ, dağ, köy ve yayla evleri",
      "Bungalov evleri",
      "Sanayi tesisleri (0-500 kg/m² hareketli yük)",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "2/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "III",
    anaGrupAdi: "III. Sınıf Yapılar",
    altGrupKodu: "A",
    altGrupAdi: "A Grubu",
    sinifKodu: "III-A",
    sinifAdi: "III. Sınıf (A) Grubu Yapılar",
    m2BirimMaliyet: 19800,
    ornekYapilar: [
      "Apartman tipi konutlar (üç kata kadar)",
      "Akaryakıt ve otogaz dolum istasyonları",
      "Katlı ve/veya kapalı otoparklar",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "2/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "III",
    anaGrupAdi: "III. Sınıf Yapılar",
    altGrupKodu: "B",
    altGrupAdi: "B Grubu",
    sinifKodu: "III-B",
    sinifAdi: "III. Sınıf (B) Grubu Yapılar",
    m2BirimMaliyet: 21050,
    ornekYapilar: [
      "Aile sağlığı merkezleri",
      "İlkokul ve ortaokul yapıları",
      "Konutlar (yapı yüksekliği 21.50 m'nin altı veya dahil)",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "3/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "III",
    anaGrupAdi: "III. Sınıf Yapılar",
    altGrupKodu: "C",
    altGrupAdi: "C Grubu",
    sinifKodu: "III-C",
    sinifAdi: "III. Sınıf (C) Grubu Yapılar",
    m2BirimMaliyet: 23400,
    ornekYapilar: [
      "Ağız ve diş sağlığı merkezleri",
      "Huzurevi ve yaşlı bakım merkezleri",
      "Konutlar (21.50 m üzeri, 30.50 m dahil veya altı)",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "3/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "IV",
    anaGrupAdi: "IV. Sınıf Yapılar",
    altGrupKodu: "A",
    altGrupAdi: "A Grubu",
    sinifKodu: "IV-A",
    sinifAdi: "IV. Sınıf (A) Grubu Yapılar",
    m2BirimMaliyet: 26450,
    ornekYapilar: [
      "Alışveriş merkezleri (25.000 m² altı)",
      "Fakülteler ve yüksekokullar",
      "Konutlar (30.50 m üzeri, 51.50 m dahil veya altı)",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "4/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "IV",
    anaGrupAdi: "IV. Sınıf Yapılar",
    altGrupKodu: "B",
    altGrupAdi: "B Grubu",
    sinifKodu: "IV-B",
    sinifAdi: "IV. Sınıf (B) Grubu Yapılar",
    m2BirimMaliyet: 33900,
    ornekYapilar: [
      "Banka ve borsa binaları",
      "Konutlar (51.50 m üzeri)",
      "Üniversite idari binaları",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "4/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "IV",
    anaGrupAdi: "IV. Sınıf Yapılar",
    altGrupKodu: "C",
    altGrupAdi: "C Grubu",
    sinifKodu: "IV-C",
    sinifAdi: "IV. Sınıf (C) Grubu Yapılar",
    m2BirimMaliyet: 40500,
    ornekYapilar: [
      "Adalet sarayları",
      "Bakanlık binaları",
      "Hastaneler (200 yatak altı) ve kapalı cezaevleri",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "5/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "V",
    anaGrupAdi: "V. Sınıf Yapılar",
    altGrupKodu: "A",
    altGrupAdi: "A Grubu",
    sinifKodu: "V-A",
    sinifAdi: "V. Sınıf (A) Grubu Yapılar",
    m2BirimMaliyet: 42350,
    ornekYapilar: [
      "Büyükelçilik ve konsolosluk binaları",
      "Eğitim ve araştırma hastaneleri",
      "Karma kullanımlı yapılar ve stadyumlar",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "5/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "V",
    anaGrupAdi: "V. Sınıf Yapılar",
    altGrupKodu: "B",
    altGrupAdi: "B Grubu",
    sinifKodu: "V-B",
    sinifAdi: "V. Sınıf (B) Grubu Yapılar",
    m2BirimMaliyet: 43850,
    ornekYapilar: [
      "Kuvvet komutanlığı tesisleri",
      "Hastaneler (200-400 yatak)",
      "Oteller (4 yıldızlı)",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "5/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "V",
    anaGrupAdi: "V. Sınıf Yapılar",
    altGrupKodu: "C",
    altGrupAdi: "C Grubu",
    sinifKodu: "V-C",
    sinifAdi: "V. Sınıf (C) Grubu Yapılar",
    m2BirimMaliyet: 48750,
    ornekYapilar: [
      "Bale, opera ve tiyatro yapıları",
      "Hastaneler (400 yatak ve üzeri)",
      "Kongre ve kültür merkezleri",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "5/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "V",
    anaGrupAdi: "V. Sınıf Yapılar",
    altGrupKodu: "D",
    altGrupAdi: "D Grubu",
    sinifKodu: "V-D",
    sinifAdi: "V. Sınıf (D) Grubu Yapılar",
    m2BirimMaliyet: 53500,
    ornekYapilar: [
      "Havalimanı terminal binaları",
      "Metro istasyonları",
      "Oteller (5 yıldızlı) ve şehir hastaneleri",
    ],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "6/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
  {
    yil: 2026,
    anaGrupKodu: "V",
    anaGrupAdi: "V. Sınıf Yapılar",
    altGrupKodu: "E",
    altGrupAdi: "E Grubu",
    sinifKodu: "V-E",
    sinifAdi: "V. Sınıf (E) Grubu Yapılar",
    m2BirimMaliyet: 103500,
    ornekYapilar: ["Rüzgâr enerji santralleri (RES)"],
    kaynakPdf: OFFICIAL_UNIT_COST_SOURCE_2026.label,
    kaynakUrl: OFFICIAL_UNIT_COST_SOURCE_2026.sourceUrl,
    kaynakSayfaVeyaBolum: "6/6",
    not: "KDV hariç, genel gider (%15) ve yüklenici kârı (%10) dahil resmi yaklaşık birim maliyettir.",
  },
];
