import { BRANCH_SOURCE_LEDGER, SOURCE_LEDGER } from "../source-ledger";
import type { BinaGuideEquipment, BinaGuidePageSpec, BinaGuideTool } from "../types";

const INCE_TOPIC_OVERRIDE_SOURCES = [...BRANCH_SOURCE_LEDGER["ince-isler"]];

export const inceIslerTopicOverrides: BinaGuidePageSpec[] = [
  {
    slugPath: "ince-isler/siva",
    kind: "topic",
    quote: "Siva, duvari kapatan ara katman degil; butun ince isin gorunur kalitesini tasiyan ana referans duzlemdir.",
    tip: "Siva isini yalniz metraj ve iscilik hizi olarak gormek, boya ve kaplama altinda kalici dalga, catlak ve tekrar is maliyeti uretir.",
    intro: [
      "Siva isleri, ince imalatlarin en sessiz ama en belirleyici kalemlerinden biridir. Boya, fayans veya duvar kagidi ne kadar iyi secilirse secilsin, altindaki siva duzlemi zayifsa kullanici kalitesi hemen dusuk algilanir.",
      "Sahada en sik yapilan hata, sivayi dekoratif sonuclardan bagimsiz bir on hazirlik adimi sanmaktir. Oysa ic ve dis siva; aderans, catlak kontrolu, su davranisi, kose dogrulugu ve boya alti kabulun birlikte yonetildigi teknik bir tabakadir.",
      "Bir insaat muhendisi icin siva yalniz usta kalitesi meselesi degildir. Is programi, alt yuzey hazirligi, file detaylari ve sonraki ekiplerin takvimi bu kalemin gercek performansini belirler.",
    ],
    theory: [
      "Siva sistemleri alt yuzeyle birlikte calisir. Tugla, gazbeton, briket veya betonarme yuzeylerin emicilikleri ve hareketleri farkli oldugu icin ayni harc davranisini beklemek yanlistir.",
      "Iyi bir siva yalniz duz gorunmez; ayni zamanda kolon-duvar birlesimi, pencere koseleri ve tesisat onarim hatlarindaki gerilme farklarini da yonetir.",
      "Dis cephede su ve gunes etkisi, ic mekanda ise kuruma hizi ve son kat uyumu one cikar. Cok hizli su kaybeden veya kur almayan siva yuzeyi tozuma ve büzülme riski tasir.",
      "Bu nedenle siva, harc surme operasyonundan cok yuzey muhendisligi olarak ele alinmalidir.",
    ],
    ruleTable: [
      {
        parameter: "Yuzey hazirligi",
        limitOrRequirement: "Alt yuzey toz, gevsek parca ve aderansi zayif tabakalardan arindirilmali",
        reference: "TS EN 13914 uygulama prensipleri",
        note: "Kirli veya parlak yuzeye atilan siva en basta zayif bag ile baslar.",
      },
      {
        parameter: "Katman kalinligi",
        limitOrRequirement: "Asiri kalin tek kat yerine kontrollu katman ve mastar duzeni kullanilmali",
        reference: "TS EN 13914 + saha kalite plani",
        note: "Tek hamlede kalinlik buyutmek ayrilma ve catlak riskini artirir.",
      },
      {
        parameter: "Kritik birlesimler",
        limitOrRequirement: "Kolon-duvar ve aciklik kenarlarinda file veya uygun destek detayi uygulanmali",
        reference: "Saha catlak kontrol disiplini",
        note: "Catlaklar en once malzeme degisim sinirlarinda gorulur.",
      },
      {
        parameter: "Kuruma ve koruma",
        limitOrRequirement: "Yeni siva ani gunes, ruzgar ve yagmur etkisinden korunmali",
        reference: "Santiye uygulama disiplini",
        note: "Kur almayan yuzey son katta renk ve tozuma problemi uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Alt yuzey tipini belirle ve betonarme, tugla veya gazbeton icin ayri hazirlik stratejisi kur.",
      "Aderans koprusu veya astar ihtiyacini ilk panelde dogrula.",
      "Mastar hatlarini, kose profillerini ve kalinlik referanslarini uygulama oncesi sabitle.",
      "Kritik birlesimlerde file donusu ve chase tamirlerini ana siva ile birlikte coz.",
      "Boya veya kaplama ekibine gecmeden once yan isikta duzlem, catlak ve yama kontrolu yap.",
    ],
    criticalChecks: [
      "Alt yuzey emiciligi ve aderansi sahada kontrol edildi mi?",
      "Kolon-duvar ve pencere koselerinde file veya uygun detay var mi?",
      "Mastar duzlemi boyunca dalga ve ani sapma olusuyor mu?",
      "Asiri kalin tek kat uygulama yapilan bolgeler var mi?",
      "Kuruma tamamlanmadan sonraki ekipler alana giriyor mu?",
    ],
    numericalExample: {
      title: "Ic duvar sivasinda duzlem ve kalinlik karari",
      inputs: [
        { label: "Duvar uzunlugu", value: "4.80 m", note: "Salon duvari" },
        { label: "Olculen yuzey sapmasi", value: "12 mm", note: "En yuksek ve en dusuk nokta arasi" },
        { label: "Planlanan ortalama siva kalinligi", value: "15 mm", note: "Ic mekan ornek deger" },
        { label: "Hedef", value: "Boya alti duzlem", note: "Son katta dalga olusturmamak" },
      ],
      assumptions: [
        "Alt yuzey tasiyici olarak saglam ve temizdir.",
        "Elektrik chase tamirleri uygulama oncesi tamamlanmistir.",
        "Son kat boya planlandigi icin dalga toleransi dusuktur.",
      ],
      steps: [
        {
          title: "Sapmayi yorumla",
          formula: "12 mm < 15 mm",
          result: "Olculen bozukluk planlanan katman icinde yonetilebilir gorunur.",
          note: "Yine de lokal cepler tek hamlede doldurulmamalidir.",
        },
        {
          title: "Duzlem stratejisini kur",
          result: "Mastar referanslari ile once ana duzlem kurulup ara bosluklar kontrollu doldurulmalidir.",
          note: "Serbest el uygulama boya altinda gozle gorulur dalga uretir.",
        },
        {
          title: "Catlak riskini ekle",
          result: "Kolon-dolgu duvar gecislerinde file detayina ihtiyac vardir.",
          note: "Duzlem saglansa bile malzeme degisim cizgileri file olmadan risklidir.",
        },
      ],
      checks: [
        "Mastar kontrolu siva sirasinda yapilmali, boya ekibine birakilmamalidir.",
        "Asiri kalin lokal cep noktalarinda katmanli yaklasim dusunulmelidir.",
        "Kritik birlesimlerde catlak onleyici detay unutulmamalidir.",
        "Kuruma suresi takvim baskisiyla kisaltilmamalidir.",
      ],
      engineeringComment: "Siva kalitesini boya geldikten sonra degil, mastar duvardayken yakalamak gerekir.",
    },
    tools: [
      { category: "Detay", name: "Cephe ve ic mekan siva detay paftalari", purpose: "Katman dizisini ve kritik koseleri uygulama oncesi netlestirmek." },
      { category: "Olcum", name: "Mastar, lazer nivo ve nem olcer", purpose: "Yuzey duzlugu ve kuruma seviyesini sayisal olarak kontrol etmek." },
      { category: "Kontrol", name: "Alan bazli kalite takip cizelgesi", purpose: "Catlak, yama ve boya alti kabul notlarini mahal bazinda izlemek." },
      { category: "Saha", name: "Deneme paneli ve fotograf kaydi", purpose: "Secilen sistemin iscilik kalitesini genellemeden once gormek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Yuzey temizlik ekipmanlari ve aderans astarlari", purpose: "Gevsek toz ve emicilik farklarini kontrol altina almak.", phase: "Hazirlik" },
      { group: "Uygulama", name: "Cimento esasli siva, alci siva ve karisim ekipmanlari", purpose: "Ic ve dis mekan ihtiyacina gore dogru katman davranisi uretmek.", phase: "Siva uygulamasi" },
      { group: "Detay", name: "Kose profili, file ve damlalik elemanlari", purpose: "Kritik koselerde catlak riskini azaltmak.", phase: "Detay cozumu" },
      { group: "Koruma", name: "Kur ve gunes koruma ekipmanlari", purpose: "Taze sivayi hizli su kaybi ve hava etkisinden korumak.", phase: "Uygulama sonrasi" },
    ],
    mistakes: [
      { wrong: "Tozlu veya kalip yagli yuzeye dogrudan siva atmak.", correct: "Yuzeyi temizleyip aderans kosullarini once dogrulamak." },
      { wrong: "Butun duzeltmeyi tek kat kalin sivayla cozmeye calismak.", correct: "Referans mastar ve katmanli uygulama ile ilerlemek." },
      { wrong: "Kolon-duvar birlesimlerinde file kullanmamak.", correct: "Malzeme degisim hatlarini catlak riski olarak gormek." },
      { wrong: "Kur almadan sonraki ekiplere alani acmak.", correct: "Sivayi yeterli kuruma ve koruma suresiyle teslim etmek." },
      { wrong: "Boya alti kaliteyi son katta duzeltmeye calismak.", correct: "Siva asamasinda duzlem ve yama kalitesini bitirmek." },
    ],
    designVsField: [
      "Projede siva kalemi cogu zaman tek satir metraj gibi gorulur; sahada ise butun gorunur kaliteyi tasiyan temel referans tabakadir.",
      "Iyi siva, boyanin daha iyi gorunmesini saglar; kotu siva ise en iyi boyayi bile kusur gosteren bir perdeye cevirir.",
    ],
    conclusion: [
      "Siva isleri dogru yuzey hazirligi, dogru detay ve dogru kuruma disipliniyle yurudugunde sonraki tum kaplamalarin performansini yukseltir.",
      "Yanlis yurudugunde ise yeni malzemeden cok gorunmeyen tekrar isciligi ve teslim gecikmesi uretir.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn13914],
    keywords: ["siva", "alci siva", "dis siva", "yuzey duzlugu", "catlak kontrolu"],
  },
  {
    slugPath: "ince-isler/cati-kaplamasi",
    kind: "topic",
    quote: "Cati kaplamasi, ust ortuyu kapatmak degil; suyu ve buhari kontrollu bir rota ile yapidan uzaklastirmaktir.",
    tip: "Catiyi yalniz ust malzeme secimi olarak okumak, asil riski mahya, dere, baca dibi ve kenar detaylarinda gormemek demektir.",
    intro: [
      "Cati kaplamasi; membran, kiremit, metal panel veya benzeri sistemlerle yapinin en kritik dis etki sinirini olusturur. Kullanici icin ust ortu gibi gorunse de saha gerceginde bu paket su, buhar, ruzgar ve gunes davranisinin birlikte yonetildigi cok katmanli bir sistemdir.",
      "Bu bolgede yapilan hata ic mekanlarda gec fark edilir ama etkisi genis olur. Tavan lekesi, izolasyon kaybi, kuf ve tasiyici elemanlarda bozulma gibi sorunlarin baslangici cogu zaman tek bir zayif detaya dayanir.",
      "Bir insaat muhendisi icin cati kaplamasi yalniz malzeme metraji degil, dugum detaylari, su akisi, ruzgar guvenligi ve bakim senaryosu ile birlikte ele alinmasi gereken bir saha paketidir.",
    ],
    theory: [
      "Cati davranisinda ana mesele suyu yuzeyden hizla uzaklastirmak ve alt katmanlara kontrollu bir savunma cizgisi kurmaktir. Ust kaplama tek basina yeterli olmaz; altinda buhar kesici, su yalitimi ve yardimci katmanlar sistemin gercek guvencesini olusturur.",
      "Capraz ruzgar ve sicaklik etkileri kaplama malzemesinde hareket uretir. Bu nedenle bindirme yonu, sabitleme ritmi ve kenar detaylari sonradan tamamlanan aksesuarlar degil, tasarimin parcasidir.",
      "Cati hatalarinin buyuk bolumu genis alanda degil, mahya, dere, baca dibi ve parapet gibi dar dugumlerde ortaya cikar.",
      "TS 825 ve enerji performansi yaklasimi da cati katmanlarinin kabuk davranisi icin duvar kadar kritik oldugunu gosterir.",
    ],
    ruleTable: [
      {
        parameter: "Katman surekliligi",
        limitOrRequirement: "Buhar, isi ve su katmanlari sistem butunlugu icinde kesintisiz kurgulanmali",
        reference: "TS 825 + BEP Yonetmeligi",
        note: "Bir katmandaki kopukluk tum catinin davranisini zayiflatir.",
      },
      {
        parameter: "Egim ve su yonu",
        limitOrRequirement: "Kaplama tipiyle uyumlu egim ve tahliye mantigi kurulmalı",
        reference: "Cati sistem detayi",
        note: "Yetersiz egim, suyu detaylara geri iter.",
      },
      {
        parameter: "Kritik dugum detaylari",
        limitOrRequirement: "Mahya, dere, baca dibi ve parapet donusleri sistem aksesuarlariyla cozulmeli",
        reference: "Saha kalite plani",
        note: "En cok kacak bu dugumlerde ortaya cikar.",
      },
      {
        parameter: "Ruzgar ve sabitleme",
        limitOrRequirement: "Kenar ve yuksek emme riski olan bolgelerde sabitleme duzeni artirilmali",
        reference: "Uretici uygulama rehberi + saha kontrolu",
        note: "Kaplama kaybi lokal gibi baslar ama tum catinin emniyetini bozar.",
      },
    ],
    designOrApplicationSteps: [
      "Cati tipine gore su akisini, tahliye noktasini ve ana katman dizisini tasarim basinda sabitle.",
      "Alt tasiyici ve alt katman duzgunlugunu kaplama oncesi bagimsiz bir kabul kalemi olarak degerlendir.",
      "Mahya, dere, baca dibi ve parapet donuslerini saha cozumlerine birakmadan paftala.",
      "Kaplama montajinda bindirme yonu, sabitleme ritmi ve kenar guvenligini aks aks takip et.",
      "Yagis veya su deneyi ile kritik dugumleri teslim oncesi fiilen test et.",
    ],
    criticalChecks: [
      "Egim gercekten suyu tahliyeye yonlendiriyor mu?",
      "Alt katmanlarda yirtik, kopukluk veya ters bindirme var mi?",
      "Baca dibi, dere ve mahya detaylari uretici sistemine uygun mu?",
      "Kenar ve sakak bolgelerinde sabitleme sikligi yeterli mi?",
      "Su testi yalniz genis yuzeyde degil kritik dugumlerde de yapildi mi?",
    ],
    numericalExample: {
      title: "600 m2 cati yuzeyinde su tahliye ritmi yorumu",
      inputs: [
        { label: "Cati alani", value: "600 m2", note: "Endustriyel tek hacim ornegi" },
        { label: "Tahliye noktasi", value: "4 adet", note: "Es dagilmis varsayim" },
        { label: "Bir tahliyeye dusen alan", value: "150 m2", note: "Yaklasik dagilim" },
        { label: "Hedef", value: "Dugumlerde su bekletmemek", note: "Kacagi azaltmak" },
      ],
      assumptions: [
        "Tahliye noktalarinin konumu egim planiyla uyumludur.",
        "Oluk ve inisler montaj sonrasi serbesttir.",
        "Su testi kritik dugumleri de kapsayacaktir.",
      ],
      steps: [
        {
          title: "Alan dagilimini oku",
          formula: "600 / 4 = 150 m2",
          result: "Her tahliye noktasina dusen alan dengeli gorunmektedir.",
          note: "Ancak bu tek basina yeterli degildir; dere boyu ve lokal gol riski ayrica kontrol edilmelidir.",
        },
        {
          title: "Dugum riskini ekle",
          result: "Baca dibi ve parapet donusleri, genis alandan daha yuksek kacak riski tasir.",
          note: "Bu nedenle kabul turunda yalniz yatay yuzeye bakmak eksik kalir.",
        },
        {
          title: "Bakim etkisini yorumla",
          result: "Oluk temizligi ve yaprak birikimi icin erisim yoksa ilk kis mevsiminde sistem davranisi bozulabilir.",
          note: "Bakim plani cati performansinin parcasidir.",
        },
      ],
      checks: [
        "Tahliye noktasi sayisi kadar konumu da sorgulanmalidir.",
        "Su testinde mahya, dere ve baca dibi ayrica izlenmelidir.",
        "Bakim erisimi olmayan cati uzun omurlu kabul edilmemelidir.",
        "Alt katman fotograflari teslim dosyasinda tutulmalidir.",
      ],
      engineeringComment: "Cati kaplamasinda sorun genellikle ortada degil, detay cizgisinde baslar.",
    },
    tools: [
      { category: "Detay", name: "Cati katman ve dugum paftalari", purpose: "Mahya, dere ve baca dibi detaylarini uygulama oncesi netlestirmek." },
      { category: "Olcum", name: "Egim, aks ve bindirme kontrol seti", purpose: "Su akisi ve kaplama ritmini uygulama boyunca izlemek." },
      { category: "Kontrol", name: "Su testi ve ruzgar checklisti", purpose: "Kritik dugumlerde performans dogrulamasi yapmak." },
      { category: "Kayit", name: "Kapatma oncesi foto arsivi", purpose: "Sonradan gorulmeyecek alt katman detaylarini teslim dosyasina tasimak." },
    ],
    equipmentAndMaterials: [
      { group: "Alt katman", name: "Buhar kesici, su yalitimi ortusu ve tasiyici alt katmanlar", purpose: "Kaplama oncesi su ve buhar davranisini kontrol etmek.", phase: "Alt hazirlik" },
      { group: "Kaplama", name: "Membran, kiremit veya metal panel sistemi", purpose: "Ana su atma ve dis etki dayanimi saglamak.", phase: "Kaplama montaji" },
      { group: "Birlesim", name: "Mahya, dere, kenar ve baca dibi aksesuarlari", purpose: "Kritik cati dugumlerini sistematik sekilde kapatmak.", phase: "Detay cozumu" },
      { group: "Sabitleme", name: "Vida, klips ve ruzgar guvenlik elemanlari", purpose: "Kaplamanin yerinde ve emniyetli kalmasini saglamak.", phase: "Sabitleme" },
    ],
    mistakes: [
      { wrong: "Catinin kalitesini yalniz ust malzemeyle degerlendirmek.", correct: "Alt katman ve dugum detaylarini da ana kalite kalemi saymak." },
      { wrong: "Egim planini sahaya birakmak.", correct: "Su yonunu uygulama oncesi netlestirip sahada olcmek." },
      { wrong: "Baca dibi ve dere cozumlerini usta inisiyatifine birakmak.", correct: "Standart sistem detaylariyla ilerlemek." },
      { wrong: "Su testini atlamak.", correct: "Kritik dugumlerde kontrollu test yapmak." },
      { wrong: "Bakim yolunu ve oluk temizligini dusunmemek.", correct: "Isletme senaryosunu teslim dosyasina dahil etmek." },
    ],
    designVsField: [
      "Projede cati bir kesit ve ust gorunusle anlatilir; sahada ise her dugum ayri muhendislik karari ister.",
      "Iyi cati kendini gunlukte belli etmez; kotu cati ise ilk siddetli yagista tum yapinin problemi haline gelir.",
    ],
    conclusion: [
      "Cati kaplamasi dogru katman kurgusu, dogru tahliye ve dogru dugum detaylari ile calistiginda yapinin en guvenilir koruyucu katmani olur.",
      "Eksik detayla yurutuldugunde ise tamir maliyeti yuksek, ariza takibi zor ve itibar kaybi buyuk bir saha sorununa donusur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.ts825, SOURCE_LEDGER.enerjiPerformansi],
    keywords: ["cati kaplamasi", "mahya", "dere", "su tahliyesi", "TS 825"],
  },
  {
    slugPath: "ince-isler/alcipan",
    kind: "topic",
    quote: "Alcipan sistemleri hafif gorunur; ama servis koordinasyonu ve tolerans yonetimi acisindan en yogun ince is paketlerinden biridir.",
    tip: "Kuru yapida en buyuk hata, levhayi son gorunen yuzey sanip karkas ve servis planini ikinci plana atmaktir.",
    intro: [
      "Alcipan ve kuru yapi sistemleri; bolme duvar, asma tavan, shaft kapamasi ve servis gizleme gibi bircok ince is paketinin merkezinde yer alir. Hizli montaj avantajlari nedeniyle sik tercih edilir, ancak bu hiz dogru koordinasyon olmadan kalici kaliteye donusmez.",
      "Sahada alcipan islerinde gorulen sorunlarin buyuk kismi levhadan degil, tasiyici karkastan ve kapanmadan once cozulmemis servislerden kaynaklanir. Sonradan acilan delikler, unutulan bakim kapaklari ve zayif takviyeler sistemin omrunu kisaltir.",
      "Bir insaat muhendisi icin bu baslik, yalniz levha montaji degil; aks, kot, ses, yangin ve bakim erisimi gibi konularin tek paket halinde yonetilmesi anlamina gelir.",
    ],
    theory: [
      "Kuru yapi sistemlerinde performans, levha kalinligi kadar karkas davranisina baglidir. Profil araligi, aski noktasi, vidalama ritmi ve takviye elemanlari dogru kurgulanmadiginda yuzey catlagi ve sehim kisa surede ortaya cikar.",
      "Asma tavanlarda menfez, armatür, sprinkler ve bakim kapagi gibi cok sayida servis elemani ayni duzlemde bir araya gelir. Bu yogunluk levha kapatma oncesinde cozulmezse estetik kalite kadar isletme kalitesi de bozulur.",
      "Bolme duvarlarda ise akustik, yangin ve kapi boslugu performansi one cikar. Kapi kasasi, elektrik buatlari ve tesisat gecisleri bir arada dusunulmeden dogru duvar davranisi beklenemez.",
      "Bu nedenle alcipan, hafif bir sistem olmasina ragmen agir koordinasyon ister.",
    ],
    ruleTable: [
      {
        parameter: "Karkas duzeni",
        limitOrRequirement: "Profil, aski ve tasiyici ritim sistem detayina uygun kurulmalı",
        reference: "Uretici sistemi + saha kalite plani",
        note: "Levha kalitesi zayif karkasi telafi etmez.",
      },
      {
        parameter: "Servis koordinasyonu",
        limitOrRequirement: "Bakim kapagi, menfez, armatür ve gecisler kapatma oncesi sabitlenmeli",
        reference: "MEP overlay ve saha koordinasyonu",
        note: "Sonradan kesilen levha tekrar is ve catlak riski uretir.",
      },
      {
        parameter: "Mahal uyumu",
        limitOrRequirement: "Nemli ve yangin riski olan hacimlerde uygun levha tipi secilmeli",
        reference: "Yangin Yonetmeligi + mahal kullanim karari",
        note: "Her yerde ayni levha secimi teknik olarak dogru degildir.",
      },
      {
        parameter: "Derz kalitesi",
        limitOrRequirement: "Derz bandi, macun ve yuzey hazirligi katmanli sekilde uygulanmali",
        reference: "Uretici uygulama rehberi",
        note: "Tek katta hizli bitirilen derz daha sonra iz verir.",
      },
    ],
    designOrApplicationSteps: [
      "Bolme duvar ve asma tavan akslarini mimari ile MEP cakismazligi acisindan overlay uzerinden netlestir.",
      "Profil ritmini, aciklik ve yuk durumuna gore sadece usta aliskanligiyla degil detay paftasiyla kur.",
      "Bakim kapagi, ekipman takviyesi ve kapi bosluklarini kapatma oncesi isaretle ve fotola.",
      "Levha montajini sasirtmali derz mantigi ve dogru vida araligi ile tamamla.",
      "Son kat boya oncesi yan isik ve fonksiyon kontrolunu birlestir.",
    ],
    criticalChecks: [
      "Profil ve aski araligi detayla uyumlu mu?",
      "Bakim kapagi gereken tum noktalarda erisim var mi?",
      "Kapi ustu ve ekipman cevresinde gerekli takviyeler yerlestirildi mi?",
      "Levha birlesimleri ayni hatta devam eden zayif cizgi olusturuyor mu?",
      "Nemli mahallerde uygun levha tipi secildi mi?",
    ],
    numericalExample: {
      title: "2.40 m genis koridorda asma tavan servis yogunlugu yorumu",
      inputs: [
        { label: "Koridor genisligi", value: "2.40 m", note: "Uzun lineer mahal" },
        { label: "Tavan dususu", value: "35 cm", note: "Mekanik ve elektrik servisleri icin" },
        { label: "Servis elemani", value: "menfez + lineer aydinlatma + sprinkler", note: "Yogun tavan kurulumu" },
        { label: "Hedef", value: "Tek kapatma ile temiz bitis", note: "Tekrar isi azaltmak" },
      ],
      assumptions: [
        "MEP cikislari kapatma oncesi dondurulmustur.",
        "Bakim gerektiren gizli elemanlar belirlenmistir.",
        "Tavan aksi koridor merkezine gore kurulmaktadir.",
      ],
      steps: [
        {
          title: "Servis yogunlugunu oku",
          result: "Dar koridorda tum servislerin ayni eksene yaklasmasi gorsel ve teknik catisma riski tasir.",
          note: "Bu nedenle lineer aydinlatma, menfez ve sprinkler ortak ritimde tasarlanmalidir.",
        },
        {
          title: "Bakim etkisini ekle",
          result: "Damper, buat veya vana varsa en az bir bakim kapagi onceden planlanmalidir.",
          note: "Bakim noktasi unutulursa tavan ilk arizada tekrar acilir.",
        },
        {
          title: "Karkas yukunu yorumla",
          result: "Armatür ve kapak etrafinda ek tasiyici ihtiyaci kontrol edilmelidir.",
          note: "Yalniz levhaya dayali cozum zamanla sehim uretir.",
        },
      ],
      checks: [
        "Servis elemanlari rasgele degil, modullu yerlesmelidir.",
        "Bakim gerektiren gizli elemanlar kapakla erisilebilir olmalidir.",
        "Ekipman cevresi ek tasiyici ile desteklenmelidir.",
        "Kapatma oncesi fotograf kaydi alinmalidir.",
      ],
      engineeringComment: "Kuru yapinin gercek kalitesi, levha kapandiktan sonra ne kadar az geri donus gerektirdigiyle olculur.",
    },
    tools: [
      { category: "Koordinasyon", name: "Tavan duvar overlay paftalari", purpose: "Mekanik, elektrik ve kuru yapi sistemlerini tek eksende cozumlemek." },
      { category: "Olcum", name: "Kot cizelgesi, lazer nivo ve diyagonal kontrolu", purpose: "Asma tavan ve bolme duvarlarda duzlem dogrulugu saglamak." },
      { category: "Kontrol", name: "Profil, vida ve derz takip foyu", purpose: "Montaj kalitesini olculebilir hale getirmek." },
      { category: "Kayit", name: "Kapatma oncesi servis fotograf kaydi", purpose: "Bakim kapagi ve gecislerin sonradan da okunabilmesini saglamak." },
    ],
    equipmentAndMaterials: [
      { group: "Tasiyici", name: "Galvaniz profil, aski cubugu ve tasiyici kanal", purpose: "Kuru yapi karkasini rijit ve tekrar edilebilir sekilde kurmak.", phase: "Karkas montaji" },
      { group: "Kaplama", name: "Standart, neme dayanimli ve yangina dayanimli levhalar", purpose: "Mahal kullanimina gore yuzey ve yangin beklentisini karsilamak.", phase: "Levha montaji" },
      { group: "Tamamlama", name: "Derz bandi, derz dolgu ve kose profilleri", purpose: "Birlesimlerin catlak ve darbe riskini azaltmak.", phase: "Yuzey hazirligi" },
      { group: "Destek", name: "Kapak ve ekipman takviye parcalari", purpose: "Noktasal yuk alan bolgelerde sehim riskini dusurmek.", phase: "Detay cozumu" },
    ],
    mistakes: [
      { wrong: "Profil araligini goz karari kurmak.", correct: "Sistem detayina ve acikliga gore kontrollu ritim belirlemek." },
      { wrong: "Servis gecislerini levha kapandiktan sonra acmak.", correct: "Tum delik ve ekipman yerlerini once sabitlemek." },
      { wrong: "Bakim kapaklarini unutmak.", correct: "Mudahale gereken gizli noktalari uygulama basinda isaretlemek." },
      { wrong: "Noktasal yuk alan yerlerde takviye yapmamak.", correct: "Kapi, armatür ve ekipman cevresinde ek destek kullanmak." },
      { wrong: "Derzi tek kat macunla hizli kapatmaya calismak.", correct: "Katmanli bant ve yuzey hazirligi uygulamak." },
    ],
    designVsField: [
      "Tasarimda kuru yapi bir duz cizgi gibi okunur; sahada ise her profil ve her servis cikisi o cizginin gercek davranisini belirler.",
      "Iyi alcipan sistemi sessizdir; bakim zamani geldiginde kolay acilir ve kullanim sirasinda catlamaz.",
    ],
    conclusion: [
      "Alcipan sistemleri dogru karkas, dogru servis koordinasyonu ve dogru derz disipliniyle temiz sonuclar uretir.",
      "Yanlis yonetildiginde ise en cok sokulup tekrar yapilan ince is kalemlerinden biri olur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.yanginYonetmeligi],
    keywords: ["alcipan", "kuru yapi", "asma tavan", "bolme duvar", "servis koordinasyonu"],
  },
  {
    slugPath: "ince-isler/duvar-kaplamalari",
    kind: "topic",
    quote: "Duvar kaplamalari, malzeme seciminden once yuzey ve modul disiplininin gorunur sonucudur.",
    tip: "Duvar kaplamasinda kusuru son katta aramak genelde yanlistir; asil sorun cogu kez alt yuzey, nem veya bitis planinin gec kurulmasidir.",
    intro: [
      "Duvar kaplamalari; boya, fayans, dekoratif panel veya duvar kagidi ile mekanin son gorunur dilini kurar. Kullanici bu yuzeye bakarak kalite algisini olusturur; bu nedenle kucuk hata bile tum mahal hakkinda olumsuz izlenim yaratir.",
      "Ancak duvar kaplamalarinin basarisi, son kat malzemenin pahali olmasindan cok alt yuzeyin ne kadar kontrollu hazirlandigina baglidir. Dalga, emicilik farki, lokal nem ve yetersiz kose cozumu en sik sikayet kaynagidir.",
      "Bir insaat muhendisi icin duvar kaplamasi, dekoratif secim ile saha duzlem kalitesinin ayni masada cozuldugu bir kalite paketidir.",
    ],
    theory: [
      "Duvar yuzeylerinde gorunur kusur en cok yan isikta ortaya cikar. Bu nedenle kaplama kontrolu sadece onden bakilan goz karariyla degil, yuzey duzlugu ve isik davranisi ile birlikte yapilmalidir.",
      "Islak hacimlerde fayans veya seramik altinda kalan sistemler de sonucun parcasi olur. Su yalitimi, yapistirici secimi, derz tipi ve kose bitisi birlikte kurulmadan yalniz karo duzlugu uzerinden kalite okunamaz.",
      "Kuru hacimlerde boya ve duvar kagidi gibi sistemler emicilik farkina hassastir. Homojen olmayan macun veya gec kurumus tamir alanlari son katta ton ve doku farki uretir.",
      "Bu nedenle duvar kaplamalari, malzeme katalogundan secilen bir son kat degil; yuzey, modul ve birlesim disiplininin ortak ciktisidir.",
    ],
    ruleTable: [
      {
        parameter: "Yuzey hazirligi",
        limitOrRequirement: "Astar, macun, tesviye ve temizlik islemleri urun tipine uygun yapilmali",
        reference: "TS EN 13914 + urun teknik foyleri",
        note: "Ayni hazirlik tum kaplamalar icin gecerli kabul edilmemelidir.",
      },
      {
        parameter: "Islak hacim sistemi",
        limitOrRequirement: "Su yalitimi, yapistirici ve kaplama sistemi birlikte secilmeli",
        reference: "TS EN 12004 + saha islak hacim disiplini",
        note: "Duvar karosu altindaki katmanlar da performansin parcasidir.",
      },
      {
        parameter: "Modul ve bitis duzeni",
        limitOrRequirement: "Kose, nis, tesisat cikisi ve bitis cizgileri montaj oncesi planlanmali",
        reference: "Detay paftasi ve saha aplikasyonu",
        note: "Plansiz modul kose ve armatür cevresinde kusur uretir.",
      },
      {
        parameter: "Gorunur kalite",
        limitOrRequirement: "Yan isik ve farkli bakis acilarinda son kontrol yapilmali",
        reference: "Teslim kalite plani",
        note: "Sadece genel aydinlikta bakilan kontrol eksik kalir.",
      },
    ],
    designOrApplicationSteps: [
      "Mahal kullanimina gore boya, seramik veya duvar kagidi tipini teknik gerekliliklerle birlikte sec.",
      "Alt yuzeyin nem, duzgunluk ve emicilik durumunu urun seciminden bagimsiz olarak dogrula.",
      "Fayansli alanlarda nis, armatür ve kose donuslerini modul paftasi ile onceden kur.",
      "Boya ve kagit alanlarinda macun, zimpara ve astar katlarini aceleye getirmeden tamamla.",
      "Teslim turunda yan isik ve kullanici goz seviyesi ile kontrol yap.",
    ],
    criticalChecks: [
      "Alt yuzeyde lokal nem veya gec kurumus tamir alani var mi?",
      "Kose ve nis detaylari modul planina uyuyor mu?",
      "Islak hacimlerde su yalitimi ve yapistirici sistemi dogru sirada mi?",
      "Boya altinda zimpara izi, dalga veya yama farki gorunuyor mu?",
      "Derz ve bitis cizgileri ayni hatta devam ediyor mu?",
    ],
    numericalExample: {
      title: "240 cm banyo duvarinda modul ve bitis yorumu",
      inputs: [
        { label: "Duvar genisligi", value: "240 cm", note: "Banyo ana duvari" },
        { label: "Karo olcusu", value: "60 x 120 cm", note: "Dikey yerlesim" },
        { label: "Derz araligi", value: "2 mm", note: "Ornek tasarim karari" },
        { label: "Hedef", value: "Simetrik gorunus", note: "Kose parca riskini azaltmak" },
      ],
      assumptions: [
        "Kaplama merkez eksene gore planlanacaktir.",
        "Armatür cikislari modul paftasina islenecektir.",
        "Kose donusleri profil veya uygun detay ile cozulmustur.",
      ],
      steps: [
        {
          title: "Modul uygunlugunu yorumla",
          result: "240 cm olcusu, 60 cm'lik ana modulle dengeli bir baslangic verir.",
          note: "Yine de kose bitisi paftada test edilmeden uygulamaya gecilmemelidir.",
        },
        {
          title: "Armatür etkisini ekle",
          result: "Musluk ve nis cikislari modul cizgisini bozmayacak sekilde yeniden kaydirilabilir.",
          note: "Kucuk eksen kaymalari buyuk gorunur kusurlari onler.",
        },
        {
          title: "Kose parca riskini oku",
          result: "Dar bitis parcasi kalacaksa merkezleme veya modul boyu revize edilmelidir.",
          note: "Montaj sirasinda verilen anlik kararlar genelde daha kotu sonuc uretir.",
        },
      ],
      checks: [
        "Modul plani, tesisat cikislariyla birlikte okunmalidir.",
        "Dar kose parcasi riski montaj baslamadan cozulmelidir.",
        "Yalniz karo duzlugu degil, bitis cizgisi de kabul kriteridir.",
        "Islak hacimde alt sistemler de teslim dosyasina girmelidir.",
      ],
      engineeringComment: "Duvar kaplamasinda iyi sonuc, ilk karo yapismadan once modul ve bitis karari verildiginde alinir.",
    },
    tools: [
      { category: "Detay", name: "Duvar modul, renk ve bitis paftalari", purpose: "Boya ve fayans sistemlerini ayni mekan akisinda planlamak." },
      { category: "Olcum", name: "Yan isik kontrolu, mastar ve nem olcer", purpose: "Gorunur kusurlari uygulama bitmeden tespit etmek." },
      { category: "Kontrol", name: "Katman ve kuruma takip cizelgesi", purpose: "Astar, macun, yapistirici ve son kat sirasini izlemek." },
      { category: "Kayit", name: "Mahal bazli onay listesi", purpose: "Renk, doku ve bitis kararlarini teslim dosyasinda netlestirmek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Astar, macun, tesviye ve yuzey tamir urunleri", purpose: "Kaplama tasiyacak duvarda homojen emicilik ve duzgunluk elde etmek.", phase: "Hazirlik" },
      { group: "Kaplama", name: "Ic cephe boya sistemleri, fayans ve duvar kagidi tipleri", purpose: "Mahal kullanimina gore temizlenebilirlik ve gorunur kalite uretmek.", phase: "Kaplama" },
      { group: "Birlesim", name: "Kose profili, derz elemani ve bitis aksesuarleri", purpose: "Kose ve donuslerde gorunur sureklilik saglamak.", phase: "Bitis" },
      { group: "Koruma", name: "Gecici yuzey koruma ekipmanlari", purpose: "Son kat tamamlandiktan sonra duvari darbe ve lekeye karsi korumak.", phase: "Teslim oncesi" },
    ],
    mistakes: [
      { wrong: "Butun duvar kaplamalarinda ayni yuzey hazirligini uygulamak.", correct: "Kaplama tipine gore farkli hazirlik sistemi kullanmak." },
      { wrong: "Fayans modulunu montaj sirasinda belirlemek.", correct: "Kose, nis ve armatürlerle birlikte once paftalamak." },
      { wrong: "Su yalitimini kaplamadan bagimsiz gormek.", correct: "Islak hacimde sistemi butun olarak ele almak." },
      { wrong: "Boya kalitesini sadece genel isikta kontrol etmek.", correct: "Yan isik ve kullanici goz seviyesinde tekrar bakmak." },
      { wrong: "Bitis cizgilerini saha kararina birakmak.", correct: "Kapi, tavan ve supurgelikle birlikte onceden sabitlemek." },
    ],
    designVsField: [
      "Tasarimda duvar kaplamasi renk ve doku secimi gibi gorunur; sahada ise duzlem, nem, modul ve birlesim kalitesi bu secimin gercek sonucunu belirler.",
      "Pahali malzeme kusuru saklamaz; cogu zaman onu daha gorunur hale getirir.",
    ],
    conclusion: [
      "Duvar kaplamalari dogru alt yuzey, dogru modul ve dogru bitis kararlariyla birlestiginde mekani temiz ve uzun omurlu gosterir.",
      "Eksik hazirlikla uygulandiginda ise kusur en gorunur yerde ortaya cikar ve duzeltme maliyeti artar.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn13914, SOURCE_LEDGER.tsEn12004],
    keywords: ["duvar kaplamalari", "boya", "fayans", "duvar kagidi", "modul plani"],
  },
  {
    slugPath: "ince-isler/zemin-kaplamalari",
    kind: "topic",
    quote: "Zemin kaplamalarinda kalite, urunden once alt zeminin o urunu tasiyacak kadar hazir olup olmadigiyla baslar.",
    tip: "Seramik, parke veya epoksi secimi ne kadar iyi olursa olsun; nemli, dalgali ve plansiz alt zemin uzerinde uzun omurlu sonuc beklenmemelidir.",
    intro: [
      "Zemin kaplamalari; konut, ofis, islak hacim ve ticari alanlarda asinma, temizlik, hijyen ve estetik beklentilerini ayni anda karsilar. Bu nedenle zemin secimi yalniz zevk konusu degil, kullanim senaryosu ve saha performansi kararidir.",
      "Sahada en sik gorulen problem, urun kararinin cok erken; alt zemin kabulunun ise cok gec yapilmasidir. Oysa kaplamanin uzun omru, sap nemi, duzlemsellik ve esik detaylariyla dogrudan baglantilidir.",
      "Bir insaat muhendisi icin zemin kaplamasi, malzeme ve iscilik birlikteliginden daha fazlasidir. Kaplama takvimi, diger ekiplerin trafigi ve mahal gecisleri de ayni paketin parcasi olarak yonetilmelidir.",
    ],
    theory: [
      "Zemin sistemleri yuk dagitimina ve alt yuzey davranisina hassastir. Parke hareket eden bir sistem gibi davranirken, seramik ve tas daha rijit bir tabaka ister; epoksi ise alt yuzey temizligi ve aderans kalitesine cok daha fazla baglidir.",
      "Bu nedenle ayni binada kullanilan farkli zemin kaplamalari tek bir teknik kurala baglanamaz. Islak hacimde kaymazlik ve su davranisi, ofiste konfor ve akustik, ticari alanda ise asinma direnci one cikar.",
      "Alt zemin bozukluklari ilk anda gorunmeyebilir. Ancak kullanimla birlikte gicirdama, kose kalkmasi, lokal kirilma ve derz acilmasi gibi sikayetler cogu zaman esas malzemeden degil, hazirlik eksiginden dogar.",
      "Bu nedenle zemin kaplamasi, son gorunen katman degil; altinda yer alan kabul, tesviye, nem ve koruma disiplinlerinin bir sonucudur.",
    ],
    ruleTable: [
      {
        parameter: "Alt zemin duzlugu",
        limitOrRequirement: "Kaplama tipine uygun mastar ve kot surekliligi saglanmali",
        reference: "Saha kalite plani",
        note: "Dalgali sap, en pahali kaplamada bile kusuru gizlemez.",
      },
      {
        parameter: "Nem durumu",
        limitOrRequirement: "Parke ve hassas sistemlerde kaplama oncesi nem olcumu kayit altina alinmali",
        reference: "TS EN 13329 + urun teknik foyleri",
        note: "Ozellikle ahsap ve laminat esasli sistemlerde bu kontrol kritik onemdedir.",
      },
      {
        parameter: "Yapistirici ve birlesim sistemi",
        limitOrRequirement: "Kaplama ile yapistirici, derz ve altlik sistemi birlikte secilmeli",
        reference: "TS EN 12004 + saha uygulama disiplini",
        note: "Uyumsuz sistem secimi gec ariza uretir.",
      },
      {
        parameter: "Teslim ve koruma",
        limitOrRequirement: "Tamamlanan zemin diger ekiplerin trafigine kontrollu acilmali",
        reference: "Teslim plani",
        note: "Erken kullanima acilan zeminlerde ilk kusur genelde lojistikten gelir.",
      },
    ],
    designOrApplicationSteps: [
      "Mahal kullanimina gore kaplama tipini asinma, su ve bakim ihtiyaci ile birlikte sec.",
      "Alt zemini kot, duzluk ve nem acisindan bagimsiz bir kabul adimi olarak test et.",
      "Esik, supurgelik ve farkli urun gecislerini montaj oncesi paftala.",
      "Astar, yapistirici, altlik veya derz sistemini secilen kaplamayla uyumlu kur.",
      "Montaj sonrasi alan korumasini ve trafik acilisini is programina ayri bir kalem olarak yaz.",
    ],
    criticalChecks: [
      "Alt zemin 2 m mastarda kabul edilebilir duzlemde mi?",
      "Nem olcumu gereken mahallerde veri kayit altina alindi mi?",
      "Esik ve gecis detaylari kaplama montajindan once cozuldu mu?",
      "Ayni mahalde farkli zeminlerin bulustugu hatlar temiz okunuyor mu?",
      "Yeni kaplanan alan erken yuk ve darbe alip almiyor mu?",
    ],
    numericalExample: {
      title: "28 m2 odada parke oncesi nem yorumu",
      inputs: [
        { label: "Mahal alani", value: "28 m2", note: "Yatak odasi" },
        { label: "Olculen CM nemi", value: "%2.4", note: "Uc farkli noktada benzer sonuc" },
        { label: "Ornek hedef esik", value: "< %2.0", note: "Hassas parke sistemi varsayimi" },
        { label: "Mastar sapmasi", value: "2 mm / 2 m", note: "Duzlem uygun" },
      ],
      assumptions: [
        "Secilen kaplama neme hassastir.",
        "Olcum ayni cihaz ve ayni gunde alinmistir.",
        "Mahal havalandirma ile kurutulabilir durumdadir.",
      ],
      steps: [
        {
          title: "Nem verisini yorumla",
          formula: "2.4 > 2.0",
          result: "Duzlem uygun olsa da montaj icin erken davranilmaktadir.",
          note: "Alt zeminin yalniz duz olmasi yeterli degildir.",
        },
        {
          title: "Takvim etkisini ekle",
          result: "Kaplama takvimi ertelenmeli ve olcum tekrar edilmelidir.",
          note: "Kisa takvim kazanci uzun sureli kabarma riskine donusebilir.",
        },
        {
          title: "Esik ve koruma planini bagla",
          result: "Montaj tarihi revize edilirse esik ve supurgelik ekipleri de birlikte planlanmalidir.",
          note: "Zemin isi tek basina degil, bitis zinciriyle birlikte yonetilir.",
        },
      ],
      checks: [
        "Nem uygun degilse urunu degistirmek degil zemini olgunlastirmak gerekir.",
        "Duzlem ve nem birlikte okunmalidir.",
        "Kaplama takvimi lojistik baskidan cok veriye gore kurulmalidir.",
        "Koruma plani montaj karari kadar onemlidir.",
      ],
      engineeringComment: "Zemin kaplamasinda en kritik soru, urunun guzel olup olmadigi degil; zeminin o urunu tasiyacak kadar hazir olup olmadigidir.",
    },
    tools: [
      { category: "Olcum", name: "CM nem olcer, mastar ve lazer terazi", purpose: "Sap ve alt zemin kabulunu sayisal olarak dogrulamak." },
      { category: "Detay", name: "Esik, supurgelik ve gecis paftalari", purpose: "Farkli zemin kaplamalarinin birlestigi noktalari onceden cozumlemek." },
      { category: "Kontrol", name: "Deneme alan ve tuketim foyi", purpose: "Sistemi ana uygulama oncesi kucuk alanda test etmek." },
      { category: "Kayit", name: "Teslim ve koruma cizelgesi", purpose: "Tamamlanan zeminlerin trafik acilisini izlemek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Tesviye sapi, astar ve yuzey duzeltme malzemeleri", purpose: "Kaplama altinda duz ve homojen bir zemin birakmak.", phase: "Hazirlik" },
      { group: "Kaplama", name: "Seramik, parke, dogal tas ve epoksi sistemleri", purpose: "Mahal kullanimina gore asinma ve estetik beklentiyi karsilamak.", phase: "Kaplama" },
      { group: "Birlesim", name: "Yapistirici, derz dolgu, altlik ve esik profilleri", purpose: "Kaplama kenarlarinda teknik ve gorsel sureklilik saglamak.", phase: "Montaj ve bitis" },
      { group: "Koruma", name: "Yuzey koruma ortusu ve gecici trafik onlemleri", purpose: "Yeni kaplamayi erken kullanimdan korumak.", phase: "Teslim oncesi" },
    ],
    mistakes: [
      { wrong: "Sadece urun secimine odaklanip alt zemin kabulunu ertelemek.", correct: "Kaplama oncesi nem ve duzlem kontrolunu erken yapmak." },
      { wrong: "Mastar bozuklugunu yapistiriciyla telafi etmeye calismak.", correct: "Alt zemini once tesviye etmek." },
      { wrong: "Esik ve gecis kararlarini montaj sonuna birakmak.", correct: "Tum gecisleri pafta ile once cozumlemek." },
      { wrong: "Deneme alan yapmadan buyuk metraja girmek.", correct: "Sistemi kucuk alanda test edip sonra yaymak." },
      { wrong: "Yeni kaplamayi hemen yogun trafige acmak.", correct: "Koruma ve trafik planini teslimin parcasi yapmak." },
    ],
    designVsField: [
      "Tasarimda zemin kaplamasi katalog ve renk kartelasi ile secilir; sahada ise alt zemin verisi ve bitis detaylari sonucu belirler.",
      "Iyi zemin sessiz, dengeli ve temiz gorunur; kotu zemin ise once ses ve kirikla kendini gosterir.",
    ],
    conclusion: [
      "Zemin kaplamalari dogru alt zemin, dogru sistem bilesenleri ve dogru teslim disipliniyle uzun omurlu hale gelir.",
      "Bu zincirin halkalarindan biri zayif oldugunda sorun malzemede degil, saha yonetiminde ortaya cikar.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn12004, SOURCE_LEDGER.tsEn13329],
    keywords: ["zemin kaplamalari", "parke", "seramik", "sap nemi", "alt zemin kontrolu"],
  },
  {
    slugPath: "ince-isler/kapi-pencere",
    kind: "topic",
    quote: "Kapi ve pencere sistemleri, boslugu kapatan eleman degil; kabuk performansini ve gunluk kullanim konforunu belirleyen birlesim paketidir.",
    tip: "Dograma montajini yalniz kasa yerlestirme isi gibi gormek, sizdirmazlik, isi koprusu ve acilma-kapanma sorunlarini davet eder.",
    intro: [
      "Kapi ve pencere sistemleri, kullanici icin gecis ve gun isigi elemani gibi gorunur; fakat teknik olarak isi kaybi, hava-su sizdirmazligi ve guvenlik performansinin ana dugumlerinden biridir.",
      "Sahada dograma kaynakli sorunlarin buyuk bolumu urunun fabrikasyon kalitesinden degil, montaj bosluklarindan, denizlik cozumlerinden ve yetersiz ankrajdan dogar. Cogu sikayet ilk yagmurlarda veya ilk kis sezonunda ortaya cikar.",
      "Bir insaat muhendisi icin kapi-pencere isi; kaba bosluk olcusu, kasa konumu, kopuk-bant-mastik katmanlari ve denizlik akisi ile birlikte okunmasi gereken bir kabuk muhendisligi paketidir.",
    ],
    theory: [
      "Dograma performansi yalniz profil sinifi veya cam paketiyle belirlenmez. Kasanin duvar icindeki konumu, montaj boslugunun tutarliligi ve cevre sizdirmazlik katmanlari urun performansinin sahadaki gercek karsiligini olusturur.",
      "Pencerelerde isi ve hava davranisi, kapi sistemlerinde ise fonksiyon ve guvenlik daha belirgin hale gelir. Ancak her iki durumda da duvar ile kasa arasindaki birlesim cizgisi kritik bolgedir.",
      "Dograma kasasi kaba yapinin toleranslarini absorbe etmek zorundadir. Bu sebeple yamuk acikliklar ve kontrolsuz kopuk dolumu montaj sonrasinda kanat ayari ve sizdirmazlik sorunlarina donusebilir.",
      "TS 825 ve enerji performansi yaklasimi, dograma kararlarini duvar kesitinden ayri dusunmemeyi gerektirir.",
    ],
    ruleTable: [
      {
        parameter: "Kaba bosluk ve tolerans",
        limitOrRequirement: "Kasa cevresinde kontrollu montaj boslugu birakilmali ve yamuk acikliklar onceden duzeltilmeli",
        reference: "Dograma montaj detayi",
        note: "Bosluk kontrolu saglanmayan montaj sonradan ayarsizlige doner.",
      },
      {
        parameter: "Ankraj ve tasiyicilik",
        limitOrRequirement: "Kasa noktalarinda yeterli mekanik sabitleme ve ayar duzeni kurulmalı",
        reference: "Saha uygulama disiplini",
        note: "Yalniz kopuk ile tasiyicilik beklenmemelidir.",
      },
      {
        parameter: "Sizdirmazlik ve isi koprusu kontrolu",
        limitOrRequirement: "Bant, kopuk, mastik ve denizlik cozumleri katmanli olarak tamamlanmali",
        reference: "TS 825 + BEP Yonetmeligi",
        note: "Tek katmanli dusunulen birlesimler kisa surede zayiflar.",
      },
      {
        parameter: "Fonksiyon testi",
        limitOrRequirement: "Acilma-kapanma, kilit ve su davranisi teslim oncesi test edilmeli",
        reference: "Teslim kalite plani",
        note: "Yalniz gorsel kabul yeterli degildir.",
      },
    ],
    designOrApplicationSteps: [
      "Dograma tipini mahal kullanimina ve kabuk performansi beklentisine gore sec.",
      "Kaba bosluklari montajdan once olc ve yamuk ya da eksik acikliklari onceden duzelt.",
      "Kasa konumunu duvar kesiti, yalitim kalinligi ve denizlik duzeniyle birlikte belirle.",
      "Ankraj, ayar takozu, kopuk, bant ve mastik katmanlarini bir sistem olarak uygula.",
      "Teslim oncesi tum kanatlarda acilma-kapanma, kilit ve sizdirmazlik kontrolunu kayitli yap.",
    ],
    criticalChecks: [
      "Kaba bosluk olculeri kasa icin yeterli ve tutarli tolerans birakiyor mu?",
      "Kasa ankraj noktalarinda gevseklik veya asiri kopuk dolumu var mi?",
      "Denizlik ve damlalik suyu cepheden uzaklastiriyor mu?",
      "Kasa cevresinde sizdirmazlik katmanlari kesintisiz mi?",
      "Kanatlar surtme veya kilit zorlamasi yapiyor mu?",
    ],
    numericalExample: {
      title: "150 x 150 cm pencere icin kaba bosluk yorumu",
      inputs: [
        { label: "Nominal pencere olcusu", value: "150 x 150 cm", note: "PVC pencere ornegi" },
        { label: "Olculen kaba bosluk", value: "153 x 152 cm", note: "Saha olcusu" },
        { label: "Diyagonal fark", value: "8 mm", note: "Aciklik yamuklugu" },
        { label: "Hedef", value: "Dengeli montaj boslugu ve ayar", note: "Sizdirmazlik performansi icin" },
      ],
      assumptions: [
        "Pencere kasasi cevresinde montaj ve sizdirmazlik boslugu gereklidir.",
        "Aciklik sivadan once duzeltilebilir durumdadir.",
        "Denizlik detayi montajla birlikte cozulecektir.",
      ],
      steps: [
        {
          title: "Bosluk uygunlugunu oku",
          result: "Kaba bosluk nominal olcuden buyuktur ve montaj payi birakmaktadir.",
          note: "Ancak payin dengeli dagilmasi icin yamukluk da giderilmelidir.",
        },
        {
          title: "Diyagonal farki yorumla",
          formula: "8 mm diyagonal fark",
          result: "Aciklik tamamen dogru kabul edilmemelidir; kasa ayari zorlanabilir.",
          note: "Yamuk aciklik, kanat ayarini ve contanin davranisini olumsuz etkiler.",
        },
        {
          title: "Montaj stratejisini kur",
          result: "Aciklik duzeltilip kasa merkezli yerlestirilmeli, sizdirmazlik katmanlari dengeli uygulanmalidir.",
          note: "Aksi halde bir kenarda asiri kopuk, diger kenarda zayif birlesim olusur.",
        },
      ],
      checks: [
        "Bosluk buyuklugu kadar dengeli dagilimi de onemlidir.",
        "Diyagonal fark kabul edilmeden montajla kapatilmamalidir.",
        "Denizlik ve damlalik cozumleri su davranisinin ana parcasidir.",
        "Fonksiyon testi gorsel kabulden once gelmelidir.",
      ],
      engineeringComment: "Dograma montajinda en pahali urun bile yamuk bosluga dogru davranis gostermez.",
    },
    tools: [
      { category: "Detay", name: "Kapi pencere montaj ve kabuk paftalari", purpose: "Kasa konumu ve sizdirmazlik kararlarini duvar bitisiyle birlikte okumak." },
      { category: "Olcum", name: "Lazer metre, sakul ve diyagonal kontrol seti", purpose: "Kaba bosluk ve dograma dogrulugunu sayisal olarak dogrulamak." },
      { category: "Kontrol", name: "Acilma-kapanma ve sizdirmazlik test listesi", purpose: "Montaji fonksiyon testi ile teslim almak." },
      { category: "Kayit", name: "Cam dograma etiket ve bakim foyi", purpose: "Cam paketi ve servis bilgisini isletmeye devretmek." },
    ],
    equipmentAndMaterials: [
      { group: "Dograma", name: "PVC veya aluminyum kasa-kanat sistemleri", purpose: "Isi, hava, su ve gunluk kullanim beklentisini birlikte karsilamak.", phase: "Montaj" },
      { group: "Baglanti", name: "Ankraj, ayar takozu ve montaj yardimcilari", purpose: "Kasayi duvar icinde dogru aks ve duzlemde sabitlemek.", phase: "Kasa yerlestirme" },
      { group: "Sizdirmazlik", name: "Bant, kopuk, mastik ve denizlik aksesuarlari", purpose: "Kasa cevresinde su hava sizdirmazligini saglamak.", phase: "Birlesim cozumu" },
      { group: "Kontrol", name: "Ayar ekipmani ve fonksiyon test malzemeleri", purpose: "Kanat davranisini ve kilit ayarini teslim oncesi dogrulamak.", phase: "Son ayar" },
    ],
    mistakes: [
      { wrong: "Kaba boslugu olcmeden uretime veya montaja gitmek.", correct: "Acikliklari montaj oncesi sahada netlestirmek." },
      { wrong: "Kasayi yalniz kopuk ile tutturmaya calismak.", correct: "Mekanik ankraj ve ayar duzeni kurmak." },
      { wrong: "Denizlik ve damlalik detayini ikincil gormek.", correct: "Su yonetimini dograma paketinin ana parcasi saymak." },
      { wrong: "Sizdirmazligi tek kat mastikle cozmek.", correct: "Bant, kopuk ve mastik katmanlarini birlikte uygulamak." },
      { wrong: "Kanat ayarini teslim sonrasina birakmak.", correct: "Fonksiyon testini montaj kabulunun parcasi yapmak." },
    ],
    designVsField: [
      "Projede kapi ve pencere bir sembol gibi gorunur; sahada ise kasanin duvarla kurdugu birlesim gercek performansi belirler.",
      "Iyi dograma montaji sadece guzel gorunmez; ruzgarda gurultu yapmaz, yagmurda su almaz ve kisinda kullaniciyi rahatsiz etmez.",
    ],
    conclusion: [
      "Kapi ve pencere sistemleri dogru bosluk, dogru ankraj ve dogru sizdirmazlik katmanlariyla birlestiginde kabuk performansini ciddi sekilde yukseltir.",
      "Eksik detayla uygulandiginda ise en sik tekrarlanan sikayet kalemlerinden birine donusur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.ts825, SOURCE_LEDGER.enerjiPerformansi],
    keywords: ["kapi pencere", "dograma", "sizdirmazlik", "denizlik", "TS 825"],
  },
];
