import { BRANCH_SOURCE_LEDGER, SOURCE_LEDGER } from "../source-ledger";
import type { BinaGuidePageSpec } from "../types";

const INCE_TOPIC_OVERRIDE_SOURCES = [...BRANCH_SOURCE_LEDGER["ince-isler"]];

export const inceIslerTopicOverrides: BinaGuidePageSpec[] = [
  {
    slugPath: "ince-isler/siva",
    kind: "topic",
    quote: "Sıva, duvari kapatan ara katman değil; butun ince isin görünür kalitesini tasiyan ana referans duzlemdir.",
    tip: "Sıva isini yalnız metraj ve iscilik hizi olarak görmek, boya ve kaplama altinda kalici dalga, çatlak ve tekrar iş maliyeti uretir.",
    intro: [
      "Sıva isleri, ince imalatlarin en sessiz ama en belirleyici kalemlerinden biridir. Boya, fayans veya duvar kagidi ne kadar iyi secilirse secilsin, altindaki sıva duzlemi zayifsa kullanıcı kalitesi hemen düşük algilanir.",
      "Sahada en sık yapilan hata, sivayi dekoratif sonuclardan bağımsız bir on hazirlik adimi sanmaktir. Oysa iç ve dış sıva; aderans, çatlak kontrolü, su davranisi, köşe dogrulugu ve boya alti kabulun birlikte yonetildigi teknik bir tabakadir.",
      "Bir inşaat mühendisi için sıva yalnız usta kalitesi meselesi degildir. İş programi, alt yüzey hazirligi, file detaylari ve sonraki ekiplerin takvimi bu kalemin gercek performansini belirler.",
    ],
    theory: [
      "Sıva sistemleri alt yuzeyle birlikte calisir. Tuğla, gazbeton, briket veya betonarme yuzeylerin emicilikleri ve hareketleri farkli oldugu için aynı harc davranisini beklemek yanlistir.",
      "Iyi bir sıva yalnız duz görünmez; aynı zamanda kolon-duvar birleşimi, pencere koseleri ve tesisat onarim hatlarindaki gerilme farklarini da yonetir.",
      "Dış cephede su ve gunes etkisi, iç mekanda ise kuruma hizi ve son kat uyumu one çıkar. Çok hızlı su kaybeden veya kur almayan sıva yuzeyi tozuma ve büzülme riski tasir.",
      "Bu nedenle sıva, harc surme operasyonundan çok yüzey muhendisligi olarak ele alinmalidir.",
    ],
    ruleTable: [
      {
        parameter: "Yüzey hazirligi",
        limitOrRequirement: "Alt yüzey toz, gevsek parca ve aderansi zayif tabakalardan arindirilmali",
        reference: "TS EN 13914 uygulama prensipleri",
        note: "Kirli veya parlak yuzeye atilan sıva en basta zayif bag ile başlar.",
      },
      {
        parameter: "Katman kalinligi",
        limitOrRequirement: "Asiri kalin tek kat yerine kontrollu katman ve mastar düzeni kullanilmali",
        reference: "TS EN 13914 + saha kalite plani",
        note: "Tek hamlede kalinlik buyutmek ayrilma ve çatlak riskini artirir.",
      },
      {
        parameter: "Kritik birleşimler",
        limitOrRequirement: "Kolon-duvar ve aciklik kenarlarinda file veya uygun destek detayi uygulanmali",
        reference: "Saha çatlak kontrol disiplini",
        note: "Catlaklar en önce malzeme degisim sinirlarinda gorulur.",
      },
      {
        parameter: "Kuruma ve koruma",
        limitOrRequirement: "Yeni sıva ani gunes, rüzgar ve yağmur etkisinden korunmali",
        reference: "Şantiye uygulama disiplini",
        note: "Kur almayan yüzey son katta renk ve tozuma problemi uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Alt yüzey tipini belirle ve betonarme, tuğla veya gazbeton için ayri hazirlik stratejisi kur.",
      "Aderans koprusu veya astar ihtiyacini ilk panelde doğrula.",
      "Mastar hatlarini, köşe profillerini ve kalinlik referanslarini uygulama öncesi sabitle.",
      "Kritik birlesimlerde file donusu ve chase tamirlerini ana sıva ile birlikte coz.",
      "Boya veya kaplama ekibine gecmeden önce yan isikta duzlem, çatlak ve yama kontrolü yap.",
    ],
    criticalChecks: [
      "Alt yüzey emiciligi ve aderansi sahada kontrol edildi mi?",
      "Kolon-duvar ve pencere koselerinde file veya uygun detay var mi?",
      "Mastar duzlemi boyunca dalga ve ani sapma olusuyor mu?",
      "Asiri kalin tek kat uygulama yapilan bolgeler var mi?",
      "Kuruma tamamlanmadan sonraki ekipler alana giriyor mu?",
    ],
    numericalExample: {
      title: "İç duvar sivasinda duzlem ve kalinlik karari",
      inputs: [
        { label: "Duvar uzunlugu", value: "4.80 m", note: "Salon duvari" },
        { label: "Olculen yüzey sapmasi", value: "12 mm", note: "En yüksek ve en düşük nokta arasi" },
        { label: "Planlanan ortalama sıva kalinligi", value: "15 mm", note: "İç mekan ornek deger" },
        { label: "Hedef", value: "Boya alti duzlem", note: "Son katta dalga olusturmamak" },
      ],
      assumptions: [
        "Alt yüzey taşıyıcı olarak saglam ve temizdir.",
        "Elektrik chase tamirleri uygulama öncesi tamamlanmistir.",
        "Son kat boya planlandigi için dalga toleransi dusuktur.",
      ],
      steps: [
        {
          title: "Sapmayi yorumla",
          formula: "12 mm < 15 mm",
          result: "Olculen bozukluk planlanan katman icinde yonetilebilir görünür.",
          note: "Yine de lokal cepler tek hamlede doldurulmamalidir.",
        },
        {
          title: "Duzlem stratejisini kur",
          result: "Mastar referanslari ile önce ana duzlem kurulup ara boşluklar kontrollu doldurulmalidir.",
          note: "Serbest el uygulama boya altinda gozle gorulur dalga uretir.",
        },
        {
          title: "Çatlak riskini ekle",
          result: "Kolon-dolgu duvar gecislerinde file detayina ihtiyaç vardir.",
          note: "Duzlem saglansa bile malzeme degisim cizgileri file olmadan risklidir.",
        },
      ],
      checks: [
        "Mastar kontrolü sıva sirasinda yapilmali, boya ekibine birakilmamalidir.",
        "Asiri kalin lokal cep noktalarinda katmanli yaklasim dusunulmelidir.",
        "Kritik birlesimlerde çatlak onleyici detay unutulmamalidir.",
        "Kuruma süresi takvim baskisiyla kisaltilmamalidir.",
      ],
      engineeringComment: "Sıva kalitesini boya geldikten sonra değil, mastar duvardayken yakalamak gerekir.",
    },
    tools: [
      { category: "Detay", name: "Cephe ve iç mekan sıva detay paftalari", purpose: "Katman dizisini ve kritik koseleri uygulama öncesi netlestirmek." },
      { category: "Ölçüm", name: "Mastar, lazer nivo ve nem olcer", purpose: "Yüzey duzlugu ve kuruma seviyesini sayisal olarak kontrol etmek." },
      { category: "Kontrol", name: "Alan bazli kalite takip cizelgesi", purpose: "Çatlak, yama ve boya alti kabul notlarini mahal bazinda izlemek." },
      { category: "Saha", name: "Deneme paneli ve fotograf kaydı", purpose: "Secilen sistemin iscilik kalitesini genellemeden önce görmek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Yüzey temizlik ekipmanlari ve aderans astarlari", purpose: "Gevsek toz ve emicilik farklarini kontrol altina almak.", phase: "Hazirlik" },
      { group: "Uygulama", name: "Cimento esasli sıva, alçı sıva ve karisim ekipmanlari", purpose: "İç ve dış mekan ihtiyacina göre doğru katman davranisi uretmek.", phase: "Sıva uygulamasi" },
      { group: "Detay", name: "Köşe profili, file ve damlalik elemanlari", purpose: "Kritik koselerde çatlak riskini azaltmak.", phase: "Detay çözümü" },
      { group: "Koruma", name: "Kur ve gunes koruma ekipmanlari", purpose: "Taze sivayi hızlı su kaybi ve hava etkisinden korumak.", phase: "Uygulama sonrasi" },
    ],
    mistakes: [
      { wrong: "Tozlu veya kalıp yagli yuzeye doğrudan sıva atmak.", correct: "Yuzeyi temizleyip aderans kosullarini önce dogrulamak." },
      { wrong: "Butun duzeltmeyi tek kat kalin sivayla cozmeye çalışmak.", correct: "Referans mastar ve katmanli uygulama ile ilerlemek." },
      { wrong: "Kolon-duvar birlesimlerinde file kullanmamak.", correct: "Malzeme degisim hatlarini çatlak riski olarak görmek." },
      { wrong: "Kur almadan sonraki ekiplere alani acmak.", correct: "Sivayi yeterli kuruma ve koruma suresiyle teslim etmek." },
      { wrong: "Boya alti kaliteyi son katta duzeltmeye çalışmak.", correct: "Sıva asamasinda duzlem ve yama kalitesini bitirmek." },
    ],
    designVsField: [
      "Projede sıva kalemi cogu zaman tek satir metraj gibi gorulur; sahada ise butun görünür kaliteyi tasiyan temel referans tabakadir.",
      "Iyi sıva, boyanin daha iyi gorunmesini sağlar; kötü sıva ise en iyi boyayi bile kusur gosteren bir perdeye cevirir.",
    ],
    conclusion: [
      "Sıva isleri doğru yüzey hazirligi, doğru detay ve doğru kuruma disipliniyle yurudugunde sonraki tüm kaplamalarin performansini yukseltir.",
      "Yanlış yurudugunde ise yeni malzemeden çok gorunmeyen tekrar isciligi ve teslim gecikmesi uretir.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn13914],
    keywords: ["sıva", "alçı sıva", "dış sıva", "yüzey duzlugu", "çatlak kontrolü"],
  },
  {
    slugPath: "ince-isler/cati-kaplamasi",
    kind: "topic",
    quote: "Çatı kaplaması, üst ortuyu kapatmak değil; suyu ve buhari kontrollu bir rota ile yapidan uzaklastirmaktir.",
    tip: "Catiyi yalnız üst malzeme secimi olarak okumak, asil riski mahya, dere, baca dibi ve kenar detaylarinda gormemek demektir.",
    intro: [
      "Çatı kaplaması; membran, kiremit, metal panel veya benzeri sistemlerle yapının en kritik dış etki sinirini olusturur. Kullanıcı için üst ortu gibi gorunse de saha gerceginde bu paket su, buhar, rüzgar ve gunes davranisinin birlikte yonetildigi çok katmanli bir sistemdir.",
      "Bu bolgede yapilan hata iç mekanlarda gec fark edilir ama etkisi genis olur. Tavan lekesi, izolasyon kaybi, kuf ve taşıyıcı elemanlarda bozulma gibi sorunlarin başlangıcı cogu zaman tek bir zayif detaya dayanir.",
      "Bir inşaat mühendisi için çatı kaplaması yalnız malzeme metraji değil, düğüm detaylari, su akisi, rüzgar güvenliği ve bakım senaryosu ile birlikte ele alinmasi gereken bir saha paketidir.",
    ],
    theory: [
      "Çatı davranisinda ana mesele suyu yuzeyden hizla uzaklastirmak ve alt katmanlara kontrollu bir savunma cizgisi kurmaktir. Üst kaplama tek basina yeterli olmaz; altinda buhar kesici, su yalitimi ve yardimci katmanlar sistemin gercek guvencesini olusturur.",
      "Capraz rüzgar ve sıcaklık etkileri kaplama malzemesinde hareket uretir. Bu nedenle bindirme yonu, sabitleme ritmi ve kenar detaylari sonradan tamamlanan aksesuarlar değil, tasarimin parcasidir.",
      "Çatı hatalarinin buyuk bolumu genis alanda değil, mahya, dere, baca dibi ve parapet gibi dar dugumlerde ortaya çıkar.",
      "TS 825 ve enerji performansi yaklasimi da çatı katmanlarinin kabuk davranisi için duvar kadar kritik oldugunu gosterir.",
    ],
    ruleTable: [
      {
        parameter: "Katman surekliligi",
        limitOrRequirement: "Buhar, isi ve su katmanlari sistem butunlugu icinde kesintisiz kurgulanmali",
        reference: "TS 825 + BEP Yönetmeliği",
        note: "Bir katmandaki kopukluk tüm çatının davranisini zayiflatir.",
      },
      {
        parameter: "Egim ve su yonu",
        limitOrRequirement: "Kaplama tipiyle uyumlu egim ve tahliye mantigi kurulmalı",
        reference: "Çatı sistem detayi",
        note: "Yetersiz egim, suyu detaylara geri iter.",
      },
      {
        parameter: "Kritik düğüm detaylari",
        limitOrRequirement: "Mahya, dere, baca dibi ve parapet donusleri sistem aksesuarlariyla cozulmeli",
        reference: "Saha kalite plani",
        note: "En çok kacak bu dugumlerde ortaya çıkar.",
      },
      {
        parameter: "Rüzgar ve sabitleme",
        limitOrRequirement: "Kenar ve yüksek emme riski olan bolgelerde sabitleme düzeni artirilmali",
        reference: "Uretici uygulama rehberi + saha kontrolü",
        note: "Kaplama kaybi lokal gibi başlar ama tüm çatının emniyetini bozar.",
      },
    ],
    designOrApplicationSteps: [
      "Çatı tipine göre su akisini, tahliye noktasini ve ana katman dizisini tasarim basinda sabitle.",
      "Alt taşıyıcı ve alt katman duzgunlugunu kaplama öncesi bağımsız bir kabul kalemi olarak degerlendir.",
      "Mahya, dere, baca dibi ve parapet donuslerini saha cozumlerine birakmadan paftala.",
      "Kaplama montajinda bindirme yonu, sabitleme ritmi ve kenar guvenligini aks aks takip et.",
      "Yagis veya su deneyi ile kritik dugumleri teslim öncesi fiilen test et.",
    ],
    criticalChecks: [
      "Egim gercekten suyu tahliyeye yonlendiriyor mu?",
      "Alt katmanlarda yirtik, kopukluk veya ters bindirme var mi?",
      "Baca dibi, dere ve mahya detaylari uretici sistemine uygun mu?",
      "Kenar ve sakak bolgelerinde sabitleme sikligi yeterli mi?",
      "Su testi yalnız genis yuzeyde değil kritik dugumlerde de yapildi mi?",
    ],
    numericalExample: {
      title: "600 m2 çatı yuzeyinde su tahliye ritmi yorumu",
      inputs: [
        { label: "Çatı alani", value: "600 m2", note: "Endustriyel tek hacim ornegi" },
        { label: "Tahliye noktası", value: "4 adet", note: "Es dagilmis varsayim" },
        { label: "Bir tahliyeye dusen alan", value: "150 m2", note: "Yaklasik dagilim" },
        { label: "Hedef", value: "Dugumlerde su bekletmemek", note: "Kacagi azaltmak" },
      ],
      assumptions: [
        "Tahliye noktalarinin konumu egim planiyla uyumludur.",
        "Oluk ve inisler montaj sonrasi serbesttir.",
        "Su testi kritik dugumleri de kapsayacaktir.",
      ],
      steps: [
        {
          title: "Alan dagilimini oku",
          formula: "600 / 4 = 150 m2",
          result: "Her tahliye noktasina dusen alan dengeli gorunmektedir.",
          note: "Ancak bu tek basina yeterli degildir; dere boyu ve lokal gol riski ayrıca kontrol edilmelidir.",
        },
        {
          title: "Dugum riskini ekle",
          result: "Baca dibi ve parapet donusleri, genis alandan daha yüksek kacak riski tasir.",
          note: "Bu nedenle kabul turunda yalnız yatay yuzeye bakmak eksik kalir.",
        },
        {
          title: "Bakım etkisini yorumla",
          result: "Oluk temizligi ve yaprak birikimi için erişim yoksa ilk kis mevsiminde sistem davranisi bozulabilir.",
          note: "Bakım plani çatı performansinin parcasidir.",
        },
      ],
      checks: [
        "Tahliye noktası sayisi kadar konumu da sorgulanmalidir.",
        "Su testinde mahya, dere ve baca dibi ayrıca izlenmelidir.",
        "Bakım erisimi olmayan çatı uzun omurlu kabul edilmemelidir.",
        "Alt katman fotograflari teslim dosyasinda tutulmalidir.",
      ],
      engineeringComment: "Çatı kaplamasinda sorun genellikle ortada değil, detay cizgisinde başlar.",
    },
    tools: [
      { category: "Detay", name: "Çatı katman ve düğüm paftalari", purpose: "Mahya, dere ve baca dibi detaylarini uygulama öncesi netlestirmek." },
      { category: "Ölçüm", name: "Egim, aks ve bindirme kontrol seti", purpose: "Su akisi ve kaplama ritmini uygulama boyunca izlemek." },
      { category: "Kontrol", name: "Su testi ve rüzgar checklisti", purpose: "Kritik dugumlerde performans dogrulamasi yapmak." },
      { category: "Kayıt", name: "Kapatma öncesi foto arşivi", purpose: "Sonradan gorulmeyecek alt katman detaylarini teslim dosyasina tasimak." },
    ],
    equipmentAndMaterials: [
      { group: "Alt katman", name: "Buhar kesici, su yalitimi ortusu ve taşıyıcı alt katmanlar", purpose: "Kaplama öncesi su ve buhar davranisini kontrol etmek.", phase: "Alt hazirlik" },
      { group: "Kaplama", name: "Membran, kiremit veya metal panel sistemi", purpose: "Ana su atma ve dış etki dayanımı saglamak.", phase: "Kaplama montaji" },
      { group: "Birleşim", name: "Mahya, dere, kenar ve baca dibi aksesuarlari", purpose: "Kritik çatı dugumlerini sistematik sekilde kapatmak.", phase: "Detay çözümü" },
      { group: "Sabitleme", name: "Vida, klips ve rüzgar güvenlik elemanlari", purpose: "Kaplamanin yerinde ve emniyetli kalmasini saglamak.", phase: "Sabitleme" },
    ],
    mistakes: [
      { wrong: "Catinin kalitesini yalnız üst malzemeyle degerlendirmek.", correct: "Alt katman ve düğüm detaylarini da ana kalite kalemi saymak." },
      { wrong: "Egim planini sahaya birakmak.", correct: "Su yonunu uygulama öncesi netlestirip sahada olcmek." },
      { wrong: "Baca dibi ve dere cozumlerini usta inisiyatifine birakmak.", correct: "Standart sistem detaylariyla ilerlemek." },
      { wrong: "Su testini atlamak.", correct: "Kritik dugumlerde kontrollu test yapmak." },
      { wrong: "Bakım yolunu ve oluk temizligini dusunmemek.", correct: "Isletme senaryosunu teslim dosyasina dahil etmek." },
    ],
    designVsField: [
      "Projede çatı bir kesit ve üst gorunusle anlatilir; sahada ise her düğüm ayri mühendislik karari ister.",
      "Iyi çatı kendini gunlukte belli etmez; kötü çatı ise ilk siddetli yagista tüm yapının problemi haline gelir.",
    ],
    conclusion: [
      "Çatı kaplaması doğru katman kurgusu, doğru tahliye ve doğru düğüm detaylari ile calistiginda yapının en guvenilir koruyucu katmani olur.",
      "Eksik detayla yurutuldugunde ise tamir maliyeti yüksek, ariza takibi zor ve itibar kaybi buyuk bir saha sorununa donusur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.ts825, SOURCE_LEDGER.enerjiPerformansi],
    keywords: ["çatı kaplaması", "mahya", "dere", "su tahliyesi", "TS 825"],
  },
  {
    slugPath: "ince-isler/alcipan",
    kind: "topic",
    quote: "Alçıpan sistemleri hafif görünür; ama servis koordinasyonu ve tolerans yönetimi acisindan en yoğun ince iş paketlerinden biridir.",
    tip: "Kuru yapida en buyuk hata, levhayi son gorunen yüzey sanip karkas ve servis planini ikinci plana atmaktir.",
    intro: [
      "Alçıpan ve kuru yapı sistemleri; bölme duvar, asma tavan, şaft kapamasi ve servis gizleme gibi bircok ince iş paketinin merkezinde yer alir. Hızlı montaj avantajlari nedeniyle sık tercih edilir, ancak bu hiz doğru koordinasyon olmadan kalici kaliteye donusmez.",
      "Sahada alçıpan islerinde gorulen sorunlarin buyuk kismi levhadan değil, taşıyıcı karkastan ve kapanmadan önce cozulmemis servislerden kaynaklanir. Sonradan acilan delikler, unutulan bakım kapaklari ve zayif takviyeler sistemin omrunu kisaltir.",
      "Bir inşaat mühendisi için bu baslik, yalnız levha montaji değil; aks, kot, ses, yangın ve bakım erisimi gibi konularin tek paket halinde yonetilmesi anlamina gelir.",
    ],
    theory: [
      "Kuru yapı sistemlerinde performans, levha kalinligi kadar karkas davranisina baglidir. Profil araligi, aski noktası, vidalama ritmi ve takviye elemanlari doğru kurgulanmadiginda yüzey catlagi ve sehim kısa surede ortaya çıkar.",
      "Asma tavanlarda menfez, armatür, sprinkler ve bakım kapagi gibi çok sayida servis elemani aynı duzlemde bir araya gelir. Bu yogunluk levha kapatma oncesinde cozulmezse estetik kalite kadar isletme kalitesi de bozulur.",
      "Bölme duvarlarda ise akustik, yangın ve kapı boşluğu performansi one çıkar. Kapı kasasi, elektrik buatlari ve tesisat gecisleri bir arada dusunulmeden doğru duvar davranisi beklenemez.",
      "Bu nedenle alçıpan, hafif bir sistem olmasina ragmen agir koordinasyon ister.",
    ],
    ruleTable: [
      {
        parameter: "Karkas düzeni",
        limitOrRequirement: "Profil, aski ve taşıyıcı ritim sistem detayina uygun kurulmalı",
        reference: "Uretici sistemi + saha kalite plani",
        note: "Levha kalitesi zayif karkasi telafi etmez.",
      },
      {
        parameter: "Servis koordinasyonu",
        limitOrRequirement: "Bakım kapagi, menfez, armatür ve gecisler kapatma öncesi sabitlenmeli",
        reference: "MEP overlay ve saha koordinasyonu",
        note: "Sonradan kesilen levha tekrar iş ve çatlak riski uretir.",
      },
      {
        parameter: "Mahal uyumu",
        limitOrRequirement: "Nemli ve yangın riski olan hacimlerde uygun levha tipi secilmeli",
        reference: "Yangın Yönetmeliği + mahal kullanım karari",
        note: "Her yerde aynı levha secimi teknik olarak doğru degildir.",
      },
      {
        parameter: "Derz kalitesi",
        limitOrRequirement: "Derz bandi, macun ve yüzey hazirligi katmanli sekilde uygulanmali",
        reference: "Uretici uygulama rehberi",
        note: "Tek katta hızlı bitirilen derz daha sonra iz verir.",
      },
    ],
    designOrApplicationSteps: [
      "Bölme duvar ve asma tavan akslarini mimari ile MEP cakismazligi acisindan overlay uzerinden netlestir.",
      "Profil ritmini, aciklik ve yük durumuna göre sadece usta aliskanligiyla değil detay paftasiyla kur.",
      "Bakım kapagi, ekipman takviyesi ve kapı bosluklarini kapatma öncesi isaretle ve fotola.",
      "Levha montajini sasirtmali derz mantigi ve doğru vida araligi ile tamamla.",
      "Son kat boya öncesi yan isik ve fonksiyon kontrolünü birlestir.",
    ],
    criticalChecks: [
      "Profil ve aski araligi detayla uyumlu mu?",
      "Bakım kapagi gereken tüm noktalarda erişim var mi?",
      "Kapı ustu ve ekipman cevresinde gerekli takviyeler yerlestirildi mi?",
      "Levha birlesimleri aynı hatta devam eden zayif cizgi olusturuyor mu?",
      "Nemli mahallerde uygun levha tipi secildi mi?",
    ],
    numericalExample: {
      title: "2.40 m genis koridorda asma tavan servis yoğunluğu yorumu",
      inputs: [
        { label: "Koridor genisligi", value: "2.40 m", note: "Uzun lineer mahal" },
        { label: "Tavan dususu", value: "35 cm", note: "Mekanik ve elektrik servisleri için" },
        { label: "Servis elemani", value: "menfez + lineer aydinlatma + sprinkler", note: "Yoğun tavan kurulumu" },
        { label: "Hedef", value: "Tek kapatma ile temiz bitis", note: "Tekrar isi azaltmak" },
      ],
      assumptions: [
        "MEP cikislari kapatma öncesi dondurulmustur.",
        "Bakım gerektiren gizli elemanlar belirlenmistir.",
        "Tavan aksi koridor merkezine göre kurulmaktadir.",
      ],
      steps: [
        {
          title: "Servis yogunlugunu oku",
          result: "Dar koridorda tüm servislerin aynı eksene yaklasmasi görsel ve teknik catisma riski tasir.",
          note: "Bu nedenle lineer aydinlatma, menfez ve sprinkler ortak ritimde tasarlanmalidir.",
        },
        {
          title: "Bakım etkisini ekle",
          result: "Damper, buat veya vana varsa en az bir bakım kapagi önceden planlanmalidir.",
          note: "Bakım noktası unutulursa tavan ilk arizada tekrar acilir.",
        },
        {
          title: "Karkas yukunu yorumla",
          result: "Armatür ve kapak etrafinda ek taşıyıcı ihtiyaci kontrol edilmelidir.",
          note: "Yalnız levhaya dayali çözüm zamanla sehim uretir.",
        },
      ],
      checks: [
        "Servis elemanlari rasgele değil, modullu yerlesmelidir.",
        "Bakım gerektiren gizli elemanlar kapakla erişilebilir olmalidir.",
        "Ekipman cevresi ek taşıyıcı ile desteklenmelidir.",
        "Kapatma öncesi fotograf kaydı alinmalidir.",
      ],
      engineeringComment: "Kuru yapının gercek kalitesi, levha kapandiktan sonra ne kadar az geri donus gerektirdigiyle olculur.",
    },
    tools: [
      { category: "Koordinasyon", name: "Tavan duvar overlay paftalari", purpose: "Mekanik, elektrik ve kuru yapı sistemlerini tek eksende cozumlemek." },
      { category: "Ölçüm", name: "Kot cizelgesi, lazer nivo ve diyagonal kontrolü", purpose: "Asma tavan ve bölme duvarlarda duzlem dogrulugu saglamak." },
      { category: "Kontrol", name: "Profil, vida ve derz takip foyu", purpose: "Montaj kalitesini olculebilir hale getirmek." },
      { category: "Kayıt", name: "Kapatma öncesi servis fotograf kaydı", purpose: "Bakım kapagi ve gecislerin sonradan da okunabilmesini saglamak." },
    ],
    equipmentAndMaterials: [
      { group: "Taşıyıcı", name: "Galvaniz profil, aski cubugu ve taşıyıcı kanal", purpose: "Kuru yapı karkasini rijit ve tekrar edilebilir sekilde kurmak.", phase: "Karkas montaji" },
      { group: "Kaplama", name: "Standart, neme dayanimli ve yangına dayanimli levhalar", purpose: "Mahal kullanimina göre yüzey ve yangın beklentisini karsilamak.", phase: "Levha montaji" },
      { group: "Tamamlama", name: "Derz bandi, derz dolgu ve köşe profilleri", purpose: "Birlesimlerin çatlak ve darbe riskini azaltmak.", phase: "Yüzey hazirligi" },
      { group: "Destek", name: "Kapak ve ekipman takviye parcalari", purpose: "Noktasal yük alan bolgelerde sehim riskini dusurmek.", phase: "Detay çözümü" },
    ],
    mistakes: [
      { wrong: "Profil araligini göz karari kurmak.", correct: "Sistem detayina ve acikliga göre kontrollu ritim belirlemek." },
      { wrong: "Servis gecislerini levha kapandiktan sonra acmak.", correct: "Tüm delik ve ekipman yerlerini önce sabitlemek." },
      { wrong: "Bakım kapaklarini unutmak.", correct: "Mudahale gereken gizli noktaları uygulama basinda isaretlemek." },
      { wrong: "Noktasal yük alan yerlerde takviye yapmamak.", correct: "Kapı, armatür ve ekipman cevresinde ek destek kullanmak." },
      { wrong: "Derzi tek kat macunla hızlı kapatmaya çalışmak.", correct: "Katmanli bant ve yüzey hazirligi uygulamak." },
    ],
    designVsField: [
      "Tasarimda kuru yapı bir duz cizgi gibi okunur; sahada ise her profil ve her servis çıkışı o cizginin gercek davranisini belirler.",
      "Iyi alçıpan sistemi sessizdir; bakım zamani geldiginde kolay acilir ve kullanım sirasinda catlamaz.",
    ],
    conclusion: [
      "Alçıpan sistemleri doğru karkas, doğru servis koordinasyonu ve doğru derz disipliniyle temiz sonuclar uretir.",
      "Yanlış yonetildiginde ise en çok sokulup tekrar yapilan ince iş kalemlerinden biri olur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.yanginYonetmeligi],
    keywords: ["alçıpan", "kuru yapı", "asma tavan", "bölme duvar", "servis koordinasyonu"],
  },
  {
    slugPath: "ince-isler/duvar-kaplamalari",
    kind: "topic",
    quote: "Duvar kaplamaları, malzeme seciminden önce yüzey ve modul disiplininin görünür sonucudur.",
    tip: "Duvar kaplamasinda kusuru son katta aramak genelde yanlistir; asil sorun cogu kez alt yüzey, nem veya bitis planinin gec kurulmasidir.",
    intro: [
      "Duvar kaplamaları; boya, fayans, dekoratif panel veya duvar kagidi ile mekanin son görünür dilini kurar. Kullanıcı bu yuzeye bakarak kalite algisini olusturur; bu nedenle küçük hata bile tüm mahal hakkinda olumsuz izlenim yaratir.",
      "Ancak duvar kaplamalarinin basarisi, son kat malzemenin pahali olmasindan çok alt yuzeyin ne kadar kontrollu hazirlandigina baglidir. Dalga, emicilik farki, lokal nem ve yetersiz köşe çözümü en sık sikayet kaynagidir.",
      "Bir inşaat mühendisi için duvar kaplaması, dekoratif secim ile saha duzlem kalitesinin aynı masada cozuldugu bir kalite paketidir.",
    ],
    theory: [
      "Duvar yuzeylerinde görünür kusur en çok yan isikta ortaya çıkar. Bu nedenle kaplama kontrolü sadece onden bakilan göz karariyla değil, yüzey duzlugu ve isik davranisi ile birlikte yapilmalidir.",
      "Islak hacimlerde fayans veya seramik altinda kalan sistemler de sonucun parçası olur. Su yalitimi, yapıştırıcı secimi, derz tipi ve köşe bitisi birlikte kurulmadan yalnız karo duzlugu uzerinden kalite okunamaz.",
      "Kuru hacimlerde boya ve duvar kagidi gibi sistemler emicilik farkina hassastir. Homojen olmayan macun veya gec kurumus tamir alanlari son katta ton ve doku farki uretir.",
      "Bu nedenle duvar kaplamaları, malzeme katalogundan secilen bir son kat değil; yüzey, modul ve birleşim disiplininin ortak ciktisidir.",
    ],
    ruleTable: [
      {
        parameter: "Yüzey hazirligi",
        limitOrRequirement: "Astar, macun, tesviye ve temizlik islemleri urun tipine uygun yapilmali",
        reference: "TS EN 13914 + urun teknik foyleri",
        note: "Aynı hazirlik tüm kaplamalar için gecerli kabul edilmemelidir.",
      },
      {
        parameter: "Islak hacim sistemi",
        limitOrRequirement: "Su yalitimi, yapıştırıcı ve kaplama sistemi birlikte secilmeli",
        reference: "TS EN 12004 + saha islak hacim disiplini",
        note: "Duvar karosu altindaki katmanlar da performansin parcasidir.",
      },
      {
        parameter: "Modul ve bitis düzeni",
        limitOrRequirement: "Köşe, niş, tesisat çıkışı ve bitis cizgileri montaj öncesi planlanmali",
        reference: "Detay paftası ve saha aplikasyonu",
        note: "Plansiz modul köşe ve armatür cevresinde kusur uretir.",
      },
      {
        parameter: "Görünür kalite",
        limitOrRequirement: "Yan isik ve farkli bakis acilarinda son kontrol yapilmali",
        reference: "Teslim kalite plani",
        note: "Sadece genel aydinlikta bakilan kontrol eksik kalir.",
      },
    ],
    designOrApplicationSteps: [
      "Mahal kullanimina göre boya, seramik veya duvar kagidi tipini teknik gerekliliklerle birlikte sec.",
      "Alt yuzeyin nem, duzgunluk ve emicilik durumunu urun seciminden bağımsız olarak doğrula.",
      "Fayansli alanlarda niş, armatür ve köşe donuslerini modul paftası ile önceden kur.",
      "Boya ve kagit alanlarinda macun, zimpara ve astar katlarini aceleye getirmeden tamamla.",
      "Teslim turunda yan isik ve kullanıcı göz seviyesi ile kontrol yap.",
    ],
    criticalChecks: [
      "Alt yuzeyde lokal nem veya gec kurumus tamir alani var mi?",
      "Köşe ve niş detaylari modul planina uyuyor mu?",
      "Islak hacimlerde su yalitimi ve yapıştırıcı sistemi doğru sırada mi?",
      "Boya altinda zimpara izi, dalga veya yama farki gorunuyor mu?",
      "Derz ve bitis cizgileri aynı hatta devam ediyor mu?",
    ],
    numericalExample: {
      title: "240 cm banyo duvarinda modul ve bitis yorumu",
      inputs: [
        { label: "Duvar genisligi", value: "240 cm", note: "Banyo ana duvari" },
        { label: "Karo ölçüsü", value: "60 x 120 cm", note: "Dikey yerlesim" },
        { label: "Derz araligi", value: "2 mm", note: "Ornek tasarim karari" },
        { label: "Hedef", value: "Simetrik görünüş", note: "Köşe parca riskini azaltmak" },
      ],
      assumptions: [
        "Kaplama merkez eksene göre planlanacaktir.",
        "Armatür cikislari modul paftasina islenecektir.",
        "Köşe donusleri profil veya uygun detay ile cozulmustur.",
      ],
      steps: [
        {
          title: "Modul uygunlugunu yorumla",
          result: "240 cm ölçüsü, 60 cm'lik ana modulle dengeli bir başlangıç verir.",
          note: "Yine de köşe bitisi paftada test edilmeden uygulamaya gecilmemelidir.",
        },
        {
          title: "Armatür etkisini ekle",
          result: "Musluk ve niş cikislari modul cizgisini bozmayacak sekilde yeniden kaydirilabilir.",
          note: "Küçük eksen kaymalari buyuk görünür kusurlari onler.",
        },
        {
          title: "Köşe parca riskini oku",
          result: "Dar bitis parçası kalacaksa merkezleme veya modul boyu revize edilmelidir.",
          note: "Montaj sirasinda verilen anlik kararlar genelde daha kötü sonuc uretir.",
        },
      ],
      checks: [
        "Modul plani, tesisat cikislariyla birlikte okunmalidir.",
        "Dar köşe parçası riski montaj başlamadan çözülmelidir.",
        "Yalnız karo duzlugu değil, bitis cizgisi de kabul kriteridir.",
        "Islak hacimde alt sistemler de teslim dosyasina girmelidir.",
      ],
      engineeringComment: "Duvar kaplamasinda iyi sonuc, ilk karo yapismadan önce modul ve bitis karari verildiginde alinir.",
    },
    tools: [
      { category: "Detay", name: "Duvar modul, renk ve bitis paftalari", purpose: "Boya ve fayans sistemlerini aynı mekan akisinda planlamak." },
      { category: "Ölçüm", name: "Yan isik kontrolü, mastar ve nem olcer", purpose: "Görünür kusurlari uygulama bitmeden tespit etmek." },
      { category: "Kontrol", name: "Katman ve kuruma takip cizelgesi", purpose: "Astar, macun, yapıştırıcı ve son kat sirasini izlemek." },
      { category: "Kayıt", name: "Mahal bazli onay listesi", purpose: "Renk, doku ve bitis kararlarini teslim dosyasinda netlestirmek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Astar, macun, tesviye ve yüzey tamir urunleri", purpose: "Kaplama tasiyacak duvarda homojen emicilik ve duzgunluk elde etmek.", phase: "Hazirlik" },
      { group: "Kaplama", name: "İç cephe boya sistemleri, fayans ve duvar kagidi tipleri", purpose: "Mahal kullanimina göre temizlenebilirlik ve görünür kalite uretmek.", phase: "Kaplama" },
      { group: "Birleşim", name: "Köşe profili, derz elemani ve bitis aksesuarleri", purpose: "Köşe ve donuslerde görünür sureklilik saglamak.", phase: "Bitis" },
      { group: "Koruma", name: "Gecici yüzey koruma ekipmanlari", purpose: "Son kat tamamlandiktan sonra duvari darbe ve lekeye karsi korumak.", phase: "Teslim öncesi" },
    ],
    mistakes: [
      { wrong: "Butun duvar kaplamalarinda aynı yüzey hazirligini uygulamak.", correct: "Kaplama tipine göre farkli hazirlik sistemi kullanmak." },
      { wrong: "Fayans modulunu montaj sirasinda belirlemek.", correct: "Köşe, niş ve armatürlerle birlikte önce paftalamak." },
      { wrong: "Su yalitimini kaplamadan bağımsız görmek.", correct: "Islak hacimde sistemi butun olarak ele almak." },
      { wrong: "Boya kalitesini sadece genel isikta kontrol etmek.", correct: "Yan isik ve kullanıcı göz seviyesinde tekrar bakmak." },
      { wrong: "Bitis cizgilerini saha kararina birakmak.", correct: "Kapı, tavan ve supurgelikle birlikte önceden sabitlemek." },
    ],
    designVsField: [
      "Tasarimda duvar kaplaması renk ve doku secimi gibi görünür; sahada ise duzlem, nem, modul ve birleşim kalitesi bu secimin gercek sonucunu belirler.",
      "Pahali malzeme kusuru saklamaz; cogu zaman onu daha görünür hale getirir.",
    ],
    conclusion: [
      "Duvar kaplamaları doğru alt yüzey, doğru modul ve doğru bitis kararlariyla birlestiginde mekani temiz ve uzun omurlu gosterir.",
      "Eksik hazirlikla uygulandiginda ise kusur en görünür yerde ortaya çıkar ve duzeltme maliyeti artar.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn13914, SOURCE_LEDGER.tsEn12004],
    keywords: ["duvar kaplamaları", "boya", "fayans", "duvar kagidi", "modul plani"],
  },
  {
    slugPath: "ince-isler/zemin-kaplamalari",
    kind: "topic",
    quote: "Zemin kaplamalarinda kalite, urunden önce alt zeminin o urunu tasiyacak kadar hazir olup olmadigiyla başlar.",
    tip: "Seramik, parke veya epoksi secimi ne kadar iyi olursa olsun; nemli, dalgali ve plansiz alt zemin üzerinde uzun omurlu sonuc beklenmemelidir.",
    intro: [
      "Zemin kaplamaları; konut, ofis, islak hacim ve ticari alanlarda asinma, temizlik, hijyen ve estetik beklentilerini aynı anda karsilar. Bu nedenle zemin secimi yalnız zevk konusu değil, kullanım senaryosu ve saha performansi kararidir.",
      "Sahada en sık gorulen problem, urun kararinin çok erken; alt zemin kabulunun ise çok gec yapilmasidir. Oysa kaplamanin uzun omru, şap nemi, duzlemsellik ve esik detaylariyla doğrudan baglantilidir.",
      "Bir inşaat mühendisi için zemin kaplaması, malzeme ve iscilik birlikteliginden daha fazlasidir. Kaplama takvimi, diger ekiplerin trafigi ve mahal gecisleri de aynı paketin parçası olarak yonetilmelidir.",
    ],
    theory: [
      "Zemin sistemleri yük dagitimina ve alt yüzey davranisina hassastir. Parke hareket eden bir sistem gibi davranirken, seramik ve tas daha rijit bir tabaka ister; epoksi ise alt yüzey temizligi ve aderans kalitesine çok daha fazla baglidir.",
      "Bu nedenle aynı binada kullanilan farkli zemin kaplamaları tek bir teknik kurala baglanamaz. Islak hacimde kaymazlik ve su davranisi, ofiste konfor ve akustik, ticari alanda ise asinma direnci one çıkar.",
      "Alt zemin bozukluklari ilk anda gorunmeyebilir. Ancak kullanimla birlikte gicirdama, köşe kalkmasi, lokal kırılma ve derz acilmasi gibi sikayetler cogu zaman esas malzemeden değil, hazirlik eksiginden dogar.",
      "Bu nedenle zemin kaplaması, son gorunen katman değil; altinda yer alan kabul, tesviye, nem ve koruma disiplinlerinin bir sonucudur.",
    ],
    ruleTable: [
      {
        parameter: "Alt zemin duzlugu",
        limitOrRequirement: "Kaplama tipine uygun mastar ve kot surekliligi saglanmali",
        reference: "Saha kalite plani",
        note: "Dalgali şap, en pahali kaplamada bile kusuru gizlemez.",
      },
      {
        parameter: "Nem durumu",
        limitOrRequirement: "Parke ve hassas sistemlerde kaplama öncesi nem olcumu kayıt altina alinmali",
        reference: "TS EN 13329 + urun teknik foyleri",
        note: "Ozellikle ahşap ve laminat esasli sistemlerde bu kontrol kritik onemdedir.",
      },
      {
        parameter: "Yapıştırıcı ve birleşim sistemi",
        limitOrRequirement: "Kaplama ile yapıştırıcı, derz ve altlik sistemi birlikte secilmeli",
        reference: "TS EN 12004 + saha uygulama disiplini",
        note: "Uyumsuz sistem secimi gec ariza uretir.",
      },
      {
        parameter: "Teslim ve koruma",
        limitOrRequirement: "Tamamlanan zemin diger ekiplerin trafigine kontrollu acilmali",
        reference: "Teslim plani",
        note: "Erken kullanima acilan zeminlerde ilk kusur genelde lojistikten gelir.",
      },
    ],
    designOrApplicationSteps: [
      "Mahal kullanimina göre kaplama tipini asinma, su ve bakım ihtiyaci ile birlikte sec.",
      "Alt zemini kot, duzluk ve nem acisindan bağımsız bir kabul adimi olarak test et.",
      "Esik, süpürgelik ve farkli urun gecislerini montaj öncesi paftala.",
      "Astar, yapıştırıcı, altlik veya derz sistemini secilen kaplamayla uyumlu kur.",
      "Montaj sonrasi alan korumasini ve trafik acilisini iş programina ayri bir kalem olarak yaz.",
    ],
    criticalChecks: [
      "Alt zemin 2 m mastarda kabul edilebilir duzlemde mi?",
      "Nem olcumu gereken mahallerde veri kayıt altina alindi mi?",
      "Esik ve geçiş detaylari kaplama montajindan önce cozuldu mu?",
      "Aynı mahalde farkli zeminlerin bulustugu hatlar temiz okunuyor mu?",
      "Yeni kaplanan alan erken yük ve darbe alip almiyor mu?",
    ],
    numericalExample: {
      title: "28 m2 odada parke öncesi nem yorumu",
      inputs: [
        { label: "Mahal alani", value: "28 m2", note: "Yatak odasi" },
        { label: "Olculen CM nemi", value: "%2.4", note: "Uc farkli noktada benzer sonuc" },
        { label: "Ornek hedef esik", value: "< %2.0", note: "Hassas parke sistemi varsayimi" },
        { label: "Mastar sapmasi", value: "2 mm / 2 m", note: "Duzlem uygun" },
      ],
      assumptions: [
        "Secilen kaplama neme hassastir.",
        "Ölçüm aynı cihaz ve aynı gunde alinmistir.",
        "Mahal havalandirma ile kurutulabilir durumdadir.",
      ],
      steps: [
        {
          title: "Nem verisini yorumla",
          formula: "2.4 > 2.0",
          result: "Duzlem uygun olsa da montaj için erken davranilmaktadir.",
          note: "Alt zeminin yalnız duz olmasi yeterli degildir.",
        },
        {
          title: "Takvim etkisini ekle",
          result: "Kaplama takvimi ertelenmeli ve ölçüm tekrar edilmelidir.",
          note: "Kısa takvim kazanci uzun sureli kabarma riskine donusebilir.",
        },
        {
          title: "Esik ve koruma planini bagla",
          result: "Montaj tarihi revize edilirse esik ve süpürgelik ekipleri de birlikte planlanmalidir.",
          note: "Zemin isi tek basina değil, bitis zinciriyle birlikte yonetilir.",
        },
      ],
      checks: [
        "Nem uygun degilse urunu degistirmek değil zemini olgunlastirmak gerekir.",
        "Duzlem ve nem birlikte okunmalidir.",
        "Kaplama takvimi lojistik baskidan çok veriye göre kurulmalidir.",
        "Koruma plani montaj karari kadar önemlidir.",
      ],
      engineeringComment: "Zemin kaplamasinda en kritik soru, urunun güzel olup olmadigi değil; zeminin o urunu tasiyacak kadar hazir olup olmadigidir.",
    },
    tools: [
      { category: "Ölçüm", name: "CM nem olcer, mastar ve lazer terazi", purpose: "Sap ve alt zemin kabulunu sayisal olarak dogrulamak." },
      { category: "Detay", name: "Esik, süpürgelik ve geçiş paftalari", purpose: "Farkli zemin kaplamalarinin birlestigi noktaları önceden cozumlemek." },
      { category: "Kontrol", name: "Deneme alan ve tuketim foyi", purpose: "Sistemi ana uygulama öncesi küçük alanda test etmek." },
      { category: "Kayıt", name: "Teslim ve koruma cizelgesi", purpose: "Tamamlanan zeminlerin trafik acilisini izlemek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Tesviye şapı, astar ve yüzey duzeltme malzemeleri", purpose: "Kaplama altinda duz ve homojen bir zemin birakmak.", phase: "Hazirlik" },
      { group: "Kaplama", name: "Seramik, parke, dogal tas ve epoksi sistemleri", purpose: "Mahal kullanimina göre asinma ve estetik beklentiyi karsilamak.", phase: "Kaplama" },
      { group: "Birleşim", name: "Yapıştırıcı, derz dolgu, altlik ve esik profilleri", purpose: "Kaplama kenarlarinda teknik ve görsel sureklilik saglamak.", phase: "Montaj ve bitis" },
      { group: "Koruma", name: "Yüzey koruma ortusu ve gecici trafik onlemleri", purpose: "Yeni kaplamayi erken kullanimdan korumak.", phase: "Teslim öncesi" },
    ],
    mistakes: [
      { wrong: "Sadece urun secimine odaklanip alt zemin kabulunu ertelemek.", correct: "Kaplama öncesi nem ve duzlem kontrolünü erken yapmak." },
      { wrong: "Mastar bozuklugunu yapistiriciyla telafi etmeye çalışmak.", correct: "Alt zemini önce tesviye etmek." },
      { wrong: "Esik ve geçiş kararlarini montaj sonuna birakmak.", correct: "Tüm gecisleri pafta ile önce cozumlemek." },
      { wrong: "Deneme alan yapmadan buyuk metraja girmek.", correct: "Sistemi küçük alanda test edip sonra yaymak." },
      { wrong: "Yeni kaplamayi hemen yoğun trafige acmak.", correct: "Koruma ve trafik planini teslimin parçası yapmak." },
    ],
    designVsField: [
      "Tasarimda zemin kaplaması katalog ve renk kartelasi ile secilir; sahada ise alt zemin verisi ve bitis detaylari sonucu belirler.",
      "Iyi zemin sessiz, dengeli ve temiz görünür; kötü zemin ise önce ses ve kirikla kendini gosterir.",
    ],
    conclusion: [
      "Zemin kaplamaları doğru alt zemin, doğru sistem bilesenleri ve doğru teslim disipliniyle uzun omurlu hale gelir.",
      "Bu zincirin halkalarindan biri zayif oldugunda sorun malzemede değil, saha yonetiminde ortaya çıkar.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn12004, SOURCE_LEDGER.tsEn13329],
    keywords: ["zemin kaplamaları", "parke", "seramik", "şap nemi", "alt zemin kontrolü"],
  },
  {
    slugPath: "ince-isler/kapi-pencere",
    kind: "topic",
    quote: "Kapı ve pencere sistemleri, boşluğu kapatan eleman değil; kabuk performansini ve gunluk kullanım konforunu belirleyen birleşim paketidir.",
    tip: "Doğrama montajini yalnız kasa yerlestirme isi gibi görmek, sızdırmazlık, isi koprusu ve acilma-kapanma sorunlarini davet eder.",
    intro: [
      "Kapı ve pencere sistemleri, kullanıcı için geçiş ve gun isigi elemani gibi görünür; fakat teknik olarak isi kaybi, hava-su sizdirmazligi ve güvenlik performansinin ana dugumlerinden biridir.",
      "Sahada doğrama kaynakli sorunlarin buyuk bolumu urunun fabrikasyon kalitesinden değil, montaj bosluklarindan, denizlik cozumlerinden ve yetersiz ankrajdan dogar. Cogu sikayet ilk yagmurlarda veya ilk kis sezonunda ortaya çıkar.",
      "Bir inşaat mühendisi için kapı-pencere isi; kaba boşluk ölçüsü, kasa konumu, kopuk-bant-mastik katmanlari ve denizlik akisi ile birlikte okunmasi gereken bir kabuk muhendisligi paketidir.",
    ],
    theory: [
      "Doğrama performansi yalnız profil sinifi veya cam paketiyle belirlenmez. Kasanin duvar icindeki konumu, montaj boslugunun tutarliligi ve çevre sızdırmazlık katmanlari urun performansinin sahadaki gercek karsiligini olusturur.",
      "Pencerelerde isi ve hava davranisi, kapı sistemlerinde ise fonksiyon ve güvenlik daha belirgin hale gelir. Ancak her iki durumda da duvar ile kasa arasindaki birleşim cizgisi kritik bolgedir.",
      "Doğrama kasasi kaba yapının toleranslarini absorbe etmek zorundadir. Bu sebeple yamuk acikliklar ve kontrolsuz kopuk dolumu montaj sonrasinda kanat ayari ve sızdırmazlık sorunlarina donusebilir.",
      "TS 825 ve enerji performansi yaklasimi, doğrama kararlarini duvar kesitinden ayri dusunmemeyi gerektirir.",
    ],
    ruleTable: [
      {
        parameter: "Kaba boşluk ve tolerans",
        limitOrRequirement: "Kasa cevresinde kontrollu montaj boşluğu birakilmali ve yamuk acikliklar önceden duzeltilmeli",
        reference: "Doğrama montaj detayi",
        note: "Boşluk kontrolü saglanmayan montaj sonradan ayarsizlige doner.",
      },
      {
        parameter: "Ankraj ve tasiyicilik",
        limitOrRequirement: "Kasa noktalarinda yeterli mekanik sabitleme ve ayar düzeni kurulmalı",
        reference: "Saha uygulama disiplini",
        note: "Yalnız kopuk ile tasiyicilik beklenmemelidir.",
      },
      {
        parameter: "Sızdırmazlık ve isi koprusu kontrolü",
        limitOrRequirement: "Bant, kopuk, mastik ve denizlik cozumleri katmanli olarak tamamlanmali",
        reference: "TS 825 + BEP Yönetmeliği",
        note: "Tek katmanli dusunulen birleşimler kısa surede zayiflar.",
      },
      {
        parameter: "Fonksiyon testi",
        limitOrRequirement: "Acilma-kapanma, kilit ve su davranisi teslim öncesi test edilmeli",
        reference: "Teslim kalite plani",
        note: "Yalnız görsel kabul yeterli degildir.",
      },
    ],
    designOrApplicationSteps: [
      "Doğrama tipini mahal kullanimina ve kabuk performansi beklentisine göre sec.",
      "Kaba bosluklari montajdan önce olc ve yamuk ya da eksik acikliklari önceden duzelt.",
      "Kasa konumunu duvar kesiti, yalitim kalinligi ve denizlik duzeniyle birlikte belirle.",
      "Ankraj, ayar takozu, kopuk, bant ve mastik katmanlarini bir sistem olarak uygula.",
      "Teslim öncesi tüm kanatlarda acilma-kapanma, kilit ve sızdırmazlık kontrolünü kayitli yap.",
    ],
    criticalChecks: [
      "Kaba boşluk olculeri kasa için yeterli ve tutarli tolerans birakiyor mu?",
      "Kasa ankraj noktalarinda gevseklik veya asiri kopuk dolumu var mi?",
      "Denizlik ve damlalik suyu cepheden uzaklastiriyor mu?",
      "Kasa cevresinde sızdırmazlık katmanlari kesintisiz mi?",
      "Kanatlar surtme veya kilit zorlamasi yapiyor mu?",
    ],
    numericalExample: {
      title: "150 x 150 cm pencere için kaba boşluk yorumu",
      inputs: [
        { label: "Nominal pencere ölçüsü", value: "150 x 150 cm", note: "PVC pencere ornegi" },
        { label: "Olculen kaba boşluk", value: "153 x 152 cm", note: "Saha ölçüsü" },
        { label: "Diyagonal fark", value: "8 mm", note: "Aciklik yamuklugu" },
        { label: "Hedef", value: "Dengeli montaj boşluğu ve ayar", note: "Sızdırmazlık performansi için" },
      ],
      assumptions: [
        "Pencere kasasi cevresinde montaj ve sızdırmazlık boşluğu gereklidir.",
        "Aciklik sivadan önce duzeltilebilir durumdadir.",
        "Denizlik detayi montajla birlikte cozulecektir.",
      ],
      steps: [
        {
          title: "Boşluk uygunlugunu oku",
          result: "Kaba boşluk nominal olcuden buyuktur ve montaj payi birakmaktadir.",
          note: "Ancak payin dengeli dagilmasi için yamukluk da giderilmelidir.",
        },
        {
          title: "Diyagonal farki yorumla",
          formula: "8 mm diyagonal fark",
          result: "Aciklik tamamen doğru kabul edilmemelidir; kasa ayari zorlanabilir.",
          note: "Yamuk aciklik, kanat ayarini ve contanin davranisini olumsuz etkiler.",
        },
        {
          title: "Montaj stratejisini kur",
          result: "Aciklik duzeltilip kasa merkezli yerlestirilmeli, sızdırmazlık katmanlari dengeli uygulanmalidir.",
          note: "Aksi halde bir kenarda asiri kopuk, diger kenarda zayif birleşim olusur.",
        },
      ],
      checks: [
        "Boşluk buyuklugu kadar dengeli dagilimi de önemlidir.",
        "Diyagonal fark kabul edilmeden montajla kapatilmamalidir.",
        "Denizlik ve damlalik cozumleri su davranisinin ana parcasidir.",
        "Fonksiyon testi görsel kabulden önce gelmelidir.",
      ],
      engineeringComment: "Doğrama montajinda en pahali urun bile yamuk bosluga doğru davranis gostermez.",
    },
    tools: [
      { category: "Detay", name: "Kapı pencere montaj ve kabuk paftalari", purpose: "Kasa konumu ve sızdırmazlık kararlarini duvar bitisiyle birlikte okumak." },
      { category: "Ölçüm", name: "Lazer metre, şakul ve diyagonal kontrol seti", purpose: "Kaba boşluk ve doğrama dogrulugunu sayisal olarak dogrulamak." },
      { category: "Kontrol", name: "Acilma-kapanma ve sızdırmazlık test listesi", purpose: "Montaji fonksiyon testi ile teslim almak." },
      { category: "Kayıt", name: "Cam doğrama etiket ve bakım foyi", purpose: "Cam paketi ve servis bilgisini isletmeye devretmek." },
    ],
    equipmentAndMaterials: [
      { group: "Doğrama", name: "PVC veya aluminyum kasa-kanat sistemleri", purpose: "Isi, hava, su ve gunluk kullanım beklentisini birlikte karsilamak.", phase: "Montaj" },
      { group: "Bağlantı", name: "Ankraj, ayar takozu ve montaj yardimcilari", purpose: "Kasayi duvar icinde doğru aks ve duzlemde sabitlemek.", phase: "Kasa yerlestirme" },
      { group: "Sızdırmazlık", name: "Bant, kopuk, mastik ve denizlik aksesuarlari", purpose: "Kasa cevresinde su hava sizdirmazligini saglamak.", phase: "Birleşim çözümü" },
      { group: "Kontrol", name: "Ayar ekipmani ve fonksiyon test malzemeleri", purpose: "Kanat davranisini ve kilit ayarini teslim öncesi dogrulamak.", phase: "Son ayar" },
    ],
    mistakes: [
      { wrong: "Kaba boşluğu olcmeden uretime veya montaja gitmek.", correct: "Acikliklari montaj öncesi sahada netlestirmek." },
      { wrong: "Kasayi yalnız kopuk ile tutturmaya çalışmak.", correct: "Mekanik ankraj ve ayar düzeni kurmak." },
      { wrong: "Denizlik ve damlalik detayini ikincil görmek.", correct: "Su yonetimini doğrama paketinin ana parçası saymak." },
      { wrong: "Sizdirmazligi tek kat mastikle cozmek.", correct: "Bant, kopuk ve mastik katmanlarini birlikte uygulamak." },
      { wrong: "Kanat ayarini teslim sonrasina birakmak.", correct: "Fonksiyon testini montaj kabulunun parçası yapmak." },
    ],
    designVsField: [
      "Projede kapı ve pencere bir sembol gibi görünür; sahada ise kasanin duvarla kurdugu birleşim gercek performansi belirler.",
      "Iyi doğrama montaji sadece güzel görünmez; ruzgarda gürültü yapmaz, yagmurda su almaz ve kisinda kullaniciyi rahatsiz etmez.",
    ],
    conclusion: [
      "Kapı ve pencere sistemleri doğru boşluk, doğru ankraj ve doğru sızdırmazlık katmanlariyla birlestiginde kabuk performansini ciddi sekilde yukseltir.",
      "Eksik detayla uygulandiginda ise en sık tekrarlanan sikayet kalemlerinden birine donusur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.ts825, SOURCE_LEDGER.enerjiPerformansi],
    keywords: ["kapı pencere", "doğrama", "sızdırmazlık", "denizlik", "TS 825"],
  },
];
