import { BRANCH_SOURCE_LEDGER, SOURCE_LEDGER } from "../source-ledger";
import type { BinaGuidePageSpec } from "../types";

const INCE_TOPIC_OVERRIDE_SOURCES = [...BRANCH_SOURCE_LEDGER["ince-isler"]];

export const inceIslerTopicOverrides: BinaGuidePageSpec[] = [
  {
    slugPath: "ince-isler/siva",
    kind: "topic",
    quote: "Siva, duvari kapatan ara katman degil; butun ince isin görünür kalitesini tasiyan ana referans duzlemdir.",
    tip: "Siva isini yalnız metraj ve iscilik hizi olarak gormek, boya ve kaplama altinda kalici dalga, catlak ve tekrar iş maliyeti uretir.",
    intro: [
      "Siva isleri, ince imalatlarin en sessiz ama en belirleyici kalemlerinden biridir. Boya, fayans veya duvar kagidi ne kadar iyi secilirse secilsin, altindaki siva duzlemi zayifsa kullanıcı kalitesi hemen düşük algilanir.",
      "Sahada en sık yapilan hata, sivayi dekoratif sonuclardan bagimsiz bir on hazirlik adimi sanmaktir. Oysa iç ve dış siva; aderans, catlak kontrolu, su davranisi, köşe dogrulugu ve boya alti kabulun birlikte yonetildigi teknik bir tabakadir.",
      "Bir insaat muhendisi için siva yalnız usta kalitesi meselesi degildir. İş programi, alt yüzey hazirligi, file detaylari ve sonraki ekiplerin takvimi bu kalemin gercek performansini belirler.",
    ],
    theory: [
      "Siva sistemleri alt yuzeyle birlikte calisir. Tugla, gazbeton, briket veya betonarme yuzeylerin emicilikleri ve hareketleri farkli oldugu için aynı harc davranisini beklemek yanlistir.",
      "Iyi bir siva yalnız duz görünmez; aynı zamanda kolon-duvar birlesimi, pencere koseleri ve tesisat onarim hatlarindaki gerilme farklarini da yonetir.",
      "Dış cephede su ve gunes etkisi, iç mekanda ise kuruma hizi ve son kat uyumu one cikar. Çok hızlı su kaybeden veya kur almayan siva yuzeyi tozuma ve büzülme riski tasir.",
      "Bu nedenle siva, harc surme operasyonundan çok yüzey muhendisligi olarak ele alinmalidir.",
    ],
    ruleTable: [
      {
        parameter: "Yüzey hazirligi",
        limitOrRequirement: "Alt yüzey toz, gevsek parca ve aderansi zayif tabakalardan arindirilmali",
        reference: "TS EN 13914 uygulama prensipleri",
        note: "Kirli veya parlak yuzeye atilan siva en basta zayif bag ile baslar.",
      },
      {
        parameter: "Katman kalinligi",
        limitOrRequirement: "Asiri kalin tek kat yerine kontrollu katman ve mastar duzeni kullanilmali",
        reference: "TS EN 13914 + saha kalite plani",
        note: "Tek hamlede kalinlik buyutmek ayrilma ve catlak riskini artirir.",
      },
      {
        parameter: "Kritik birlesimler",
        limitOrRequirement: "Kolon-duvar ve aciklik kenarlarinda file veya uygun destek detayi uygulanmali",
        reference: "Saha catlak kontrol disiplini",
        note: "Catlaklar en once malzeme degisim sinirlarinda gorulur.",
      },
      {
        parameter: "Kuruma ve koruma",
        limitOrRequirement: "Yeni siva ani gunes, rüzgar ve yagmur etkisinden korunmali",
        reference: "Şantiye uygulama disiplini",
        note: "Kur almayan yüzey son katta renk ve tozuma problemi uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Alt yüzey tipini belirle ve betonarme, tugla veya gazbeton için ayri hazirlik stratejisi kur.",
      "Aderans koprusu veya astar ihtiyacini ilk panelde doğrula.",
      "Mastar hatlarini, köşe profillerini ve kalinlik referanslarini uygulama öncesi sabitle.",
      "Kritik birlesimlerde file donusu ve chase tamirlerini ana siva ile birlikte coz.",
      "Boya veya kaplama ekibine gecmeden once yan isikta duzlem, catlak ve yama kontrolu yap.",
    ],
    criticalChecks: [
      "Alt yüzey emiciligi ve aderansi sahada kontrol edildi mi?",
      "Kolon-duvar ve pencere koselerinde file veya uygun detay var mi?",
      "Mastar duzlemi boyunca dalga ve ani sapma olusuyor mu?",
      "Asiri kalin tek kat uygulama yapilan bolgeler var mi?",
      "Kuruma tamamlanmadan sonraki ekipler alana giriyor mu?",
    ],
    numericalExample: {
      title: "İç duvar sivasinda duzlem ve kalinlik karari",
      inputs: [
        { label: "Duvar uzunlugu", value: "4.80 m", note: "Salon duvari" },
        { label: "Olculen yüzey sapmasi", value: "12 mm", note: "En yuksek ve en düşük nokta arasi" },
        { label: "Planlanan ortalama siva kalinligi", value: "15 mm", note: "İç mekan ornek deger" },
        { label: "Hedef", value: "Boya alti duzlem", note: "Son katta dalga olusturmamak" },
      ],
      assumptions: [
        "Alt yüzey taşıyıcı olarak saglam ve temizdir.",
        "Elektrik chase tamirleri uygulama öncesi tamamlanmistir.",
        "Son kat boya planlandigi için dalga toleransi dusuktur.",
      ],
      steps: [
        {
          title: "Sapmayi yorumla",
          formula: "12 mm < 15 mm",
          result: "Olculen bozukluk planlanan katman icinde yonetilebilir görünür.",
          note: "Yine de lokal cepler tek hamlede doldurulmamalidir.",
        },
        {
          title: "Duzlem stratejisini kur",
          result: "Mastar referanslari ile once ana duzlem kurulup ara bosluklar kontrollu doldurulmalidir.",
          note: "Serbest el uygulama boya altinda gozle gorulur dalga uretir.",
        },
        {
          title: "Catlak riskini ekle",
          result: "Kolon-dolgu duvar gecislerinde file detayina ihtiyaç vardir.",
          note: "Duzlem saglansa bile malzeme degisim cizgileri file olmadan risklidir.",
        },
      ],
      checks: [
        "Mastar kontrolu siva sirasinda yapilmali, boya ekibine birakilmamalidir.",
        "Asiri kalin lokal cep noktalarinda katmanli yaklasim dusunulmelidir.",
        "Kritik birlesimlerde catlak onleyici detay unutulmamalidir.",
        "Kuruma suresi takvim baskisiyla kisaltilmamalidir.",
      ],
      engineeringComment: "Siva kalitesini boya geldikten sonra degil, mastar duvardayken yakalamak gerekir.",
    },
    tools: [
      { category: "Detay", name: "Cephe ve iç mekan siva detay paftalari", purpose: "Katman dizisini ve kritik koseleri uygulama öncesi netlestirmek." },
      { category: "Ölçüm", name: "Mastar, lazer nivo ve nem olcer", purpose: "Yüzey duzlugu ve kuruma seviyesini sayisal olarak kontrol etmek." },
      { category: "Kontrol", name: "Alan bazli kalite takip cizelgesi", purpose: "Catlak, yama ve boya alti kabul notlarini mahal bazinda izlemek." },
      { category: "Saha", name: "Deneme paneli ve fotograf kaydi", purpose: "Secilen sistemin iscilik kalitesini genellemeden once gormek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Yüzey temizlik ekipmanlari ve aderans astarlari", purpose: "Gevsek toz ve emicilik farklarini kontrol altina almak.", phase: "Hazirlik" },
      { group: "Uygulama", name: "Cimento esasli siva, alci siva ve karisim ekipmanlari", purpose: "İç ve dış mekan ihtiyacina göre doğru katman davranisi uretmek.", phase: "Siva uygulamasi" },
      { group: "Detay", name: "Köşe profili, file ve damlalik elemanlari", purpose: "Kritik koselerde catlak riskini azaltmak.", phase: "Detay cozumu" },
      { group: "Koruma", name: "Kur ve gunes koruma ekipmanlari", purpose: "Taze sivayi hızlı su kaybi ve hava etkisinden korumak.", phase: "Uygulama sonrasi" },
    ],
    mistakes: [
      { wrong: "Tozlu veya kalip yagli yuzeye doğrudan siva atmak.", correct: "Yuzeyi temizleyip aderans kosullarini once dogrulamak." },
      { wrong: "Butun duzeltmeyi tek kat kalin sivayla cozmeye çalışmak.", correct: "Referans mastar ve katmanli uygulama ile ilerlemek." },
      { wrong: "Kolon-duvar birlesimlerinde file kullanmamak.", correct: "Malzeme degisim hatlarini catlak riski olarak gormek." },
      { wrong: "Kur almadan sonraki ekiplere alani acmak.", correct: "Sivayi yeterli kuruma ve koruma suresiyle teslim etmek." },
      { wrong: "Boya alti kaliteyi son katta duzeltmeye çalışmak.", correct: "Siva asamasinda duzlem ve yama kalitesini bitirmek." },
    ],
    designVsField: [
      "Projede siva kalemi cogu zaman tek satir metraj gibi gorulur; sahada ise butun görünür kaliteyi tasiyan temel referans tabakadir.",
      "Iyi siva, boyanin daha iyi gorunmesini saglar; kötü siva ise en iyi boyayi bile kusur gosteren bir perdeye cevirir.",
    ],
    conclusion: [
      "Siva isleri doğru yüzey hazirligi, doğru detay ve doğru kuruma disipliniyle yurudugunde sonraki tüm kaplamalarin performansini yukseltir.",
      "Yanlış yurudugunde ise yeni malzemeden çok gorunmeyen tekrar isciligi ve teslim gecikmesi uretir.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn13914],
    keywords: ["siva", "alci siva", "dış siva", "yüzey duzlugu", "catlak kontrolu"],
  },
  {
    slugPath: "ince-isler/cati-kaplamasi",
    kind: "topic",
    quote: "Çatı kaplamasi, üst ortuyu kapatmak degil; suyu ve buhari kontrollu bir rota ile yapidan uzaklastirmaktir.",
    tip: "Catiyi yalnız üst malzeme secimi olarak okumak, asil riski mahya, dere, baca dibi ve kenar detaylarinda gormemek demektir.",
    intro: [
      "Çatı kaplamasi; membran, kiremit, metal panel veya benzeri sistemlerle yapinin en kritik dış etki sinirini olusturur. Kullanıcı için üst ortu gibi gorunse de saha gerceginde bu paket su, buhar, rüzgar ve gunes davranisinin birlikte yonetildigi çok katmanli bir sistemdir.",
      "Bu bolgede yapilan hata iç mekanlarda gec fark edilir ama etkisi genis olur. Tavan lekesi, izolasyon kaybi, kuf ve taşıyıcı elemanlarda bozulma gibi sorunlarin baslangici cogu zaman tek bir zayif detaya dayanir.",
      "Bir insaat muhendisi için çatı kaplamasi yalnız malzeme metraji degil, dugum detaylari, su akisi, rüzgar guvenligi ve bakım senaryosu ile birlikte ele alinmasi gereken bir saha paketidir.",
    ],
    theory: [
      "Çatı davranisinda ana mesele suyu yuzeyden hizla uzaklastirmak ve alt katmanlara kontrollu bir savunma cizgisi kurmaktir. Üst kaplama tek basina yeterli olmaz; altinda buhar kesici, su yalitimi ve yardimci katmanlar sistemin gercek guvencesini olusturur.",
      "Capraz rüzgar ve sıcaklık etkileri kaplama malzemesinde hareket uretir. Bu nedenle bindirme yonu, sabitleme ritmi ve kenar detaylari sonradan tamamlanan aksesuarlar degil, tasarimin parcasidir.",
      "Çatı hatalarinin buyuk bolumu genis alanda degil, mahya, dere, baca dibi ve parapet gibi dar dugumlerde ortaya cikar.",
      "TS 825 ve enerji performansi yaklasimi da çatı katmanlarinin kabuk davranisi için duvar kadar kritik oldugunu gosterir.",
    ],
    ruleTable: [
      {
        parameter: "Katman surekliligi",
        limitOrRequirement: "Buhar, isi ve su katmanlari sistem butunlugu icinde kesintisiz kurgulanmali",
        reference: "TS 825 + BEP Yonetmeligi",
        note: "Bir katmandaki kopukluk tüm catinin davranisini zayiflatir.",
      },
      {
        parameter: "Egim ve su yonu",
        limitOrRequirement: "Kaplama tipiyle uyumlu egim ve tahliye mantigi kurulmalı",
        reference: "Çatı sistem detayi",
        note: "Yetersiz egim, suyu detaylara geri iter.",
      },
      {
        parameter: "Kritik dugum detaylari",
        limitOrRequirement: "Mahya, dere, baca dibi ve parapet donusleri sistem aksesuarlariyla cozulmeli",
        reference: "Saha kalite plani",
        note: "En çok kacak bu dugumlerde ortaya cikar.",
      },
      {
        parameter: "Rüzgar ve sabitleme",
        limitOrRequirement: "Kenar ve yuksek emme riski olan bolgelerde sabitleme duzeni artirilmali",
        reference: "Uretici uygulama rehberi + saha kontrolu",
        note: "Kaplama kaybi lokal gibi baslar ama tüm catinin emniyetini bozar.",
      },
    ],
    designOrApplicationSteps: [
      "Çatı tipine göre su akisini, tahliye noktasini ve ana katman dizisini tasarim basinda sabitle.",
      "Alt taşıyıcı ve alt katman duzgunlugunu kaplama öncesi bagimsiz bir kabul kalemi olarak degerlendir.",
      "Mahya, dere, baca dibi ve parapet donuslerini saha cozumlerine birakmadan paftala.",
      "Kaplama montajinda bindirme yonu, sabitleme ritmi ve kenar guvenligini aks aks takip et.",
      "Yagis veya su deneyi ile kritik dugumleri teslim öncesi fiilen test et.",
    ],
    criticalChecks: [
      "Egim gercekten suyu tahliyeye yonlendiriyor mu?",
      "Alt katmanlarda yirtik, kopukluk veya ters bindirme var mi?",
      "Baca dibi, dere ve mahya detaylari uretici sistemine uygun mu?",
      "Kenar ve sakak bolgelerinde sabitleme sikligi yeterli mi?",
      "Su testi yalnız genis yuzeyde degil kritik dugumlerde de yapildi mi?",
    ],
    numericalExample: {
      title: "600 m2 çatı yuzeyinde su tahliye ritmi yorumu",
      inputs: [
        { label: "Çatı alani", value: "600 m2", note: "Endustriyel tek hacim ornegi" },
        { label: "Tahliye noktasi", value: "4 adet", note: "Es dagilmis varsayim" },
        { label: "Bir tahliyeye dusen alan", value: "150 m2", note: "Yaklasik dagilim" },
        { label: "Hedef", value: "Dugumlerde su bekletmemek", note: "Kacagi azaltmak" },
      ],
      assumptions: [
        "Tahliye noktalarinin konumu egim planiyla uyumludur.",
        "Oluk ve inisler montaj sonrasi serbesttir.",
        "Su testi kritik dugumleri de kapsayacaktir.",
      ],
      steps: [
        {
          title: "Alan dagilimini oku",
          formula: "600 / 4 = 150 m2",
          result: "Her tahliye noktasina dusen alan dengeli gorunmektedir.",
          note: "Ancak bu tek basina yeterli degildir; dere boyu ve lokal gol riski ayrıca kontrol edilmelidir.",
        },
        {
          title: "Dugum riskini ekle",
          result: "Baca dibi ve parapet donusleri, genis alandan daha yuksek kacak riski tasir.",
          note: "Bu nedenle kabul turunda yalnız yatay yuzeye bakmak eksik kalir.",
        },
        {
          title: "Bakım etkisini yorumla",
          result: "Oluk temizligi ve yaprak birikimi için erişim yoksa ilk kis mevsiminde sistem davranisi bozulabilir.",
          note: "Bakım plani çatı performansinin parcasidir.",
        },
      ],
      checks: [
        "Tahliye noktasi sayisi kadar konumu da sorgulanmalidir.",
        "Su testinde mahya, dere ve baca dibi ayrıca izlenmelidir.",
        "Bakım erisimi olmayan çatı uzun omurlu kabul edilmemelidir.",
        "Alt katman fotograflari teslim dosyasinda tutulmalidir.",
      ],
      engineeringComment: "Çatı kaplamasinda sorun genellikle ortada degil, detay cizgisinde baslar.",
    },
    tools: [
      { category: "Detay", name: "Çatı katman ve dugum paftalari", purpose: "Mahya, dere ve baca dibi detaylarini uygulama öncesi netlestirmek." },
      { category: "Ölçüm", name: "Egim, aks ve bindirme kontrol seti", purpose: "Su akisi ve kaplama ritmini uygulama boyunca izlemek." },
      { category: "Kontrol", name: "Su testi ve rüzgar checklisti", purpose: "Kritik dugumlerde performans dogrulamasi yapmak." },
      { category: "Kayıt", name: "Kapatma öncesi foto arşivi", purpose: "Sonradan gorulmeyecek alt katman detaylarini teslim dosyasina tasimak." },
    ],
    equipmentAndMaterials: [
      { group: "Alt katman", name: "Buhar kesici, su yalitimi ortusu ve taşıyıcı alt katmanlar", purpose: "Kaplama öncesi su ve buhar davranisini kontrol etmek.", phase: "Alt hazirlik" },
      { group: "Kaplama", name: "Membran, kiremit veya metal panel sistemi", purpose: "Ana su atma ve dış etki dayanimi saglamak.", phase: "Kaplama montaji" },
      { group: "Birlesim", name: "Mahya, dere, kenar ve baca dibi aksesuarlari", purpose: "Kritik çatı dugumlerini sistematik sekilde kapatmak.", phase: "Detay cozumu" },
      { group: "Sabitleme", name: "Vida, klips ve rüzgar güvenlik elemanlari", purpose: "Kaplamanin yerinde ve emniyetli kalmasini saglamak.", phase: "Sabitleme" },
    ],
    mistakes: [
      { wrong: "Catinin kalitesini yalnız üst malzemeyle degerlendirmek.", correct: "Alt katman ve dugum detaylarini da ana kalite kalemi saymak." },
      { wrong: "Egim planini sahaya birakmak.", correct: "Su yonunu uygulama öncesi netlestirip sahada olcmek." },
      { wrong: "Baca dibi ve dere cozumlerini usta inisiyatifine birakmak.", correct: "Standart sistem detaylariyla ilerlemek." },
      { wrong: "Su testini atlamak.", correct: "Kritik dugumlerde kontrollu test yapmak." },
      { wrong: "Bakım yolunu ve oluk temizligini dusunmemek.", correct: "Isletme senaryosunu teslim dosyasina dahil etmek." },
    ],
    designVsField: [
      "Projede çatı bir kesit ve üst gorunusle anlatilir; sahada ise her dugum ayri muhendislik karari ister.",
      "Iyi çatı kendini gunlukte belli etmez; kötü çatı ise ilk siddetli yagista tüm yapinin problemi haline gelir.",
    ],
    conclusion: [
      "Çatı kaplamasi doğru katman kurgusu, doğru tahliye ve doğru dugum detaylari ile calistiginda yapinin en guvenilir koruyucu katmani olur.",
      "Eksik detayla yurutuldugunde ise tamir maliyeti yuksek, ariza takibi zor ve itibar kaybi buyuk bir saha sorununa donusur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.ts825, SOURCE_LEDGER.enerjiPerformansi],
    keywords: ["çatı kaplamasi", "mahya", "dere", "su tahliyesi", "TS 825"],
  },
  {
    slugPath: "ince-isler/alcipan",
    kind: "topic",
    quote: "Alcipan sistemleri hafif görünür; ama servis koordinasyonu ve tolerans yonetimi acisindan en yoğun ince iş paketlerinden biridir.",
    tip: "Kuru yapida en buyuk hata, levhayi son gorunen yüzey sanip karkas ve servis planini ikinci plana atmaktir.",
    intro: [
      "Alcipan ve kuru yapı sistemleri; bolme duvar, asma tavan, shaft kapamasi ve servis gizleme gibi bircok ince iş paketinin merkezinde yer alir. Hızlı montaj avantajlari nedeniyle sık tercih edilir, ancak bu hiz doğru koordinasyon olmadan kalici kaliteye donusmez.",
      "Sahada alcipan islerinde gorulen sorunlarin buyuk kismi levhadan degil, taşıyıcı karkastan ve kapanmadan once cozulmemis servislerden kaynaklanir. Sonradan acilan delikler, unutulan bakım kapaklari ve zayif takviyeler sistemin omrunu kisaltir.",
      "Bir insaat muhendisi için bu baslik, yalnız levha montaji degil; aks, kot, ses, yangin ve bakım erisimi gibi konularin tek paket halinde yonetilmesi anlamina gelir.",
    ],
    theory: [
      "Kuru yapı sistemlerinde performans, levha kalinligi kadar karkas davranisina baglidir. Profil araligi, aski noktasi, vidalama ritmi ve takviye elemanlari doğru kurgulanmadiginda yüzey catlagi ve sehim kısa surede ortaya cikar.",
      "Asma tavanlarda menfez, armatür, sprinkler ve bakım kapagi gibi çok sayida servis elemani aynı duzlemde bir araya gelir. Bu yogunluk levha kapatma oncesinde cozulmezse estetik kalite kadar isletme kalitesi de bozulur.",
      "Bolme duvarlarda ise akustik, yangin ve kapı boslugu performansi one cikar. Kapı kasasi, elektrik buatlari ve tesisat gecisleri bir arada dusunulmeden doğru duvar davranisi beklenemez.",
      "Bu nedenle alcipan, hafif bir sistem olmasina ragmen agir koordinasyon ister.",
    ],
    ruleTable: [
      {
        parameter: "Karkas duzeni",
        limitOrRequirement: "Profil, aski ve taşıyıcı ritim sistem detayina uygun kurulmalı",
        reference: "Uretici sistemi + saha kalite plani",
        note: "Levha kalitesi zayif karkasi telafi etmez.",
      },
      {
        parameter: "Servis koordinasyonu",
        limitOrRequirement: "Bakım kapagi, menfez, armatür ve gecisler kapatma öncesi sabitlenmeli",
        reference: "MEP overlay ve saha koordinasyonu",
        note: "Sonradan kesilen levha tekrar iş ve catlak riski uretir.",
      },
      {
        parameter: "Mahal uyumu",
        limitOrRequirement: "Nemli ve yangin riski olan hacimlerde uygun levha tipi secilmeli",
        reference: "Yangin Yonetmeligi + mahal kullanım karari",
        note: "Her yerde aynı levha secimi teknik olarak doğru degildir.",
      },
      {
        parameter: "Derz kalitesi",
        limitOrRequirement: "Derz bandi, macun ve yüzey hazirligi katmanli sekilde uygulanmali",
        reference: "Uretici uygulama rehberi",
        note: "Tek katta hızlı bitirilen derz daha sonra iz verir.",
      },
    ],
    designOrApplicationSteps: [
      "Bolme duvar ve asma tavan akslarini mimari ile MEP cakismazligi acisindan overlay uzerinden netlestir.",
      "Profil ritmini, aciklik ve yuk durumuna göre sadece usta aliskanligiyla degil detay paftasiyla kur.",
      "Bakım kapagi, ekipman takviyesi ve kapı bosluklarini kapatma öncesi isaretle ve fotola.",
      "Levha montajini sasirtmali derz mantigi ve doğru vida araligi ile tamamla.",
      "Son kat boya öncesi yan isik ve fonksiyon kontrolunu birlestir.",
    ],
    criticalChecks: [
      "Profil ve aski araligi detayla uyumlu mu?",
      "Bakım kapagi gereken tüm noktalarda erişim var mi?",
      "Kapı ustu ve ekipman cevresinde gerekli takviyeler yerlestirildi mi?",
      "Levha birlesimleri aynı hatta devam eden zayif cizgi olusturuyor mu?",
      "Nemli mahallerde uygun levha tipi secildi mi?",
    ],
    numericalExample: {
      title: "2.40 m genis koridorda asma tavan servis yogunlugu yorumu",
      inputs: [
        { label: "Koridor genisligi", value: "2.40 m", note: "Uzun lineer mahal" },
        { label: "Tavan dususu", value: "35 cm", note: "Mekanik ve elektrik servisleri için" },
        { label: "Servis elemani", value: "menfez + lineer aydinlatma + sprinkler", note: "Yoğun tavan kurulumu" },
        { label: "Hedef", value: "Tek kapatma ile temiz bitis", note: "Tekrar isi azaltmak" },
      ],
      assumptions: [
        "MEP cikislari kapatma öncesi dondurulmustur.",
        "Bakım gerektiren gizli elemanlar belirlenmistir.",
        "Tavan aksi koridor merkezine göre kurulmaktadir.",
      ],
      steps: [
        {
          title: "Servis yogunlugunu oku",
          result: "Dar koridorda tüm servislerin aynı eksene yaklasmasi görsel ve teknik catisma riski tasir.",
          note: "Bu nedenle lineer aydinlatma, menfez ve sprinkler ortak ritimde tasarlanmalidir.",
        },
        {
          title: "Bakım etkisini ekle",
          result: "Damper, buat veya vana varsa en az bir bakım kapagi önceden planlanmalidir.",
          note: "Bakım noktasi unutulursa tavan ilk arizada tekrar acilir.",
        },
        {
          title: "Karkas yukunu yorumla",
          result: "Armatür ve kapak etrafinda ek taşıyıcı ihtiyaci kontrol edilmelidir.",
          note: "Yalnız levhaya dayali cozum zamanla sehim uretir.",
        },
      ],
      checks: [
        "Servis elemanlari rasgele degil, modullu yerlesmelidir.",
        "Bakım gerektiren gizli elemanlar kapakla erişilebilir olmalidir.",
        "Ekipman cevresi ek taşıyıcı ile desteklenmelidir.",
        "Kapatma öncesi fotograf kaydi alinmalidir.",
      ],
      engineeringComment: "Kuru yapinin gercek kalitesi, levha kapandiktan sonra ne kadar az geri donus gerektirdigiyle olculur.",
    },
    tools: [
      { category: "Koordinasyon", name: "Tavan duvar overlay paftalari", purpose: "Mekanik, elektrik ve kuru yapı sistemlerini tek eksende cozumlemek." },
      { category: "Ölçüm", name: "Kot cizelgesi, lazer nivo ve diyagonal kontrolu", purpose: "Asma tavan ve bolme duvarlarda duzlem dogrulugu saglamak." },
      { category: "Kontrol", name: "Profil, vida ve derz takip foyu", purpose: "Montaj kalitesini olculebilir hale getirmek." },
      { category: "Kayıt", name: "Kapatma öncesi servis fotograf kaydi", purpose: "Bakım kapagi ve gecislerin sonradan da okunabilmesini saglamak." },
    ],
    equipmentAndMaterials: [
      { group: "Taşıyıcı", name: "Galvaniz profil, aski cubugu ve taşıyıcı kanal", purpose: "Kuru yapı karkasini rijit ve tekrar edilebilir sekilde kurmak.", phase: "Karkas montaji" },
      { group: "Kaplama", name: "Standart, neme dayanimli ve yangina dayanimli levhalar", purpose: "Mahal kullanimina göre yüzey ve yangin beklentisini karsilamak.", phase: "Levha montaji" },
      { group: "Tamamlama", name: "Derz bandi, derz dolgu ve köşe profilleri", purpose: "Birlesimlerin catlak ve darbe riskini azaltmak.", phase: "Yüzey hazirligi" },
      { group: "Destek", name: "Kapak ve ekipman takviye parcalari", purpose: "Noktasal yuk alan bolgelerde sehim riskini dusurmek.", phase: "Detay cozumu" },
    ],
    mistakes: [
      { wrong: "Profil araligini göz karari kurmak.", correct: "Sistem detayina ve acikliga göre kontrollu ritim belirlemek." },
      { wrong: "Servis gecislerini levha kapandiktan sonra acmak.", correct: "Tüm delik ve ekipman yerlerini once sabitlemek." },
      { wrong: "Bakım kapaklarini unutmak.", correct: "Mudahale gereken gizli noktalari uygulama basinda isaretlemek." },
      { wrong: "Noktasal yuk alan yerlerde takviye yapmamak.", correct: "Kapı, armatür ve ekipman cevresinde ek destek kullanmak." },
      { wrong: "Derzi tek kat macunla hızlı kapatmaya çalışmak.", correct: "Katmanli bant ve yüzey hazirligi uygulamak." },
    ],
    designVsField: [
      "Tasarimda kuru yapı bir duz cizgi gibi okunur; sahada ise her profil ve her servis cikisi o cizginin gercek davranisini belirler.",
      "Iyi alcipan sistemi sessizdir; bakım zamani geldiginde kolay acilir ve kullanım sirasinda catlamaz.",
    ],
    conclusion: [
      "Alcipan sistemleri doğru karkas, doğru servis koordinasyonu ve doğru derz disipliniyle temiz sonuclar uretir.",
      "Yanlış yonetildiginde ise en çok sokulup tekrar yapilan ince iş kalemlerinden biri olur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.yanginYonetmeligi],
    keywords: ["alcipan", "kuru yapı", "asma tavan", "bolme duvar", "servis koordinasyonu"],
  },
  {
    slugPath: "ince-isler/duvar-kaplamalari",
    kind: "topic",
    quote: "Duvar kaplamalari, malzeme seciminden once yüzey ve modul disiplininin görünür sonucudur.",
    tip: "Duvar kaplamasinda kusuru son katta aramak genelde yanlistir; asil sorun cogu kez alt yüzey, nem veya bitis planinin gec kurulmasidir.",
    intro: [
      "Duvar kaplamalari; boya, fayans, dekoratif panel veya duvar kagidi ile mekanin son görünür dilini kurar. Kullanıcı bu yuzeye bakarak kalite algisini olusturur; bu nedenle küçük hata bile tüm mahal hakkinda olumsuz izlenim yaratir.",
      "Ancak duvar kaplamalarinin basarisi, son kat malzemenin pahali olmasindan çok alt yuzeyin ne kadar kontrollu hazirlandigina baglidir. Dalga, emicilik farki, lokal nem ve yetersiz köşe cozumu en sık sikayet kaynagidir.",
      "Bir insaat muhendisi için duvar kaplamasi, dekoratif secim ile saha duzlem kalitesinin aynı masada cozuldugu bir kalite paketidir.",
    ],
    theory: [
      "Duvar yuzeylerinde görünür kusur en çok yan isikta ortaya cikar. Bu nedenle kaplama kontrolu sadece onden bakilan göz karariyla degil, yüzey duzlugu ve isik davranisi ile birlikte yapilmalidir.",
      "Islak hacimlerde fayans veya seramik altinda kalan sistemler de sonucun parçası olur. Su yalitimi, yapıştırıcı secimi, derz tipi ve köşe bitisi birlikte kurulmadan yalnız karo duzlugu uzerinden kalite okunamaz.",
      "Kuru hacimlerde boya ve duvar kagidi gibi sistemler emicilik farkina hassastir. Homojen olmayan macun veya gec kurumus tamir alanlari son katta ton ve doku farki uretir.",
      "Bu nedenle duvar kaplamalari, malzeme katalogundan secilen bir son kat degil; yüzey, modul ve birlesim disiplininin ortak ciktisidir.",
    ],
    ruleTable: [
      {
        parameter: "Yüzey hazirligi",
        limitOrRequirement: "Astar, macun, tesviye ve temizlik islemleri urun tipine uygun yapilmali",
        reference: "TS EN 13914 + urun teknik foyleri",
        note: "Aynı hazirlik tüm kaplamalar için gecerli kabul edilmemelidir.",
      },
      {
        parameter: "Islak hacim sistemi",
        limitOrRequirement: "Su yalitimi, yapıştırıcı ve kaplama sistemi birlikte secilmeli",
        reference: "TS EN 12004 + saha islak hacim disiplini",
        note: "Duvar karosu altindaki katmanlar da performansin parcasidir.",
      },
      {
        parameter: "Modul ve bitis duzeni",
        limitOrRequirement: "Köşe, niş, tesisat cikisi ve bitis cizgileri montaj öncesi planlanmali",
        reference: "Detay paftasi ve saha aplikasyonu",
        note: "Plansiz modul köşe ve armatür cevresinde kusur uretir.",
      },
      {
        parameter: "Görünür kalite",
        limitOrRequirement: "Yan isik ve farkli bakis acilarinda son kontrol yapilmali",
        reference: "Teslim kalite plani",
        note: "Sadece genel aydinlikta bakilan kontrol eksik kalir.",
      },
    ],
    designOrApplicationSteps: [
      "Mahal kullanimina göre boya, seramik veya duvar kagidi tipini teknik gerekliliklerle birlikte sec.",
      "Alt yuzeyin nem, duzgunluk ve emicilik durumunu urun seciminden bagimsiz olarak doğrula.",
      "Fayansli alanlarda niş, armatür ve köşe donuslerini modul paftasi ile önceden kur.",
      "Boya ve kagit alanlarinda macun, zimpara ve astar katlarini aceleye getirmeden tamamla.",
      "Teslim turunda yan isik ve kullanıcı göz seviyesi ile kontrol yap.",
    ],
    criticalChecks: [
      "Alt yuzeyde lokal nem veya gec kurumus tamir alani var mi?",
      "Köşe ve niş detaylari modul planina uyuyor mu?",
      "Islak hacimlerde su yalitimi ve yapıştırıcı sistemi doğru sirada mi?",
      "Boya altinda zimpara izi, dalga veya yama farki gorunuyor mu?",
      "Derz ve bitis cizgileri aynı hatta devam ediyor mu?",
    ],
    numericalExample: {
      title: "240 cm banyo duvarinda modul ve bitis yorumu",
      inputs: [
        { label: "Duvar genisligi", value: "240 cm", note: "Banyo ana duvari" },
        { label: "Karo olcusu", value: "60 x 120 cm", note: "Dikey yerlesim" },
        { label: "Derz araligi", value: "2 mm", note: "Ornek tasarim karari" },
        { label: "Hedef", value: "Simetrik gorunus", note: "Köşe parca riskini azaltmak" },
      ],
      assumptions: [
        "Kaplama merkez eksene göre planlanacaktir.",
        "Armatür cikislari modul paftasina islenecektir.",
        "Köşe donusleri profil veya uygun detay ile cozulmustur.",
      ],
      steps: [
        {
          title: "Modul uygunlugunu yorumla",
          result: "240 cm olcusu, 60 cm'lik ana modulle dengeli bir başlangıç verir.",
          note: "Yine de köşe bitisi paftada test edilmeden uygulamaya gecilmemelidir.",
        },
        {
          title: "Armatür etkisini ekle",
          result: "Musluk ve niş cikislari modul cizgisini bozmayacak sekilde yeniden kaydirilabilir.",
          note: "Küçük eksen kaymalari buyuk görünür kusurlari onler.",
        },
        {
          title: "Köşe parca riskini oku",
          result: "Dar bitis parçası kalacaksa merkezleme veya modul boyu revize edilmelidir.",
          note: "Montaj sirasinda verilen anlik kararlar genelde daha kötü sonuc uretir.",
        },
      ],
      checks: [
        "Modul plani, tesisat cikislariyla birlikte okunmalidir.",
        "Dar köşe parçası riski montaj baslamadan cozulmelidir.",
        "Yalnız karo duzlugu degil, bitis cizgisi de kabul kriteridir.",
        "Islak hacimde alt sistemler de teslim dosyasina girmelidir.",
      ],
      engineeringComment: "Duvar kaplamasinda iyi sonuc, ilk karo yapismadan once modul ve bitis karari verildiginde alinir.",
    },
    tools: [
      { category: "Detay", name: "Duvar modul, renk ve bitis paftalari", purpose: "Boya ve fayans sistemlerini aynı mekan akisinda planlamak." },
      { category: "Ölçüm", name: "Yan isik kontrolu, mastar ve nem olcer", purpose: "Görünür kusurlari uygulama bitmeden tespit etmek." },
      { category: "Kontrol", name: "Katman ve kuruma takip cizelgesi", purpose: "Astar, macun, yapıştırıcı ve son kat sirasini izlemek." },
      { category: "Kayıt", name: "Mahal bazli onay listesi", purpose: "Renk, doku ve bitis kararlarini teslim dosyasinda netlestirmek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Astar, macun, tesviye ve yüzey tamir urunleri", purpose: "Kaplama tasiyacak duvarda homojen emicilik ve duzgunluk elde etmek.", phase: "Hazirlik" },
      { group: "Kaplama", name: "İç cephe boya sistemleri, fayans ve duvar kagidi tipleri", purpose: "Mahal kullanimina göre temizlenebilirlik ve görünür kalite uretmek.", phase: "Kaplama" },
      { group: "Birlesim", name: "Köşe profili, derz elemani ve bitis aksesuarleri", purpose: "Köşe ve donuslerde görünür sureklilik saglamak.", phase: "Bitis" },
      { group: "Koruma", name: "Gecici yüzey koruma ekipmanlari", purpose: "Son kat tamamlandiktan sonra duvari darbe ve lekeye karsi korumak.", phase: "Teslim öncesi" },
    ],
    mistakes: [
      { wrong: "Butun duvar kaplamalarinda aynı yüzey hazirligini uygulamak.", correct: "Kaplama tipine göre farkli hazirlik sistemi kullanmak." },
      { wrong: "Fayans modulunu montaj sirasinda belirlemek.", correct: "Köşe, niş ve armatürlerle birlikte once paftalamak." },
      { wrong: "Su yalitimini kaplamadan bagimsiz gormek.", correct: "Islak hacimde sistemi butun olarak ele almak." },
      { wrong: "Boya kalitesini sadece genel isikta kontrol etmek.", correct: "Yan isik ve kullanıcı göz seviyesinde tekrar bakmak." },
      { wrong: "Bitis cizgilerini saha kararina birakmak.", correct: "Kapı, tavan ve supurgelikle birlikte önceden sabitlemek." },
    ],
    designVsField: [
      "Tasarimda duvar kaplamasi renk ve doku secimi gibi görünür; sahada ise duzlem, nem, modul ve birlesim kalitesi bu secimin gercek sonucunu belirler.",
      "Pahali malzeme kusuru saklamaz; cogu zaman onu daha görünür hale getirir.",
    ],
    conclusion: [
      "Duvar kaplamalari doğru alt yüzey, doğru modul ve doğru bitis kararlariyla birlestiginde mekani temiz ve uzun omurlu gosterir.",
      "Eksik hazirlikla uygulandiginda ise kusur en görünür yerde ortaya cikar ve duzeltme maliyeti artar.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn13914, SOURCE_LEDGER.tsEn12004],
    keywords: ["duvar kaplamalari", "boya", "fayans", "duvar kagidi", "modul plani"],
  },
  {
    slugPath: "ince-isler/zemin-kaplamalari",
    kind: "topic",
    quote: "Zemin kaplamalarinda kalite, urunden once alt zeminin o urunu tasiyacak kadar hazir olup olmadigiyla baslar.",
    tip: "Seramik, parke veya epoksi secimi ne kadar iyi olursa olsun; nemli, dalgali ve plansiz alt zemin üzerinde uzun omurlu sonuc beklenmemelidir.",
    intro: [
      "Zemin kaplamalari; konut, ofis, islak hacim ve ticari alanlarda asinma, temizlik, hijyen ve estetik beklentilerini aynı anda karsilar. Bu nedenle zemin secimi yalnız zevk konusu degil, kullanım senaryosu ve saha performansi kararidir.",
      "Sahada en sık gorulen problem, urun kararinin çok erken; alt zemin kabulunun ise çok gec yapilmasidir. Oysa kaplamanin uzun omru, sap nemi, duzlemsellik ve esik detaylariyla doğrudan baglantilidir.",
      "Bir insaat muhendisi için zemin kaplamasi, malzeme ve iscilik birlikteliginden daha fazlasidir. Kaplama takvimi, diger ekiplerin trafigi ve mahal gecisleri de aynı paketin parçası olarak yonetilmelidir.",
    ],
    theory: [
      "Zemin sistemleri yuk dagitimina ve alt yüzey davranisina hassastir. Parke hareket eden bir sistem gibi davranirken, seramik ve tas daha rijit bir tabaka ister; epoksi ise alt yüzey temizligi ve aderans kalitesine çok daha fazla baglidir.",
      "Bu nedenle aynı binada kullanilan farkli zemin kaplamalari tek bir teknik kurala baglanamaz. Islak hacimde kaymazlik ve su davranisi, ofiste konfor ve akustik, ticari alanda ise asinma direnci one cikar.",
      "Alt zemin bozukluklari ilk anda gorunmeyebilir. Ancak kullanimla birlikte gicirdama, köşe kalkmasi, lokal kirilma ve derz acilmasi gibi sikayetler cogu zaman esas malzemeden degil, hazirlik eksiginden dogar.",
      "Bu nedenle zemin kaplamasi, son gorunen katman degil; altinda yer alan kabul, tesviye, nem ve koruma disiplinlerinin bir sonucudur.",
    ],
    ruleTable: [
      {
        parameter: "Alt zemin duzlugu",
        limitOrRequirement: "Kaplama tipine uygun mastar ve kot surekliligi saglanmali",
        reference: "Saha kalite plani",
        note: "Dalgali sap, en pahali kaplamada bile kusuru gizlemez.",
      },
      {
        parameter: "Nem durumu",
        limitOrRequirement: "Parke ve hassas sistemlerde kaplama öncesi nem olcumu kayıt altina alinmali",
        reference: "TS EN 13329 + urun teknik foyleri",
        note: "Ozellikle ahşap ve laminat esasli sistemlerde bu kontrol kritik onemdedir.",
      },
      {
        parameter: "Yapıştırıcı ve birlesim sistemi",
        limitOrRequirement: "Kaplama ile yapıştırıcı, derz ve altlik sistemi birlikte secilmeli",
        reference: "TS EN 12004 + saha uygulama disiplini",
        note: "Uyumsuz sistem secimi gec ariza uretir.",
      },
      {
        parameter: "Teslim ve koruma",
        limitOrRequirement: "Tamamlanan zemin diger ekiplerin trafigine kontrollu acilmali",
        reference: "Teslim plani",
        note: "Erken kullanima acilan zeminlerde ilk kusur genelde lojistikten gelir.",
      },
    ],
    designOrApplicationSteps: [
      "Mahal kullanimina göre kaplama tipini asinma, su ve bakım ihtiyaci ile birlikte sec.",
      "Alt zemini kot, duzluk ve nem acisindan bagimsiz bir kabul adimi olarak test et.",
      "Esik, süpürgelik ve farkli urun gecislerini montaj öncesi paftala.",
      "Astar, yapıştırıcı, altlik veya derz sistemini secilen kaplamayla uyumlu kur.",
      "Montaj sonrasi alan korumasini ve trafik acilisini iş programina ayri bir kalem olarak yaz.",
    ],
    criticalChecks: [
      "Alt zemin 2 m mastarda kabul edilebilir duzlemde mi?",
      "Nem olcumu gereken mahallerde veri kayıt altina alindi mi?",
      "Esik ve geçiş detaylari kaplama montajindan once cozuldu mu?",
      "Aynı mahalde farkli zeminlerin bulustugu hatlar temiz okunuyor mu?",
      "Yeni kaplanan alan erken yuk ve darbe alip almiyor mu?",
    ],
    numericalExample: {
      title: "28 m2 odada parke öncesi nem yorumu",
      inputs: [
        { label: "Mahal alani", value: "28 m2", note: "Yatak odasi" },
        { label: "Olculen CM nemi", value: "%2.4", note: "Uc farkli noktada benzer sonuc" },
        { label: "Ornek hedef esik", value: "< %2.0", note: "Hassas parke sistemi varsayimi" },
        { label: "Mastar sapmasi", value: "2 mm / 2 m", note: "Duzlem uygun" },
      ],
      assumptions: [
        "Secilen kaplama neme hassastir.",
        "Ölçüm aynı cihaz ve aynı gunde alinmistir.",
        "Mahal havalandirma ile kurutulabilir durumdadir.",
      ],
      steps: [
        {
          title: "Nem verisini yorumla",
          formula: "2.4 > 2.0",
          result: "Duzlem uygun olsa da montaj için erken davranilmaktadir.",
          note: "Alt zeminin yalnız duz olmasi yeterli degildir.",
        },
        {
          title: "Takvim etkisini ekle",
          result: "Kaplama takvimi ertelenmeli ve ölçüm tekrar edilmelidir.",
          note: "Kısa takvim kazanci uzun sureli kabarma riskine donusebilir.",
        },
        {
          title: "Esik ve koruma planini bagla",
          result: "Montaj tarihi revize edilirse esik ve süpürgelik ekipleri de birlikte planlanmalidir.",
          note: "Zemin isi tek basina degil, bitis zinciriyle birlikte yonetilir.",
        },
      ],
      checks: [
        "Nem uygun degilse urunu degistirmek degil zemini olgunlastirmak gerekir.",
        "Duzlem ve nem birlikte okunmalidir.",
        "Kaplama takvimi lojistik baskidan çok veriye göre kurulmalidir.",
        "Koruma plani montaj karari kadar onemlidir.",
      ],
      engineeringComment: "Zemin kaplamasinda en kritik soru, urunun güzel olup olmadigi degil; zeminin o urunu tasiyacak kadar hazir olup olmadigidir.",
    },
    tools: [
      { category: "Ölçüm", name: "CM nem olcer, mastar ve lazer terazi", purpose: "Sap ve alt zemin kabulunu sayisal olarak dogrulamak." },
      { category: "Detay", name: "Esik, süpürgelik ve geçiş paftalari", purpose: "Farkli zemin kaplamalarinin birlestigi noktalari önceden cozumlemek." },
      { category: "Kontrol", name: "Deneme alan ve tuketim foyi", purpose: "Sistemi ana uygulama öncesi küçük alanda test etmek." },
      { category: "Kayıt", name: "Teslim ve koruma cizelgesi", purpose: "Tamamlanan zeminlerin trafik acilisini izlemek." },
    ],
    equipmentAndMaterials: [
      { group: "Hazirlik", name: "Tesviye sapi, astar ve yüzey duzeltme malzemeleri", purpose: "Kaplama altinda duz ve homojen bir zemin birakmak.", phase: "Hazirlik" },
      { group: "Kaplama", name: "Seramik, parke, dogal tas ve epoksi sistemleri", purpose: "Mahal kullanimina göre asinma ve estetik beklentiyi karsilamak.", phase: "Kaplama" },
      { group: "Birlesim", name: "Yapıştırıcı, derz dolgu, altlik ve esik profilleri", purpose: "Kaplama kenarlarinda teknik ve görsel sureklilik saglamak.", phase: "Montaj ve bitis" },
      { group: "Koruma", name: "Yüzey koruma ortusu ve gecici trafik onlemleri", purpose: "Yeni kaplamayi erken kullanimdan korumak.", phase: "Teslim öncesi" },
    ],
    mistakes: [
      { wrong: "Sadece urun secimine odaklanip alt zemin kabulunu ertelemek.", correct: "Kaplama öncesi nem ve duzlem kontrolunu erken yapmak." },
      { wrong: "Mastar bozuklugunu yapistiriciyla telafi etmeye çalışmak.", correct: "Alt zemini once tesviye etmek." },
      { wrong: "Esik ve geçiş kararlarini montaj sonuna birakmak.", correct: "Tüm gecisleri pafta ile once cozumlemek." },
      { wrong: "Deneme alan yapmadan buyuk metraja girmek.", correct: "Sistemi küçük alanda test edip sonra yaymak." },
      { wrong: "Yeni kaplamayi hemen yoğun trafige acmak.", correct: "Koruma ve trafik planini teslimin parçası yapmak." },
    ],
    designVsField: [
      "Tasarimda zemin kaplamasi katalog ve renk kartelasi ile secilir; sahada ise alt zemin verisi ve bitis detaylari sonucu belirler.",
      "Iyi zemin sessiz, dengeli ve temiz görünür; kötü zemin ise once ses ve kirikla kendini gosterir.",
    ],
    conclusion: [
      "Zemin kaplamalari doğru alt zemin, doğru sistem bilesenleri ve doğru teslim disipliniyle uzun omurlu hale gelir.",
      "Bu zincirin halkalarindan biri zayif oldugunda sorun malzemede degil, saha yonetiminde ortaya cikar.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn12004, SOURCE_LEDGER.tsEn13329],
    keywords: ["zemin kaplamalari", "parke", "seramik", "sap nemi", "alt zemin kontrolu"],
  },
  {
    slugPath: "ince-isler/kapi-pencere",
    kind: "topic",
    quote: "Kapı ve pencere sistemleri, boslugu kapatan eleman degil; kabuk performansini ve gunluk kullanım konforunu belirleyen birlesim paketidir.",
    tip: "Doğrama montajini yalnız kasa yerlestirme isi gibi gormek, sızdırmazlık, isi koprusu ve acilma-kapanma sorunlarini davet eder.",
    intro: [
      "Kapı ve pencere sistemleri, kullanıcı için geçiş ve gun isigi elemani gibi görünür; fakat teknik olarak isi kaybi, hava-su sizdirmazligi ve güvenlik performansinin ana dugumlerinden biridir.",
      "Sahada doğrama kaynakli sorunlarin buyuk bolumu urunun fabrikasyon kalitesinden degil, montaj bosluklarindan, denizlik cozumlerinden ve yetersiz ankrajdan dogar. Cogu sikayet ilk yagmurlarda veya ilk kis sezonunda ortaya cikar.",
      "Bir insaat muhendisi için kapi-pencere isi; kaba bosluk olcusu, kasa konumu, kopuk-bant-mastik katmanlari ve denizlik akisi ile birlikte okunmasi gereken bir kabuk muhendisligi paketidir.",
    ],
    theory: [
      "Doğrama performansi yalnız profil sinifi veya cam paketiyle belirlenmez. Kasanin duvar icindeki konumu, montaj boslugunun tutarliligi ve çevre sızdırmazlık katmanlari urun performansinin sahadaki gercek karsiligini olusturur.",
      "Pencerelerde isi ve hava davranisi, kapı sistemlerinde ise fonksiyon ve güvenlik daha belirgin hale gelir. Ancak her iki durumda da duvar ile kasa arasindaki birlesim cizgisi kritik bolgedir.",
      "Doğrama kasasi kaba yapinin toleranslarini absorbe etmek zorundadir. Bu sebeple yamuk acikliklar ve kontrolsuz kopuk dolumu montaj sonrasinda kanat ayari ve sızdırmazlık sorunlarina donusebilir.",
      "TS 825 ve enerji performansi yaklasimi, doğrama kararlarini duvar kesitinden ayri dusunmemeyi gerektirir.",
    ],
    ruleTable: [
      {
        parameter: "Kaba bosluk ve tolerans",
        limitOrRequirement: "Kasa cevresinde kontrollu montaj boslugu birakilmali ve yamuk acikliklar önceden duzeltilmeli",
        reference: "Doğrama montaj detayi",
        note: "Bosluk kontrolu saglanmayan montaj sonradan ayarsizlige doner.",
      },
      {
        parameter: "Ankraj ve tasiyicilik",
        limitOrRequirement: "Kasa noktalarinda yeterli mekanik sabitleme ve ayar duzeni kurulmalı",
        reference: "Saha uygulama disiplini",
        note: "Yalnız kopuk ile tasiyicilik beklenmemelidir.",
      },
      {
        parameter: "Sızdırmazlık ve isi koprusu kontrolu",
        limitOrRequirement: "Bant, kopuk, mastik ve denizlik cozumleri katmanli olarak tamamlanmali",
        reference: "TS 825 + BEP Yonetmeligi",
        note: "Tek katmanli dusunulen birlesimler kısa surede zayiflar.",
      },
      {
        parameter: "Fonksiyon testi",
        limitOrRequirement: "Acilma-kapanma, kilit ve su davranisi teslim öncesi test edilmeli",
        reference: "Teslim kalite plani",
        note: "Yalnız görsel kabul yeterli degildir.",
      },
    ],
    designOrApplicationSteps: [
      "Doğrama tipini mahal kullanimina ve kabuk performansi beklentisine göre sec.",
      "Kaba bosluklari montajdan once olc ve yamuk ya da eksik acikliklari önceden duzelt.",
      "Kasa konumunu duvar kesiti, yalitim kalinligi ve denizlik duzeniyle birlikte belirle.",
      "Ankraj, ayar takozu, kopuk, bant ve mastik katmanlarini bir sistem olarak uygula.",
      "Teslim öncesi tüm kanatlarda acilma-kapanma, kilit ve sızdırmazlık kontrolunu kayitli yap.",
    ],
    criticalChecks: [
      "Kaba bosluk olculeri kasa için yeterli ve tutarli tolerans birakiyor mu?",
      "Kasa ankraj noktalarinda gevseklik veya asiri kopuk dolumu var mi?",
      "Denizlik ve damlalik suyu cepheden uzaklastiriyor mu?",
      "Kasa cevresinde sızdırmazlık katmanlari kesintisiz mi?",
      "Kanatlar surtme veya kilit zorlamasi yapiyor mu?",
    ],
    numericalExample: {
      title: "150 x 150 cm pencere için kaba bosluk yorumu",
      inputs: [
        { label: "Nominal pencere olcusu", value: "150 x 150 cm", note: "PVC pencere ornegi" },
        { label: "Olculen kaba bosluk", value: "153 x 152 cm", note: "Saha olcusu" },
        { label: "Diyagonal fark", value: "8 mm", note: "Aciklik yamuklugu" },
        { label: "Hedef", value: "Dengeli montaj boslugu ve ayar", note: "Sızdırmazlık performansi için" },
      ],
      assumptions: [
        "Pencere kasasi cevresinde montaj ve sızdırmazlık boslugu gereklidir.",
        "Aciklik sivadan once duzeltilebilir durumdadir.",
        "Denizlik detayi montajla birlikte cozulecektir.",
      ],
      steps: [
        {
          title: "Bosluk uygunlugunu oku",
          result: "Kaba bosluk nominal olcuden buyuktur ve montaj payi birakmaktadir.",
          note: "Ancak payin dengeli dagilmasi için yamukluk da giderilmelidir.",
        },
        {
          title: "Diyagonal farki yorumla",
          formula: "8 mm diyagonal fark",
          result: "Aciklik tamamen doğru kabul edilmemelidir; kasa ayari zorlanabilir.",
          note: "Yamuk aciklik, kanat ayarini ve contanin davranisini olumsuz etkiler.",
        },
        {
          title: "Montaj stratejisini kur",
          result: "Aciklik duzeltilip kasa merkezli yerlestirilmeli, sızdırmazlık katmanlari dengeli uygulanmalidir.",
          note: "Aksi halde bir kenarda asiri kopuk, diger kenarda zayif birlesim olusur.",
        },
      ],
      checks: [
        "Bosluk buyuklugu kadar dengeli dagilimi de onemlidir.",
        "Diyagonal fark kabul edilmeden montajla kapatilmamalidir.",
        "Denizlik ve damlalik cozumleri su davranisinin ana parcasidir.",
        "Fonksiyon testi görsel kabulden once gelmelidir.",
      ],
      engineeringComment: "Doğrama montajinda en pahali urun bile yamuk bosluga doğru davranis gostermez.",
    },
    tools: [
      { category: "Detay", name: "Kapı pencere montaj ve kabuk paftalari", purpose: "Kasa konumu ve sızdırmazlık kararlarini duvar bitisiyle birlikte okumak." },
      { category: "Ölçüm", name: "Lazer metre, şakul ve diyagonal kontrol seti", purpose: "Kaba bosluk ve doğrama dogrulugunu sayisal olarak dogrulamak." },
      { category: "Kontrol", name: "Acilma-kapanma ve sızdırmazlık test listesi", purpose: "Montaji fonksiyon testi ile teslim almak." },
      { category: "Kayıt", name: "Cam doğrama etiket ve bakım foyi", purpose: "Cam paketi ve servis bilgisini isletmeye devretmek." },
    ],
    equipmentAndMaterials: [
      { group: "Doğrama", name: "PVC veya aluminyum kasa-kanat sistemleri", purpose: "Isi, hava, su ve gunluk kullanım beklentisini birlikte karsilamak.", phase: "Montaj" },
      { group: "Bağlantı", name: "Ankraj, ayar takozu ve montaj yardimcilari", purpose: "Kasayi duvar icinde doğru aks ve duzlemde sabitlemek.", phase: "Kasa yerlestirme" },
      { group: "Sızdırmazlık", name: "Bant, kopuk, mastik ve denizlik aksesuarlari", purpose: "Kasa cevresinde su hava sizdirmazligini saglamak.", phase: "Birlesim cozumu" },
      { group: "Kontrol", name: "Ayar ekipmani ve fonksiyon test malzemeleri", purpose: "Kanat davranisini ve kilit ayarini teslim öncesi dogrulamak.", phase: "Son ayar" },
    ],
    mistakes: [
      { wrong: "Kaba boslugu olcmeden uretime veya montaja gitmek.", correct: "Acikliklari montaj öncesi sahada netlestirmek." },
      { wrong: "Kasayi yalnız kopuk ile tutturmaya çalışmak.", correct: "Mekanik ankraj ve ayar duzeni kurmak." },
      { wrong: "Denizlik ve damlalik detayini ikincil gormek.", correct: "Su yonetimini doğrama paketinin ana parçası saymak." },
      { wrong: "Sizdirmazligi tek kat mastikle cozmek.", correct: "Bant, kopuk ve mastik katmanlarini birlikte uygulamak." },
      { wrong: "Kanat ayarini teslim sonrasina birakmak.", correct: "Fonksiyon testini montaj kabulunun parçası yapmak." },
    ],
    designVsField: [
      "Projede kapı ve pencere bir sembol gibi görünür; sahada ise kasanin duvarla kurdugu birlesim gercek performansi belirler.",
      "Iyi doğrama montaji sadece güzel görünmez; ruzgarda gürültü yapmaz, yagmurda su almaz ve kisinda kullaniciyi rahatsiz etmez.",
    ],
    conclusion: [
      "Kapı ve pencere sistemleri doğru bosluk, doğru ankraj ve doğru sızdırmazlık katmanlariyla birlestiginde kabuk performansini ciddi sekilde yukseltir.",
      "Eksik detayla uygulandiginda ise en sık tekrarlanan sikayet kalemlerinden birine donusur.",
    ],
    sources: [...INCE_TOPIC_OVERRIDE_SOURCES, SOURCE_LEDGER.ts825, SOURCE_LEDGER.enerjiPerformansi],
    keywords: ["kapı pencere", "doğrama", "sızdırmazlık", "denizlik", "TS 825"],
  },
];
