import { BRANCH_SOURCE_LEDGER, SOURCE_LEDGER } from "../source-ledger";
import type { BinaGuideEquipment, BinaGuidePageSpec, BinaGuideTool } from "../types";

const KABA_LEAF_OVERRIDE_SOURCES = [...BRANCH_SOURCE_LEDGER["kaba-insaat"]];

const KALIP_TOOLS: BinaGuideTool[] = [
  { category: "Cizim", name: "Kalıp paftaları, rezervasyon planlari ve shop drawing seti", purpose: "Aks, boşluk, embed ve kot kararlarini uygulama öncesi kesinlestirmek." },
  { category: "Ölçüm", name: "Total station, lazer nivo ve deformasyon takip listesi", purpose: "Kolon şakülü, kiriş alt kötü ve döşeme duzlemini beton öncesi veriye baglamak." },
  { category: "Planlama", name: "Kat cevrimi, sokum ve reshoring cizelgesi", purpose: "Kalıp kurulumunu yalnız dokum gunu değil, sonraki yük transferiyle birlikte yonetmek." },
  { category: "Kontrol", name: "On kabul ve beton öncesi checklist", purpose: "Sahadaki son kalite turunu kisilere değil standarda baglamak." },
];

const KALIP_EQUIPMENT: BinaGuideEquipment[] = [
  { group: "Taşıyıcı", name: "Panel kalıp, ahşap kusak, H20 kiriş ve tali dikme sistemi", purpose: "Taze beton yükünü, ekip yükünü ve geometriyi guvenle tasimak.", phase: "Kalıp kurulumu" },
  { group: "Bağlantı", name: "Tij, somun, kelebek, kusak ve kilit sistemleri", purpose: "Yanak acilmasi, panel ayrilmasi ve kesit kaymasi riskini azaltmak.", phase: "Montaj ve sıkma" },
  { group: "Ölçüm", name: "Lazer nivo, şakul, metre, isaretleme seti ve kot civileri", purpose: "Aks, şakul, kalinlik ve alt kötü sahada sürekli izlemek.", phase: "Ölçüm ve kabul" },
  { group: "Güvenlik", name: "Kenar koruma, çalışma platformu ve alt destek emniyet elemanlari", purpose: "Kalıp ve betonlama sırasında güvenli çalışma ortami saglamak.", phase: "Tüm süreç" },
];

const VIBRATION_TOOLS: BinaGuideTool[] = [
  { category: "Planlama", name: "Beton sevkiyat ve katman plani", purpose: "Vibrasyon ritmini pompa akisi ve eleman geometrisiyle uyumlu kurmak." },
  { category: "Ölçüm", name: "Katman ve nokta takip formu", purpose: "Yoğun düğümlerde nerede ve hangi sırada vibrasyon yapildigini izlemek." },
  { category: "Kontrol", name: "Kalıp acma sonrasi kusur geri bildirim listesi", purpose: "Peteklenme ve segregasyon gozlemlerini bir sonraki dokum planiyla baglamak." },
  { category: "Ekipman", name: "Igne vibrator cap seti ve yedek enerji kaynagi", purpose: "Kesit tipine göre doğru ucu secmek ve ariza riskini azaltmak." },
];

const VIBRATION_EQUIPMENT: BinaGuideEquipment[] = [
  { group: "Betonlama", name: "Igne vibrator, yedek igne ve yedek motor seti", purpose: "Taze betonun kesit icinde boşluksuz yerlesmesine yardim etmek.", phase: "Betonlama" },
  { group: "Dağıtım", name: "Pompa hortumu ve yonlendirme ekipmani", purpose: "Betonun kontrollu yukseklikten ve doğru noktaya verilmesini saglamak.", phase: "Yerlestirme" },
  { group: "Kalite", name: "Slump konisi, termometre ve taze beton kabul ekipmani", purpose: "Vibrasyon kararini etkileyen kivam ve sıcaklık bilgisini toplamak.", phase: "Beton kabulu" },
  { group: "Kontrol", name: "Kalıp acma sonrasi kusur haritasi", purpose: "Yüzey kusurlarini belirli bolgelere baglayarak saha ogrenmesi uretmek.", phase: "Beton sonrasi" },
];

export const kabaInsaatLeafOverrides: BinaGuidePageSpec[] = [
  {
    slugPath: "kaba-insaat/beton-isleri/vibrasyon",
    kind: "topic",
    quote: "Vibrasyon, betona enerji vererek yerlesmesini sağlar; su ekleyerek akitmaya çalışan saha refleksinin teknik panzehiridir.",
    tip: "Eksik vibrasyon kadar asiri vibrasyon da zararlidir; biri peteklenme uretir, digeri segregasyon ve serbet ayrismasi yaratir.",
    intro: [
      "Vibrasyon, betonun donatı cevresini ve kalıp koselerini boşluksuz doldurabilmesi için gerekli en kritik saha operasyonlarindan biridir. Dokum gununde göz genellikle pompa hortumuna, mikser sirasina ve yüzey bitisine odaklanir; oysa elemanin gercek iç kalitesi cogu zaman vibrasyon disiplininde belirlenir.",
      "Sahada vibrasyon cogu kez ustalik refleksiyle yurutulur. Ancak farkli kesitler, farkli donatı yoğunluğu ve farkli kivamlar aynı uygulama ritmini kabul etmez. Kolon dibi, kiriş mesneti, perde ayagi, döşeme-kiriş birleşimi ve sık etriyeli düğümler farkli dikkat ister.",
      "Yetersiz vibrasyon sonucunda peteklenme, boşluk, aderans zayifligi ve yüzey kusurlari dogabilir. Asiri vibrasyon ise iri agreganin ayrismasi, serbet birikmesi ve ozellikle daha akiskan betonlarda segregasyon riski uretir. Iyi vibrasyon bu iki uc davranis arasindaki teknik dengeyi kurmaktir.",
      "Bir inşaat mühendisi için vibrasyonun gorevi yalnız betonu sarsmak degildir; eleman geometrisini okuyup doğru ekipman, doğru katman ve doğru ritim secmektir.",
    ],
    theory: [
      "Igne vibrator, taze betonda gecici akiskanlik olusturarak tanelerin daha iyi yerlesmesini ve hapsolmus havanin disari cikmasini sağlar. Buradaki amac betonu sıvı hale getirmek değil, mevcut karisimi kesit icinde daha duzenli oturtmaktir.",
      "Bu nedenle vibrasyonun basarisi beton kivami ile birlikte ele alinmalidir. Düşük kivamli karisimlarda daha dikkatli yerlestirme gerekirken, yüksek kivamli karisimlarda fazla sureli titresim ayrisma riskini arttirabilir. Tek bir saha refleksi tüm karisimlara uygulanamaz.",
      "Katman mantigi burada belirleyicidir. Beton çok kalin tek tabakada birakilirsa vibrator alt bolgelere yeterince etkili ulasamaz ve ustteki hareket altta boşluk kalarak sonlanabilir. Bu nedenle katman yüksekliği ile vibrasyon noktasi birlikte planlanmalidir.",
      "Ayrıca vibrasyon doğrudan kalıp ve donatı ile de iliskilidir. Yanlış capta igne secilirse dar donatı araliklarina girilemez ya da gereksiz buyuk enerji verilerek yüzey bozulur. Beton akisi, vibrasyon ve kalıp rijitligi tek zincir gibi okunmalidir.",
    ],
    ruleTable: [
      {
        parameter: "Katmanli yerlestirme",
        limitOrRequirement: "Beton, vibrator etkisinin tüm kesite ulasacagi kontrollu katmanlarla verilmeli",
        reference: "TS EN 13670 uygulama prensipleri",
        note: "Asiri yüksek tek katman, altta boşluk birakma riskini arttırır.",
      },
      {
        parameter: "Igne capi ve erişim",
        limitOrRequirement: "Kesit ve donatı sikligina uygun vibrator capi secilmeli",
        reference: "Saha ekipman secim disiplini",
        note: "Dar dugumde buyuk igne, genis hacimde ise çok ince igne sorun yaratabilir.",
      },
      {
        parameter: "Uygulama süresi",
        limitOrRequirement: "Titresim süresi boşluğu giderecek ama segregasyon yaratmayacak noktada tutulmali",
        reference: "TS EN 13670 + saha geri bildirimi",
        note: "Iyi vibrasyonun gostergesi serbet tasmasi değil boşluksuz kesittir.",
      },
      {
        parameter: "Sureklilik ve yedekleme",
        limitOrRequirement: "Yedek vibrator ve yedek enerji kaynagi dokumde hazir olmali",
        reference: "Betonlama risk plani",
        note: "Vibrasyon arizasi soğuk derz kadar kritik bir risk dogurabilir.",
      },
      {
        parameter: "Geri bildirim dongusu",
        limitOrRequirement: "Kalıp acma sonrasi kusurlar sonraki dokum planina veri olarak tasinmali",
        reference: "Kalite kapanis toplantisi",
        note: "Vibrasyon hatasi her katta yeniden tekrar edilmemelidir.",
      },
    ],
    designOrApplicationSteps: [
      "Eleman tipine ve donatı yogunluguna göre uygun vibrator capini, yedek seti ve sorumlu personeli dokum öncesi belirle.",
      "Betonu katmanli vererek vibratorun etkili calisabilecegi hacimler yarat; pompa hortumunu buna göre yonlendir.",
      "Igneyi belirli araliklarla daldir, önceki katmana kismen girecek sekilde süreklilik sagla.",
      "Yoğun düğümler, köşe noktalar ve kolon diplerinde ayri dikkat goster; bu bolgeleri zaten dolar varsayimiyla gecme.",
      "Titresim tamamlaninca betonu gereksiz yere tekrar tekrar kurcalama; yüzey hareketini izleyerek yeterli noktada dur.",
      "Kalıp acma sonrasi gordugun kusurlari rastlanti sayma; hangi kesitte, hangi ekipmanla ve hangi ritimle dokum yapildigini geri izle.",
    ],
    criticalChecks: [
      "Vibrator capi ve uzunlugu eleman geometrisine uygun mu?",
      "Katman yüksekliği, vibratorun alt bolgelere etkisini engelleyecek kadar buyuk mu?",
      "Köşe ve düğümlerde peteklenme riski olan noktalara fiilen erisiliyor mu?",
      "Yuzeyde asiri serbet ayrismasi veya iri agrega birikmesi goruluyor mu?",
      "Yedek vibrator calisir durumda ve ulasilabilir yerde mi?",
      "Kalıp acma sonrasi kusur haritasi bir sonraki dokum için kullanildi mi?",
    ],
    numericalExample: {
      title: "3,0 m yuksekliginde 40 x 60 cm kolonda vibrasyon ritmi ornegi",
      inputs: [
        { label: "Kolon yüksekliği", value: "3,0 m", note: "Tipik kat kolonu" },
        { label: "Planlanan katman yüksekliği", value: "50 cm", note: "Kontrollu yerlestirme" },
        { label: "Tahmini vibrasyon noktasi", value: "Her katmanda 2 nokta", note: "Kesit boyutuna göre" },
        { label: "Nokta basi süre", value: "4-8 saniye", note: "Ornek saha bandi" },
      ],
      assumptions: [
        "Beton kivami proje kabul bandindadir ve segregasyon belirtisi yoktur.",
        "Igne vibrator donatı arasina emniyetli bicimde girebilmektedir.",
        "Pompa akisi, her katmanı kontrol etmeye izin verecek tempodadir.",
      ],
      steps: [
        {
          title: "Katman sayisini bul",
          formula: "3,0 / 0,50 = 6 katman",
          result: "Kolon dokumu yaklasik 6 kontrollu katman halinde yonetilmelidir.",
          note: "Tek seferde yüksek dokum yerine katmanli yaklasim daha guvenlidir.",
        },
        {
          title: "Toplam vibrasyon noktasi sayisini yorumla",
          formula: "6 x 2 = 12 nokta",
          result: "Kolon boyunca yaklasik 12 kontrollu vibrasyon noktasi gerekir.",
          note: "Donatı sık ise ara nokta ihtiyaci artabilir.",
        },
        {
          title: "Aktif vibrasyon suresini hesapla",
          formula: "12 x 4-8 sn = 48-96 sn",
          result: "Toplam aktif vibrasyon süresi yaklasik 1-1,5 dakika bandindadir.",
          note: "Bu süre, tüm kolonun rastgele titrestirilmesi değil planli nokta kontrolü anlamina gelir.",
        },
      ],
      checks: [
        "Katman sayisi ve nokta adedi, eleman geometrisine göre bastan tanimlanmalidir.",
        "Vibrasyon süresi arttikca kalite her zaman artmaz; ayrisma riski de buyur.",
        "Aynı plan, farkli kivam veya farkli donatı yogunlugunda yeniden ayarlanmalidir.",
        "Hesap saha egitiminde ortak dil kurmak için kullanilmali, kor uygulama formuna donusturulmemelidir.",
      ],
      engineeringComment: "Vibrasyonda kalite, ne kadar uzun süre titrestirdiginden değil, nerede ve hangi ritimle titrestirdiginden anlasilir.",
    },
    tools: VIBRATION_TOOLS,
    equipmentAndMaterials: VIBRATION_EQUIPMENT,
    mistakes: [
      { wrong: "Vibrasyonu yalnız yuzeyde gezdirmek.", correct: "Igneyi kesit icine kontrollu olarak daldirip katmanlari birlikte sikistirmak." },
      { wrong: "Her kesitte aynı igne capi ve aynı sureyi kullanmak.", correct: "Kesit boyutu ve donatı yogunluguna göre ekipmani ayarlamak." },
      { wrong: "Peteklenmeyi yalnız beton sinifina baglamak.", correct: "Yerlestirme ve vibrasyon kalitesini birlikte sorgulamak." },
      { wrong: "Asiri serbet cikisini iyi vibrasyon sanmak.", correct: "Segregasyon belirtisini fark edip sureyi sinirlamak." },
      { wrong: "Yedek vibrator olmadan buyuk dokume girmek.", correct: "Ariza riskini saha planinin parçası olarak yonetmek." },
      { wrong: "Kalıp acma kusurlarini bir sonraki dokumle baglamamak.", correct: "Her kusuru geri bildirim verisine cevirmek." },
    ],
    designVsField: [
      "Projede vibrasyon bir not olarak görünür; sahada ise kesitin gercek dayanım ve yüzey kalitesini belirleyen temel uygulama halkasidir.",
      "Hazir beton kalitesi ne kadar iyi olursa olsun, yetersiz vibrasyonla bu kalite eleman icine aktarilamaz.",
      "Bu nedenle vibrasyon, beton dokumunun tali değil ana mühendislik adimidir.",
    ],
    conclusion: [
      "Vibrasyon doğru ekipman, doğru katman ve doğru süre ile yurutuldugunde peteklenme riskini azaltir, donatı cevresinde daha guvenilir yerlestirme sağlar ve kalıp acma kalitesini belirgin bicimde iyilestirir. Rastgele yapildiginda ise betonun iç kalitesini sansa birakir.",
      "Saha pratiginde en güçlü yaklasim, vibrasyonu ustalik refleksi olarak değil, olculebilir bir uygulama protokolu olarak gormektir. Bu yaklasim her katta birikimli kalite uretir.",
    ],
    sources: [...KABA_LEAF_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn206, SOURCE_LEDGER.tsEn13670],
    keywords: ["vibrasyon", "beton yerlestirme", "peteklenme", "segregasyon", "TS EN 13670"],
    relatedPaths: ["kaba-insaat", "kaba-insaat/beton-isleri", "kaba-insaat/beton-isleri/beton-dokumu"],
  },
  {
    slugPath: "kaba-insaat/kalip-isleri/kolon-kalibi",
    kind: "topic",
    quote: "Kolon kalıbı, yalnız bir kalıp paneli değil; aksin, kesitin ve duseyligin sahada gercege donustugu karar noktasidir.",
    tip: "Kolon kalibini şakul, taban sizdirmazligi ve kusak-tij disiplininden ayirirsan, beton doğru gelse bile kesit doğru cikmayabilir.",
    intro: [
      "Kolon kalıbı, betonarme taşıyıcı sistemde düşey eleman geometrisinin sahada kuruldugu ilk kritik imalatlardan biridir. Kolon ekseni, kesit boyutu ve düşeylik burada yanlış kurulursa sonraki kiriş, döşeme ve duvar imalatlari bu hatanin uzerine oturur.",
      "Sahada kolon kalıbı basit gorundugu için cogu zaman hizla kapanan bir iş gibi degerlendirilir. Oysa taban takozu, köşe kilidi, kusak-tij araligi, rezervasyonlar ve dokum hizina uygun sıkma disiplini birlikte çözülmelidir. Bu unsurlardan biri eksik oldugunda beton disari kacar, panel acar veya kolon şakülü bozulur.",
      "Bir inşaat mühendisi için kolon kalıbı, proje aksini sahada doğru okumak ve o geometriyi beton baskisi altinda koruyabilmek anlamina gelir. Kalıp kurulumunun kalitesi, yalnız kalıp ekibinin değil tüm kat cevriminin guvenilirligini etkiler.",
      "Bu nedenle kolon kalibini, kuruldu mu sorusuyla değil, beton geldikten sonra da geometrisini koruyacak mi sorusuyla denetlemek gerekir.",
    ],
    theory: [
      "Kolon kalıbında en kritik konu, taze beton basincina ragmen panel davranisinin kontrol altinda kalmasidir. Ozellikle yüksek kolonlarda, akiskan betonlarda ve hızlı dokum ritminde tabana yakin bolgelerde yan basinc artar. Bu nedenle tij, kusak ve köşe baglantilari yalnız montaj elemani değil güvenlik unsurudur.",
      "Duseylik de ikinci ana konudur. Kalıp panelleri teorik olarak doğru kesitte olsa bile taban oturumu zayif, bağlantı gevsek veya sıkma dengesiz ise kolon ustte baska, altta baska eksende bitebilir. Boyle bir sapma, kiriş oturumu ve duvar aksini domino etkisiyle bozar.",
      "Taban sizdirmazligi da göz ardi edilmemelidir. Ozellikle kolon kaidesi veya döşeme ustune kurulan kaliplarda alttan serbet kacisi yasanirsa kesit yuzeyi zayiflar ve tabanda peteklenme riski artar. Sızdırmazlık detayi, dokum öncesi kapanmasi gereken ana maddelerden biridir.",
      "Ayrıca kolon kalıbında gomulu elemanlar, filiz cikislari ve perde-kiriş birlesimleriyle koordinasyon gerekir. Kalıp kurulduktan sonra duzeltilmeye calisilan rezervasyonlar genellikle kesit dogrulugunu bozar.",
    ],
    ruleTable: [
      {
        parameter: "Aks ve kesit kontrolü",
        limitOrRequirement: "Kolon ekseni, kesit boyutu ve diagonal doğruluğu beton öncesi ölçü ile teyit edilmeli",
        reference: "TS EN 13670 uygulama ve tolerans prensipleri",
        note: "Eksenden kacmis kolon, bir katta kalmaz üst imalatlara da tasinir.",
      },
      {
        parameter: "Şakul ve rijitlik",
        limitOrRequirement: "Kusak, tij ve payandalar duseyligi koruyacak sekilde dengeli sikilmali",
        reference: "Saha kalıp kabul disiplini",
        note: "Panel varligi ile panel rijitligi aynı sey degildir.",
      },
      {
        parameter: "Taban sizdirmazligi",
        limitOrRequirement: "Kalıp ayaginda serbet kacisina izin verecek boşluk birakilmamali",
        reference: "Beton öncesi kontrol listesi",
        note: "En iyi beton bile tabandan kactiginda yüzey kalitesi bozulur.",
      },
      {
        parameter: "Dokum hizi uyumu",
        limitOrRequirement: "Kolon dokum hizi, kalıp rijitligi ve ekipman kapasitesiyle uyumlu olmali",
        reference: "Betonlama plani",
        note: "Hiz baskisi kalıp zorlanmasini buyutebilir.",
      },
      {
        parameter: "Embed ve rezervasyon koordinasyonu",
        limitOrRequirement: "Gomulu parca ve filiz cikislari kalıp kapanmadan önce yerinde dogrulanmali",
        reference: "Shop drawing + saha turu",
        note: "Kalıp kapandiktan sonra yapilan mudahale kesiti bozar.",
      },
    ],
    designOrApplicationSteps: [
      "Akslari ve kolon köşe noktalarini döşeme üzerinde net isaretle; yalnız göz karariyla panel kapatma.",
      "Taban takozu ve sızdırmazlık hazirligini tamamla, ardindan paneli kurup diagonal ve kesit olcusunu al.",
      "Kusak, tij ve payandalari dengeli sık; kolon sakulunu iki dogrultuda ayri kontrol et.",
      "Filiz, gomulu parca, perde-kiriş birleşimi ve döşeme seviyesi ile cakisan detaylari kalıp kapanmadan önce netlestir.",
      "Beton öncesi son turda şakul, taban kacagi, tij sikiligi ve üst kot isaretini tekrar kontrol et.",
      "Dokum sırasında kolon davranisini izle; anormal acilma, serbet kacisi veya şakul kaymasi gorursen akisı yavaslat ve mudahale et.",
    ],
    criticalChecks: [
      "Kolon ekseni ve kesit olculeri shop drawing ile uyumlu mu?",
      "Iki dogrultuda şakul kontrolü aynı anda yapildi mi?",
      "Taban bolgesinde serbet kacagina neden olacak aciklik var mi?",
      "Tij ve kusak araliklari, koselerde yeterli rijitlik sagliyor mu?",
      "Filiz, gomulu parca veya rezervasyonlar kalıp kapanmadan önce teyit edildi mi?",
      "Dokum sırasında payanda ve panel davranisini izleyecek sorumlu kisi tanimli mi?",
    ],
    numericalExample: {
      title: "40 x 60 cm ve 3,20 m yuksekligindeki kolonda taze beton yan basinci yorumu",
      inputs: [
        { label: "Kolon kesiti", value: "40 x 60 cm", note: "Orta boy bina kolonu" },
        { label: "Kolon yüksekliği", value: "3,20 m", note: "Kat yüksekliği" },
        { label: "Beton birim hacim agirligi", value: "24 kN/m3", note: "Yaklasik taze beton degeri" },
        { label: "Hedef", value: "Kalıp rijitligini ve dokum hizini yorumlamak", note: "Detay tasarımı için" },
      ],
      assumptions: [
        "Dokum akiskan bir betonla ve nispeten hızlı ritimde yapilacaktir.",
        "Yan basinc için en olumsuz yaklasim olarak hidrostatik esdeger yorum kullanilmistir.",
        "Gercek tij araligi ve panel kapasitesi sistem ureticisine göre ayri kontrol edilecektir.",
      ],
      steps: [
        {
          title: "Tabandaki esdeger basinci hesapla",
          formula: "24 x 3,20 = 76,8 kPa",
          result: "Taban seviyesinde teorik yan basinc yaklasik 76,8 kPa mertebesine cikabilir.",
          note: "Gercek saha degeri dokum hizi ve kivama göre daha düşük olabilir; ama kalıp güvenliği daha muhafazakar okunmalidir.",
        },
        {
          title: "Basincin ne anlattigini yorumla",
          result: "Tij ve kusak araliklari, ozellikle tabana yakin bolgelerde gevsek birakilamaz.",
          note: "Kolon yüksekliği arttikca küçük montaj ihmalinin etkisi buyur.",
        },
        {
          title: "Dokum hizina karari bagla",
          result: "Kalıp rijitligine guvenmeden hızlı dokum yapmak yerine katmanli ve kontrollu ilerlemek daha guvenlidir.",
          note: "Kalıp güvenliği yalnız malzeme değil operasyon kararidir.",
        },
      ],
      checks: [
        "Hesap, gercek sistem kapasitesini teyit ihtiyacini ortadan kaldirmaz; fakat risk seviyesini görünür kilar.",
        "Taban bolgesindeki bağlantılar üst bölge kadar değil, daha fazla dikkat ister.",
        "Kalıp rijitligi ile beton akisi birlikte yonetilmelidir.",
        "Sızdırmazlık detayi, basinc hesabinin sahadaki tamamlayicisidir.",
      ],
      engineeringComment: "Kolon kalıbında sorun cogu zaman panel eksiginden değil, panelin beton basinci altinda nasil davranacaginin hafife alinmasindan dogar.",
    },
    tools: KALIP_TOOLS,
    equipmentAndMaterials: KALIP_EQUIPMENT,
    mistakes: [
      { wrong: "Kolon panelini aks cizgisine bakmadan hizla kapatmak.", correct: "Aks, diagonal ve kesit olcusunu kalıp kapanmadan önce almak." },
      { wrong: "Şakul kontrolünü tek yuzden yapmak.", correct: "Iki dogrultuda ayri şakul ve lazer kontrolü yapmak." },
      { wrong: "Taban serbet kacagini küçük kusur saymak.", correct: "Sizdirmazligi ana on kabul maddesi olarak görmek." },
      { wrong: "Tij ve kusak sikiligini göz karariyla birakmak.", correct: "Sistematik sıkma ve denetim ritmi kurmak." },
      { wrong: "Gomulu parca ve filizleri beton öncesi son ana birakmak.", correct: "Kalıp kapanmadan önce koordinasyonu tamamlamak." },
      { wrong: "Dokum sırasında kalıbın davranisini izlememek.", correct: "Akisi gozleyen ve mudahale edecek sorumlu kisi tanimlamak." },
    ],
    designVsField: [
      "Projede kolon 40 x 60 cizilir; sahada ise bu kesiti doğru cikaran sey kalıp, sıkma ve ölçü disiplinidir.",
      "Kolon kalıbı ne kadar sessiz tamamlaniyorsa, kat geometrisi o kadar guvenle kuruluyor demektir.",
      "Bu nedenle kolon kalıbı, kalıp isleri icinde en küçük gorunen ama en zincirleme etki ureten imalatlardan biridir.",
    ],
    conclusion: [
      "Kolon kalıbı doğru aks, doğru şakul ve doğru rijitlik ile kuruldugunda kat cevriminin geri kalanina sağlam referans verir. Zayif kuruldugunda ise kiriş, döşeme ve duvar imalatlarini aynı anda cezalandiran bir hata zinciri baslatir.",
      "Saha muhendisligi acisindan en doğru yaklasim, kolon kalibini beton gelmeden önce tamamlanmis değil, beton baskisi altinda da dogrulugunu koruyacak sistem olarak dusunmektir.",
    ],
    sources: [...KABA_LEAF_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670],
    keywords: ["kolon kalıbı", "şakul kontrolü", "kalıp rijitligi", "taze beton basinci", "TS EN 13670"],
    relatedPaths: ["kaba-insaat", "kaba-insaat/kalip-isleri", "kaba-insaat/kalip-isleri/kiris-kalibi"],
  },
  {
    slugPath: "kaba-insaat/kalip-isleri/kiris-kalibi",
    kind: "topic",
    quote: "Kiriş kalıbı, taşıyıcı sistemin basit bir kanali değil; alt kötü, kesiti ve mesnet geometrisini aynı anda yoneten hassas bir imalattir.",
    tip: "Kiriş kalıbında birkaç milimetrelik ihmal, donatı yerlestirimi, döşeme kötü ve görünür tavan hatlarina aynı anda yansiyabilir.",
    intro: [
      "Kiriş kalıbı, döşeme ile kolonlar arasindaki ana yük aktarim elemaninin sahada geometrik olarak kuruldugu imalattir. Kiriş genisligi, yüksekliği, alt kötü ve mesnet baglantilari burada belirlenir. Dolayisiyla bir kiriş kalıbı yanlış kuruldugunda problem yalnız bir beton yuzeyi sorunu olarak kalmaz; donatı yerlestirimi, döşeme kalinligi ve bitis kotlarini etkiler.",
      "Sahada kiriş kalibinin en zorlayici yani, onu izole bir eleman gibi kuramiyor olmamizdir. Kolonlar, döşeme kalıbı, tesisat rezervasyonlari, filizler ve cogu zaman sık donatili mesnet bolgeleri kiriş kalıbı ile aynı anda okunmak zorundadir.",
      "Bu nedenle kiriş kalıbı, ahşap veya panel elemanlarini bir araya getirmekten ibaret degildir. Mesnetlerde genisleme yapmayan, tabanda sehim biriktirmeyen, yanaklarda acilmayan ve beton öncesi ölçü ile okunabilir kalan bir sistem kurmak gerekir.",
      "Bir inşaat mühendisi için kiriş kalıbı; proje kesitini sahada uygulanabilir hale getirmek, bunu da betonlama esnasinda guvenle korumak demektir.",
    ],
    theory: [
      "Kiriş kalıbında iki ana risk vardir: alt kot kaybi ve yanak acilmasi. Alt kot kaybi genellikle yetersiz tali destek, uygun olmayan alt taşıyıcı düzeni veya uzun aciklikta kontrol edilmeyen deformasyondan kaynaklanir. Yanak acilmasi ise tij, kusak ve köşe baglantilarinin zayifligindan ya da hızlı betonlamadan etkilenir.",
      "Mesnet bolgeleri ayrıca kritik noktalardir. Kolon-kiriş birlesimlerinde donatı yoğunluğu arttikca hem kalıp toleransi hem beton akisi daha hassas hale gelir. Kesit planlanan genislikten kayarsa donatı sikisir, paspayı zorlanir ve vibrasyon kalitesi duser.",
      "Kiriş kalıbı ile döşeme kalıbı birlikte davranir. Kiriş tabani doğru kotta degilse döşeme alt yuzeyi de sasar; tavan hizasi ve asma tavan detaylari ileride farkli duzeltmeler ister. Bu yuzden kiriş kalibini sadece betonarme ekibinin sorunu olarak görmek eksik olur.",
      "Ayrıca kiriş icinden gecen rezervasyonlar, tesisat askilari veya sonradan acilmasi planlanan boşluklar kalıp asamasinda netlesmelidir. Beton gelmeden cozulmeyen her nokta, sonradan kırma veya mühendislik riski olarak geri doner.",
    ],
    ruleTable: [
      {
        parameter: "Kesit ve alt kot",
        limitOrRequirement: "Kiriş genisligi, yüksekliği ve alt kötü shop drawing ile ölçülerek dogrulanmali",
        reference: "TS EN 13670 uygulama ve tolerans prensipleri",
        note: "Bir kere dokulen kiriş, sonradan planda gorundugu hale gelemez.",
      },
      {
        parameter: "Alt taşıyıcı ve deformasyon",
        limitOrRequirement: "Aciliga uygun destek ritmi ve rijit alt taşıyıcı düzeni kurulmalı",
        reference: "Kalıp tasarim ve uygulama disiplini",
        note: "Kalıp sağlam gorunse de sehim yapabilir.",
      },
      {
        parameter: "Yanak rijitligi",
        limitOrRequirement: "Yanak paneli, köşe ve bağlantı elemanlari beton basincina karsi yeterli sikilikta olmali",
        reference: "Beton öncesi kabul listesi",
        note: "Yanak acilmasi kesit kaybina ve yüzey bozulmasina yol acar.",
      },
      {
        parameter: "Birleşim ve rezervasyon",
        limitOrRequirement: "Kolon mesnetleri, döşeme birleşimi ve rezervasyonlar beton öncesi kapatilmali",
        reference: "Shop drawing + koordinasyon turu",
        note: "Kiriş, diger elemanlardan bağımsız okunamaz.",
      },
      {
        parameter: "Sokum ve tali destek",
        limitOrRequirement: "Kiriş alti destekler, betonun erken yas davranisi dikkate alinmadan kaldirilmamali",
        reference: "TS EN 13670 + kat cevrimi plani",
        note: "Erken sokum, çatlak ve gereksiz sehim riski uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Kiriş aksini, genisligini ve mesnet noktalarini kolon akslariyla birlikte zeminde veya mevcut döşemede isaretle.",
      "Alt taşıyıcı dizilimi ve tali dikme araligini aciklik, panel tipi ve beton yukune göre kür.",
      "Kiriş tabanini doğru kota getir, gerekiyorsa aciklik uzunluguna göre kontrollu ters sehim kararini proje ve saha planina bagla.",
      "Yanak panellerini kusak ve tijlerle kapat; koselerde acilma riskini azaltacak sıkma ritmini kür.",
      "Mesnet bolgesi donatısı, rezervasyonlar ve döşeme birleşimi ile cakisan noktalari beton öncesi son turda kontrol et.",
      "Dokum sırasında ozellikle mesnet ve yanak bolgelerinde kalıp davranisini izle; deformasyon emaresi varsa dokum ritmini duzelt.",
    ],
    criticalChecks: [
      "Kiriş tabani proje kotunda ve eksende mi?",
      "Acilik boyunca alt destek araliklari ve oturmalari yeterli mi?",
      "Yanak panellerinde lokal bombe veya acilma egilimi var mi?",
      "Mesnet bolgelerinde donatı sikisikligi kalıp kesitini zorluyor mu?",
      "Rezervasyon ve gomulu parcalar beton öncesi dogrulandi mi?",
      "Kiriş alti tali desteklerin ne zaman sokulecegi yazili planla tanimlandi mi?",
    ],
    numericalExample: {
      title: "30 x 60 cm ve 6,0 m aciklikli kiriste alt destek yük yorumu",
      inputs: [
        { label: "Kiriş kesiti", value: "30 x 60 cm", note: "Betonarme kiriş" },
        { label: "Aciliklik", value: "6,0 m", note: "Orta aciklik" },
        { label: "Taze beton birim hacim agirligi", value: "25 kN/m3", note: "Yaklasik deger" },
        { label: "Alt destek araligi", value: "1,0 m", note: "Ornek saha yerlesimi" },
      ],
      assumptions: [
        "Dokum sırasında isci ve ekipman etkisi için ilave emniyet payi vardir.",
        "Alt destekler sağlam zemine veya yeterli dagitici taban plakasina oturmaktadir.",
        "Gercek sistem kapasitesi uretici verisiyle ayri kontrol edilecektir.",
      ],
      steps: [
        {
          title: "Betonun birim boydaki ağırlığını hesapla",
          formula: "0,30 x 0,60 x 25 = 4,5 kN/m",
          result: "Kiriş yalnız taze beton olarak yaklasik 4,5 kN/m yük uretir.",
          note: "Bu degere kalıp, isci ve ekipman etkisi ayrıca eklenir.",
        },
        {
          title: "Saha payi ile yorumla",
          formula: "4,5 + 1,5 ≈ 6,0 kN/m",
          result: "Kalıp ve isci etkisiyle pratik yorumda 6,0 kN/m mertebesi okunabilir.",
          note: "Kesin deger sistem ve çalışma duzenine göre degisir.",
        },
        {
          title: "1 m aralikli destek ritmini oku",
          result: "Her 1 metrelik bolgede alt taşıyıcı sistem en az bu mertebede yük tasir.",
          note: "Uzun acikliklarda destek oturmasi ve taşıyıcı rijitlik beraber düşünülmelidir.",
        },
      ],
      checks: [
        "Destek araligi hesabi yalnız panel dizisine göre değil yük mantigina göre okunmalidir.",
        "Zemin oturmasi veya taban plakasinin zayifligi, teorik kapasiteyi sahada anlamsiz kilabilir.",
        "Mesnete yakin bolgelerde yük etkisi ve donatı yoğunluğu bir arada degerlendirilmelidir.",
        "Hesap, uygulama öncesi destek duzeninin neden disiplinli olmasi gerektigini görünür kilar.",
      ],
      engineeringComment: "Kiriş kalıbı cogu zaman aciklik boyunca sessiz durur; ama o sessizlik, ancak altindaki destek düzeni gercekten dogruysa guven verir.",
    },
    tools: KALIP_TOOLS,
    equipmentAndMaterials: KALIP_EQUIPMENT,
    mistakes: [
      { wrong: "Kiriş taban kotunu yalnız göz karariyla kurmak.", correct: "Lazer ve aks kontrolü ile alt kötü olcerek sabitlemek." },
      { wrong: "Acilik arttikca destek ritmini degistirmemek.", correct: "Yük ve deformasyon riskine göre destek planini guncellemek." },
      { wrong: "Mesnet bolgesi donatisini kalıp kapandiktan sonra dusunmek.", correct: "Donatı sikisikligini kalıp kesitiyle birlikte okumak." },
      { wrong: "Yanak panelindeki küçük acilmalari onemsiz görmek.", correct: "Kesit kaymasi yaratacak her acilmayi aninda duzeltmek." },
      { wrong: "Rezervasyonlari beton öncesi kesinlestirmemek.", correct: "Tesisat ve gomulu detaylari kalıp turunda kapatmak." },
      { wrong: "Tali destek sokumunu yalnız takvime göre yapmak.", correct: "Betonun erken yas davranisini ve reshoring planini esas almak." },
    ],
    designVsField: [
      "Projede kiriş bir cizgi ve kesit bilgisi olarak durur; sahada ise kalıp, donatı ve betonlama davranisiyla gercek olur.",
      "Kiriş kalibindeki küçük kot veya kesit hatasi, daha sonra tavan ve bitis imalatlarinda çok daha görünür hale gelir.",
      "Bu nedenle kiriş kalıbı, kaba insaatta sadece taşıyıcı sistem değil aynı zamanda bitis doğruluğu uretir.",
    ],
    conclusion: [
      "Kiriş kalıbı doğru kot, doğru destek ve doğru yanak rijitligiyle kuruldugunda hem taşıyıcı sistem davranisi hem de kat geometrisi için güvenli bir temel olusturur. Zayif kuruldugunda ise hatayi beton sertlestikten sonra fark ettirir.",
      "Pratikte en iyi sonuc, kiriş kalibini panel montaji olarak değil, aciklik boyunca yük ve tolerans yönetimi olarak ele alan ekiplerde alinir.",
    ],
    sources: [...KABA_LEAF_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670],
    keywords: ["kiriş kalıbı", "alt kot kontrolü", "mesnet bolgesi", "kalıp sehim", "TS EN 13670"],
    relatedPaths: ["kaba-insaat", "kaba-insaat/kalip-isleri", "kaba-insaat/kalip-isleri/doseme-kalibi"],
  },
  {
    slugPath: "kaba-insaat/kalip-isleri/doseme-kalibi",
    kind: "topic",
    quote: "Döşeme kalıbı, yalnız betonu tasiyan gecici iskele değil; katin bitis kotunu, duzlemini ve alt imalat referansini ureten ana platformdur.",
    tip: "Döşeme kalıbına sadece dikme ormani gibi bakarsan, beton sonrasi tavan duzlemi ve tesisat koordinasyonu tesadufe kalir.",
    intro: [
      "Döşeme kalıbı, bir katin yatay geometri kalitesini belirleyen temel imalattir. Döşeme kalinligi, alt yüzey duzlugu, rezervasyonlarin yeri ve balkon veya islak hacim gibi kritik kot farklari burada sahada gercege donusur. Bu nedenle hatasi en gec fark edilen, ama etkisi en genis yayilan kalıp kalemlerinden biridir.",
      "Sahada döşeme kalıbı cogu zaman genis alan kapladigi için seri iş gibi görünür. Oysa bu genislik, kontrol zorlugu da getirir. Küçük bir kot sapmasi yuzlerce metrekare boyunca yayilabilir; yanlış birakilan bir rezervasyon ise beton sonrasinda pahali mudahalelere neden olabilir.",
      "Bir inşaat mühendisi için döşeme kalıbı; sadece tasima kapasitesi değil, aynı zamanda sonrasinda asma tavan, şap, seramik, parke ve mekanik tesisat koordinasyonunu etkileyen temel referans katmandir.",
      "Bu nedenle döşeme kalıbı, kurulduktan sonra değil beton öncesi ölçülerek ve gezilerek kabul edilmesi gereken bir sistem olarak ele alinmalidir.",
    ],
    theory: [
      "Döşeme kalıbında yük davranisi birim alana yayilan taze beton, donatı, ekipman ve isci etkilerinden olusur. Genis yuzeylerde sorun cogu zaman tek bir dikmenin kapasitesinden değil, desteklerin oturma farkindan ve sistemin genel rijitliginden kaynaklanir.",
      "Duzlem kalitesi, bitis islerinde en görünür etkilerden birini uretir. Beton sonrasi alt tavanda dalga, lokal cokme veya aksa uymayan kenar hatti olusursa, sonraki ekipler bunu siva, asma tavan veya şap ile telafi etmeye calisir. Bu da maliyet ve süre kaybi demektir.",
      "Döşeme kalıbı ayrıca rezervasyon ve boşluk yönetimi ister. Merdiven boşluğu, saft, tesisat gecisi, balkon kenari veya döşeme kot farki gibi detaylar yalnız paftada değil kalıp ustunde de net okunmalidir. Aksi halde dokum gunu acele mudahaleler ortaya çıkar.",
      "Sokum ve reshoring konusu da önemlidir. Döşeme betonu yeterli erken yas davranisina ulasmadan alt destekleri almak, çatlak ve gereksiz sehim riskini buyutur. Yani döşeme kalıbı, kurulumu kadar sokum planiyla da degerlendirilmelidir.",
    ],
    ruleTable: [
      {
        parameter: "Kot ve duzlem",
        limitOrRequirement: "Döşeme üst kötü ve alt yüzey referansi lazer veya total station ile sistematik kontrol edilmeli",
        reference: "TS EN 13670 uygulama ve tolerans prensipleri",
        note: "Genis alanda küçük hata, toplam etkiyi buyutur.",
      },
      {
        parameter: "Destek izgara ve taban oturumu",
        limitOrRequirement: "Dikme araliklari, alt taşıyıcı yonu ve taban dagitimi yük mantigina göre kurulmalı",
        reference: "Kalıp tasarim disiplini",
        note: "Saglam gorunen sistem, zayif zeminde oturabilir.",
      },
      {
        parameter: "Rezervasyon ve boşluklar",
        limitOrRequirement: "Saft, merdiven, tesisat ve balkon detaylari beton öncesi görünür ve sabit olmali",
        reference: "Shop drawing + koordinasyon turu",
        note: "Son dakika acilan boşluk, kalıp butunlugunu bozar.",
      },
      {
        parameter: "Kenar güvenliği ve kenar dogrusalligi",
        limitOrRequirement: "Döşeme kenarlari, parapet ve balkon hatlari dogrusal ve güvenli sekilde kapatilmali",
        reference: "Beton öncesi saha güvenliği ve kalite turu",
        note: "Kenar hatti hem geometri hem iş güvenliği konusudur.",
      },
      {
        parameter: "Sokum ve reshoring",
        limitOrRequirement: "Alt destekler betonun erken yas davranisina göre planli kaldirilmali",
        reference: "TS EN 13670 + kat cevrimi plani",
        note: "Takvim baskisi ile yapilan erken sokum gorunmeyen hasar uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Döşeme planini acarak akslari, kalinliklari, rezervasyonlari ve kot farki olan bolgeleri iş programi öncesi netlestir.",
      "Alt taşıyıcı ve dikme izgarasini aciklik, panel tipi ve zemin durumuna göre kür; taban plakalarini ihmal etme.",
      "Kot civileri, lazer referanslari ve kenar hatlari ile tüm yuzeyde ortak bir duzlem dili olustur.",
      "Saft, merdiven, balkon, islak hacim ve tesisat bosluklarini kalıp ustunde fiziksel olarak isaretleyip sabitle.",
      "Beton öncesi yuruyus turunda panel birlesimleri, dikme oturmalari, kenar güvenliği ve rezervasyon sabitligini birlikte kontrol et.",
      "Beton sonrasi sokum ve tali destek planini yazili hale getir; bir sonraki kat baskisina göre reshoring disiplinini koru.",
    ],
    criticalChecks: [
      "Genis alanda lazer kot kontrolü noktasal değil ag mantigiyla yapildi mi?",
      "Dikme tabanlari sağlam, kuru ve oturma riski düşük bir zemine oturuyor mu?",
      "Rezervasyonlar ve saft boşlukları beton öncesi gercek boy ve konumunda mi?",
      "Balkon ve islak hacim gibi kot farki istenen bolgeler kalipta netlesti mi?",
      "Kenar hatlari ve döşeme kalinligi isaretleri tüm ekip tarafindan okunabilir mi?",
      "Sokum ve reshoring karari takvimden değil teknik plandan mi veriliyor?",
    ],
    numericalExample: {
      title: "7,20 x 5,40 m ve 15 cm kalinlikli döşemede birim alan yük yorumu",
      inputs: [
        { label: "Döşeme alani", value: "7,20 x 5,40 m", note: "Ornek kat parçası" },
        { label: "Döşeme kalinligi", value: "15 cm", note: "Betonarme döşeme" },
        { label: "Taze beton birim hacim agirligi", value: "25 kN/m3", note: "Yaklasik deger" },
        { label: "Dikme izgarasi", value: "1,20 x 1,20 m", note: "Ornek saha ritmi" },
      ],
      assumptions: [
        "Kalıp agirligi ve canli yapim yukleri için ilave emniyet payi ayrıca dikkate alinacaktir.",
        "Alt taşıyıcı sistem yukleri dikmelere dengeli aktarmaktadir.",
        "Zemin oturmasi ve taban plaka etkisi sahada ayrıca kontrol edilmistir.",
      ],
      steps: [
        {
          title: "Betonun birim alan yükünü hesapla",
          formula: "0,15 x 25 = 3,75 kN/m2",
          result: "Taze beton, döşeme kalıbı uzerine yaklasik 3,75 kN/m2 yük bindirir.",
          note: "Bu hesap yalnız beton agirligidir; kalıp ve uygulama yukleri ilave edilmelidir.",
        },
        {
          title: "Saha payi ile toplam yorumu yap",
          formula: "3,75 + 1,50 ≈ 5,25 kN/m2",
          result: "Kalıp ve isci etkisiyle pratik yorumda 5,25 kN/m2 mertebesi okunabilir.",
          note: "Gercek emniyet hesabi sistem uretici verisi ile tamamlanmalidir.",
        },
        {
          title: "Bir dikmeye düşen alani yorumla",
          formula: "1,20 x 1,20 = 1,44 m2; 1,44 x 5,25 = 7,56 kN",
          result: "Ornek gridde her dikme yaklasik 7,6 kN mertebesinde yük tasiyabilir.",
          note: "Bu deger, oturma riski olan zeminde daha kritik hale gelir.",
        },
      ],
      checks: [
        "Genis yuzeyli dosemelerde yük hesabi tek dikmeye bakarak değil grid mantigiyla okunmalidir.",
        "Dikme kapasitesi kadar altindaki zemin ve taban plaka davranisi da önemlidir.",
        "Rezervasyonlar ve kot farklari, destek izgarasini yerel olarak degistirebilir.",
        "Bu tur hesaplar saha ekibine neden belirli ritimde destek kurulmasi gerektigini aciklar.",
      ],
      engineeringComment: "Döşeme kalıbında en tehlikeli hata, genis yüzey nedeniyle küçük deformasyonlari onemsiz sanmaktir.",
    },
    tools: KALIP_TOOLS,
    equipmentAndMaterials: KALIP_EQUIPMENT,
    mistakes: [
      { wrong: "Döşeme kalibini genis alan diye göz karari kotlamak.", correct: "Lazer ve ag mantigiyla sistematik kot kontrolü yapmak." },
      { wrong: "Dikme tabanlarini dagitici plaka olmadan zayif zemine oturtmak.", correct: "Taban dagilimini ve oturma riskini bastan çözmek." },
      { wrong: "Saft ve rezervasyonlari beton gunu hatirlamak.", correct: "Tüm boşlukları kalıp ustunde önceden sabitlemek." },
      { wrong: "Kenar hattini yalnız iş güvenliği olarak görmek.", correct: "Geometri ve güvenliği birlikte kontrol etmek." },
      { wrong: "Döşeme duzlemsizligini sapla telafi ederiz diye dusunmek.", correct: "Duzlem kalitesini kalıp asamasinda uretmek." },
      { wrong: "Tali destekleri sirf takvim geregi erken sokmek.", correct: "Reshoring planini teknik kararla yurutmek." },
    ],
    designVsField: [
      "Projede döşeme tek bir kalinlik degeri gibi görünür; sahada ise o degeri gercekten ureten unsur kalıp izgarasi ve kot disiplinidir.",
      "Döşeme kalıbı ne kadar dogruysa, sonraki şap, seramik, parke ve asma tavan ekipleri o kadar sessiz calisir.",
      "Bu nedenle döşeme kalıbı, kaba insaatin gorunmeyen ama tüm bitisleri etkileyen ana referans duzlemidir.",
    ],
    conclusion: [
      "Döşeme kalıbı doğru yük okumasi, doğru kot ve doğru rezervasyon yönetimi ile kuruldugunda yapının hem taşıyıcı guvenine hem de bitis kalitesine doğrudan katki verir. Hatasi buyuk yuzeye yayildigi için duzeltilmesi de her zaman daha pahali olur.",
      "Saha pratiginde en verimli yaklasim, döşeme kalibini dikme dikildi, panel kapandi seviyesinde değil, olculebilir geometri ve planli sokum sistemi olarak yonetmektir.",
    ],
    sources: [...KABA_LEAF_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670],
    keywords: ["döşeme kalıbı", "kot kontrolü", "rezervasyon", "reshoring", "TS EN 13670"],
    relatedPaths: ["kaba-insaat", "kaba-insaat/kalip-isleri", "kaba-insaat/kalip-isleri/kiris-kalibi"],
  },
];
