import { BRANCH_SOURCE_LEDGER, SOURCE_LEDGER } from "../source-ledger";
import type { BinaGuideEquipment, BinaGuidePageSpec, BinaGuideTool } from "../types";

const KABA_LEAF_OVERRIDE_SOURCES = [...BRANCH_SOURCE_LEDGER["kaba-insaat"]];

const KALIP_TOOLS: BinaGuideTool[] = [
  { category: "Cizim", name: "Kalip paftalari, rezervasyon planlari ve shop drawing seti", purpose: "Aks, bosluk, embed ve kot kararlarini uygulama öncesi kesinlestirmek." },
  { category: "Ölçüm", name: "Total station, lazer nivo ve deformasyon takip listesi", purpose: "Kolon sakulu, kiris alt kötü ve doseme duzlemini beton öncesi veriye baglamak." },
  { category: "Planlama", name: "Kat cevrimi, sokum ve reshoring cizelgesi", purpose: "Kalip kurulumunu yalnız dokum gunu degil, sonraki yuk transferiyle birlikte yonetmek." },
  { category: "Kontrol", name: "On kabul ve beton öncesi checklist", purpose: "Sahadaki son kalite turunu kisilere degil standarda baglamak." },
];

const KALIP_EQUIPMENT: BinaGuideEquipment[] = [
  { group: "Taşıyıcı", name: "Panel kalip, ahşap kusak, H20 kiris ve tali dikme sistemi", purpose: "Taze beton yukunu, ekip yukunu ve geometriyi guvenle tasimak.", phase: "Kalip kurulumu" },
  { group: "Bağlantı", name: "Tij, somun, kelebek, kusak ve kilit sistemleri", purpose: "Yanak acilmasi, panel ayrilmasi ve kesit kaymasi riskini azaltmak.", phase: "Montaj ve sıkma" },
  { group: "Ölçüm", name: "Lazer nivo, şakul, metre, isaretleme seti ve kot civileri", purpose: "Aks, şakul, kalinlik ve alt kötü sahada surekli izlemek.", phase: "Ölçüm ve kabul" },
  { group: "Güvenlik", name: "Kenar koruma, çalışma platformu ve alt destek emniyet elemanlari", purpose: "Kalip ve betonlama sirasinda guvenli çalışma ortami saglamak.", phase: "Tüm süreç" },
];

const VIBRATION_TOOLS: BinaGuideTool[] = [
  { category: "Planlama", name: "Beton sevkiyat ve katman plani", purpose: "Vibrasyon ritmini pompa akisi ve eleman geometrisiyle uyumlu kurmak." },
  { category: "Ölçüm", name: "Katman ve nokta takip formu", purpose: "Yoğun dugumlerde nerede ve hangi sirada vibrasyon yapildigini izlemek." },
  { category: "Kontrol", name: "Kalip acma sonrasi kusur geri bildirim listesi", purpose: "Peteklenme ve segregasyon gozlemlerini bir sonraki dokum planiyla baglamak." },
  { category: "Ekipman", name: "Igne vibrator cap seti ve yedek enerji kaynagi", purpose: "Kesit tipine göre doğru ucu secmek ve ariza riskini azaltmak." },
];

const VIBRATION_EQUIPMENT: BinaGuideEquipment[] = [
  { group: "Betonlama", name: "Igne vibrator, yedek igne ve yedek motor seti", purpose: "Taze betonun kesit icinde bosluksuz yerlesmesine yardim etmek.", phase: "Betonlama" },
  { group: "Dağıtım", name: "Pompa hortumu ve yonlendirme ekipmani", purpose: "Betonun kontrollu yukseklikten ve doğru noktaya verilmesini saglamak.", phase: "Yerlestirme" },
  { group: "Kalite", name: "Slump konisi, termometre ve taze beton kabul ekipmani", purpose: "Vibrasyon kararini etkileyen kivam ve sıcaklık bilgisini toplamak.", phase: "Beton kabulu" },
  { group: "Kontrol", name: "Kalip acma sonrasi kusur haritasi", purpose: "Yüzey kusurlarini belirli bolgelere baglayarak saha ogrenmesi uretmek.", phase: "Beton sonrasi" },
];

export const kabaInsaatLeafOverrides: BinaGuidePageSpec[] = [
  {
    slugPath: "kaba-insaat/beton-isleri/vibrasyon",
    kind: "topic",
    quote: "Vibrasyon, betona enerji vererek yerlesmesini saglar; su ekleyerek akitmaya çalışan saha refleksinin teknik panzehiridir.",
    tip: "Eksik vibrasyon kadar asiri vibrasyon da zararlidir; biri peteklenme uretir, digeri segregasyon ve serbet ayrismasi yaratir.",
    intro: [
      "Vibrasyon, betonun donati cevresini ve kalip koselerini bosluksuz doldurabilmesi için gerekli en kritik saha operasyonlarindan biridir. Dokum gununde göz genellikle pompa hortumuna, mikser sirasina ve yüzey bitisine odaklanir; oysa elemanin gercek iç kalitesi cogu zaman vibrasyon disiplininde belirlenir.",
      "Sahada vibrasyon cogu kez ustalik refleksiyle yurutulur. Ancak farkli kesitler, farkli donati yogunlugu ve farkli kivamlar aynı uygulama ritmini kabul etmez. Kolon dibi, kiris mesneti, perde ayagi, doseme-kiris birlesimi ve sık etriyeli dugumler farkli dikkat ister.",
      "Yetersiz vibrasyon sonucunda peteklenme, bosluk, aderans zayifligi ve yüzey kusurlari dogabilir. Asiri vibrasyon ise iri agreganin ayrismasi, serbet birikmesi ve ozellikle daha akiskan betonlarda segregasyon riski uretir. Iyi vibrasyon bu iki uc davranis arasindaki teknik dengeyi kurmaktir.",
      "Bir insaat muhendisi için vibrasyonun gorevi yalnız betonu sarsmak degildir; eleman geometrisini okuyup doğru ekipman, doğru katman ve doğru ritim secmektir.",
    ],
    theory: [
      "Igne vibrator, taze betonda gecici akiskanlik olusturarak tanelerin daha iyi yerlesmesini ve hapsolmus havanin disari cikmasini saglar. Buradaki amac betonu sivi hale getirmek degil, mevcut karisimi kesit icinde daha duzenli oturtmaktir.",
      "Bu nedenle vibrasyonun basarisi beton kivami ile birlikte ele alinmalidir. Düşük kivamli karisimlarda daha dikkatli yerlestirme gerekirken, yuksek kivamli karisimlarda fazla sureli titresim ayrisma riskini arttirabilir. Tek bir saha refleksi tüm karisimlara uygulanamaz.",
      "Katman mantigi burada belirleyicidir. Beton çok kalin tek tabakada birakilirsa vibrator alt bolgelere yeterince etkili ulasamaz ve ustteki hareket altta bosluk kalarak sonlanabilir. Bu nedenle katman yuksekligi ile vibrasyon noktasi birlikte planlanmalidir.",
      "Ayrıca vibrasyon doğrudan kalip ve donati ile de iliskilidir. Yanlış capta igne secilirse dar donati araliklarina girilemez ya da gereksiz buyuk enerji verilerek yüzey bozulur. Beton akisi, vibrasyon ve kalip rijitligi tek zincir gibi okunmalidir.",
    ],
    ruleTable: [
      {
        parameter: "Katmanli yerlestirme",
        limitOrRequirement: "Beton, vibrator etkisinin tüm kesite ulasacagi kontrollu katmanlarla verilmeli",
        reference: "TS EN 13670 uygulama prensipleri",
        note: "Asiri yuksek tek katman, altta bosluk birakma riskini arttırır.",
      },
      {
        parameter: "Igne capi ve erişim",
        limitOrRequirement: "Kesit ve donati sikligina uygun vibrator capi secilmeli",
        reference: "Saha ekipman secim disiplini",
        note: "Dar dugumde buyuk igne, genis hacimde ise çok ince igne sorun yaratabilir.",
      },
      {
        parameter: "Uygulama suresi",
        limitOrRequirement: "Titresim suresi boslugu giderecek ama segregasyon yaratmayacak noktada tutulmali",
        reference: "TS EN 13670 + saha geri bildirimi",
        note: "Iyi vibrasyonun gostergesi serbet tasmasi degil bosluksuz kesittir.",
      },
      {
        parameter: "Sureklilik ve yedekleme",
        limitOrRequirement: "Yedek vibrator ve yedek enerji kaynagi dokumde hazir olmali",
        reference: "Betonlama risk plani",
        note: "Vibrasyon arizasi soğuk derz kadar kritik bir risk dogurabilir.",
      },
      {
        parameter: "Geri bildirim dongusu",
        limitOrRequirement: "Kalip acma sonrasi kusurlar sonraki dokum planina veri olarak tasinmali",
        reference: "Kalite kapanis toplantisi",
        note: "Vibrasyon hatasi her katta yeniden tekrar edilmemelidir.",
      },
    ],
    designOrApplicationSteps: [
      "Eleman tipine ve donati yogunluguna göre uygun vibrator capini, yedek seti ve sorumlu personeli dokum öncesi belirle.",
      "Betonu katmanli vererek vibratorun etkili calisabilecegi hacimler yarat; pompa hortumunu buna göre yonlendir.",
      "Igneyi belirli araliklarla daldir, onceki katmana kismen girecek sekilde sureklilik sagla.",
      "Yoğun dugumler, köşe noktalar ve kolon diplerinde ayri dikkat goster; bu bolgeleri zaten dolar varsayimiyla gecme.",
      "Titresim tamamlaninca betonu gereksiz yere tekrar tekrar kurcalama; yüzey hareketini izleyerek yeterli noktada dur.",
      "Kalip acma sonrasi gordugun kusurlari rastlanti sayma; hangi kesitte, hangi ekipmanla ve hangi ritimle dokum yapildigini geri izle.",
    ],
    criticalChecks: [
      "Vibrator capi ve uzunlugu eleman geometrisine uygun mu?",
      "Katman yuksekligi, vibratorun alt bolgelere etkisini engelleyecek kadar buyuk mu?",
      "Köşe ve dugumlerde peteklenme riski olan noktalara fiilen erisiliyor mu?",
      "Yuzeyde asiri serbet ayrismasi veya iri agrega birikmesi goruluyor mu?",
      "Yedek vibrator calisir durumda ve ulasilabilir yerde mi?",
      "Kalip acma sonrasi kusur haritasi bir sonraki dokum için kullanildi mi?",
    ],
    numericalExample: {
      title: "3,0 m yuksekliginde 40 x 60 cm kolonda vibrasyon ritmi ornegi",
      inputs: [
        { label: "Kolon yuksekligi", value: "3,0 m", note: "Tipik kat kolonu" },
        { label: "Planlanan katman yuksekligi", value: "50 cm", note: "Kontrollu yerlestirme" },
        { label: "Tahmini vibrasyon noktasi", value: "Her katmanda 2 nokta", note: "Kesit boyutuna göre" },
        { label: "Nokta basi sure", value: "4-8 saniye", note: "Ornek saha bandi" },
      ],
      assumptions: [
        "Beton kivami proje kabul bandindadir ve segregasyon belirtisi yoktur.",
        "Igne vibrator donati arasina emniyetli bicimde girebilmektedir.",
        "Pompa akisi, her katmani kontrol etmeye izin verecek tempodadir.",
      ],
      steps: [
        {
          title: "Katman sayisini bul",
          formula: "3,0 / 0,50 = 6 katman",
          result: "Kolon dokumu yaklasik 6 kontrollu katman halinde yonetilmelidir.",
          note: "Tek seferde yuksek dokum yerine katmanli yaklasim daha guvenlidir.",
        },
        {
          title: "Toplam vibrasyon noktasi sayisini yorumla",
          formula: "6 x 2 = 12 nokta",
          result: "Kolon boyunca yaklasik 12 kontrollu vibrasyon noktasi gerekir.",
          note: "Donati sık ise ara nokta ihtiyaci artabilir.",
        },
        {
          title: "Aktif vibrasyon suresini hesapla",
          formula: "12 x 4-8 sn = 48-96 sn",
          result: "Toplam aktif vibrasyon suresi yaklasik 1-1,5 dakika bandindadir.",
          note: "Bu sure, tüm kolonun rastgele titrestirilmesi degil planli nokta kontrolu anlamina gelir.",
        },
      ],
      checks: [
        "Katman sayisi ve nokta adedi, eleman geometrisine göre bastan tanimlanmalidir.",
        "Vibrasyon suresi arttikca kalite her zaman artmaz; ayrisma riski de buyur.",
        "Aynı plan, farkli kivam veya farkli donati yogunlugunda yeniden ayarlanmalidir.",
        "Hesap saha egitiminde ortak dil kurmak için kullanilmali, kor uygulama formuna donusturulmemelidir.",
      ],
      engineeringComment: "Vibrasyonda kalite, ne kadar uzun sure titrestirdiginden degil, nerede ve hangi ritimle titrestirdiginden anlasilir.",
    },
    tools: VIBRATION_TOOLS,
    equipmentAndMaterials: VIBRATION_EQUIPMENT,
    mistakes: [
      { wrong: "Vibrasyonu yalnız yuzeyde gezdirmek.", correct: "Igneyi kesit icine kontrollu olarak daldirip katmanlari birlikte sikistirmak." },
      { wrong: "Her kesitte aynı igne capi ve aynı sureyi kullanmak.", correct: "Kesit boyutu ve donati yogunluguna göre ekipmani ayarlamak." },
      { wrong: "Peteklenmeyi yalnız beton sinifina baglamak.", correct: "Yerlestirme ve vibrasyon kalitesini birlikte sorgulamak." },
      { wrong: "Asiri serbet cikisini iyi vibrasyon sanmak.", correct: "Segregasyon belirtisini fark edip sureyi sinirlamak." },
      { wrong: "Yedek vibrator olmadan buyuk dokume girmek.", correct: "Ariza riskini saha planinin parçası olarak yonetmek." },
      { wrong: "Kalip acma kusurlarini bir sonraki dokumle baglamamak.", correct: "Her kusuru geri bildirim verisine cevirmek." },
    ],
    designVsField: [
      "Projede vibrasyon bir not olarak görünür; sahada ise kesitin gercek dayanim ve yüzey kalitesini belirleyen temel uygulama halkasidir.",
      "Hazir beton kalitesi ne kadar iyi olursa olsun, yetersiz vibrasyonla bu kalite eleman icine aktarilamaz.",
      "Bu nedenle vibrasyon, beton dokumunun tali degil ana muhendislik adimidir.",
    ],
    conclusion: [
      "Vibrasyon doğru ekipman, doğru katman ve doğru sure ile yurutuldugunde peteklenme riskini azaltir, donati cevresinde daha guvenilir yerlestirme saglar ve kalip acma kalitesini belirgin bicimde iyilestirir. Rastgele yapildiginda ise betonun iç kalitesini sansa birakir.",
      "Saha pratiginde en guclu yaklasim, vibrasyonu ustalik refleksi olarak degil, olculebilir bir uygulama protokolu olarak gormektir. Bu yaklasim her katta birikimli kalite uretir.",
    ],
    sources: [...KABA_LEAF_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn206, SOURCE_LEDGER.tsEn13670],
    keywords: ["vibrasyon", "beton yerlestirme", "peteklenme", "segregasyon", "TS EN 13670"],
    relatedPaths: ["kaba-insaat", "kaba-insaat/beton-isleri", "kaba-insaat/beton-isleri/beton-dokumu"],
  },
  {
    slugPath: "kaba-insaat/kalip-isleri/kolon-kalibi",
    kind: "topic",
    quote: "Kolon kalibi, yalnız bir kalip paneli degil; aksin, kesitin ve duseyligin sahada gercege donustugu karar noktasidir.",
    tip: "Kolon kalibini şakul, taban sizdirmazligi ve kusak-tij disiplininden ayirirsan, beton doğru gelse bile kesit doğru cikmayabilir.",
    intro: [
      "Kolon kalibi, betonarme taşıyıcı sistemde düşey eleman geometrisinin sahada kuruldugu ilk kritik imalatlardan biridir. Kolon ekseni, kesit boyutu ve duseylik burada yanlış kurulursa sonraki kiris, doseme ve duvar imalatlari bu hatanin uzerine oturur.",
      "Sahada kolon kalibi basit gorundugu için cogu zaman hizla kapanan bir iş gibi degerlendirilir. Oysa taban takozu, köşe kilidi, kusak-tij araligi, rezervasyonlar ve dokum hizina uygun sıkma disiplini birlikte cozulmelidir. Bu unsurlardan biri eksik oldugunda beton disari kacar, panel acar veya kolon sakulu bozulur.",
      "Bir insaat muhendisi için kolon kalibi, proje aksini sahada doğru okumak ve o geometriyi beton baskisi altinda koruyabilmek anlamina gelir. Kalip kurulumunun kalitesi, yalnız kalip ekibinin degil tüm kat cevriminin guvenilirligini etkiler.",
      "Bu nedenle kolon kalibini, kuruldu mu sorusuyla degil, beton geldikten sonra da geometrisini koruyacak mi sorusuyla denetlemek gerekir.",
    ],
    theory: [
      "Kolon kalibinda en kritik konu, taze beton basincina ragmen panel davranisinin kontrol altinda kalmasidir. Ozellikle yuksek kolonlarda, akiskan betonlarda ve hızlı dokum ritminde tabana yakin bolgelerde yan basinc artar. Bu nedenle tij, kusak ve köşe baglantilari yalnız montaj elemani degil güvenlik unsurudur.",
      "Duseylik de ikinci ana konudur. Kalip panelleri teorik olarak doğru kesitte olsa bile taban oturumu zayif, bağlantı gevsek veya sıkma dengesiz ise kolon ustte baska, altta baska eksende bitebilir. Boyle bir sapma, kiris oturumu ve duvar aksini domino etkisiyle bozar.",
      "Taban sizdirmazligi da göz ardi edilmemelidir. Ozellikle kolon kaidesi veya doseme ustune kurulan kaliplarda alttan serbet kacisi yasanirsa kesit yuzeyi zayiflar ve tabanda peteklenme riski artar. Sızdırmazlık detayi, dokum öncesi kapanmasi gereken ana maddelerden biridir.",
      "Ayrıca kolon kalibinda gomulu elemanlar, filiz cikislari ve perde-kiris birlesimleriyle koordinasyon gerekir. Kalip kurulduktan sonra duzeltilmeye calisilan rezervasyonlar genellikle kesit dogrulugunu bozar.",
    ],
    ruleTable: [
      {
        parameter: "Aks ve kesit kontrolu",
        limitOrRequirement: "Kolon ekseni, kesit boyutu ve diagonal dogrulugu beton öncesi ölçü ile teyit edilmeli",
        reference: "TS EN 13670 uygulama ve tolerans prensipleri",
        note: "Eksenden kacmis kolon, bir katta kalmaz üst imalatlara da tasinir.",
      },
      {
        parameter: "Şakul ve rijitlik",
        limitOrRequirement: "Kusak, tij ve payandalar duseyligi koruyacak sekilde dengeli sikilmali",
        reference: "Saha kalip kabul disiplini",
        note: "Panel varligi ile panel rijitligi aynı sey degildir.",
      },
      {
        parameter: "Taban sizdirmazligi",
        limitOrRequirement: "Kalip ayaginda serbet kacisina izin verecek bosluk birakilmamali",
        reference: "Beton öncesi kontrol listesi",
        note: "En iyi beton bile tabandan kactiginda yüzey kalitesi bozulur.",
      },
      {
        parameter: "Dokum hizi uyumu",
        limitOrRequirement: "Kolon dokum hizi, kalip rijitligi ve ekipman kapasitesiyle uyumlu olmali",
        reference: "Betonlama plani",
        note: "Hiz baskisi kalip zorlanmasini buyutebilir.",
      },
      {
        parameter: "Embed ve rezervasyon koordinasyonu",
        limitOrRequirement: "Gomulu parca ve filiz cikislari kalip kapanmadan once yerinde dogrulanmali",
        reference: "Shop drawing + saha turu",
        note: "Kalip kapandiktan sonra yapilan mudahale kesiti bozar.",
      },
    ],
    designOrApplicationSteps: [
      "Akslari ve kolon köşe noktalarini doseme üzerinde net isaretle; yalnız göz karariyla panel kapatma.",
      "Taban takozu ve sızdırmazlık hazirligini tamamla, ardindan paneli kurup diagonal ve kesit olcusunu al.",
      "Kusak, tij ve payandalari dengeli sık; kolon sakulunu iki dogrultuda ayri kontrol et.",
      "Filiz, gomulu parca, perde-kiris birlesimi ve doseme seviyesi ile cakisan detaylari kalip kapanmadan once netlestir.",
      "Beton öncesi son turda şakul, taban kacagi, tij sikiligi ve üst kot isaretini tekrar kontrol et.",
      "Dokum sirasinda kolon davranisini izle; anormal acilma, serbet kacisi veya şakul kaymasi gorursen akisı yavaslat ve mudahale et.",
    ],
    criticalChecks: [
      "Kolon ekseni ve kesit olculeri shop drawing ile uyumlu mu?",
      "Iki dogrultuda şakul kontrolu aynı anda yapildi mi?",
      "Taban bolgesinde serbet kacagina neden olacak aciklik var mi?",
      "Tij ve kusak araliklari, koselerde yeterli rijitlik sagliyor mu?",
      "Filiz, gomulu parca veya rezervasyonlar kalip kapanmadan once teyit edildi mi?",
      "Dokum sirasinda payanda ve panel davranisini izleyecek sorumlu kisi tanimli mi?",
    ],
    numericalExample: {
      title: "40 x 60 cm ve 3,20 m yuksekligindeki kolonda taze beton yan basinci yorumu",
      inputs: [
        { label: "Kolon kesiti", value: "40 x 60 cm", note: "Orta boy bina kolonu" },
        { label: "Kolon yuksekligi", value: "3,20 m", note: "Kat yuksekligi" },
        { label: "Beton birim hacim agirligi", value: "24 kN/m3", note: "Yaklasik taze beton degeri" },
        { label: "Hedef", value: "Kalip rijitligini ve dokum hizini yorumlamak", note: "Detay tasarımı için" },
      ],
      assumptions: [
        "Dokum akiskan bir betonla ve nispeten hızlı ritimde yapilacaktir.",
        "Yan basinc için en olumsuz yaklasim olarak hidrostatik esdeger yorum kullanilmistir.",
        "Gercek tij araligi ve panel kapasitesi sistem ureticisine göre ayri kontrol edilecektir.",
      ],
      steps: [
        {
          title: "Tabandaki esdeger basinci hesapla",
          formula: "24 x 3,20 = 76,8 kPa",
          result: "Taban seviyesinde teorik yan basinc yaklasik 76,8 kPa mertebesine cikabilir.",
          note: "Gercek saha degeri dokum hizi ve kivama göre daha düşük olabilir; ama kalip guvenligi daha muhafazakar okunmalidir.",
        },
        {
          title: "Basincin ne anlattigini yorumla",
          result: "Tij ve kusak araliklari, ozellikle tabana yakin bolgelerde gevsek birakilamaz.",
          note: "Kolon yuksekligi arttikca küçük montaj ihmalinin etkisi buyur.",
        },
        {
          title: "Dokum hizina karari bagla",
          result: "Kalip rijitligine guvenmeden hızlı dokum yapmak yerine katmanli ve kontrollu ilerlemek daha guvenlidir.",
          note: "Kalip guvenligi yalnız malzeme degil operasyon kararidir.",
        },
      ],
      checks: [
        "Hesap, gercek sistem kapasitesini teyit ihtiyacini ortadan kaldirmaz; fakat risk seviyesini görünür kilar.",
        "Taban bolgesindeki baglantilar üst bölge kadar degil, daha fazla dikkat ister.",
        "Kalip rijitligi ile beton akisi birlikte yonetilmelidir.",
        "Sızdırmazlık detayi, basinc hesabinin sahadaki tamamlayicisidir.",
      ],
      engineeringComment: "Kolon kalibinda sorun cogu zaman panel eksiginden degil, panelin beton basinci altinda nasil davranacaginin hafife alinmasindan dogar.",
    },
    tools: KALIP_TOOLS,
    equipmentAndMaterials: KALIP_EQUIPMENT,
    mistakes: [
      { wrong: "Kolon panelini aks cizgisine bakmadan hizla kapatmak.", correct: "Aks, diagonal ve kesit olcusunu kalip kapanmadan once almak." },
      { wrong: "Şakul kontrolunu tek yuzden yapmak.", correct: "Iki dogrultuda ayri şakul ve lazer kontrolu yapmak." },
      { wrong: "Taban serbet kacagini küçük kusur saymak.", correct: "Sizdirmazligi ana on kabul maddesi olarak gormek." },
      { wrong: "Tij ve kusak sikiligini göz karariyla birakmak.", correct: "Sistematik sıkma ve denetim ritmi kurmak." },
      { wrong: "Gomulu parca ve filizleri beton öncesi son ana birakmak.", correct: "Kalip kapanmadan once koordinasyonu tamamlamak." },
      { wrong: "Dokum sirasinda kalibin davranisini izlememek.", correct: "Akisi gozleyen ve mudahale edecek sorumlu kisi tanimlamak." },
    ],
    designVsField: [
      "Projede kolon 40 x 60 cizilir; sahada ise bu kesiti doğru cikaran sey kalip, sıkma ve ölçü disiplinidir.",
      "Kolon kalibi ne kadar sessiz tamamlaniyorsa, kat geometrisi o kadar guvenle kuruluyor demektir.",
      "Bu nedenle kolon kalibi, kalip isleri icinde en küçük gorunen ama en zincirleme etki ureten imalatlardan biridir.",
    ],
    conclusion: [
      "Kolon kalibi doğru aks, doğru şakul ve doğru rijitlik ile kuruldugunda kat cevriminin geri kalanina saglam referans verir. Zayif kuruldugunda ise kiris, doseme ve duvar imalatlarini aynı anda cezalandiran bir hata zinciri baslatir.",
      "Saha muhendisligi acisindan en doğru yaklasim, kolon kalibini beton gelmeden once tamamlanmis degil, beton baskisi altinda da dogrulugunu koruyacak sistem olarak dusunmektir.",
    ],
    sources: [...KABA_LEAF_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670],
    keywords: ["kolon kalibi", "şakul kontrolu", "kalip rijitligi", "taze beton basinci", "TS EN 13670"],
    relatedPaths: ["kaba-insaat", "kaba-insaat/kalip-isleri", "kaba-insaat/kalip-isleri/kiris-kalibi"],
  },
  {
    slugPath: "kaba-insaat/kalip-isleri/kiris-kalibi",
    kind: "topic",
    quote: "Kiris kalibi, taşıyıcı sistemin basit bir kanali degil; alt kötü, kesiti ve mesnet geometrisini aynı anda yoneten hassas bir imalattir.",
    tip: "Kiris kalibinda birkaç milimetrelik ihmal, donati yerlestirimi, doseme kötü ve görünür tavan hatlarina aynı anda yansiyabilir.",
    intro: [
      "Kiris kalibi, doseme ile kolonlar arasindaki ana yuk aktarim elemaninin sahada geometrik olarak kuruldugu imalattir. Kiris genisligi, yuksekligi, alt kötü ve mesnet baglantilari burada belirlenir. Dolayisiyla bir kiris kalibi yanlış kuruldugunda problem yalnız bir beton yuzeyi sorunu olarak kalmaz; donati yerlestirimi, doseme kalinligi ve bitis kotlarini etkiler.",
      "Sahada kiris kalibinin en zorlayici yani, onu izole bir eleman gibi kuramiyor olmamizdir. Kolonlar, doseme kalibi, tesisat rezervasyonlari, filizler ve cogu zaman sık donatili mesnet bolgeleri kiris kalibi ile aynı anda okunmak zorundadir.",
      "Bu nedenle kiris kalibi, ahşap veya panel elemanlarini bir araya getirmekten ibaret degildir. Mesnetlerde genisleme yapmayan, tabanda sehim biriktirmeyen, yanaklarda acilmayan ve beton öncesi ölçü ile okunabilir kalan bir sistem kurmak gerekir.",
      "Bir insaat muhendisi için kiris kalibi; proje kesitini sahada uygulanabilir hale getirmek, bunu da betonlama esnasinda guvenle korumak demektir.",
    ],
    theory: [
      "Kiris kalibinda iki ana risk vardir: alt kot kaybi ve yanak acilmasi. Alt kot kaybi genellikle yetersiz tali destek, uygun olmayan alt taşıyıcı duzeni veya uzun aciklikta kontrol edilmeyen deformasyondan kaynaklanir. Yanak acilmasi ise tij, kusak ve köşe baglantilarinin zayifligindan ya da hızlı betonlamadan etkilenir.",
      "Mesnet bolgeleri ayrıca kritik noktalardir. Kolon-kiris birlesimlerinde donati yogunlugu arttikca hem kalip toleransi hem beton akisi daha hassas hale gelir. Kesit planlanan genislikten kayarsa donati sikisir, pas payi zorlanir ve vibrasyon kalitesi duser.",
      "Kiris kalibi ile doseme kalibi birlikte davranir. Kiris tabani doğru kotta degilse doseme alt yuzeyi de sasar; tavan hizasi ve asma tavan detaylari ileride farkli duzeltmeler ister. Bu yuzden kiris kalibini sadece betonarme ekibinin sorunu olarak gormek eksik olur.",
      "Ayrıca kiris icinden gecen rezervasyonlar, tesisat askilari veya sonradan acilmasi planlanan bosluklar kalip asamasinda netlesmelidir. Beton gelmeden cozulmeyen her nokta, sonradan kirma veya muhendislik riski olarak geri doner.",
    ],
    ruleTable: [
      {
        parameter: "Kesit ve alt kot",
        limitOrRequirement: "Kiris genisligi, yuksekligi ve alt kötü shop drawing ile olculerek dogrulanmali",
        reference: "TS EN 13670 uygulama ve tolerans prensipleri",
        note: "Bir kere dokulen kiris, sonradan planda gorundugu hale gelemez.",
      },
      {
        parameter: "Alt taşıyıcı ve deformasyon",
        limitOrRequirement: "Aciliga uygun destek ritmi ve rijit alt taşıyıcı duzeni kurulmalı",
        reference: "Kalip tasarim ve uygulama disiplini",
        note: "Kalip saglam gorunse de sehim yapabilir.",
      },
      {
        parameter: "Yanak rijitligi",
        limitOrRequirement: "Yanak paneli, köşe ve bağlantı elemanlari beton basincina karsi yeterli sikilikta olmali",
        reference: "Beton öncesi kabul listesi",
        note: "Yanak acilmasi kesit kaybina ve yüzey bozulmasina yol acar.",
      },
      {
        parameter: "Birlesim ve rezervasyon",
        limitOrRequirement: "Kolon mesnetleri, doseme birlesimi ve rezervasyonlar beton öncesi kapatilmali",
        reference: "Shop drawing + koordinasyon turu",
        note: "Kiris, diger elemanlardan bagimsiz okunamaz.",
      },
      {
        parameter: "Sokum ve tali destek",
        limitOrRequirement: "Kiris alti destekler, betonun erken yas davranisi dikkate alinmadan kaldirilmamali",
        reference: "TS EN 13670 + kat cevrimi plani",
        note: "Erken sokum, catlak ve gereksiz sehim riski uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Kiris aksini, genisligini ve mesnet noktalarini kolon akslariyla birlikte zeminde veya mevcut dosemede isaretle.",
      "Alt taşıyıcı dizilimi ve tali dikme araligini aciklik, panel tipi ve beton yukune göre kur.",
      "Kiris tabanini doğru kota getir, gerekiyorsa aciklik uzunluguna göre kontrollu ters sehim kararini proje ve saha planina bagla.",
      "Yanak panellerini kusak ve tijlerle kapat; koselerde acilma riskini azaltacak sıkma ritmini kur.",
      "Mesnet bolgesi donatisi, rezervasyonlar ve doseme birlesimi ile cakisan noktalari beton öncesi son turda kontrol et.",
      "Dokum sirasinda ozellikle mesnet ve yanak bolgelerinde kalip davranisini izle; deformasyon emaresi varsa dokum ritmini duzelt.",
    ],
    criticalChecks: [
      "Kiris tabani proje kotunda ve eksende mi?",
      "Acilik boyunca alt destek araliklari ve oturmalari yeterli mi?",
      "Yanak panellerinde lokal bombe veya acilma egilimi var mi?",
      "Mesnet bolgelerinde donati sikisikligi kalip kesitini zorluyor mu?",
      "Rezervasyon ve gomulu parcalar beton öncesi dogrulandi mi?",
      "Kiris alti tali desteklerin ne zaman sokulecegi yazili planla tanimlandi mi?",
    ],
    numericalExample: {
      title: "30 x 60 cm ve 6,0 m aciklikli kiriste alt destek yuk yorumu",
      inputs: [
        { label: "Kiris kesiti", value: "30 x 60 cm", note: "Betonarme kiris" },
        { label: "Aciliklik", value: "6,0 m", note: "Orta aciklik" },
        { label: "Taze beton birim hacim agirligi", value: "25 kN/m3", note: "Yaklasik deger" },
        { label: "Alt destek araligi", value: "1,0 m", note: "Ornek saha yerlesimi" },
      ],
      assumptions: [
        "Dokum sirasinda isci ve ekipman etkisi için ilave emniyet payi vardir.",
        "Alt destekler saglam zemine veya yeterli dagitici taban plakasina oturmaktadir.",
        "Gercek sistem kapasitesi uretici verisiyle ayri kontrol edilecektir.",
      ],
      steps: [
        {
          title: "Betonun birim boydaki agirligini hesapla",
          formula: "0,30 x 0,60 x 25 = 4,5 kN/m",
          result: "Kiris yalnız taze beton olarak yaklasik 4,5 kN/m yuk uretir.",
          note: "Bu degere kalip, isci ve ekipman etkisi ayrıca eklenir.",
        },
        {
          title: "Saha payi ile yorumla",
          formula: "4,5 + 1,5 ≈ 6,0 kN/m",
          result: "Kalip ve isci etkisiyle pratik yorumda 6,0 kN/m mertebesi okunabilir.",
          note: "Kesin deger sistem ve çalışma duzenine göre degisir.",
        },
        {
          title: "1 m aralikli destek ritmini oku",
          result: "Her 1 metrelik bolgede alt taşıyıcı sistem en az bu mertebede yuk tasir.",
          note: "Uzun acikliklarda destek oturmasi ve taşıyıcı rijitlik beraber dusunulmelidir.",
        },
      ],
      checks: [
        "Destek araligi hesabi yalnız panel dizisine göre degil yuk mantigina göre okunmalidir.",
        "Zemin oturmasi veya taban plakasinin zayifligi, teorik kapasiteyi sahada anlamsiz kilabilir.",
        "Mesnete yakin bolgelerde yuk etkisi ve donati yogunlugu bir arada degerlendirilmelidir.",
        "Hesap, uygulama öncesi destek duzeninin neden disiplinli olmasi gerektigini görünür kilar.",
      ],
      engineeringComment: "Kiris kalibi cogu zaman aciklik boyunca sessiz durur; ama o sessizlik, ancak altindaki destek duzeni gercekten dogruysa guven verir.",
    },
    tools: KALIP_TOOLS,
    equipmentAndMaterials: KALIP_EQUIPMENT,
    mistakes: [
      { wrong: "Kiris taban kotunu yalnız göz karariyla kurmak.", correct: "Lazer ve aks kontrolu ile alt kötü olcerek sabitlemek." },
      { wrong: "Acilik arttikca destek ritmini degistirmemek.", correct: "Yuk ve deformasyon riskine göre destek planini guncellemek." },
      { wrong: "Mesnet bolgesi donatisini kalip kapandiktan sonra dusunmek.", correct: "Donati sikisikligini kalip kesitiyle birlikte okumak." },
      { wrong: "Yanak panelindeki küçük acilmalari onemsiz gormek.", correct: "Kesit kaymasi yaratacak her acilmayi aninda duzeltmek." },
      { wrong: "Rezervasyonlari beton öncesi kesinlestirmemek.", correct: "Tesisat ve gomulu detaylari kalip turunda kapatmak." },
      { wrong: "Tali destek sokumunu yalnız takvime göre yapmak.", correct: "Betonun erken yas davranisini ve reshoring planini esas almak." },
    ],
    designVsField: [
      "Projede kiris bir cizgi ve kesit bilgisi olarak durur; sahada ise kalip, donati ve betonlama davranisiyla gercek olur.",
      "Kiris kalibindeki küçük kot veya kesit hatasi, daha sonra tavan ve bitis imalatlarinda çok daha görünür hale gelir.",
      "Bu nedenle kiris kalibi, kaba insaatta sadece taşıyıcı sistem degil aynı zamanda bitis dogrulugu uretir.",
    ],
    conclusion: [
      "Kiris kalibi doğru kot, doğru destek ve doğru yanak rijitligiyle kuruldugunda hem taşıyıcı sistem davranisi hem de kat geometrisi için guvenli bir temel olusturur. Zayif kuruldugunda ise hatayi beton sertlestikten sonra fark ettirir.",
      "Pratikte en iyi sonuc, kiris kalibini panel montaji olarak degil, aciklik boyunca yuk ve tolerans yonetimi olarak ele alan ekiplerde alinir.",
    ],
    sources: [...KABA_LEAF_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670],
    keywords: ["kiris kalibi", "alt kot kontrolu", "mesnet bolgesi", "kalip sehim", "TS EN 13670"],
    relatedPaths: ["kaba-insaat", "kaba-insaat/kalip-isleri", "kaba-insaat/kalip-isleri/doseme-kalibi"],
  },
  {
    slugPath: "kaba-insaat/kalip-isleri/doseme-kalibi",
    kind: "topic",
    quote: "Doseme kalibi, yalnız betonu tasiyan gecici iskele degil; katin bitis kotunu, duzlemini ve alt imalat referansini ureten ana platformdur.",
    tip: "Doseme kalibina sadece dikme ormani gibi bakarsan, beton sonrasi tavan duzlemi ve tesisat koordinasyonu tesadufe kalir.",
    intro: [
      "Doseme kalibi, bir katin yatay geometri kalitesini belirleyen temel imalattir. Doseme kalinligi, alt yüzey duzlugu, rezervasyonlarin yeri ve balkon veya islak hacim gibi kritik kot farklari burada sahada gercege donusur. Bu nedenle hatasi en gec fark edilen, ama etkisi en genis yayilan kalip kalemlerinden biridir.",
      "Sahada doseme kalibi cogu zaman genis alan kapladigi için seri iş gibi görünür. Oysa bu genislik, kontrol zorlugu da getirir. Küçük bir kot sapmasi yuzlerce metrekare boyunca yayilabilir; yanlış birakilan bir rezervasyon ise beton sonrasinda pahali mudahalelere neden olabilir.",
      "Bir insaat muhendisi için doseme kalibi; sadece tasima kapasitesi degil, aynı zamanda sonrasinda asma tavan, sap, seramik, parke ve mekanik tesisat koordinasyonunu etkileyen temel referans katmandir.",
      "Bu nedenle doseme kalibi, kurulduktan sonra degil beton öncesi olculerek ve gezilerek kabul edilmesi gereken bir sistem olarak ele alinmalidir.",
    ],
    theory: [
      "Doseme kalibinda yuk davranisi birim alana yayilan taze beton, donati, ekipman ve isci etkilerinden olusur. Genis yuzeylerde sorun cogu zaman tek bir dikmenin kapasitesinden degil, desteklerin oturma farkindan ve sistemin genel rijitliginden kaynaklanir.",
      "Duzlem kalitesi, bitis islerinde en görünür etkilerden birini uretir. Beton sonrasi alt tavanda dalga, lokal cokme veya aksa uymayan kenar hatti olusursa, sonraki ekipler bunu siva, asma tavan veya sap ile telafi etmeye calisir. Bu da maliyet ve sure kaybi demektir.",
      "Doseme kalibi ayrıca rezervasyon ve bosluk yonetimi ister. Merdiven boslugu, saft, tesisat gecisi, balkon kenari veya doseme kot farki gibi detaylar yalnız paftada degil kalip ustunde de net okunmalidir. Aksi halde dokum gunu acele mudahaleler ortaya cikar.",
      "Sokum ve reshoring konusu da onemlidir. Doseme betonu yeterli erken yas davranisina ulasmadan alt destekleri almak, catlak ve gereksiz sehim riskini buyutur. Yani doseme kalibi, kurulumu kadar sokum planiyla da degerlendirilmelidir.",
    ],
    ruleTable: [
      {
        parameter: "Kot ve duzlem",
        limitOrRequirement: "Doseme üst kötü ve alt yüzey referansi lazer veya total station ile sistematik kontrol edilmeli",
        reference: "TS EN 13670 uygulama ve tolerans prensipleri",
        note: "Genis alanda küçük hata, toplam etkiyi buyutur.",
      },
      {
        parameter: "Destek izgara ve taban oturumu",
        limitOrRequirement: "Dikme araliklari, alt taşıyıcı yonu ve taban dagitimi yuk mantigina göre kurulmalı",
        reference: "Kalip tasarim disiplini",
        note: "Saglam gorunen sistem, zayif zeminde oturabilir.",
      },
      {
        parameter: "Rezervasyon ve bosluklar",
        limitOrRequirement: "Saft, merdiven, tesisat ve balkon detaylari beton öncesi görünür ve sabit olmali",
        reference: "Shop drawing + koordinasyon turu",
        note: "Son dakika acilan bosluk, kalip butunlugunu bozar.",
      },
      {
        parameter: "Kenar guvenligi ve kenar dogrusalligi",
        limitOrRequirement: "Doseme kenarlari, parapet ve balkon hatlari dogrusal ve guvenli sekilde kapatilmali",
        reference: "Beton öncesi saha guvenligi ve kalite turu",
        note: "Kenar hatti hem geometri hem iş guvenligi konusudur.",
      },
      {
        parameter: "Sokum ve reshoring",
        limitOrRequirement: "Alt destekler betonun erken yas davranisina göre planli kaldirilmali",
        reference: "TS EN 13670 + kat cevrimi plani",
        note: "Takvim baskisi ile yapilan erken sokum gorunmeyen hasar uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Doseme planini acarak akslari, kalinliklari, rezervasyonlari ve kot farki olan bolgeleri iş programi öncesi netlestir.",
      "Alt taşıyıcı ve dikme izgarasini aciklik, panel tipi ve zemin durumuna göre kur; taban plakalarini ihmal etme.",
      "Kot civileri, lazer referanslari ve kenar hatlari ile tüm yuzeyde ortak bir duzlem dili olustur.",
      "Saft, merdiven, balkon, islak hacim ve tesisat bosluklarini kalip ustunde fiziksel olarak isaretleyip sabitle.",
      "Beton öncesi yuruyus turunda panel birlesimleri, dikme oturmalari, kenar guvenligi ve rezervasyon sabitligini birlikte kontrol et.",
      "Beton sonrasi sokum ve tali destek planini yazili hale getir; bir sonraki kat baskisina göre reshoring disiplinini koru.",
    ],
    criticalChecks: [
      "Genis alanda lazer kot kontrolu noktasal degil ag mantigiyla yapildi mi?",
      "Dikme tabanlari saglam, kuru ve oturma riski düşük bir zemine oturuyor mu?",
      "Rezervasyonlar ve saft bosluklari beton öncesi gercek boy ve konumunda mi?",
      "Balkon ve islak hacim gibi kot farki istenen bolgeler kalipta netlesti mi?",
      "Kenar hatlari ve doseme kalinligi isaretleri tüm ekip tarafindan okunabilir mi?",
      "Sokum ve reshoring karari takvimden degil teknik plandan mi veriliyor?",
    ],
    numericalExample: {
      title: "7,20 x 5,40 m ve 15 cm kalinlikli dosemede birim alan yuk yorumu",
      inputs: [
        { label: "Doseme alani", value: "7,20 x 5,40 m", note: "Ornek kat parçası" },
        { label: "Doseme kalinligi", value: "15 cm", note: "Betonarme doseme" },
        { label: "Taze beton birim hacim agirligi", value: "25 kN/m3", note: "Yaklasik deger" },
        { label: "Dikme izgarasi", value: "1,20 x 1,20 m", note: "Ornek saha ritmi" },
      ],
      assumptions: [
        "Kalip agirligi ve canli yapim yukleri için ilave emniyet payi ayrıca dikkate alinacaktir.",
        "Alt taşıyıcı sistem yukleri dikmelere dengeli aktarmaktadir.",
        "Zemin oturmasi ve taban plaka etkisi sahada ayrıca kontrol edilmistir.",
      ],
      steps: [
        {
          title: "Betonun birim alan yukunu hesapla",
          formula: "0,15 x 25 = 3,75 kN/m2",
          result: "Taze beton, doseme kalibi uzerine yaklasik 3,75 kN/m2 yuk bindirir.",
          note: "Bu hesap yalnız beton agirligidir; kalip ve uygulama yukleri ilave edilmelidir.",
        },
        {
          title: "Saha payi ile toplam yorumu yap",
          formula: "3,75 + 1,50 ≈ 5,25 kN/m2",
          result: "Kalip ve isci etkisiyle pratik yorumda 5,25 kN/m2 mertebesi okunabilir.",
          note: "Gercek emniyet hesabi sistem uretici verisi ile tamamlanmalidir.",
        },
        {
          title: "Bir dikmeye dusen alani yorumla",
          formula: "1,20 x 1,20 = 1,44 m2; 1,44 x 5,25 = 7,56 kN",
          result: "Ornek gridde her dikme yaklasik 7,6 kN mertebesinde yuk tasiyabilir.",
          note: "Bu deger, oturma riski olan zeminde daha kritik hale gelir.",
        },
      ],
      checks: [
        "Genis yuzeyli dosemelerde yuk hesabi tek dikmeye bakarak degil grid mantigiyla okunmalidir.",
        "Dikme kapasitesi kadar altindaki zemin ve taban plaka davranisi da onemlidir.",
        "Rezervasyonlar ve kot farklari, destek izgarasini yerel olarak degistirebilir.",
        "Bu tur hesaplar saha ekibine neden belirli ritimde destek kurulmasi gerektigini aciklar.",
      ],
      engineeringComment: "Doseme kalibinda en tehlikeli hata, genis yüzey nedeniyle küçük deformasyonlari onemsiz sanmaktir.",
    },
    tools: KALIP_TOOLS,
    equipmentAndMaterials: KALIP_EQUIPMENT,
    mistakes: [
      { wrong: "Doseme kalibini genis alan diye göz karari kotlamak.", correct: "Lazer ve ag mantigiyla sistematik kot kontrolu yapmak." },
      { wrong: "Dikme tabanlarini dagitici plaka olmadan zayif zemine oturtmak.", correct: "Taban dagilimini ve oturma riskini bastan cozmek." },
      { wrong: "Saft ve rezervasyonlari beton gunu hatirlamak.", correct: "Tüm bosluklari kalip ustunde önceden sabitlemek." },
      { wrong: "Kenar hattini yalnız iş guvenligi olarak gormek.", correct: "Geometri ve guvenligi birlikte kontrol etmek." },
      { wrong: "Doseme duzlemsizligini sapla telafi ederiz diye dusunmek.", correct: "Duzlem kalitesini kalip asamasinda uretmek." },
      { wrong: "Tali destekleri sirf takvim geregi erken sokmek.", correct: "Reshoring planini teknik kararla yurutmek." },
    ],
    designVsField: [
      "Projede doseme tek bir kalinlik degeri gibi görünür; sahada ise o degeri gercekten ureten unsur kalip izgarasi ve kot disiplinidir.",
      "Doseme kalibi ne kadar dogruysa, sonraki sap, seramik, parke ve asma tavan ekipleri o kadar sessiz calisir.",
      "Bu nedenle doseme kalibi, kaba insaatin gorunmeyen ama tüm bitisleri etkileyen ana referans duzlemidir.",
    ],
    conclusion: [
      "Doseme kalibi doğru yuk okumasi, doğru kot ve doğru rezervasyon yonetimi ile kuruldugunda yapinin hem taşıyıcı guvenine hem de bitis kalitesine doğrudan katki verir. Hatasi buyuk yuzeye yayildigi için duzeltilmesi de her zaman daha pahali olur.",
      "Saha pratiginde en verimli yaklasim, doseme kalibini dikme dikildi, panel kapandi seviyesinde degil, olculebilir geometri ve planli sokum sistemi olarak yonetmektir.",
    ],
    sources: [...KABA_LEAF_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670],
    keywords: ["doseme kalibi", "kot kontrolu", "rezervasyon", "reshoring", "TS EN 13670"],
    relatedPaths: ["kaba-insaat", "kaba-insaat/kalip-isleri", "kaba-insaat/kalip-isleri/kiris-kalibi"],
  },
];
