import { BRANCH_SOURCE_LEDGER, SOURCE_LEDGER } from "../source-ledger";
import type { BinaGuidePageSpec } from "../types";

const KABA_OVERRIDE_SOURCES = [...BRANCH_SOURCE_LEDGER["kaba-insaat"]];

export const kabaInsaatOverrides: BinaGuidePageSpec[] = [
  {
    slugPath: "kaba-insaat/duvar-orme",
    kind: "topic",
    quote: "Dolgu duvar, boslugu kapatan ikincil eleman degil; kaba insaat ile ince isler arasindaki tolerans zincirini tasiyan ana ara katmandir.",
    tip: "Duvar orme isini yalnız metraj ve hiz gibi gormek, siva, doğrama ve tesisat tarafinda katlanarak buyuyen tekrar iş uretir.",
    intro: [
      "Duvar orme fazi, taşıyıcı sistem tamamlandiktan sonra mekanlari ayiran, doğrama bosluklarini netlestiren ve tesisat gecislerini fiziksel olarak belirleyen ana imalat paketidir. Bu nedenle yalnız tugla dizme operasyonu degil, koordinasyon ve tolerans yonetimi isidir.",
      "Sahada duvar imalatindan kaynaklanan sorunlarin buyuk kismi malzemenin kendisinden degil, aks kaymasi, bozuk ilk sira, plansiz tesisat kirimi ve yanlış bosluk kararlarindan dogar. Bu sorunlar duvar bitince degil, siva, seramik ve pencere montaji geldikce buyur.",
      "Bir insaat muhendisi için duvar orme; malzeme secimi, aks kontrolu, lento, ankraj, tesisat koordinasyonu ve sonraki ekiplere temiz bir yüzey birakma meselesidir.",
    ],
    theory: [
      "Dolgu duvarlar taşıyıcı ana sistem elemani olmasalar da depremde hasar davranisi, kullanıcı guvenligi ve bitirme kalitesi üzerinde belirleyicidir. Duvarin kolon ve kirislerle kurdugu temas, rötresi ve farkli deformasyon davranisi birlikte okunmalidir.",
      "Duvar kalitesi ilk sirada kurulur. Ilk sirada yapilan kot veya eksen hatasi, üst siralarda buyur ve sonunda siva kalinligina, doğrama bosluguna ve mahal netine zarar verir. Bu nedenle duvarcilikta hizdan once referans doğrudur.",
      "Ayrıca duvar orme, tesisat ekibiyle doğrudan koordinasyon ister. Sonradan gelişi güzel kirilan kanal ve buat bosluklari duvar performansini ve yüzey surekliligini zayiflatir.",
      "Bu nedenle dolgu duvar imalati, mimari planla saha gercegini birbirine ceviren kritik uygulama faslidir.",
    ],
    ruleTable: [
      {
        parameter: "Aks ve dusaylik",
        limitOrRequirement: "Duvar aksa oturmali, şakul ve mastar kontrolu surekli yapilmali",
        reference: "Saha kalite plani",
        note: "Eksenden kacmis duvar, sonraki tüm imalatlari iter.",
      },
      {
        parameter: "Bosluk ve lento karari",
        limitOrRequirement: "Kapı-pencere bosluklari ile lento detaylari doğrama ve üst yuk mantigiyla uyumlu olmali",
        reference: "Mimari detay + saha kabul disiplini",
        note: "Kaba bosluk karari duvar biterken degil, baslarken net olmalidir.",
      },
      {
        parameter: "Birlesim davranisi",
        limitOrRequirement: "Betonarme ile temaslarda catlak riskini azaltacak detay uygulanmali",
        reference: "Saha birlesim pratiği",
        note: "Kolon-duvar temaslari en zayif cizgilerdendir.",
      },
      {
        parameter: "Tesisat koordinasyonu",
        limitOrRequirement: "Kanal ve gecisler plansiz kirma yerine önceden belirlenmeli",
        reference: "Koordinasyon matrisi",
        note: "Duvar biterken tesisat için zayiflatilmis olmamalidir.",
      },
    ],
    designOrApplicationSteps: [
      "Malzeme tipini, duvar kalinligini ve mahal bazli ihtiyaci netlestir.",
      "Aks, bosluk ve tesisat gecislerini duvar ormeden once isaretle.",
      "Ilk sirayi kot ve referans ipiyle kur, sonradan telafi etmeye çalışma.",
      "Lento, kısa duvar parçası ve betonarme temas noktalarini detayina göre tamamla.",
      "Tesisat ekibiyle buat, kanal ve cihaz yerlerini duvar ilerlerken birlikte kapat.",
      "Siva ve doğrama öncesi duvari mastar, bosluk ve yüzey sürekliligi acisindan kabul et.",
    ],
    criticalChecks: [
      "Ilk sira doğru kot ve doğru eksende mi?",
      "Kapı-pencere bosluklari net doğrama kararina uygun mu?",
      "Plansiz tesisat kirimi ihtiyaci doguyor mu?",
      "Kolon ve kiris temaslarinda catlak riski yaratan zayif hat var mi?",
      "Siva kalinligini gereksiz buyutecek dalga veya saskinlik olustu mu?",
    ],
    numericalExample: {
      title: "İç kapı boslugunda kaba ölçü yorumu",
      inputs: [
        { label: "Kapı net geçiş", value: "90 cm", note: "İç kapı hedefi" },
        { label: "Kasa ve montaj payi", value: "3-5 cm", note: "Kasa + ayar toleransi" },
        { label: "Siva etkisi", value: "Her yanda 1-1,5 cm", note: "Ornek uygulama" },
        { label: "Hedef kaba bosluk", value: "93-95 cm", note: "Saha kabul bandi" },
      ],
      assumptions: [
        "Kasa tipi ve duvar kalinligi önceden secilmistir.",
        "Siva kalinligi tipik uygulama bandindadir.",
        "Duvar aksa tam oturtulmustur.",
      ],
      steps: [
        {
          title: "Bosluk bandini yorumla",
          result: "90 cm net kapı için 93-95 cm kaba bosluk saha için makul kabul araligidir.",
          note: "Sifir tolerans doğrama montajini zorlar, fazla bosluk ise dolgu ihtiyaci dogurur.",
        },
        {
          title: "Siva etkisini ekle",
          result: "Duvar yalnız bosluk genisligiyle degil, siva sonrasi net gecisle de kontrol edilmelidir.",
          note: "Siva payi unutulursa net geçiş daralir.",
        },
        {
          title: "Aks etkisini bagla",
          result: "Bosluk doğru olsa bile duvar ekseni kayiksa kapı ortalamasi ve mahal neti bozulur.",
          note: "Bu nedenle sadece santimetre degil merkezleme de kontrol edilmelidir.",
        },
      ],
      checks: [
        "Bosluk kontrolu siva sonrasi net ile birlikte okunmalidir.",
        "Kapı boslugu yalnız genislik degil eksen olarak da kontrol edilmelidir.",
        "Lento ve kenar parcalari zayif kalmamalidir.",
        "Doğrama montaji için zorlama yaratacak duzensizlikler erkenden duzeltilmelidir.",
      ],
      engineeringComment: "Duvar ormede 2-3 cm'lik hata, doğrama montajinda santiyenin en pahali santimetrelerine donusebilir.",
    },
    tools: [
      { category: "Cizim", name: "Mimari aks ve mahal paftalari", purpose: "Duvar eksenlerini ve bosluklari doğru okumak." },
      { category: "Koordinasyon", name: "Tesisat geçiş matrisi", purpose: "Sonradan kirma ihtiyacini azaltmak." },
      { category: "Ölçüm", name: "Lazer terazi, şakul ve mastar seti", purpose: "Duvar duseyligi ve yüzey surekliligini hızlı kontrol etmek." },
      { category: "Kontrol", name: "Mahal bazli duvar teslim cizelgesi", purpose: "Siva ve doğrama öncesi kabul kalitesini standartlastirmak." },
    ],
    equipmentAndMaterials: [
      { group: "Uygulama", name: "Mala, ip, mastar ve lastik tokmak", purpose: "Blok veya tugla elemanlari kontrollu yerlestirmek.", phase: "Duvar orumu" },
      { group: "Ölçüm", name: "Şakul, lazer ve metre", purpose: "Aks, duseylik ve bosluk kontrolu yapmak.", phase: "Surekli" },
      { group: "Birlesim", name: "Ankraj elemanlari ve lento cozumleri", purpose: "Aciklik ve betonarme temaslarini guvenli tamamlamak.", phase: "Detay" },
      { group: "Koordinasyon", name: "Tesisat kilif ve geçiş parcalari", purpose: "Plansiz kirma yerine önceden geçiş birakmak.", phase: "Koordinasyon" },
    ],
    mistakes: [
      { wrong: "Ilk sirayi göz karari kurmak.", correct: "Ilk sirayi tüm duvarin referansi olarak olcerek kurmak." },
      { wrong: "Bosluk kararlarini duvar biterken vermek.", correct: "Kapı ve pencere olculerini duvar baslamadan netlestirmek." },
      { wrong: "Tesisat için sonradan gelişi güzel kanal kirimak.", correct: "Gecisleri duvar ilerlerken planlamak." },
      { wrong: "Kolon-duvar temasini detay kabul etmemek.", correct: "Catlak riskini azaltacak birlesim disiplini kurmak." },
      { wrong: "Siva ekibinin duzeltecegini dusunerek dalgayi kabul etmek.", correct: "Duvari kendi asamasinda doğru teslim etmek." },
    ],
    designVsField: [
      "Projede duvar bir tarama alani gibi görünür; sahada ise doğrama, tesisat ve siva toleranslarinin tam ortasinda durur.",
      "Iyi duvar imalati sessizdir; kötü duvar ise kendini en çok bir sonraki ekip geldiginde belli eder.",
    ],
    conclusion: [
      "Duvar orme fazi doğru aks, doğru bosluk ve doğru koordinasyonla yurudugunde ince islerin kalitesini belirgin sekilde yukseltir.",
      "Yanlış yonetildiginde ise saha tekrar islerinin en yaygin kaynagindan birine donusur.",
    ],
    sources: [...KABA_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670, SOURCE_LEDGER.yanginYonetmeligi],
    keywords: ["duvar orme", "dolgu duvar", "kapı boslugu", "tesisat koordinasyonu", "saha toleransi"],
  },
  {
    slugPath: "kaba-insaat/duvar-orme/tugla-duvar",
    kind: "topic",
    quote: "Tugla duvar, ucuz ve tanidik bir imalat gibi görünür; ama iyi uygulanmadiginda en çok dalga, catlak ve doğrama sorunu üreten dolgu tiplerinden biri olur.",
    tip: "Tuglada sorun genelde malzemenin kendisinden degil, islatici disiplin, derz duzeni ve plansiz kirimdan kaynaklanir.",
    intro: [
      "Tugla duvar, konut ve ticari yapılarda uzun yillardir kullanilan en tanidik dolgu duvar sistemlerinden biridir. Kolay temin edilmesi ve alisilan uygulama bicimi sebebiyle hızlı karar verilir; fakat bu tanidiklik cogu santiyede kalite disiplinini zayiflatir.",
      "Tugla duvarlarda en çok karsilasilan problemler; duvar yuzeyindeki dalgalar, aciklik kenarlarinda kirik parcalar, kolon temaslarinda catlak ve plansiz tesisat kirimidir. Bunlarin cogu malzeme seciminden degil, duvar orme sirasinin zayif kurgulanmasindan dogar.",
      "Bir insaat muhendisi için tugla duvar, klasik bir imalat olmasina ragmen aks, bosluk, derz ve sonraki ekip gecisleri acisindan ciddiyetle yonetilmesi gereken bir saha isidir.",
    ],
    theory: [
      "Tugla, gorece daha küçük birim elemanlardan olustugu için derz duzeni tüm yüzey davranisinda belirleyici olur. Yatay ve dusay derzlerdeki tutarsizlik, duvarin kendisini de siva yukunu de bozar.",
      "Tugla duvarlarda su emme davranisi da uygulama kalitesini etkiler. Asiri kuru veya kontrolsuz islatilan birimlerle yapılan orgu, harc davranisini ve aderansi zayiflatabilir.",
      "Ayrıca tugla ile betonarme elemanların farkli deformasyon davranisi, ozellikle kolon ve kiris temaslarinda catlak riskini artirir. Bu nedenle birlesim detaylari ve açiklik köşe destekleri birlikte dusunulmelidir.",
      "Bu sebeple tugla duvar, ustalik aliskanligi kadar ölçu disiplini isteyen klasik ama hassas bir imalattir.",
    ],
    ruleTable: [
      {
        parameter: "Derz duzeni",
        limitOrRequirement: "Yatay ve dusay derzler ritmik ve kontrollu ilerlemeli",
        reference: "Saha uygulama disiplini",
        note: "Derz dengesizligi dalga ve dayanim problemi uretir.",
      },
      {
        parameter: "Bosluk ve kesim",
        limitOrRequirement: "Aciklik kenarlarinda rastgele kirik parca yerine kontrollu kesim uygulanmali",
        reference: "Mimari bosluk detayi",
        note: "Kirik ve dar parçalar aciklik etrafinda zayif hat olusturur.",
      },
      {
        parameter: "Tesisat gecisi",
        limitOrRequirement: "Duvar biter bitmez kirim gerektirmeyecek koordinasyon kurulmalı",
        reference: "Şantiye koordinasyon plani",
        note: "Tugla duvarda plansiz kirim hızlı hasar uretir.",
      },
      {
        parameter: "Birlesim davranisi",
        limitOrRequirement: "Betonarme temaslarinda catlak riskini azaltacak uygulama benimsenmeli",
        reference: "Saha detay pratiği",
        note: "Malzeme degisim hattı kritik risk cizgisidir.",
      },
    ],
    designOrApplicationSteps: [
      "Tugla cinsini, duvar kalinligini ve aciklik kararlarini mahal bazinda netlestir.",
      "Ilk sirayi kot ve referans ipiyle kur, köşe bloklarini once sabitle.",
      "Derz ritmini bozmadan ilerle, aciklik kenarlarinda kontrollu kesim kullan.",
      "Kolon ve kiris temaslarinda zayif hatlari azaltacak detayi uygula.",
      "Tesisat gecislerini plansiz kirim gerektirmeyecek sekilde orme sirasinda koordine et.",
    ],
    criticalChecks: [
      "Derz kalinligi ve ritmi duvar boyunca tutarli mi?",
      "Kapı ve pencere kenarlarinda dar, kirik veya zayif parcaciklar var mi?",
      "Tesisat için duvar biter bitmez kirma ihtiyaci doguyor mu?",
      "Kolon temas hatlari siva altinda catlak riski tasiyor mu?",
      "Siva kalinligini gereksiz buyuten dalga oluştu mu?",
    ],
    numericalExample: {
      title: "100 cm pencere boslugunda kenar parca yorumu",
      inputs: [
        { label: "Pencere kaba boslugu", value: "100 cm", note: "Ornek bosluk" },
        { label: "Tugla modul varsayimi", value: "19 cm + derz", note: "Yaklasik saha modulu" },
        { label: "Hedef", value: "Kenarda zayif dar parca birakmamak", note: "Saha kalitesi için" },
      ],
      assumptions: [
        "Bosluk kenarlari kontrollu kesimle tamamlanabilir.",
        "Doğrama olcusu kesinlesmistir.",
        "Lento ve denizlik detaylari hazirdir.",
      ],
      steps: [
        {
          title: "Modul etkisini oku",
          result: "100 cm bosluk, tam modül yerine kesimli parca gerektirebilir.",
          note: "Bu kesimler rastgele kirma ile degil kontrollu hazırlikla yapılmalıdır.",
        },
        {
          title: "Kenar parca riskini yorumla",
          result: "Çok dar kenar parçası bırakılırsa aciklik etrafinda kirilma ve catlak riski artar.",
          note: "Bosluk merkezi veya modul dizisi gerekirse revize edilmelidir.",
        },
        {
          title: "Doğrama baglantisini ekle",
          result: "Bosluk yalnız tugla modulu ile degil, doğrama montaj toleransi ile birlikte okunmalidir.",
          note: "Bosluk doğru ama montaj zor ise proje sahada yine problem üretir.",
        },
      ],
      checks: [
        "Acilik kenarlarinda zayif dar parca birakilmamalidir.",
        "Kirik malzeme ile bosluk tamamlanmamali, kontrollu kesim tercih edilmelidir.",
        "Doğrama toleransi modul kararina dahil edilmelidir.",
        "Lento ve kenar sürekliligi birlikte okunmalidir.",
      ],
      engineeringComment: "Tugla duvarda açiklik etrafindaki son 5-10 cm, çoğu zaman duvarin geri kalanindan daha kritik davranir.",
    },
    tools: [
      { category: "Cizim", name: "Mimari aks ve bosluk paftalari", purpose: "Kapı ve pencere bosluklarini doğru modulle kurmak." },
      { category: "Ölçüm", name: "Ip, şakul ve mastar seti", purpose: "Derz ritmi ve duzlem kalitesini kontrol etmek." },
      { category: "Koordinasyon", name: "Tesisat geçiş listesi", purpose: "Plansiz kirma ihtiyacini azaltmak." },
      { category: "Kontrol", name: "Mahal bazli duvar kabul cizelgesi", purpose: "Siva öncesi duvarı standarda baglamak." },
    ],
    equipmentAndMaterials: [
      { group: "Malzeme", name: "Tugla birimleri ve uygun orgu harci", purpose: "Duvarin ana gövdesini ve derz davranisini olusturmak.", phase: "Duvar orumu" },
      { group: "Ölçüm", name: "Şakul, lazer ve metre", purpose: "Duzey, aks ve bosluk kontrolu yapmak.", phase: "Surekli" },
      { group: "Kesim", name: "Kontrollu kesim ekipmani", purpose: "Acilik kenarlarinda düzgün parca uretmek.", phase: "Aciklik detaylari" },
      { group: "Detay", name: "Lento ve ankraj yardimci elemanlari", purpose: "Acilik ve betonarme temaslarinda güvenli detay olusturmak.", phase: "Detay" },
    ],
    mistakes: [
      { wrong: "Derz ritmini göz karari ilerletmek.", correct: "Her sira için ip ve referansla ilerlemek." },
      { wrong: "Aciklik kenarlarini kirik malzemeyle tamamlamak.", correct: "Kontrollu kesim ve düzenli modul kullanmak." },
      { wrong: "Tesisat için duvar bittikten sonra rastgele kirimak.", correct: "Gecisleri duvar ilerlerken planlamak." },
      { wrong: "Kolon temasini onemsiz gormek.", correct: "Malzeme degisim hattini catlak riski olarak ele almak." },
      { wrong: "Siva ile düzelecegini düşünerek dalgayi kabul etmek.", correct: "Duvari kendi asamasinda duz teslim etmek." },
    ],
    designVsField: [
      "Tugla duvar kagit üzerinde basit bir tarama gibi görünür; sahada ise her derz ve her aciklik kenari kalite farki uretir.",
      "Klasik bir imalat olmasi, tuglayi önemsiz yapmaz; aksine en çok hafife alinan ama en çok sorun üreten kalemlerden biri yapar.",
    ],
    conclusion: [
      "Tugla duvar doğru derz ritmi, kontrollu bosluk ve iyi koordinasyonla yapildiginda guvenilir ve temiz bir dolgu duvar cozumü sunar.",
      "Disiplinsiz uygulandiginda ise ince islerde en çok düzeltme gerektiren yüzeylerden birine donusur.",
    ],
    sources: [...KABA_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670],
    keywords: ["tugla duvar", "dolgu duvar", "derz duzeni", "kapı boslugu", "saha toleransi"],
  },
  {
    slugPath: "kaba-insaat/duvar-orme/ytong-gazbeton",
    kind: "topic",
    quote: "Gazbeton duvar, hafif ve hızlı oldugu için degil; doğru kesim ve ince derz disiplini kuruldugunda gerçekten avantaj üretir.",
    tip: "Gazbetonda en yaygin hata, malzemenin hafifligine guvenip ölçü ve yüzey disiplinini gevsetmektir.",
    intro: [
      "Gazbeton bloklar, hafiflikleri, issil performanslari ve hızlı uygulanabilirlikleri nedeniyle konut ve ticari yapılarda yaygin tercih edilir. Ancak bu avantajlar sadece uygun blok secimi ve doğru uygulama disiplini kuruldugunda gercek sonuca donusur.",
      "Sahada gazbeton duvarlarda gorulen hatalarin buyuk bolumu; bozuk ilk sira, düzensiz ince derz, plansiz tesisat kanali ve yetersiz bosluk detaylarindan kaynaklanir. Malzeme hafif oldugu için hata tolere ediyormus gibi görünür; gerçekte ise yüzey ve geometri hatalarini daha görünur kilar.",
      "Bir insaat muhendisi için gazbeton duvar, yalnız hafif dolgu secimi degil; termal, geometrik ve saha koordinasyonu performansini aynı anda yöneten bir uygulama paketidir.",
    ],
    theory: [
      "Gazbeton sistemleri ince derz mantigi ile çalışır. Bu nedenle klasik kalin harçlı duvar alışkanligini aynen taşımak doğru değildir; asıl kalite, düzgün kesilmiş blok ve kontrollü ince yatay-düşey birleşimle gelir.",
      "Malzemenin hafifligi üst yapı yükünü ve lojistiği rahatlatır; ancak bu hafiflik plansiz kirima ve zayif kenar parça kullanımına açık bir davranis da uretebilir. Özellikle pencere altları, kısa duvar parçaları ve tesisat chase'leri dikkat ister.",
      "Gazbetonun issil avantajı yalnız malzemenin kendisinden gelmez. Duvarın betonarme ile birleşimi, doğrama detayi ve sıva sürekliliği bozulursa beklenen kabuk performansi zayiflar.",
      "Bu nedenle gazbeton duvar, hızlı imalat kadar net detay gerektiren bir sistem olarak ele alinmalidir.",
    ],
    ruleTable: [
      {
        parameter: "Ince derz duzeni",
        limitOrRequirement: "Bloklar düzgün kesim ve ince derz mantigiyla yerlestirilmeli",
        reference: "Uygulama disiplini + saha kalite plani",
        note: "Klasik kalin harç alışkanligi gazbeton kalitesini bozar.",
      },
      {
        parameter: "Isil ve kabuk davranisi",
        limitOrRequirement: "Doğrama, kolon ve duvar birleşimleri TS 825 mantigiyla okunmali",
        reference: "TS 825 + saha detay karari",
        note: "Malzemenin tek basina iyi olmasi kabuk detayini kurtarmaz.",
      },
      {
        parameter: "Bosluk ve kesim disiplini",
        limitOrRequirement: "Acilik kenarlari ve kısa duvar parcaciklari kontrollu cozulmeli",
        reference: "Mimari detay plani",
        note: "Kısa ve zayif parcalar catlak ve kirilma riskini buyutur.",
      },
      {
        parameter: "Tesisat koordinasyonu",
        limitOrRequirement: "Kanal ve buat yerleri plansiz oyma gerektirmeyecek sekilde belirlenmeli",
        reference: "Koordinasyon matrisi",
        note: "Gazbeton plansiz oyuldugunda yerel zayiflik hizla artar.",
      },
    ],
    designOrApplicationSteps: [
      "Blok kalinligini, mahal kullanimini ve kabuk davranisini birlikte degerlendir.",
      "Ilk sirayi tesviye ederek ve referans ipiyle kur, tüm duvarı buna bagla.",
      "Kesimleri düzgün ekipmanla yap, kenar parcalarini rastgele kirma ile çözme.",
      "Doğrama bosluklari, tesisat chase'leri ve betonarme temaslarini duvar ilerlerken netlestir.",
      "Siva ve doğrama öncesi duvarı duzlem, termal birleşim ve bosluk kalitesi acisindan kabul et.",
    ],
    criticalChecks: [
      "Ilk sira duzlem hatasi butun duvara yayiliyor mu?",
      "Blok kesimleri kontrollu ve temiz mi?",
      "Kısa duvar parcaciklari veya pencere alti zayif bölgeler olustu mu?",
      "Doğrama ve kolon birleşimlerinde ısıl/zayif hat riski var mi?",
      "Tesisat için plansiz oyma ihtiyaci doguyor mu?",
    ],
    numericalExample: {
      title: "25 cm gazbeton duvarda pencere alti parca yorumu",
      inputs: [
        { label: "Duvar kalinligi", value: "25 cm", note: "Dış duvar ornegi" },
        { label: "Pencere denizlik alti yukseklik", value: "85 cm", note: "Mimari karar" },
        { label: "Blok yuksekligi varsayimi", value: "25 cm", note: "Tipik modul" },
        { label: "Hedef", value: "Zayif kısa parca olusturmamak", note: "Catlak riskini azaltmak" },
      ],
      assumptions: [
        "Pencere kötü revize edilebilir durumdadir.",
        "Blok modulu standart seriyle uyumludur.",
        "Denizlik ve sıva kararlari projede nettir.",
      ],
      steps: [
        {
          title: "Modul etkisini oku",
          result: "85 cm yukseklik, tam blok moduluyle tam oturmayabilir ve kısa parça ihtiyaci doğurabilir.",
          note: "Kısa parca ozellikle pencere altinda zayif cizgi uretir.",
        },
        {
          title: "Revizyon imkanini değerlendir",
          result: "Pencere kotunda küçük düzenleme veya blok dizisinde planli kesim ile daha dengeli çözum kurulabilir.",
          note: "Erken karar, sahadaki catlak riskini azaltir.",
        },
        {
          title: "Kabuk performansini bagla",
          result: "Pencere alti detay yalnız blok dizisi degil, denizlik ve ısıl köprü davranisiyla birlikte okunmalidir.",
          note: "Gazbetonun issil avantaji detayda kaybedilebilir.",
        },
      ],
      checks: [
        "Kısa pencere alti parçası zorunluysa detay güçlendirilmelidir.",
        "Modul karari doğrama ve denizlikle birlikte verilmelidir.",
        "Temiz kesim kalitesi siva yukunu azaltir.",
        "Detay yalnız geometri degil termal davranis olarak da okunmalidir.",
      ],
      engineeringComment: "Gazbetonun avantaji hafifliginde degil; o hafifligi boşa cikarmayan temiz detay disiplini kurabilmektedir.",
    },
    tools: [
      { category: "Cizim", name: "Mimari detay ve doğrama paftalari", purpose: "Gazbetonun bosluk ve kabuk detaylarini netlestirmek." },
      { category: "Ölçüm", name: "Lazer, mastar ve ince derz kontrol seti", purpose: "Duzlem ve derz kalitesini izlemek." },
      { category: "Koordinasyon", name: "Tesisat chase listesi", purpose: "Plansiz oyma ihtiyacini azaltmak." },
      { category: "Kontrol", name: "Kabuk ve doğrama birlesim checklisti", purpose: "Isil performans zafiyetlerini erken gormek." },
    ],
    equipmentAndMaterials: [
      { group: "Malzeme", name: "Gazbeton bloklar ve ince derz yapıştırıcı", purpose: "Hafif ve düzgün bir dolgu duvar sistemi kurmak.", phase: "Duvar orumu" },
      { group: "Kesim", name: "Gazbeton kesim ekipmani", purpose: "Temiz ve kontrollu blok kesimleri yapmak.", phase: "Kesim ve detay" },
      { group: "Ölçüm", name: "Lazer, şakul ve mastar", purpose: "Duzlem ve aks kalitesini korumak.", phase: "Surekli" },
      { group: "Detay", name: "Doğrama ve birleşim yardimci elemanlari", purpose: "Pencere, kolon ve denizlik detaylarini temiz tamamlamak.", phase: "Detay" },
    ],
    mistakes: [
      { wrong: "Gazbetonu klasik kalin harçlı duvar gibi uygulamak.", correct: "Ince derz ve temiz kesim mantigiyla ilerlemek." },
      { wrong: "Hafif malzemeye guvenip ilk sira dogrulugunu ihmal etmek.", correct: "Ilk sirayi tüm duvarin referansi olarak hassas kurmak." },
      { wrong: "Pencere altinda zayif kısa parça birakmak.", correct: "Modul ve kot kararini bu riski azaltacak sekilde düzenlemek." },
      { wrong: "Tesisat için duvar bittikten sonra plansiz oyma yapmak.", correct: "Chase kararlarini önceden netlestirmek." },
      { wrong: "Gazbetonun issil avantajini detaylarla boşa cikarmak.", correct: "Doğrama ve kolon birleşimlerini kabuk mantigiyla cozumlemek." },
    ],
    designVsField: [
      "Gazbeton projede hafif dolgu tercihi gibi görünür; sahada ise duzlem, kesim ve doğrama detayi kalitenin gercek belirleyicisidir.",
      "Doğru uygulandiginda siva ve doğrama ekiplerine temiz bir yüzey birakir; yanlış uygulandiginda hafif olmasina ragmen agir tekrar iş uretir.",
    ],
    conclusion: [
      "Gazbeton duvar doğru ince derz disiplini, temiz kesim ve kabuk detayi ile uygulandiginda hızlı ve nitelikli bir dolgu duvar çözumu sunar.",
      "Bu disiplin kurulmadiginda ise avantaj olarak görülen hafiflik, sahada zayif detay ve tekrar iş olarak geri döner.",
    ],
    sources: [...KABA_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.ts825, SOURCE_LEDGER.tsEn13670],
    keywords: ["gazbeton", "ytong", "ince derz", "dolgu duvar", "TS 825"],
  },
  {
    slugPath: "kaba-insaat/duvar-orme/briket",
    kind: "topic",
    quote: "Briket duvar, sahada hızlı yukselen ama detaysiz birakildiginda en hızlı deforme olan dolgu duvar tiplerinden biridir.",
    tip: "Briketi kaba malzeme diye gorup ölçü, bosluk ve siva yukunu ikinci plana atmak, ince islerde bedeli buyuk bir hata zinciri üretir.",
    intro: [
      "Briket duvarlar, ozellikle ekonomik ve hızlı dolgu ihtiyacinin one ciktigi yapilarda sık kullanilir. Ancak bu tercih, duvarin teknik olarak daha az dikkat gerektirdigi anlamina gelmez; aksine, yüzey duzgunlugu ve bosluk disiplini daha kritik hale gelebilir.",
      "Sahada briket duvarlarda en sık görülen problemler; düzensiz derz, asiri siva ihtiyaci, zayif aciklik kenarlari ve plansiz tesisat kirimidir. Briketin daha kaba dokuya sahip olmasi, sahada 'nasil olsa sivayla toparlanir' yanilgisini güçlendirir.",
      "Bir insaat muhendisi için briket duvar, ekonomik bir cozum olsa da tolerans, yüzey ve koordinasyon bakımından yakın takip gerektiren bir dolgu duvar kalemidir.",
    ],
    theory: [
      "Briket duvarlarda birim eleman toleransi ve yüzey yapisi, duvar düzlemini diğer blok sistemlere göre daha hızlı bozabilir. Bu nedenle ilk sıra doğruluğu ve hat boyunca kontrol daha fazla önem kazanır.",
      "Malzemenin gözenekli ve kaba yüzeyi siva aderansı için avantaj sağlayabilir; ancak duvarın dalgalı örülmesi halinde bu avantaj büyük bir siva metrajına ve dengesiz yüzeye döner.",
      "Acilik kenarlarında zayif parçalar, kolon temaslarında çatlak çizgileri ve gelişigüzel kırılmış tesisat kanalları briket duvarda daha görünür hasar davranışı üretebilir.",
      "Bu nedenle briket duvar, 'kaba' bir malzeme olarak değil, düzgün teslim edilmesi gereken hassas bir yüzey altyapısı olarak değerlendirilmelidir.",
    ],
    ruleTable: [
      {
        parameter: "Duzlem ve tolerans",
        limitOrRequirement: "Duvar yüzeyi siva yükünü aşırı artırmayacak doğrulukta örülmeli",
        reference: "Saha kalite plani",
        note: "Briket duvarda dalga kabul eşiği daha erken problem üretir.",
      },
      {
        parameter: "Acilik ve kenar parcalar",
        limitOrRequirement: "Kapı-pencere etrafında zayif, kirik ve dar parçalar bırakılmamalı",
        reference: "Mimari bosluk detayi",
        note: "Briketin kaba yapisi bu bölgeleri daha kırılgan hale getirir.",
      },
      {
        parameter: "Tesisat kirimi",
        limitOrRequirement: "Kanal ve buat yerleri duvar örümü sırasında planlanmalı",
        reference: "Koordinasyon matrisi",
        note: "Sonradan gelişigüzel kırılan briket, yüzey bütünlüğünü hızla bozar.",
      },
      {
        parameter: "Betonarme birlesim",
        limitOrRequirement: "Kolon ve kiris temaslarında çatlak riskini azaltacak detay benimsenmeli",
        reference: "Saha detay pratiği",
        note: "Malzeme degisim cizgisi yine en kritik bölgedir.",
      },
    ],
    designOrApplicationSteps: [
      "Briket ebat ve duvar kalinligini mahal ihtiyacina göre netlestir.",
      "Ilk sirayi kot, referans ipi ve köşe doğruluğu ile kur.",
      "Duvar hatlarini sık mastar kontrolüyle ilerlet, siva ile telafi mantığına kayma.",
      "Acilik kenarları ve kısa duvar parçalarını kontrollü çöz, zayif parça birakma.",
      "Tesisat ekibiyle kanal ve cihaz yerlerini duvar ilerlerken kapat.",
      "Siva öncesi duvarı yüzey, boşluk ve çatlak riski acisindan kabul et.",
    ],
    criticalChecks: [
      "Duvar dalgası siva kalinligini gereksiz arttiriyor mu?",
      "Kapı-pencere kenarlarinda zayif parcaciklar var mi?",
      "Plansiz kirim ihtiyaci duvar tamamlanmadan fark edildi mi?",
      "Kolon temaslarında zayif cizgi veya ayrılma belirtisi var mi?",
      "Mahal netini bozan aks kaymalari oluştu mu?",
    ],
    numericalExample: {
      title: "20 m uzunlukta briket duvarda duzlem sapmasi yorumu",
      inputs: [
        { label: "Duvar uzunlugu", value: "20 m", note: "Koridor hattı" },
        { label: "Mastar kontrol noktasi", value: "Her 2 m", note: "Saha takip ritmi" },
        { label: "Olculen lokal sapma", value: "8-10 mm", note: "Bazi noktalarda" },
        { label: "Hedef", value: "Siva yukunu dengede tutmak", note: "Yüzey kalitesi" },
      ],
      assumptions: [
        "Duvar ilk sirası genel olarak doğru kurulmuştur.",
        "Siva kalinligi tipik mahal standardındadır.",
        "Saha ekibi duvarı ilerlerken düzeltme yapabilecek durumdadır.",
      ],
      steps: [
        {
          title: "Sapmayi oku",
          result: "8-10 mm'lik yerel sapmalar uzun duvarda siva yükünü büyütmeye başlamaktadır.",
          note: "Bu seviyede müdahale edilmezse hata hat boyunca yayılır.",
        },
        {
          title: "Saha aksiyonunu belirle",
          result: "Duvar ilerlemesi durdurulup referans hat yeniden kurulmalıdır.",
          note: "İlerledikçe düzeltmek zorlaşır ve maliyet artar.",
        },
        {
          title: "Sonraki ekip etkisini ekle",
          result: "Bu dalga doğrama kasasi, süpürgelik ve uzun koridor ışığında daha görünür hale gelir.",
          note: "Briket hatası çoğu zaman duvar bitince değil, ince işte görünür olur.",
        },
      ],
      checks: [
        "Uzun duvarlarda düzenli mastar kontrolü şarttır.",
        "Dalgayi siva ile çözmek yerine duvar aşamasında durdurmak gerekir.",
        "Koridor ve geniş yüzeylerde tolerans daha görünür sonuç üretir.",
        "Aks doğruluğu ile düzlem doğruluğu birlikte izlenmelidir.",
      ],
      engineeringComment: "Briket duvarda 1 cm'lik dalga, uzun bir koridorda kullanıcının ilk gördüğü kalite kusuruna dönüşebilir.",
    },
    tools: [
      { category: "Cizim", name: "Mimari aks ve bosluk paftalari", purpose: "Uzun duvar hatlari ve acikliklari doğru kurmak." },
      { category: "Ölçüm", name: "Lazer, şakul ve mastar seti", purpose: "Duzlem ve aks kalitesini sık araliklarla izlemek." },
      { category: "Koordinasyon", name: "Tesisat kanal listesi", purpose: "Plansiz kirim ihtiyacini azaltmak." },
      { category: "Kontrol", name: "Duvar ve siva on kabul cizelgesi", purpose: "Briket duvarı ince iş öncesi standarda baglamak." },
    ],
    equipmentAndMaterials: [
      { group: "Malzeme", name: "Briket birimleri ve uygun örgu harci", purpose: "Ekonomik ama kontrollu bir dolgu duvar kurmak.", phase: "Duvar orumu" },
      { group: "Ölçüm", name: "Lazer, metre, mastar ve şakul", purpose: "Uzun duvar hatlarinda toleransi izlemek.", phase: "Surekli" },
      { group: "Kesim", name: "Kontrollu kesim ekipmani", purpose: "Bosluk etrafinda zayif kirik parca birakmamak.", phase: "Detay" },
      { group: "Koordinasyon", name: "Tesisat geçiş ve kilif parcalari", purpose: "Sonradan kirim ihtiyacini azaltmak.", phase: "Koordinasyon" },
    ],
    mistakes: [
      { wrong: "Briketi kaba malzeme diye duzlem kontrolunu gevsetmek.", correct: "Uzun duvarlarda daha sık mastar kontrolü yapmak." },
      { wrong: "Siva ile toplariz diyerek dalgayi kabul etmek.", correct: "Duvar asamasinda hatayi durdurup düzeltmek." },
      { wrong: "Acilik kenarlarinda kirik ve zayif parca birakmak.", correct: "Bosluk detayini kontrollu kesimle çözmek." },
      { wrong: "Tesisat için duvar bittikten sonra plansiz kirimak.", correct: "Kanal ve buat yerlerini önceden kapatmak." },
      { wrong: "Betonarme temaslarini önemsiz görmek.", correct: "Catlak çizgilerini azaltacak saha disiplini kurmak." },
    ],
    designVsField: [
      "Briket duvar projede ekonomik bir tarama gibi görünür; sahada ise tolerans yönetilmezse en pahalı siva ve düzeltme yüklerinden birine dönüşür.",
      "Iyi uygulandiginda ekonomik avantajını korur; kötü uygulandığında sonraki ekiplerin maliyetini sessizce büyütür.",
    ],
    conclusion: [
      "Briket duvar doğru düzlem, doğru bosluk ve doğru koordinasyonla yürütüldüğünde ekonomik ve yeterli bir dolgu duvar çözümü sunar.",
      "Kontrolsüz bırakıldığında ise kaba görünen ama ince iş bütçesini yiyen bir saha problemine dönüşür.",
    ],
    sources: [...KABA_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670],
    keywords: ["briket", "briket duvar", "dolgu duvar", "siva yuku", "saha toleransi"],
  },
  {
    slugPath: "kaba-insaat/cati-iskeleti",
    kind: "topic",
    quote: "Çatı iskeleti, üst ortuyu tasiyan konstruksiyon degil; rüzgar, su, bakım ve geometriyi aynı anda tasiyan üst sistem omurgasidir.",
    tip: "Çatı iskeletini yalnız makas montaji gibi gormek, asil riski birlesimlerde, egimde ve üst katman koordinasyonunda gözden kacirmak demektir.",
    intro: [
      "Çatı iskeleti; ahşap, çelik veya benzeri taşıyıcı elemanlarla kaplamayi, bakım yuklerini ve cevresel etkileri üst yapidan temel sisteme aktaran ana taşıyıcı paketidir. Bu nedenle yalnız montaj operasyonu degil, geometri ve güvenlik kararidir.",
      "Sahada çatı iskeleti kaynakli sorunlarin buyuk kismi ana elemanlardan degil; mahya dogrultusu, askı-bağlantı detaylari, cihaz ayaklari ve kaplama altı hazırlıktaki koordinasyon eksiginden kaynaklanir.",
      "Bir insaat muhendisi için çatı iskeleti, makas hesabı kadar montaj sirasi, bağlantı okunurlugu, egim davranisi ve sonradan gelecek kaplama-tesisat ekiplerinin gereksinimleriyle birlikte yönetilmesi gereken bir yapisal fasildir.",
    ],
    theory: [
      "Çatı iskeletinde ana mesele, taşıyıcı elemanların yalnız düşey yükleri değil; rüzgar emmesi, bakım yükleri ve kaplama altı servis etkilerini de düzenli olarak aktarmasidir. Bu nedenle dügum detaylari ana eleman kadar kritik hale gelir.",
      "Mahya doğrultusu, aşıklık düzeni, makas veya taşıyıcı ritim, kaplama altı yüzeyin kalitesini doğrudan etkiler. İskelet geometrisindeki küçük kaçıklıklar üstte kiremitte, metal panelde veya membran altında büyük görsel ve teknik soruna dönüşebilir.",
      "Çatı iskeleti aynı zamanda mekanik çıkışlar, baca, güneş paneli ayağı ve bakım erişimi gibi yükleri de önceden düşünmek zorundadır. Sonradan açılan delik veya eklenen taşıyıcı parça sistemi düzensiz ve zayıf hale getirebilir.",
      "Bu nedenle çatı iskeleti, taşıyıcı sistem ile kaplama sistemi arasında yalnız geçiş değil; uyum kuran teknik bir ara katmandir.",
    ],
    ruleTable: [
      {
        parameter: "Geometri ve eğim",
        limitOrRequirement: "Mahya, aks ve eğim kararları montaj boyunca sürekli doğrulanmalı",
        reference: "Çatı planı ve saha ölçüm disiplini",
        note: "İskelet geometrisindeki hata üst katmanda büyür.",
      },
      {
        parameter: "Birleşim ve ankraj",
        limitOrRequirement: "Makas, aşık ve kenar bağlantıları tasarımla uyumlu tamamlanmalı",
        reference: "Taşıyıcı detay paftalari",
        note: "Çatı sorunları çoğu zaman ana elemanda değil düğümde başlar.",
      },
      {
        parameter: "Kaplama ve servis koordinasyonu",
        limitOrRequirement: "Baca, mekanik çıkış, güneş paneli veya cihaz yükleri iskeletle birlikte planlanmalı",
        reference: "Koordinasyon paftasi",
        note: "Sonradan eklenen yükler sistemi zayiflatabilir.",
      },
      {
        parameter: "Güvenlik ve bakım",
        limitOrRequirement: "Montaj sırasında ve sonrasında güvenli erişim senaryosu düşünülmeli",
        reference: "Saha güvenlik plani",
        note: "Bakım erişimi olmayan çatı, işletmede risk üretir.",
      },
    ],
    designOrApplicationSteps: [
      "Çatı geometrisini, mahya hattini ve ana taşıyıcı ritmi montaj öncesi netlestir.",
      "Ahşap veya çelik elemanlari sahada montaj sirasiyla birlikte numaralandir ve sırala.",
      "Birlesim, ankraj ve aşıklık detaylarini yalnız cizimde degil saha kurulum mantiginda da test et.",
      "Kaplama altı yüzeyi, cihaz ayaklari ve baca çıkışlarını iskelet kurulurken çöz.",
      "Montaj sonrası eğim, aks, rijitlik ve kaplama öncesi yüzey hazırlığını kabul et.",
    ],
    criticalChecks: [
      "Mahya hattı ve eğim doğrultusu sahada sapma gösteriyor mu?",
      "Birleşim ve ankraj detayları çizimdekiyle uyumlu mu?",
      "Kaplama altı için düz ve sürekli bir yüzey bırakıldı mı?",
      "Mekanik çıkışlar veya cihaz ayakları sonradan taşıyıcıyı zorluyor mu?",
      "Bakım ve güvenli erişim senaryosu düşünüldü mü?",
    ],
    numericalExample: {
      title: "8 m açıklıkta çatı iskeleti montaj toleransi yorumu",
      inputs: [
        { label: "Ana açıklik", value: "8 m", note: "Orta ölçekli çatı modülü" },
        { label: "Mahya boyunca ölçülen kot farkı", value: "12 mm", note: "Uçlar arasi" },
        { label: "Hedef", value: "Kaplama altı süreklilik", note: "Üst katman kalitesi için" },
      ],
      assumptions: [
        "İskelet montajı henüz kaplama öncesi aşamadadır.",
        "Aşıklık ve bağlantı elemanları tamamlanmıştır.",
        "Kaplama sistemi düzgün alt yüzey gerektirmektedir.",
      ],
      steps: [
        {
          title: "Kot farkini oku",
          result: "8 m açıklıkta 12 mm'lik mahya farkı küçük görünse de üst kaplamada hiz ve su davranışını etkileyebilir.",
          note: "İskelet toleransı üst katmanda büyüyerek görünür hale gelir.",
        },
        {
          title: "Saha aksiyonunu belirle",
          result: "Kaplama öncesi mahya ve aşık hattı yeniden ayarlanmalı veya lokal düzeltme yapılmalıdır.",
          note: "Kaplama sonrası bu düzeltme çok daha pahalıdır.",
        },
        {
          title: "Koordinasyon etkisini ekle",
          result: "Baca, dere veya panel birleşimi gibi kritik detaylar bu sapmadan ilk etkilenecek bölgeler olur.",
          note: "Geometri hatası en önce düğüm detaylarında sorun çıkarır.",
        },
      ],
      checks: [
        "Geometri kontrolü kaplama başlamadan tamamlanmalıdır.",
        "Mahya ve aşık çizgileri birlikte okunmalıdır.",
        "Kritik detay bölgeleri ilave dikkatle kontrol edilmelidir.",
        "Küçük toleransların üst katmanda büyüyeceği unutulmamalıdır.",
      ],
      engineeringComment: "Çatı iskeletinde milimetreler çoğu zaman kaplamada santimetre gibi görünür.",
    },
    tools: [
      { category: "Cizim", name: "Çatı planı, kesit ve düğüm paftalari", purpose: "Geometri ve birleşim kararlarını sahaya net indirmek." },
      { category: "Ölçüm", name: "Lazer nivo ve eğim kontrol ekipmani", purpose: "Mahya, aks ve yüzey sürekliliğini doğrulamak." },
      { category: "Koordinasyon", name: "Mekanik çıkış ve ekipman matrisi", purpose: "Baca, cihaz ayağı ve servis yüklerini erken çözmek." },
      { category: "Kontrol", name: "Bağlantı ve ankraj checklisti", purpose: "Düğümlerin tasarımla uyumlu tamamlandığını izlemek." },
    ],
    equipmentAndMaterials: [
      { group: "Taşıyıcı", name: "Makas, aşık ve ana taşıyıcı elemanlar", purpose: "Çatı geometrisini ve yük aktarımını kurmak.", phase: "Montaj" },
      { group: "Bağlantı", name: "Bulon, levha, ankraj ve bağlantı elemanlari", purpose: "Düğümleri güvenli ve süreklilik sağlayacak biçimde tamamlamak.", phase: "Birleşim" },
      { group: "Ölçüm", name: "Lazer, metre, açı ve kot kontrol ekipmani", purpose: "Geometriyi kaplama öncesi doğrulamak.", phase: "Kontrol" },
      { group: "Güvenlik", name: "Yaşam hattı, iskele ve düşmeye karşı ekipman", purpose: "Montaj ve bakım sırasında güvenli çalışma sağlamak.", phase: "Surekli" },
    ],
    mistakes: [
      { wrong: "Çatı iskeletini yalnız makas montaji gibi görmek.", correct: "Geometri, düğüm ve üst katman koordinasyonunu birlikte yönetmek." },
      { wrong: "Mahya ve eğim kontrolünü kaplama sonrasina birakmak.", correct: "İskelet aşamasında sürekli ölçmek." },
      { wrong: "Birleşim detaylarını sahada usta kararına bırakmak.", correct: "Ankraj ve düğüm mantığını net paftalarla kurmak." },
      { wrong: "Mekanik çıkışları sonradan taşıyıcıya yüklemek.", correct: "Servis ve cihaz yüklerini iskelet kurulurken çözmek." },
      { wrong: "Bakım erişimini düşünmemek.", correct: "Montaj kadar işletme güvenliğini de planlamak." },
    ],
    designVsField: [
      "Projede çatı iskeleti birkaç çizgi ve kesit gibi görünür; sahada ise üst yapı ile kaplama sistemi arasındaki bütün uyumu taşır.",
      "Iyi çatı iskeleti kendini görünmeden belli eder; kaplama düzgün oturur, su doğru akar ve bakım riski azalır.",
    ],
    conclusion: [
      "Çatı iskeleti doğru geometri, doğru birleşim ve doğru koordinasyonla kurulduğunda üst sistemin uzun ömürlü çalışmasının temelini oluşturur.",
      "Eksik yönetildiğinde ise sorun önce düğümde, sonra kaplamada ve en son işletmede görünür hale gelir.",
    ],
    sources: [...KABA_OVERRIDE_SOURCES, SOURCE_LEDGER.ts500, SOURCE_LEDGER.tsEn13670, SOURCE_LEDGER.ts825],
    keywords: ["çatı iskeleti", "mahya", "aşık", "ankraj", "çatı geometrisi"],
  },
];
