import { BRANCH_SOURCE_LEDGER, SOURCE_LEDGER } from "../source-ledger";
import type { BinaGuideEquipment, BinaGuidePageSpec, BinaGuideTool } from "../types";

const TESISAT_OVERRIDE_SOURCES = [...BRANCH_SOURCE_LEDGER["tesisat-isleri"]];

const TESISAT_OVERRIDE_TOOLS: BinaGuideTool[] = [
  { category: "Model", name: "Revit MEP / MagiCAD", purpose: "Saft, cihaz ve asma tavan koordinasyonunu cakisma bazinda cozmek." },
  { category: "Elektrik", name: "Caneco / benzeri dogrulama araclari", purpose: "Pano, kesit, koruma ve secicilik kararlarini kontrol etmek." },
  { category: "Kontrol", name: "Excel devreye alma matrisi", purpose: "Basinc, izolasyon, debi ve fonksiyon testlerini tek tabloda izlemek." },
  { category: "Saha", name: "Lazer metre, nivo ve etiketleme setleri", purpose: "Hat kotu, cihaz erisimi ve teslim okunabilirligini sahada dogrulamak." },
];

const TESISAT_OVERRIDE_EQUIPMENT: BinaGuideEquipment[] = [
  { group: "Test", name: "Basinc test pompasi ve manometre seti", purpose: "Su, isitma ve yangin hatlarinda sizdirmazlik ile basinc dayanimini dogrulamak.", phase: "Kapatma oncesi" },
  { group: "Elektrik", name: "Megger, multimetre ve sureklilik test ekipmani", purpose: "Izolasyon, topraklama ve devre surekliligini devreye alma oncesi olcmek.", phase: "Devreye alma" },
  { group: "Montaj", name: "Aski, kelepce, vana ve etiketleme aksesuarlari", purpose: "Hatlari tasiyip bakim erisimi ve okunabilir tanimlama saglamak.", phase: "Montaj" },
  { group: "Kontrol", name: "Termal kamera ve debi/sicaklik yardimci olcum araclari", purpose: "Dengesiz dagitim, sicaklik farki ve isletme sorunlarini devreye alma sirasinda gormek.", phase: "Devreye alma" },
];

export const tesisatIsleriTopicOverrides: BinaGuidePageSpec[] = [
  {
    slugPath: "tesisat-isleri/isitma-sogutma",
    kind: "topic",
    quote: "Isitma-sogutma sistemlerinde konfor, cihaz kapasitesinden cok dagitimin dengeli kurulmasiyla hissedilir.",
    tip: "Hatlar test edilmeden, dengeleme yapilmadan ve kontrol senaryosu yazili hale getirilmeden kapatilan sistemler kullaniciya dengesiz sicaklik ve yuksek enerji tuketimi olarak geri doner.",
    intro: [
      "Isitma-sogutma sistemleri; isitma uretimi, sogutma, dagitim hatlari, terminal cihazlar ve kontrol elemanlarindan olusan bir konfor zinciridir. Bu zincirin herhangi bir halkasi zayif kaldiginda en pahali cihaz dahi beklenen kullanici memnuniyetini uretemez.",
      "Santiyede en sik gorulen yanlis yaklasim, cihaz kapasitesini ana karar sanip dagitim geometrisini ikinci plana atmaktir. Oysa devre boyu, kollektör konumu, vana ayari, yogusma drenaji, boru izolasyonu ve bakim erisimi gercek performansi belirler.",
      "Bu baslik, isitma-sogutma islerini cihaz montaji degil; muhendislik, saha kontrolu ve isletmeye devredilebilir kayit disiplini olarak ele alir.",
    ],
    theory: [
      "Mekanik konfor sistemlerinde kullanici memnuniyetsizligi cogunlukla yetersiz kapasiteden degil, dengesiz dagitimdan kaynaklanir. Bir mahale fazla debi giderken baska mahalin yetersiz beslenmesi, teorik olarak dogru secilmis cihazi pratikte yetersiz hale getirir.",
      "Hidronik sistemlerde hat uzunlugu, basinc kaybi ve devre dengelemesi birlikte okunmalidir. Hava tarafinda ise menfez yerlesimi, kanal kacaklari ve cihaz kontrol algoritmasi dogrudan konfor davranisi uretir.",
      "Yogusma drenaji ve izolasyon kalinligi ozellikle sogutma calisan sistemlerde kritik hale gelir. Sahada ihmal edilen kucuk bir egim veya eksik izolasyon, tavanda leke, kuf ve su damlamasina donusebilir.",
      "30 Haziran 2025 itibariyla yururlukte olan guncel enerji performansi yaklasiminin da isaret ettigi gibi, mekanik verim yalniz cihaz etiketinde degil; kontrol, dagitim ve kabuk davranisi ile birlikte degerlendirilir.",
    ],
    ruleTable: [
      {
        parameter: "Yalitim ve enerji kaybi",
        limitOrRequirement: "Hat ve cihaz izolasyonu enerji kaybini ve yogusma riskini sinirlandirmali",
        reference: "TS 825 + BEP Yonetmeligi",
        note: "Yalitimsiz veya eksik yalitilmis hatlar cihaz verimini sahada dusurur.",
      },
      {
        parameter: "Bakim erisimi",
        limitOrRequirement: "Kollektor, vana, cihaz ve kontrol elemanlari mudahale edilebilir kalmali",
        reference: "MEP uygulama disiplini",
        note: "Bakim yapilamayan sistem teslim edilmis sayilmaz.",
      },
      {
        parameter: "Devre boyu ve dengeleme",
        limitOrRequirement: "Dagitim sistemi dengeli devre boylari ve ayarlanabilir hat mantigiyla kurulmali",
        reference: "Sistem tasarim ilkeleri",
        note: "Ozellikle yerden isitma ve kollektorlu cozumlerde kritik kontroldur.",
      },
      {
        parameter: "Devreye alma ve kontrol",
        limitOrRequirement: "Termostat, vana ve otomasyon ayarlari kayitli dogrulamayla tamamlanmali",
        reference: "BEP Yonetmeligi + saha devreye alma disiplini",
        note: "Ayarsiz sistemler montaji tamamlanmis gorunse de isletmede sorun uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Sistem tipini mahal kullanim, enerji hedefi ve bakim kurgusuyla birlikte sec.",
      "Kollektor, cihaz ve ana boru guzergahlarini erisim ve mudahale senaryosuna gore yerlestir.",
      "Devre uzunluklarini, basinc kaybini ve dengeleme ihtiyacini montaj baslamadan coz.",
      "Basinc testi, izolasyon, drenaj ve aski kontrollerini kapatma oncesinde tamamla.",
      "Devreye alma sirasinda sicaklik dagilimi, debi dengesi ve kontrol ayarlarini kayit altina al.",
      "Isletmeye teslim oncesi kullaniciya birakilan sicaklik kontrol mantigini ve bakim noktasini son kez dogrula.",
    ],
    criticalChecks: [
      "Kollektor ve cihazlar servis icin erisilebilir mi?",
      "Devre boylari birbirinden asiri sapiyor mu?",
      "Basinc testi ve foto-kayit kapatma oncesi tamamlandi mi?",
      "Yogusma drenaji, egim ve tahliye noktalari gercekten calisiyor mu?",
      "Izolasyon surekliligi kesintisiz mi?",
      "Termostat, vana ve otomasyon ayarlari teslim dosyasina islendi mi?",
    ],
    numericalExample: {
      title: "Yerden isitma devre boyu dengesi icin saha yorumu",
      inputs: [
        { label: "Mahal alani", value: "32 m2", note: "Salon" },
        { label: "Devre sayisi", value: "3 adet", note: "Kollektorlu sistem" },
        { label: "Devre uzunluklari", value: "95 m, 100 m, 105 m", note: "Ornek saha plani" },
        { label: "Hedef", value: "Dengeli isi dagilimi", note: "Homojen konfor icin" },
      ],
      assumptions: [
        "Boru araligi tum mahalde benzer tutulacaktir.",
        "Kollektor konumu bu mahal icin uygundur.",
        "Sap oncesi sistem basinc altinda teslim alinacaktir.",
      ],
      steps: [
        {
          title: "Uzunluk farkini oku",
          formula: "(105 - 95) / 100 ~= %10",
          result: "Yaklasik %10 boy farki, dengeleme acisindan yonetilebilir bandi isaret eder.",
          note: "Fark buyudukce bazi devreler daha zor dengelenir ve sicaklik farki artar.",
        },
        {
          title: "Sap oncesi riski yorumla",
          result: "Basinc altindaki sistem foto ve test kaydi olmadan sap altina birakilmamalidir.",
          note: "Sap sonrasi mudahale maliyeti yuksek ve yikicidir.",
        },
        {
          title: "Isletme ayarini ekle",
          result: "Kollektor uzerindeki dengeleme degerleri teslim klasorune yazilmalidir.",
          note: "Aksi halde ilk bakimda ayarlar kaybolur ve sistem tekrar dengesizlesir.",
        },
      ],
      checks: [
        "Devre boylari asiri dengesiz birakilmamalidir.",
        "Kollektor etiketi ve mahal karsiligi net olmalidir.",
        "Sap oncesi test ve kayit tamamlanmalidir.",
        "Devreye alma sonucu yalniz sozlu degil yazili birakilmalidir.",
      ],
      engineeringComment: "Isitma-sogutma sistemlerinde kullanici en cok cihazi degil, dagitimin dengesini hisseder.",
    },
    tools: TESISAT_OVERRIDE_TOOLS,
    equipmentAndMaterials: TESISAT_OVERRIDE_EQUIPMENT,
    mistakes: [
      { wrong: "Devre boylarini sahada rastgele ayirmak.", correct: "Dengeli dagitim mantigiyla planlamak." },
      { wrong: "Kollektoru erisimsiz yere koymak.", correct: "Bakim ve dengeleme erisimini korumak." },
      { wrong: "Sap oncesi test yapmadan sistemi kapatmak.", correct: "Basinc ve foto-kayitla teslim almak." },
      { wrong: "Yogusma drenajini ikincil gormek.", correct: "Sogutma sisteminde ana kontrol kalemi saymak." },
      { wrong: "Devreye alma ayarlarini kayitsiz birakmak.", correct: "Dengeleme degerlerini teslim dokumanina islemek." },
      { wrong: "Otomasyon ve termostat konumlarini kullanim senaryosundan kopuk birakmak.", correct: "Kontrol stratejisini saha isletmesiyle birlikte dogrulamak." },
    ],
    designVsField: [
      "Tasarim tarafinda isitma-sogutma semasi yeterli gorunebilir; sahada ise boru boyu, izolasyon, drenaj ve bakim erisimi sistemi gercekten calistirir.",
      "Bu yuzden konfor tesisati, en cok devreye alma aninda muhendislik niteligini belli eder.",
      "Iyi mekanik montaj gorunmez olabilir; kotu devreye alma ise hemen sicaklik farki, gurultu ve yuksek enerji tuketimi olarak hissedilir.",
    ],
    conclusion: [
      "Isitma-sogutma isleri dogru dagitim ve dogru kayitla yurutuldugunde enerji verimli ve dengeli konfor saglar.",
      "Yanlis yurutuldugunde cihaz kapasitesi yeterli olsa bile kullanici memnuniyetsizligi ve yuksek isletme gideri ortaya cikar.",
    ],
    sources: [...TESISAT_OVERRIDE_SOURCES, SOURCE_LEDGER.ts825],
    keywords: ["isitma sogutma", "yerden isitma", "devre boyu", "mekanik dengeleme", "konfor tesisati"],
  },
  {
    slugPath: "tesisat-isleri/yangin-tesisati",
    kind: "topic",
    quote: "Yangin tesisati, yangin aninda calismasi beklendigi icin diger sistemlerden daha fazla onceden dogrulanmak zorundadir.",
    tip: "Yangin hattindaki kucuk ihmal, normal gunde gorunmeyebilir; ama kritik anda sistemin tamamini degersiz hale getirebilir.",
    intro: [
      "Yangin tesisati; aktif sondurme, yangin suyu dagitimi, alarm ve ekipman erisimini kapsayan, guvenlik odakli bir sistemdir.",
      "Bu sistemin degeri gunluk kullanimda degil, acil durumda ortaya ciktigi icin tasarim, montaj ve test disiplininin diger sistemlerden daha siki kurulmasi gerekir.",
      "Normal gunlerde sessiz kalan bu sistem, kritik anda tek seferde ve gecikmesiz calismak zorundadir. Bu nedenle yangin hattinda yapilan kucuk bir ihmal, diger tesisatlardaki benzer kusurlardan daha agir sonuc uretir.",
    ],
    theory: [
      "Yangin tesisatinda ana amac, dogru debi ve basinci dogru noktaya guvenle ulastirmaktir. Ancak bu amac yalnizca boru capi secimiyle degil; zonlama, vana duzeni, gecis guvenligi ve bakim erisimiyle tamamlanir.",
      "Sistem cogu zaman diger mekanik ve elektrik sistemlerle ayni saftlari paylasir. Bu nedenle yangin hatti, aktif koruma sistemi oldugu icin koordinasyonda oncelikli dusunulmelidir.",
      "Yangin tesisati duzenli test ve kontrol gerektirir; testlenmeyen sistem guvence uretmez. Ozellikle pompa odasi, basinc bolgesi, drenaj ve kat bazli ekipman erisimi teslim oncesi fiilen dogrulanmalidir.",
      "Aktif sondurme hatti ile pasif yangin guvenligi birlikte dusunulmelidir. Saft gecislerinde yangin durdurucu eksik birakildiginda veya vana-dolap erisimi kapandiginda, borulama dogru gorunse bile sistem butuncul koruma saglayamaz.",
    ],
    ruleTable: [
      {
        parameter: "Yangin koruma sistemi",
        limitOrRequirement: "Zonlama, ekipman ve kacis stratejisiyle uyumlu olmali",
        reference: "Yangin Yonetmeligi",
        note: "Sistem yalnizca boru hatti degildir; butuncul guvenlik paketidir.",
      },
      {
        parameter: "Bakim ve erisim",
        limitOrRequirement: "Vana, dolap ve test noktalari erisilebilir kalmali",
        reference: "Yangin Yonetmeligi + saha disiplini",
        note: "Kapatma arkasinda birakilan elemanlar bakim kabiliyetini yok eder.",
      },
      {
        parameter: "Test ve devreye alma",
        limitOrRequirement: "Fonksiyon ve basinc kontrolleri kayitli yapilmali",
        reference: "Sistem kalite plani",
        note: "Acil durumda calisacak sistem, normal gunde dogrulanmalidir.",
      },
      {
        parameter: "Gecis ve yangin durdurucu",
        limitOrRequirement: "Bolme duvar ve doseme gecisleri yangin butunlugunu koruyacak sekilde tamamlanmali",
        reference: "Yangin Yonetmeligi",
        note: "Aktif hat, pasif bolme surekliligini bozmamalidir.",
      },
    ],
    designOrApplicationSteps: [
      "Yangin senaryosu, zonlama ve ekipman yerlesimini proje basinda netlestir.",
      "Hat guzergahi, vana odasi ve dolap erisimini mimariyle birlikte coz.",
      "Gecis ve durdurucu detaylarini diger tesisatlarla cakismayacak sekilde planla.",
      "Basinc ve fonksiyon testlerini devreye alma oncesi tamamla.",
      "Bakim talimati, etiketleme ve test kayitlarini teslim dosyasina ekle.",
      "Pompa odasi, test-drenaj hatti ve alarm entegrasyonunu tek devreye alma matrisinde birlestir.",
    ],
    criticalChecks: [
      "Dolap, vana ve test noktalari erisilebilir mi?",
      "Yangin hatlari diger sistemlerle cakisiyor mu?",
      "Gecis detaylari yangin guvenligine uygun mu?",
      "Basinc ve fonksiyon testleri tamamlandi mi?",
      "Etiketleme ve bakim talimati hazir mi?",
      "Yangin durdurucu ve zon butunlugu saha turunda dogrulandi mi?",
    ],
    numericalExample: {
      title: "Yangin dolabi hatti icin erisim ve test mantigi",
      inputs: [
        { label: "Kat sayisi", value: "5", note: "Orta yukseklikte yapi" },
        { label: "Yangin dolabi", value: "her katta 1 adet", note: "Ornek kurgu" },
        { label: "Test noktasi", value: "ana hatta 1 + kat bazli kontrol", note: "Teslim oncesi plan" },
        { label: "Hedef", value: "Erisilebilir ve testlenmis sistem", note: "Bakim guvenligi icin" },
      ],
      assumptions: [
        "Dolap yerleri kacis ve kullanim senaryosuna gore secilmistir.",
        "Vana erisimi kapatilmayacaktir.",
        "Testler teslim oncesi kayit altina alinacaktir.",
      ],
      steps: [
        {
          title: "Erisim ihtiyacini yorumla",
          result: "Her katta ekipman gorunur ve erisilebilir olmalidir.",
          note: "Dekoratif gizleme guvenlik performansini zayiflatir.",
        },
        {
          title: "Test mantigini kur",
          result: "Ana hat ve kat bazli kontrol noktalari birlikte planlanmalidir.",
          note: "Sistem sadece monte edilmekle guvenilir hale gelmez.",
        },
        {
          title: "Ekipman sayisini yonet",
          formula: "5 kat x 1 dolap = 5 dolap noktasi",
          result: "Her kat icin erisim, etiketleme ve test dogrulamasi ayri yapilmalidir.",
          note: "Bir katta dogru calisan kurgu, diger katlarin otomatik olarak dogru tamamlandigi anlamina gelmez.",
        },
      ],
      checks: [
        "Yangin ekipmani onunde depolama veya kapatma yapilmamalidir.",
        "Test kayitlari teslim dosyasinda yer almalidir.",
        "Sistemin zon mantigi saha personeli tarafindan anlasilabilir olmalidir.",
        "Test bosaltma ve drenaj guvenligi devreye alma senaryosuna dahil edilmelidir.",
      ],
      engineeringComment: "Yangin tesisatinda erisim ve test, boru capi kadar hayati iki tasarim ciktisidir.",
    },
    tools: TESISAT_OVERRIDE_TOOLS,
    equipmentAndMaterials: TESISAT_OVERRIDE_EQUIPMENT,
    mistakes: [
      { wrong: "Yangin hattini diger sistemlerle ayni onem duzeyinde gormek.", correct: "Guvenlik onceligi vererek koordinasyonu cozmek." },
      { wrong: "Dolap ve vana onlerini kapatmak.", correct: "Bakim erisimini surekli acik birakmak." },
      { wrong: "Testi teslim sonu formalitesi saymak.", correct: "Sistemin guvenilirlik kaniti olarak gormek." },
      { wrong: "Gecisleri yangin durdurucusuz birakmak.", correct: "Yangin guvenligi detayi ile tamamlamak." },
      { wrong: "Etiketleme yapmadan sistemi devretmek.", correct: "Ekipman ve zon bilgisini acik bicimde tanimlamak." },
      { wrong: "Yangin hattini diger tesisatlarla ayni koordinasyon onceliginde birakmak.", correct: "Aktif guvenlik sistemi oldugu icin oncelikli cozmek." },
    ],
    designVsField: [
      "Projede yangin hatti bir guvenlik cizgisi gibi gorunur; sahada ise erisim, test ve bakim yapilabilirlik bu sistemin gercek degerini belirler.",
      "Bu nedenle yangin tesisati, yalnizca montaj kalemi degil, isletme guvenligi disiplini olarak gorulmelidir.",
      "Sahada en iyi yangin sistemi, yalniz dogru monte edilmis olan degil; acil durumda kimsenin tereddut etmeden kullanabilecegi kadar okunabilir olandir.",
    ],
    conclusion: [
      "Yangin tesisati dogru kuruldugunda acil durumda guven veren sistem haline gelir.",
      "Hatali kuruldugunda ise fark edilmesi en gec, bedeli en agir sorunlardan birini uretir.",
    ],
    sources: [...TESISAT_OVERRIDE_SOURCES, SOURCE_LEDGER.yanginYonetmeligi],
    keywords: ["yangin tesisati", "yangin dolabi", "sprinkler", "yangin yonetmeligi", "aktif yangin guvenligi"],
  },
  {
    slugPath: "tesisat-isleri/sihhi-tesisat",
    kind: "topic",
    quote: "Sihhi tesisat, boru dosemek degil; hijyen, egim ve servis erisimini ayni sistemde yasatmaktir.",
    tip: "Temiz su ve pis su sistemleri proje uzerinde cozulmeden kapatilirsa sorun kullaniciya koku, gurultu, geri tepme ve kacak olarak doner.",
    intro: [
      "Sihhi tesisat; temiz su, sicak su, pis su, havalik ve armatür baglantilarinin birlikte calistigi, bakim erisimi gerektiren bir sistem butunudur.",
      "Bu sistemin kalitesi sadece boru malzemesiyle degil; egim, havalik, vana erisimi ve kapatma oncesi test disipliniyle belirlenir.",
      "Kullanici tarafindan en hizli fark edilen tesisat sorunlari da cogu zaman bu grupta ortaya cikar: kotu koku, geri tepme, dusuk basinc, gizli kacak veya islak hacimde surekli gurultu. Bu nedenle sihhi tesisat, duvar arkasinda kaldigi icin degil kapatildiktan sonra mudahalesi zor oldugu icin yuksek disiplin ister.",
    ],
    theory: [
      "Temiz su tarafinda hijyen, basinc ve dengeleme onemlidir; atik su tarafinda ise egim, havalik ve geri tepme riskinin yonetimi one cikar.",
      "Sihhi tesisat hatlari cogu zaman saft, islak hacim ve tavan icinde gizlenir. Bu yuzden kapatma oncesi kayitsiz birakilan bir hata sonradan en zor mudahale edilen kusurlardan biri haline gelir.",
      "Pis su sisteminde cap, egim ve havalik kadar temizleme kapagi noktalari da kritik onemdedir. Akis normal gorunse bile bakim erisimi birakilmayan hatlar isletme doneminde yuksek servis yuku uretir.",
      "Temiz su tarafinda ise hijyen zinciri; vana erisimi, kor uclarin azaltilmasi ve basinc testinin belgeli bicimde tamamlanmasina baglidir. Iyi sihhi tesisat, kullanici fark etmeden duzgun calisan sistemdir.",
    ],
    ruleTable: [
      {
        parameter: "Temiz su hijyeni ve dagitimi",
        limitOrRequirement: "Hatlar test edilebilir ve bakim erisimli olmali",
        reference: "TS EN 806",
        note: "Vana ve kritik baglanti noktalari erisilebilir kalmalidir.",
      },
      {
        parameter: "Pis su egimi ve havalik",
        limitOrRequirement: "Akisi bozmayacak egim ve havalik duzeni kurulmalidir",
        reference: "TS EN 12056",
        note: "Koku ve geri tepme riski cogu zaman burada dogar.",
      },
      {
        parameter: "Kapatma oncesi test",
        limitOrRequirement: "Basinc ve sizdirmazlik kayitlari tamamlanmalidir",
        reference: "Saha kalite plani",
        note: "Foto-kayit ve test raporu birlikte tutulmalidir.",
      },
      {
        parameter: "Temizleme ve mudahale noktalari",
        limitOrRequirement: "Kolon, yatay donus ve kritik hatlarda bakim erisimi korunmalidir",
        reference: "TS EN 12056 + saha isletme disiplini",
        note: "Bakim kapaklari dekoratif kaygiyla erisilemez hale getirilmemelidir.",
      },
    ],
    designOrApplicationSteps: [
      "Temiz su, sicak su ve pis su guzergahlarini islak hacim planiyla birlikte coz.",
      "Saft, havalik ve dusey kolon yerlerini bakim erisimine gore belirle.",
      "Yatay pis su hatlarinda egim ve yon degisimlerini gorunur sekilde planla.",
      "Kapatma oncesi basinc ve sizdirmazlik testlerini tamamla.",
      "Vana, sayac ve temizleme noktalarini etiketleyerek teslim et.",
      "Armatür yukleri, doseme kotu ve kolon baglantilarini banyo/saft kesitleri uzerinden son kez dogrula.",
    ],
    criticalChecks: [
      "Pis su hattinda gerekli egim korunuyor mu?",
      "Havalik sistemi dogru baglandi mi?",
      "Temiz su hatlarinda basinc testi tamamlandi mi?",
      "Vana ve temizleme noktalari erisilebilir mi?",
      "Islak hacim kapatilmadan once foto-kayit alindi mi?",
      "Kolon baglantisi veya dirseklerde ters egim olusturacak zayif nokta var mi?",
    ],
    numericalExample: {
      title: "Pis su hatti egim yorumu",
      inputs: [
        { label: "Hat uzunlugu", value: "6,0 m", note: "Banyo cikisi ile kolona kadar" },
        { label: "Hedef egim", value: "%1,5", note: "Ornek proje yaklasimi" },
        { label: "Gerekli kot farki", value: "9 cm", note: "6,0 m boyunca" },
        { label: "Hat capi", value: "O100", note: "Ornek atik su hatti" },
      ],
      assumptions: [
        "Hatta ters egim yaratacak kot engeli yoktur.",
        "Dirsek sayisi minimumda tutulacaktir.",
        "Kolon baglantisi dogru kotta hazirlanmistir.",
      ],
      steps: [
        {
          title: "Kot farkini hesapla",
          formula: "6,0 m x %1,5 = 0,09 m",
          result: "Toplam 9 cm dusus gerekir.",
          note: "Bu deger, saft ve doseme gecisleriyle birlikte okunmalidir.",
        },
        {
          title: "Uygulanabilirligi yorumla",
          result: "Dusus saglanamiyorsa rota veya cozum revize edilmelidir.",
          note: "Egimi santiyede rastgele azaltmak dogru degildir.",
        },
        {
          title: "Kot rezervini kontrol et",
          result: "Saft veya doseme icinde yalniz 6 cm rezerv varsa, 9 cm ihtiyac bu guzergah icin yetersiz kalir.",
          note: "Bu durumda guzergah veya tesisat duzeni is baslamadan revize edilmelidir.",
        },
      ],
      checks: [
        "Gerekli kot farki uygulamada korunmalidir.",
        "Dirsek ve birlesimler akisi bozmayacak sekilde duzenlenmelidir.",
        "Kapama oncesi su testi veya gozlem yapilmalidir.",
        "Doseme icinde ters egim yaratacak yuksek nokta birakilmamalidir.",
      ],
      engineeringComment: "Sihhi tesisatta santimetre seviyesindeki kot karari, kullanim konforunu yillarca etkiler.",
    },
    tools: TESISAT_OVERRIDE_TOOLS,
    equipmentAndMaterials: TESISAT_OVERRIDE_EQUIPMENT,
    mistakes: [
      { wrong: "Pis su egimini sahada goz karari vermek.", correct: "Kot ve uzunlukla olculu ilerlemek." },
      { wrong: "Vana ve temizleme noktalarini kapatmak.", correct: "Bakim erisimini gorunur birakmak." },
      { wrong: "Basinc testini formalite gormek.", correct: "Kayitli ve sistematik yapmak." },
      { wrong: "Havalik sistemini onemsiz gormek.", correct: "Koku ve akis davranisi icin zorunlu kabul etmek." },
      { wrong: "Islak hacmi test tamamlanmadan kapatmak.", correct: "Foto-kayit ve testten sonra ilerlemek." },
      { wrong: "Kolon baglanti kotunu kucuk fark diye onemsememek.", correct: "Santimetre seviyesindeki kotlari proje karari gibi yonetmek." },
    ],
    designVsField: [
      "Tasarim tarafinda birkac boru hatti gibi gorunen sihhi tesisat, sahada ses, koku, bakim ve sizdirmazlik davranisi uretir.",
      "Bu nedenle sihhi tesisatin basarisi, kullanici hissetmeden duzgun calisabilmesidir.",
      "Iyi sihhi tesisat gorunmedigi icin degil, sorun cikarmadigi icin fark edilmez; kotu tesisat ise ilk kullanici sikayetleriyle hemen gorunur olur.",
    ],
    conclusion: [
      "Sihhi tesisat dogru kuruldugunda yapi sessiz ve sorunsuz calisir.",
      "Hatali kuruldugunda ise kullanici sikayetleriyle en hizli gorunur hale gelen sistemlerden biri olur.",
    ],
    sources: [...TESISAT_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn806, SOURCE_LEDGER.tsEn12056],
    keywords: ["sihhi tesisat", "pis su egimi", "temiz su", "TS EN 806", "TS EN 12056"],
  },
  {
    slugPath: "tesisat-isleri/elektrik-tesisati",
    kind: "topic",
    quote: "Elektrik tesisati, akimi tasimaktan once guvenli koruma ve okunabilir devre mantigi kurmalidir.",
    tip: "Kabloyu dosemek kolaydir; zor olan, yillar sonra bakim ekibinin o devreyi guvenle okuyup mudahale edebilmesidir.",
    intro: [
      "Elektrik tesisati; enerji dagitimi, priz-aydinlatma devreleri, pano sistemi, kablolama guzergahlari ve topraklama duzenini kapsar.",
      "Bu sistemin kalitesi, devrelerin calismasi kadar guvenli kapanma, etiketleme ve erisilebilir bakim duzeniyle olculur.",
      "Sahada gorunur montaj cogu zaman tamamlanmis hissi verir; fakat koruma kurgusu dogrulanmamis, panosu okunmayan ve devreleri etiketlenmemis bir tesisat teknik olarak eksik kabul edilmelidir.",
    ],
    theory: [
      "Elektrik tesisatinda tasarim hedefi yalnizca enerji vermek degildir; kacak akim, kisa devre, secicilik ve bakim guvenligi gibi koruma ilkeleri de ayni derecede onemlidir.",
      "Kablo tavalari, borulama ve pano yerlesimi mimariden bagimsiz dusunulemez. Fiziksel guzergah hatalari, sonradan en cok kirma ve duzenleme gerektiren islerden biridir.",
      "TS HD 60364 serisinin dogrulama yaklasiminin da isaret ettigi gibi, enerji verilmeden once tesisatin olculmesi ve koruma mantiginin sahadaki gercek montajla uyustugunun gorulmesi gerekir. Ozellikle topraklama surekliligi, izolasyon direnci ve koruma cihazlarinin seciciligi kritik kabul kalemidir.",
      "Bu nedenle elektrik tesisati, cizimle baslayan ama olcum, etiketleme ve as-built butunluguyle tamamlanan sistem isidir.",
    ],
    ruleTable: [
      {
        parameter: "Devre korumasi ve topraklama",
        limitOrRequirement: "Koruma duzeni ve topraklama surekliligi dogrulanmali",
        reference: "TS HD 60364",
        note: "Devreye alma olcumleri yapilmadan teslim tamamlanmis sayilmaz.",
      },
      {
        parameter: "Kablo guzergahi",
        limitOrRequirement: "Fiziksel tasima sistemi bakim ve rezerv birakmali",
        reference: "TS HD 60364 + saha koordinasyonu",
        note: "Tava dolulugu ve erisim birlikte degerlendirilmelidir.",
      },
      {
        parameter: "Pano ve etiketleme",
        limitOrRequirement: "Devreler acikca tanimlanmali ve erisilebilir kalmali",
        reference: "Elektrik uygulama disiplini",
        note: "Etiketsiz pano uzun vadede guvenlik riski uretir.",
      },
      {
        parameter: "Dogrulama ve olcum",
        limitOrRequirement: "Izolasyon, sureklilik ve koruma kontrolleri enerji verme oncesi kayit altina alinmali",
        reference: "TS HD 60364-6 dogrulama yaklasimi",
        note: "Calisan sistem, olculmeden guvenli kabul edilmemelidir.",
      },
    ],
    designOrApplicationSteps: [
      "Pano ve devre semasini yuk listesiyle birlikte kesinlestir.",
      "Kablo guzergahlarini saft ve tavan koordinasyonuna gore yerlestir.",
      "Topraklama ve espotansiyel baglantilari montajin basindan itibaren kur.",
      "Kacak akim, asiri akim ve secicilik mantigini pano bazinda yazili hale getir.",
      "Izolasyon, sureklilik ve fonksiyon testlerini devreye alma oncesi tamamla.",
      "Tum devre ve ekipmanlari etiketleyerek as-built setine isle.",
    ],
    criticalChecks: [
      "Pano onu ve bakim erisimi yeterli mi?",
      "Kablo tavalari asiri dolu mu?",
      "Topraklama surekliligi olculdu mu?",
      "Izolasyon testleri tamamlandi mi?",
      "Etiketleme sistemi as-built ile uyumlu mu?",
      "Koruma cihazlari ile gercek devre kurgusu ayni secicilik mantigini tasiyor mu?",
    ],
    numericalExample: {
      title: "Pano etiketleme ve devre sayisi icin bakim yorumu",
      inputs: [
        { label: "Pano devre sayisi", value: "36 adet", note: "Aydinlatma, priz ve ozel yukler birlikte" },
        { label: "Etiketsiz devre adedi", value: "5 adet", note: "Devreye alma oncesi tespit" },
        { label: "Hedef", value: "0 etiketsiz devre", note: "Teslim kriteri" },
        { label: "Kritik risk", value: "Yanlis devreye mudahale", note: "Isletme guvenligi" },
      ],
      assumptions: [
        "Pano semasi guncel haldedir.",
        "Devre numaralari saha etiketleriyle eslesecektir.",
        "Etiketsiz devreler teslim oncesi kapatilacaktir.",
      ],
      steps: [
        {
          title: "Uygunsuzluk oranini oku",
          formula: "5 / 36 ~= %14",
          result: "Pano devrelerinin onemli bolumu bakim acisindan belirsizdir.",
          note: "Calisan sistem, tanimli sistem demek degildir.",
        },
        {
          title: "Teslim kararini yorumla",
          result: "Etiketsiz devreler tamamlanmadan pano teslim edilmemelidir.",
          note: "Etiketleme, guvenlik ekipmaninin bir parcasidir.",
        },
        {
          title: "Bakim riskini degerlendir",
          result: "Yaklasik %14 belirsizlik, sahada yanlis kesici acma veya yanlis devreye mudahale riskini kabul edilemez duzeye tasir.",
          note: "Elektrikte kucuk tanimsizlik, buyuk guvenlik riski uretir.",
        },
      ],
      checks: [
        "Her devre panoda ve saha ucunda ayni kodla tanimlanmalidir.",
        "Etiketleme as-built cizimle uyumlu olmalidir.",
        "Izolasyon ve fonksiyon testi etiketsiz devre birakmadan tamamlanmalidir.",
        "Pano kapak ici semasi ile sahadaki gercek dagilim ayni olmalidir.",
      ],
      engineeringComment: "Elektrik tesisatinda gorunmez kalite, cogu zaman olcum ve etiketleme disiplininde saklidir.",
    },
    tools: TESISAT_OVERRIDE_TOOLS,
    equipmentAndMaterials: TESISAT_OVERRIDE_EQUIPMENT,
    mistakes: [
      { wrong: "Kablo guzergahini bosluk buldukca degistirmek.", correct: "Koordinasyon planina sadik kalmak." },
      { wrong: "Etiketlemeyi sonradan yapilacak is saymak.", correct: "Montajin ayrilmaz parcasi yapmak." },
      { wrong: "Topraklama olcusunu atlamak.", correct: "Teslim oncesi zorunlu test saymak." },
      { wrong: "Pano onunu farkli ekipmanlarla kapatmak.", correct: "Bakim alanini korumak." },
      { wrong: "Izolasyon testi olmadan devreye alma yapmak.", correct: "Olcum zincirini tamamlamak." },
      { wrong: "Test sonrasi saha revizyonlarini pano semasina islememek.", correct: "As-built ve pano tanimlarini ayni anda guncellemek." },
    ],
    designVsField: [
      "Tasarimda tek hat semasi yeterli gorunebilir; sahada ise kablo yolu, pano erisimi ve etiketleme olmadan guvenli isletme mumkun degildir.",
      "Bu nedenle elektrik tesisatinin gercek kalitesi, montaj tamamlandiginda degil olcum kayitlari ciktiginda gorulur.",
      "Iyi elektrik montaji yalniz enerji verir hale gelmis sistem degil; yillar sonra bile okunabilir ve emniyetli mudahale edilebilir sistemdir.",
    ],
    conclusion: [
      "Elektrik tesisati dogru planlandiginda hem guvenli hem okunabilir olur.",
      "Hatali planlandiginda ise yillarca surecek bakim ve guvenlik sorunlari uretir.",
    ],
    sources: [...TESISAT_OVERRIDE_SOURCES, SOURCE_LEDGER.tsHd60364],
    keywords: ["elektrik tesisati", "topraklama", "pano etiketleme", "TS HD 60364", "devreye alma"],
  },
];
