import { BRANCH_SOURCE_LEDGER, SOURCE_LEDGER } from "../source-ledger";
import type { BinaGuideEquipment, BinaGuidePageSpec, BinaGuideTool } from "../types";

const TESISAT_OVERRIDE_SOURCES = [...BRANCH_SOURCE_LEDGER["tesisat-isleri"]];

const TESISAT_OVERRIDE_TOOLS: BinaGuideTool[] = [
  { category: "Model", name: "Revit MEP / MagiCAD", purpose: "Saft, cihaz ve asma tavan koordinasyonunu cakisma bazinda cozmek." },
  { category: "Elektrik", name: "Caneco / benzeri dogrulama araclari", purpose: "Pano, kesit, koruma ve secicilik kararlarini kontrol etmek." },
  { category: "Kontrol", name: "Excel devreye alma matrisi", purpose: "Basinc, izolasyon, debi ve fonksiyon testlerini tek tabloda izlemek." },
  { category: "Saha", name: "Lazer metre, nivo ve etiketleme setleri", purpose: "Hat kötü, cihaz erisimi ve teslim okunabilirligini sahada dogrulamak." },
];

const TESISAT_OVERRIDE_EQUIPMENT: BinaGuideEquipment[] = [
  { group: "Test", name: "Basinc test pompasi ve manometre seti", purpose: "Su, isitma ve yangin hatlarinda sızdırmazlık ile basinc dayanimini dogrulamak.", phase: "Kapatma öncesi" },
  { group: "Elektrik", name: "Megger, multimetre ve sureklilik test ekipmani", purpose: "Izolasyon, topraklama ve devre surekliligini devreye alma öncesi olcmek.", phase: "Devreye alma" },
  { group: "Montaj", name: "Aski, kelepce, vana ve etiketleme aksesuarlari", purpose: "Hatlari tasiyip bakım erisimi ve okunabilir tanimlama saglamak.", phase: "Montaj" },
  { group: "Kontrol", name: "Termal kamera ve debi/sıcaklık yardimci ölçüm araclari", purpose: "Dengesiz dağıtım, sıcaklık farki ve isletme sorunlarini devreye alma sirasinda gormek.", phase: "Devreye alma" },
];

export const tesisatIsleriTopicOverrides: BinaGuidePageSpec[] = [
  {
    slugPath: "tesisat-isleri/isitma-sogutma",
    kind: "topic",
    quote: "Isitma-sogutma sistemlerinde konfor, cihaz kapasitesinden çok dagitimin dengeli kurulmasiyla hissedilir.",
    tip: "Hatlar test edilmeden, dengeleme yapilmadan ve kontrol senaryosu yazili hale getirilmeden kapatilan sistemler kullaniciya dengesiz sıcaklık ve yuksek enerji tuketimi olarak geri doner.",
    intro: [
      "Isitma-sogutma sistemleri; isitma uretimi, sogutma, dağıtım hatlari, terminal cihazlar ve kontrol elemanlarindan olusan bir konfor zinciridir. Bu zincirin herhangi bir halkasi zayif kaldiginda en pahali cihaz dahi beklenen kullanıcı memnuniyetini uretemez.",
      "Santiyede en sık gorulen yanlış yaklasim, cihaz kapasitesini ana karar sanip dağıtım geometrisini ikinci plana atmaktir. Oysa devre boyu, kollektör konumu, vana ayari, yoğuşma drenaji, boru izolasyonu ve bakım erisimi gercek performansi belirler.",
      "Bu baslik, isitma-sogutma islerini cihaz montaji degil; muhendislik, saha kontrolu ve isletmeye devredilebilir kayıt disiplini olarak ele alir.",
    ],
    theory: [
      "Mekanik konfor sistemlerinde kullanıcı memnuniyetsizligi cogunlukla yetersiz kapasiteden degil, dengesiz dagitimdan kaynaklanir. Bir mahale fazla debi giderken baska mahalin yetersiz beslenmesi, teorik olarak doğru secilmis cihazi pratikte yetersiz hale getirir.",
      "Hidronik sistemlerde hat uzunlugu, basinc kaybi ve devre dengelemesi birlikte okunmalidir. Hava tarafinda ise menfez yerlesimi, kanal kacaklari ve cihaz kontrol algoritmasi doğrudan konfor davranisi uretir.",
      "Yoğuşma drenaji ve izolasyon kalinligi ozellikle sogutma çalışan sistemlerde kritik hale gelir. Sahada ihmal edilen küçük bir egim veya eksik izolasyon, tavanda leke, kuf ve su damlamasina donusebilir.",
      "30 Haziran 2025 itibariyla yururlukte olan guncel enerji performansi yaklasiminin da isaret ettigi gibi, mekanik verim yalnız cihaz etiketinde degil; kontrol, dağıtım ve kabuk davranisi ile birlikte degerlendirilir.",
    ],
    ruleTable: [
      {
        parameter: "Yalitim ve enerji kaybi",
        limitOrRequirement: "Hat ve cihaz izolasyonu enerji kaybini ve yoğuşma riskini sinirlandirmali",
        reference: "TS 825 + BEP Yonetmeligi",
        note: "Yalıtımsız veya eksik yalitilmis hatlar cihaz verimini sahada dusurur.",
      },
      {
        parameter: "Bakım erisimi",
        limitOrRequirement: "Kollektor, vana, cihaz ve kontrol elemanlari mudahale edilebilir kalmali",
        reference: "MEP uygulama disiplini",
        note: "Bakım yapilamayan sistem teslim edilmis sayilmaz.",
      },
      {
        parameter: "Devre boyu ve dengeleme",
        limitOrRequirement: "Dağıtım sistemi dengeli devre boylari ve ayarlanabilir hat mantigiyla kurulmali",
        reference: "Sistem tasarim ilkeleri",
        note: "Ozellikle yerden isitma ve kollektorlu cozumlerde kritik kontroldur.",
      },
      {
        parameter: "Devreye alma ve kontrol",
        limitOrRequirement: "Termostat, vana ve otomasyon ayarlari kayitli dogrulamayla tamamlanmali",
        reference: "BEP Yonetmeligi + saha devreye alma disiplini",
        note: "Ayarsiz sistemler montaji tamamlanmis gorunse de isletmede sorun uretir.",
      },
    ],
    designOrApplicationSteps: [
      "Sistem tipini mahal kullanım, enerji hedefi ve bakım kurgusuyla birlikte sec.",
      "Kollektor, cihaz ve ana boru guzergahlarini erişim ve mudahale senaryosuna göre yerlestir.",
      "Devre uzunluklarini, basinc kaybini ve dengeleme ihtiyacini montaj baslamadan coz.",
      "Basinc testi, izolasyon, drenaj ve aski kontrollerini kapatma oncesinde tamamla.",
      "Devreye alma sirasinda sıcaklık dagilimi, debi dengesi ve kontrol ayarlarini kayıt altina al.",
      "Isletmeye teslim öncesi kullaniciya birakilan sıcaklık kontrol mantigini ve bakım noktasini son kez doğrula.",
    ],
    criticalChecks: [
      "Kollektor ve cihazlar servis için erişilebilir mi?",
      "Devre boylari birbirinden asiri sapiyor mu?",
      "Basinc testi ve foto-kayıt kapatma öncesi tamamlandi mi?",
      "Yoğuşma drenaji, egim ve tahliye noktalari gercekten calisiyor mu?",
      "Izolasyon surekliligi kesintisiz mi?",
      "Termostat, vana ve otomasyon ayarlari teslim dosyasina islendi mi?",
    ],
    numericalExample: {
      title: "Yerden isitma devre boyu dengesi için saha yorumu",
      inputs: [
        { label: "Mahal alani", value: "32 m2", note: "Salon" },
        { label: "Devre sayisi", value: "3 adet", note: "Kollektorlu sistem" },
        { label: "Devre uzunluklari", value: "95 m, 100 m, 105 m", note: "Ornek saha plani" },
        { label: "Hedef", value: "Dengeli isi dagilimi", note: "Homojen konfor için" },
      ],
      assumptions: [
        "Boru araligi tüm mahalde benzer tutulacaktir.",
        "Kollektor konumu bu mahal için uygundur.",
        "Sap öncesi sistem basinc altinda teslim alinacaktir.",
      ],
      steps: [
        {
          title: "Uzunluk farkini oku",
          formula: "(105 - 95) / 100 ~= %10",
          result: "Yaklasik %10 boy farki, dengeleme acisindan yonetilebilir bandi isaret eder.",
          note: "Fark buyudukce bazi devreler daha zor dengelenir ve sıcaklık farki artar.",
        },
        {
          title: "Sap öncesi riski yorumla",
          result: "Basinc altindaki sistem foto ve test kaydi olmadan sap altina birakilmamalidir.",
          note: "Sap sonrasi mudahale maliyeti yuksek ve yikicidir.",
        },
        {
          title: "Isletme ayarini ekle",
          result: "Kollektor uzerindeki dengeleme degerleri teslim klasorune yazilmalidir.",
          note: "Aksi halde ilk bakimda ayarlar kaybolur ve sistem tekrar dengesizlesir.",
        },
      ],
      checks: [
        "Devre boylari asiri dengesiz birakilmamalidir.",
        "Kollektor etiketi ve mahal karsiligi net olmalidir.",
        "Sap öncesi test ve kayıt tamamlanmalidir.",
        "Devreye alma sonucu yalnız sozlu degil yazili birakilmalidir.",
      ],
      engineeringComment: "Isitma-sogutma sistemlerinde kullanıcı en çok cihazi degil, dagitimin dengesini hisseder.",
    },
    tools: TESISAT_OVERRIDE_TOOLS,
    equipmentAndMaterials: TESISAT_OVERRIDE_EQUIPMENT,
    mistakes: [
      { wrong: "Devre boylarini sahada rastgele ayirmak.", correct: "Dengeli dağıtım mantigiyla planlamak." },
      { wrong: "Kollektoru erisimsiz yere koymak.", correct: "Bakım ve dengeleme erisimini korumak." },
      { wrong: "Sap öncesi test yapmadan sistemi kapatmak.", correct: "Basinc ve foto-kayitla teslim almak." },
      { wrong: "Yoğuşma drenajini ikincil gormek.", correct: "Sogutma sisteminde ana kontrol kalemi saymak." },
      { wrong: "Devreye alma ayarlarini kayitsiz birakmak.", correct: "Dengeleme degerlerini teslim dokumanina islemek." },
      { wrong: "Otomasyon ve termostat konumlarini kullanım senaryosundan kopuk birakmak.", correct: "Kontrol stratejisini saha isletmesiyle birlikte dogrulamak." },
    ],
    designVsField: [
      "Tasarim tarafinda isitma-sogutma semasi yeterli gorunebilir; sahada ise boru boyu, izolasyon, drenaj ve bakım erisimi sistemi gercekten calistirir.",
      "Bu yuzden konfor tesisati, en çok devreye alma aninda muhendislik niteligini belli eder.",
      "Iyi mekanik montaj görünmez olabilir; kötü devreye alma ise hemen sıcaklık farki, gürültü ve yuksek enerji tuketimi olarak hissedilir.",
    ],
    conclusion: [
      "Isitma-sogutma isleri doğru dağıtım ve doğru kayitla yurutuldugunde enerji verimli ve dengeli konfor saglar.",
      "Yanlış yurutuldugunde cihaz kapasitesi yeterli olsa bile kullanıcı memnuniyetsizligi ve yuksek isletme gideri ortaya cikar.",
    ],
    sources: [...TESISAT_OVERRIDE_SOURCES, SOURCE_LEDGER.ts825],
    keywords: ["isitma sogutma", "yerden isitma", "devre boyu", "mekanik dengeleme", "konfor tesisati"],
  },
  {
    slugPath: "tesisat-isleri/yangin-tesisati",
    kind: "topic",
    quote: "Yangin tesisati, yangin aninda calismasi beklendigi için diger sistemlerden daha fazla önceden dogrulanmak zorundadir.",
    tip: "Yangin hattindaki küçük ihmal, normal gunde gorunmeyebilir; ama kritik anda sistemin tamamini degersiz hale getirebilir.",
    intro: [
      "Yangin tesisati; aktif sondurme, yangin suyu dagitimi, alarm ve ekipman erisimini kapsayan, güvenlik odakli bir sistemdir.",
      "Bu sistemin degeri gunluk kullanimda degil, acil durumda ortaya ciktigi için tasarim, montaj ve test disiplininin diger sistemlerden daha siki kurulmasi gerekir.",
      "Normal gunlerde sessiz kalan bu sistem, kritik anda tek seferde ve gecikmesiz çalışmak zorundadir. Bu nedenle yangin hattinda yapilan küçük bir ihmal, diger tesisatlardaki benzer kusurlardan daha agir sonuc uretir.",
    ],
    theory: [
      "Yangin tesisatinda ana amac, doğru debi ve basinci doğru noktaya guvenle ulastirmaktir. Ancak bu amac yalnizca boru capi secimiyle degil; zonlama, vana duzeni, geçiş guvenligi ve bakım erisimiyle tamamlanir.",
      "Sistem cogu zaman diger mekanik ve elektrik sistemlerle aynı saftlari paylasir. Bu nedenle yangin hatti, aktif koruma sistemi oldugu için koordinasyonda oncelikli dusunulmelidir.",
      "Yangin tesisati duzenli test ve kontrol gerektirir; testlenmeyen sistem guvence uretmez. Ozellikle pompa odasi, basinc bolgesi, drenaj ve kat bazli ekipman erisimi teslim öncesi fiilen dogrulanmalidir.",
      "Aktif sondurme hatti ile pasif yangin guvenligi birlikte dusunulmelidir. Saft gecislerinde yangin durdurucu eksik birakildiginda veya vana-dolap erisimi kapandiginda, borulama doğru gorunse bile sistem butuncul koruma saglayamaz.",
    ],
    ruleTable: [
      {
        parameter: "Yangin koruma sistemi",
        limitOrRequirement: "Zonlama, ekipman ve kacis stratejisiyle uyumlu olmali",
        reference: "Yangin Yonetmeligi",
        note: "Sistem yalnizca boru hatti degildir; butuncul güvenlik paketidir.",
      },
      {
        parameter: "Bakım ve erişim",
        limitOrRequirement: "Vana, dolap ve test noktalari erişilebilir kalmali",
        reference: "Yangin Yonetmeligi + saha disiplini",
        note: "Kapatma arkasinda birakilan elemanlar bakım kabiliyetini yok eder.",
      },
      {
        parameter: "Test ve devreye alma",
        limitOrRequirement: "Fonksiyon ve basinc kontrolleri kayitli yapilmali",
        reference: "Sistem kalite plani",
        note: "Acil durumda calisacak sistem, normal gunde dogrulanmalidir.",
      },
      {
        parameter: "Geçiş ve yangin durdurucu",
        limitOrRequirement: "Bolme duvar ve doseme gecisleri yangin butunlugunu koruyacak sekilde tamamlanmali",
        reference: "Yangin Yonetmeligi",
        note: "Aktif hat, pasif bolme surekliligini bozmamalidir.",
      },
    ],
    designOrApplicationSteps: [
      "Yangin senaryosu, zonlama ve ekipman yerlesimini proje basinda netlestir.",
      "Hat guzergahi, vana odasi ve dolap erisimini mimariyle birlikte coz.",
      "Geçiş ve durdurucu detaylarini diger tesisatlarla cakismayacak sekilde planla.",
      "Basinc ve fonksiyon testlerini devreye alma öncesi tamamla.",
      "Bakım talimati, etiketleme ve test kayitlarini teslim dosyasina ekle.",
      "Pompa odasi, test-drenaj hatti ve alarm entegrasyonunu tek devreye alma matrisinde birlestir.",
    ],
    criticalChecks: [
      "Dolap, vana ve test noktalari erişilebilir mi?",
      "Yangin hatlari diger sistemlerle cakisiyor mu?",
      "Geçiş detaylari yangin guvenligine uygun mu?",
      "Basinc ve fonksiyon testleri tamamlandi mi?",
      "Etiketleme ve bakım talimati hazir mi?",
      "Yangin durdurucu ve zon butunlugu saha turunda dogrulandi mi?",
    ],
    numericalExample: {
      title: "Yangin dolabi hatti için erişim ve test mantigi",
      inputs: [
        { label: "Kat sayisi", value: "5", note: "Orta yukseklikte yapı" },
        { label: "Yangin dolabi", value: "her katta 1 adet", note: "Ornek kurgu" },
        { label: "Test noktasi", value: "ana hatta 1 + kat bazli kontrol", note: "Teslim öncesi plan" },
        { label: "Hedef", value: "Erişilebilir ve testlenmis sistem", note: "Bakım guvenligi için" },
      ],
      assumptions: [
        "Dolap yerleri kacis ve kullanım senaryosuna göre secilmistir.",
        "Vana erisimi kapatilmayacaktir.",
        "Testler teslim öncesi kayıt altina alinacaktir.",
      ],
      steps: [
        {
          title: "Erişim ihtiyacini yorumla",
          result: "Her katta ekipman görünür ve erişilebilir olmalidir.",
          note: "Dekoratif gizleme güvenlik performansini zayiflatir.",
        },
        {
          title: "Test mantigini kur",
          result: "Ana hat ve kat bazli kontrol noktalari birlikte planlanmalidir.",
          note: "Sistem sadece monte edilmekle guvenilir hale gelmez.",
        },
        {
          title: "Ekipman sayisini yonet",
          formula: "5 kat x 1 dolap = 5 dolap noktasi",
          result: "Her kat için erişim, etiketleme ve test dogrulamasi ayri yapilmalidir.",
          note: "Bir katta doğru çalışan kurgu, diger katlarin otomatik olarak doğru tamamlandigi anlamina gelmez.",
        },
      ],
      checks: [
        "Yangin ekipmani onunde depolama veya kapatma yapilmamalidir.",
        "Test kayitlari teslim dosyasinda yer almalidir.",
        "Sistemin zon mantigi saha personeli tarafindan anlasilabilir olmalidir.",
        "Test bosaltma ve drenaj guvenligi devreye alma senaryosuna dahil edilmelidir.",
      ],
      engineeringComment: "Yangin tesisatinda erişim ve test, boru capi kadar hayati iki tasarim ciktisidir.",
    },
    tools: TESISAT_OVERRIDE_TOOLS,
    equipmentAndMaterials: TESISAT_OVERRIDE_EQUIPMENT,
    mistakes: [
      { wrong: "Yangin hattini diger sistemlerle aynı onem duzeyinde gormek.", correct: "Güvenlik onceligi vererek koordinasyonu cozmek." },
      { wrong: "Dolap ve vana onlerini kapatmak.", correct: "Bakım erisimini surekli acik birakmak." },
      { wrong: "Testi teslim sonu formalitesi saymak.", correct: "Sistemin guvenilirlik kaniti olarak gormek." },
      { wrong: "Gecisleri yangin durdurucusuz birakmak.", correct: "Yangin guvenligi detayi ile tamamlamak." },
      { wrong: "Etiketleme yapmadan sistemi devretmek.", correct: "Ekipman ve zon bilgisini acik bicimde tanimlamak." },
      { wrong: "Yangin hattini diger tesisatlarla aynı koordinasyon onceliginde birakmak.", correct: "Aktif güvenlik sistemi oldugu için oncelikli cozmek." },
    ],
    designVsField: [
      "Projede yangin hatti bir güvenlik cizgisi gibi görünür; sahada ise erişim, test ve bakım yapılabilirlik bu sistemin gercek degerini belirler.",
      "Bu nedenle yangin tesisati, yalnizca montaj kalemi degil, isletme guvenligi disiplini olarak gorulmelidir.",
      "Sahada en iyi yangin sistemi, yalnız doğru monte edilmis olan degil; acil durumda kimsenin tereddut etmeden kullanabilecegi kadar okunabilir olandir.",
    ],
    conclusion: [
      "Yangin tesisati doğru kuruldugunda acil durumda guven veren sistem haline gelir.",
      "Hatali kuruldugunda ise fark edilmesi en gec, bedeli en agir sorunlardan birini uretir.",
    ],
    sources: [...TESISAT_OVERRIDE_SOURCES, SOURCE_LEDGER.yanginYonetmeligi],
    keywords: ["yangin tesisati", "yangin dolabi", "sprinkler", "yangin yonetmeligi", "aktif yangin guvenligi"],
  },
  {
    slugPath: "tesisat-isleri/sihhi-tesisat",
    kind: "topic",
    quote: "Sihhi tesisat, boru dosemek degil; hijyen, egim ve servis erisimini aynı sistemde yasatmaktir.",
    tip: "Temiz su ve pis su sistemleri proje üzerinde cozulmeden kapatilirsa sorun kullaniciya koku, gürültü, geri tepme ve kacak olarak doner.",
    intro: [
      "Sihhi tesisat; temiz su, sıcak su, pis su, havalik ve armatür baglantilarinin birlikte calistigi, bakım erisimi gerektiren bir sistem butunudur.",
      "Bu sistemin kalitesi sadece boru malzemesiyle degil; egim, havalik, vana erisimi ve kapatma öncesi test disipliniyle belirlenir.",
      "Kullanıcı tarafindan en hızlı fark edilen tesisat sorunlari da cogu zaman bu grupta ortaya cikar: kötü koku, geri tepme, düşük basinc, gizli kacak veya islak hacimde surekli gürültü. Bu nedenle sihhi tesisat, duvar arkasinda kaldigi için degil kapatildiktan sonra mudahalesi zor oldugu için yuksek disiplin ister.",
    ],
    theory: [
      "Temiz su tarafinda hijyen, basinc ve dengeleme onemlidir; atik su tarafinda ise egim, havalik ve geri tepme riskinin yonetimi one cikar.",
      "Sihhi tesisat hatlari cogu zaman saft, islak hacim ve tavan icinde gizlenir. Bu yuzden kapatma öncesi kayitsiz birakilan bir hata sonradan en zor mudahale edilen kusurlardan biri haline gelir.",
      "Pis su sisteminde cap, egim ve havalik kadar temizleme kapagi noktalari da kritik onemdedir. Akis normal gorunse bile bakım erisimi birakilmayan hatlar isletme doneminde yuksek servis yuku uretir.",
      "Temiz su tarafinda ise hijyen zinciri; vana erisimi, kor uclarin azaltilmasi ve basinc testinin belgeli bicimde tamamlanmasina baglidir. Iyi sihhi tesisat, kullanıcı fark etmeden düzgün çalışan sistemdir.",
    ],
    ruleTable: [
      {
        parameter: "Temiz su hijyeni ve dagitimi",
        limitOrRequirement: "Hatlar test edilebilir ve bakım erisimli olmali",
        reference: "TS EN 806",
        note: "Vana ve kritik bağlantı noktalari erişilebilir kalmalidir.",
      },
      {
        parameter: "Pis su egimi ve havalik",
        limitOrRequirement: "Akisi bozmayacak egim ve havalik duzeni kurulmalidir",
        reference: "TS EN 12056",
        note: "Koku ve geri tepme riski cogu zaman burada dogar.",
      },
      {
        parameter: "Kapatma öncesi test",
        limitOrRequirement: "Basinc ve sızdırmazlık kayitlari tamamlanmalidir",
        reference: "Saha kalite plani",
        note: "Foto-kayıt ve test raporu birlikte tutulmalidir.",
      },
      {
        parameter: "Temizleme ve mudahale noktalari",
        limitOrRequirement: "Kolon, yatay donus ve kritik hatlarda bakım erisimi korunmalidir",
        reference: "TS EN 12056 + saha isletme disiplini",
        note: "Bakım kapaklari dekoratif kaygiyla erisilemez hale getirilmemelidir.",
      },
    ],
    designOrApplicationSteps: [
      "Temiz su, sıcak su ve pis su guzergahlarini islak hacim planiyla birlikte coz.",
      "Saft, havalik ve düşey kolon yerlerini bakım erisimine göre belirle.",
      "Yatay pis su hatlarinda egim ve yon degisimlerini görünür sekilde planla.",
      "Kapatma öncesi basinc ve sızdırmazlık testlerini tamamla.",
      "Vana, sayac ve temizleme noktalarini etiketleyerek teslim et.",
      "Armatür yukleri, doseme kötü ve kolon baglantilarini banyo/saft kesitleri uzerinden son kez doğrula.",
    ],
    criticalChecks: [
      "Pis su hattinda gerekli egim korunuyor mu?",
      "Havalik sistemi doğru baglandi mi?",
      "Temiz su hatlarinda basinc testi tamamlandi mi?",
      "Vana ve temizleme noktalari erişilebilir mi?",
      "Islak hacim kapatilmadan once foto-kayıt alindi mi?",
      "Kolon baglantisi veya dirseklerde ters egim olusturacak zayif nokta var mi?",
    ],
    numericalExample: {
      title: "Pis su hatti egim yorumu",
      inputs: [
        { label: "Hat uzunlugu", value: "6,0 m", note: "Banyo cikisi ile kolona kadar" },
        { label: "Hedef egim", value: "%1,5", note: "Ornek proje yaklasimi" },
        { label: "Gerekli kot farki", value: "9 cm", note: "6,0 m boyunca" },
        { label: "Hat capi", value: "O100", note: "Ornek atik su hatti" },
      ],
      assumptions: [
        "Hatta ters egim yaratacak kot engeli yoktur.",
        "Dirsek sayisi minimumda tutulacaktir.",
        "Kolon baglantisi doğru kotta hazirlanmistir.",
      ],
      steps: [
        {
          title: "Kot farkini hesapla",
          formula: "6,0 m x %1,5 = 0,09 m",
          result: "Toplam 9 cm dusus gerekir.",
          note: "Bu deger, saft ve doseme gecisleriyle birlikte okunmalidir.",
        },
        {
          title: "Uygulanabilirligi yorumla",
          result: "Dusus saglanamiyorsa rota veya cozum revize edilmelidir.",
          note: "Egimi santiyede rastgele azaltmak doğru degildir.",
        },
        {
          title: "Kot rezervini kontrol et",
          result: "Saft veya doseme icinde yalnız 6 cm rezerv varsa, 9 cm ihtiyaç bu guzergah için yetersiz kalir.",
          note: "Bu durumda guzergah veya tesisat duzeni iş baslamadan revize edilmelidir.",
        },
      ],
      checks: [
        "Gerekli kot farki uygulamada korunmalidir.",
        "Dirsek ve birlesimler akisi bozmayacak sekilde duzenlenmelidir.",
        "Kapama öncesi su testi veya gozlem yapilmalidir.",
        "Doseme icinde ters egim yaratacak yuksek nokta birakilmamalidir.",
      ],
      engineeringComment: "Sihhi tesisatta santimetre seviyesindeki kot karari, kullanım konforunu yillarca etkiler.",
    },
    tools: TESISAT_OVERRIDE_TOOLS,
    equipmentAndMaterials: TESISAT_OVERRIDE_EQUIPMENT,
    mistakes: [
      { wrong: "Pis su egimini sahada göz karari vermek.", correct: "Kot ve uzunlukla olculu ilerlemek." },
      { wrong: "Vana ve temizleme noktalarini kapatmak.", correct: "Bakım erisimini görünür birakmak." },
      { wrong: "Basinc testini formalite gormek.", correct: "Kayitli ve sistematik yapmak." },
      { wrong: "Havalik sistemini onemsiz gormek.", correct: "Koku ve akis davranisi için zorunlu kabul etmek." },
      { wrong: "Islak hacmi test tamamlanmadan kapatmak.", correct: "Foto-kayıt ve testten sonra ilerlemek." },
      { wrong: "Kolon bağlantı kotunu küçük fark diye onemsememek.", correct: "Santimetre seviyesindeki kotlari proje karari gibi yonetmek." },
    ],
    designVsField: [
      "Tasarim tarafinda birkaç boru hatti gibi gorunen sihhi tesisat, sahada ses, koku, bakım ve sızdırmazlık davranisi uretir.",
      "Bu nedenle sihhi tesisatin basarisi, kullanıcı hissetmeden düzgün calisabilmesidir.",
      "Iyi sihhi tesisat gorunmedigi için degil, sorun cikarmadigi için fark edilmez; kötü tesisat ise ilk kullanıcı sikayetleriyle hemen görünür olur.",
    ],
    conclusion: [
      "Sihhi tesisat doğru kuruldugunda yapı sessiz ve sorunsuz calisir.",
      "Hatali kuruldugunda ise kullanıcı sikayetleriyle en hızlı görünür hale gelen sistemlerden biri olur.",
    ],
    sources: [...TESISAT_OVERRIDE_SOURCES, SOURCE_LEDGER.tsEn806, SOURCE_LEDGER.tsEn12056],
    keywords: ["sihhi tesisat", "pis su egimi", "temiz su", "TS EN 806", "TS EN 12056"],
  },
  {
    slugPath: "tesisat-isleri/elektrik-tesisati",
    kind: "topic",
    quote: "Elektrik tesisati, akimi tasimaktan once guvenli koruma ve okunabilir devre mantigi kurmalidir.",
    tip: "Kabloyu dosemek kolaydir; zor olan, yillar sonra bakım ekibinin o devreyi guvenle okuyup mudahale edebilmesidir.",
    intro: [
      "Elektrik tesisati; enerji dagitimi, priz-aydinlatma devreleri, pano sistemi, kablolama guzergahlari ve topraklama duzenini kapsar.",
      "Bu sistemin kalitesi, devrelerin calismasi kadar guvenli kapanma, etiketleme ve erişilebilir bakım duzeniyle olculur.",
      "Sahada görünür montaj cogu zaman tamamlanmis hissi verir; fakat koruma kurgusu dogrulanmamis, panosu okunmayan ve devreleri etiketlenmemis bir tesisat teknik olarak eksik kabul edilmelidir.",
    ],
    theory: [
      "Elektrik tesisatinda tasarim hedefi yalnizca enerji vermek degildir; kacak akim, kısa devre, secicilik ve bakım guvenligi gibi koruma ilkeleri de aynı derecede onemlidir.",
      "Kablo tavalari, borulama ve pano yerlesimi mimariden bagimsiz dusunulemez. Fiziksel guzergah hatalari, sonradan en çok kirma ve duzenleme gerektiren islerden biridir.",
      "TS HD 60364 serisinin dogrulama yaklasiminin da isaret ettigi gibi, enerji verilmeden once tesisatin olculmesi ve koruma mantiginin sahadaki gercek montajla uyustugunun gorulmesi gerekir. Ozellikle topraklama surekliligi, izolasyon direnci ve koruma cihazlarinin seciciligi kritik kabul kalemidir.",
      "Bu nedenle elektrik tesisati, cizimle baslayan ama ölçüm, etiketleme ve as-built butunluguyle tamamlanan sistem isidir.",
    ],
    ruleTable: [
      {
        parameter: "Devre korumasi ve topraklama",
        limitOrRequirement: "Koruma duzeni ve topraklama surekliligi dogrulanmali",
        reference: "TS HD 60364",
        note: "Devreye alma olcumleri yapilmadan teslim tamamlanmis sayilmaz.",
      },
      {
        parameter: "Kablo guzergahi",
        limitOrRequirement: "Fiziksel tasima sistemi bakım ve rezerv birakmali",
        reference: "TS HD 60364 + saha koordinasyonu",
        note: "Tava dolulugu ve erişim birlikte degerlendirilmelidir.",
      },
      {
        parameter: "Pano ve etiketleme",
        limitOrRequirement: "Devreler acikca tanimlanmali ve erişilebilir kalmali",
        reference: "Elektrik uygulama disiplini",
        note: "Etiketsiz pano uzun vadede güvenlik riski uretir.",
      },
      {
        parameter: "Dogrulama ve ölçüm",
        limitOrRequirement: "Izolasyon, sureklilik ve koruma kontrolleri enerji verme öncesi kayıt altina alinmali",
        reference: "TS HD 60364-6 dogrulama yaklasimi",
        note: "Çalışan sistem, olculmeden guvenli kabul edilmemelidir.",
      },
    ],
    designOrApplicationSteps: [
      "Pano ve devre semasini yuk listesiyle birlikte kesinlestir.",
      "Kablo guzergahlarini saft ve tavan koordinasyonuna göre yerlestir.",
      "Topraklama ve espotansiyel baglantilari montajin basindan itibaren kur.",
      "Kacak akim, asiri akim ve secicilik mantigini pano bazinda yazili hale getir.",
      "Izolasyon, sureklilik ve fonksiyon testlerini devreye alma öncesi tamamla.",
      "Tüm devre ve ekipmanlari etiketleyerek as-built setine isle.",
    ],
    criticalChecks: [
      "Pano onu ve bakım erisimi yeterli mi?",
      "Kablo tavalari asiri dolu mu?",
      "Topraklama surekliligi olculdu mu?",
      "Izolasyon testleri tamamlandi mi?",
      "Etiketleme sistemi as-built ile uyumlu mu?",
      "Koruma cihazlari ile gercek devre kurgusu aynı secicilik mantigini tasiyor mu?",
    ],
    numericalExample: {
      title: "Pano etiketleme ve devre sayisi için bakım yorumu",
      inputs: [
        { label: "Pano devre sayisi", value: "36 adet", note: "Aydinlatma, priz ve ozel yukler birlikte" },
        { label: "Etiketsiz devre adedi", value: "5 adet", note: "Devreye alma öncesi tespit" },
        { label: "Hedef", value: "0 etiketsiz devre", note: "Teslim kriteri" },
        { label: "Kritik risk", value: "Yanlış devreye mudahale", note: "Isletme guvenligi" },
      ],
      assumptions: [
        "Pano semasi guncel haldedir.",
        "Devre numaralari saha etiketleriyle eslesecektir.",
        "Etiketsiz devreler teslim öncesi kapatilacaktir.",
      ],
      steps: [
        {
          title: "Uygunsuzluk oranini oku",
          formula: "5 / 36 ~= %14",
          result: "Pano devrelerinin onemli bolumu bakım acisindan belirsizdir.",
          note: "Çalışan sistem, tanimli sistem demek degildir.",
        },
        {
          title: "Teslim kararini yorumla",
          result: "Etiketsiz devreler tamamlanmadan pano teslim edilmemelidir.",
          note: "Etiketleme, güvenlik ekipmaninin bir parcasidir.",
        },
        {
          title: "Bakım riskini degerlendir",
          result: "Yaklasik %14 belirsizlik, sahada yanlış kesici acma veya yanlış devreye mudahale riskini kabul edilemez duzeye tasir.",
          note: "Elektrikte küçük tanimsizlik, buyuk güvenlik riski uretir.",
        },
      ],
      checks: [
        "Her devre panoda ve saha ucunda aynı kodla tanimlanmalidir.",
        "Etiketleme as-built cizimle uyumlu olmalidir.",
        "Izolasyon ve fonksiyon testi etiketsiz devre birakmadan tamamlanmalidir.",
        "Pano kapak ici semasi ile sahadaki gercek dagilim aynı olmalidir.",
      ],
      engineeringComment: "Elektrik tesisatinda görünmez kalite, cogu zaman ölçüm ve etiketleme disiplininde saklidir.",
    },
    tools: TESISAT_OVERRIDE_TOOLS,
    equipmentAndMaterials: TESISAT_OVERRIDE_EQUIPMENT,
    mistakes: [
      { wrong: "Kablo guzergahini bosluk buldukca degistirmek.", correct: "Koordinasyon planina sadik kalmak." },
      { wrong: "Etiketlemeyi sonradan yapilacak iş saymak.", correct: "Montajin ayrilmaz parçası yapmak." },
      { wrong: "Topraklama olcusunu atlamak.", correct: "Teslim öncesi zorunlu test saymak." },
      { wrong: "Pano onunu farkli ekipmanlarla kapatmak.", correct: "Bakım alanini korumak." },
      { wrong: "Izolasyon testi olmadan devreye alma yapmak.", correct: "Ölçüm zincirini tamamlamak." },
      { wrong: "Test sonrasi saha revizyonlarini pano semasina islememek.", correct: "As-built ve pano tanimlarini aynı anda guncellemek." },
    ],
    designVsField: [
      "Tasarimda tek hat semasi yeterli gorunebilir; sahada ise kablo yolu, pano erisimi ve etiketleme olmadan guvenli isletme mumkun degildir.",
      "Bu nedenle elektrik tesisatinin gercek kalitesi, montaj tamamlandiginda degil ölçüm kayitlari ciktiginda gorulur.",
      "Iyi elektrik montaji yalnız enerji verir hale gelmis sistem degil; yillar sonra bile okunabilir ve emniyetli mudahale edilebilir sistemdir.",
    ],
    conclusion: [
      "Elektrik tesisati doğru planlandiginda hem guvenli hem okunabilir olur.",
      "Hatali planlandiginda ise yillarca surecek bakım ve güvenlik sorunlari uretir.",
    ],
    sources: [...TESISAT_OVERRIDE_SOURCES, SOURCE_LEDGER.tsHd60364],
    keywords: ["elektrik tesisati", "topraklama", "pano etiketleme", "TS HD 60364", "devreye alma"],
  },
];
