export const pdfViewerStrings = {
  viewer: "PDF görüntüleyici",
  toolbar: "PDF stüdyo araç çubuğu",
  backToManager: "Dosya Yöneticisine Dön",
  page: "Sayfa",
  pageNumber: (page: number) => `Sayfa ${page}`,
  pageCount: (count: number) => `${count} Sayfa`,
  pagePosition: (page: number, total: number) => `Sayfa ${page} / ${total}`,
  currentPage: "Geçerli Sayfa",
  previousPage: "Önceki Sayfa",
  nextPage: "Sonraki Sayfa",
  firstPage: "İlk Sayfaya Git",
  lastPage: "Son Sayfaya Git",
  pageLabel: (label: string) => `Sayfa Etiketi: ${label}`,
  pageJump: "Sayfaya git",
  pageJumpAction: (page: number, total: number) => `Sayfa ${page} / ${total}; sayfaya gitmek için etkinleştir`,
  pageScrubber: "PDF sayfa gezgini",
  close: "Kapat",
  closeSidebar: "Kenar çubuğunu kapat",
  sidebarToggle: "Kenar Çubuğunu Aç/Kapat",
  pages: "Sayfalar",
  pageThumbnails: "Sayfa küçük resimleri",
  pageList: (count: number) => `Sayfalar (${count})`,
  outlineEmpty: "Bu dokümanda içindekiler bulunmuyor.",
  collapse: "Daralt",
  expand: "Genişlet",
  outline: "İçindekiler",
  outlineBookmarks: "İçindekiler / Yer İmleri",
  historyBack: "Önceki Konuma Dön",
  historyBackLower: "Önceki konuma dön",
  historyForward: "Sonraki görünüme git",
  firstPageTitle: "İlk Sayfaya Git",
  previousPageTitle: "Önceki Sayfa",
  nextPageTitle: "Sonraki Sayfa",
  lastPageTitle: "Son Sayfaya Git",
  searchDocument: "Dokümanda Ara",
  searchDocumentShortcut: "Dokümanda Ara (Ctrl+F)",
  textSelectionTool: "Metin Seçim İmleci",
  textSelectionToolShortcut: "Metin Seçim İmleci (V)",
  handTool: "Kaydırma / El Aracı",
  handToolShortcut: "Kaydırma / El Aracı (H)",
  zoom: "Yakınlaştırma",
  zoomMenuTitle: (percent: number) => `Ölçek Menüsü · ${percent}%`,
  zoomMenuLabel: (percent: number) => `Yakınlaştırma menüsü, yüzde ${percent}`,
  zoomOut: "Uzaklaştır",
  zoomOutShortcut: "Uzaklaştır (Ctrl+-)",
  zoomIn: "Yakınlaştır",
  zoomInShortcut: "Yakınlaştır (Ctrl++)",
  fitWidth: "Genişliğe sığdır",
  fitWidthName: "Genişliğe Sığdır",
  fitWidthTitle: "Genişliğe Sığdır (Ctrl+2)",
  fitPage: "Sayfaya sığdır",
  fitPageName: "Sayfaya Sığdır",
  fitPageTitle: "Sayfaya Sığdır (Ctrl+0)",
  actualSize: "Gerçek boyut (%100)",
  originalSize: "Orijinal boyut (%100)",
  textRepairTooltip: "Bozuk font harf eşlemesi (Ĝ -> i) kopyalama ve aramada otomatik onarıldı",
  textRepaired: "Metin onarıldı",
  rotateClockwise: "Görünümü Saat Yönünde Döndür (Ctrl+Shift++)",
  rotateView: "Görünümü döndür",
  printPdf: "PDF Yazdır (Ctrl+P)",
  downloadPdf: "PDF İndir",
  downloadPdfShortcut: "PDF İndir",
  fullscreenExit: "Tam Ekrandan Çık",
  fullscreenEnter: "Tam Ekran Yap",
  morePdfActions: "PDF ek işlemleri",
  shareLink: "Paylaşım bağlantısı oluştur",
  shareLinkShortcut: "Paylaşım Bağlantısı Oluştur (Ctrl+Shift+S)",
  rename: "Yeniden Adlandır",
  moveToTrash: "Çöp Kutusuna At",
  rememberPosition: "Son okunan konumu hatırla",
  on: "Açık",
  off: "Kapalı",
  system: "Sistem",
  nightMode: "Gece modu",
  defaultView: "Varsayılan görünüm",
  reduceMotion: "Hareketleri azalt",
  repairBrokenText: "Bozuk harf onarımı (Ĝ → i)",
  keyboardShortcuts: "Klavye kısayolları",
  bookmarks: "Yer imleri",
  search: "Ara",
  searchBar: "Doküman içi metin arama",
  searchInput: "Dokümanda ara",
  searchPlaceholder: "Dokümanda ara...",
  searchOptions: "Arama Seçenekleri",
  previousMatch: "Önceki Eşleşme",
  previousMatchShortcut: "Önceki Eşleşme (Shift+Enter)",
  nextMatch: "Sonraki Eşleşme",
  nextMatchShortcut: "Sonraki Eşleşme (Enter)",
  allResults: "Tüm Sonuçları Listele",
  resultList: "Sonuç Listesi",
  closeSearch: "Aramayı Kapat",
  closeSearchShortcut: "Kapat (Esc)",
  scannedPdf: "Bu PDF taranmış görüntü içeriyor, metin araması yapılamaz.",
  caseSensitive: "Büyük/küçük harf duyarlı",
  turkishLetterSensitive: "Türkçe harflere duyarlı (I ≠ İ)",
  wholeWord: "Tam kelime",
  searching: "Aranıyor...",
  matchCount: (total: number, current: number) => `${total} eşleşmeden ${current}. gösteriliyor`,
  matchNotFound: "Eşleşme bulunamadı",
  searchResults: "Arama Sonuçları",
  searchResultsCount: (count: number, overflow: boolean) => `Arama Sonuçları (${count}${overflow ? "+" : ""})`,
  searchResultsList: "Arama sonuçları listesi",
  closeSearchPanel: "Arama panelini kapat",
  searchedFor: "Aranan:",
  noMatches: "Eşleşen sonuç bulunamadı.",
  tryAnotherWord: "Farklı bir kelime deneyebilirsiniz.",
  pageLink: "PDF içi bağlantıya git",
  pageLinkTitle: "Sayfa bağlantısı",
  externalLink: (url: string) => `Harici bağlantıyı aç: ${url}`,
  loadingPasswordError: "Hatalı parola. Lütfen tekrar deneyin.",
  passwordProtectedTitle: "Parola Korumalı Belge",
  passwordProtectedDescription: "Bu PDF dokümanını görüntülemek için parola gereklidir.",
  documentPassword: "Belge Parolası",
  enterPassword: "Parolayı girin...",
  cancel: "Vazgeç",
  openDocument: "Belgeyi Aç",
  shortcutsTitle: "Klavye Kısayolları",
  shortcutsDescription: "PDF stüdyosunda hızlı kullanım için desteklenen klavye kısayolları",
  shortcutsZoomCategory: "Zoom ve Ölçek",
  shortcutsPageCategory: "Sayfa Gezinimi",
  shortcutsToolsCategory: "Araçlar ve Paneller",
  shortcutOr: "veya",
  shortcutPreviousPage: "Önceki Sayfa",
  shortcutNextPage: "Sonraki Sayfa",
  shortcutFirstPage: "İlk Sayfaya Git",
  shortcutLastPage: "Son Sayfaya Git",
  shortcutFind: "Dokümanda Ara",
  shortcutHandTool: "El Aracı (Sayfayı Kaydır / Pan)",
  shortcutTextSelection: "Metin Seçim İmleci",
  shortcutSidebar: "Küçük Resimler Kenar Çubuğu",
  shortcutRotate: "90° Sağa Döndür",
  shortcutEscape: "Arama / Panelleri Kapat",
  shortcutHelp: "Klavye Kısayolları (Bu Menü)",
  understood: "Anladım",
  viewerLoading: "Belge yükleniyor",
  refreshingAccess: "PDF erişim bağlantısı yenileniyor...",
  loadingPdfPercent: (percent: number) => `PDF dokümanı yükleniyor (%${percent})...`,
  preparingPdf: "PDF dokümanı ve katmanlar hazırlanıyor...",
  viewerLoadingError: "PDF yüklenemedi",
  corruptTitle: "Bozuk veya Geçersiz Dosya",
  missingTitle: "Dosya Bulunamadı",
  loadErrorTitle: "PDF Yükleme Hatası",
  downloadFile: "Dosyayı İndir",
  enterPasswordButton: "Parola Gir",
  retryButton: "Yeniden Dene",
  retry: "Yeniden dene",
  corruptPdf: "PDF dosyası bozuk veya geçersiz bir formatta.",
  missingPdf: "PDF dosyası sunucuda veya depolama alanında bulunamadı.",
  passwordError: "Bu belge parola korumalıdır. Açmak için lütfen geçerli bir parola girin.",
  accessRefreshError: "PDF erişim bağlantısı yenilenemedi. Lütfen sayfayı yenileyin.",
  genericLoadError: "PDF dokümanı yüklenirken bir hata oluştu.",
  pageLoadError: (page: number) => `Sayfa ${page} alınamadı:`,
  pageRenderError: (page: number) => `Sayfa ${page} render hatası:`,
  loading: "Belge yükleniyor",
  loadingError: "PDF yüklenemedi",
  openNewTab: "Yeni sekmede aç",
  password: "Parola",
  wrongPassword: "Parola hatalı",
  unsupportedBrowser: "Bu tarayıcı sürümü PDF görüntüleyiciyi desteklemiyor. Dosyayı indirip cihazınızdaki PDF uygulamasında açabilirsiniz.",
  unsupportedTitle: "Desteklenmeyen Tarayıcı",
} as const;
