import fs from "fs";
import path from "path";
import { getAllIndexedBinaNodes, type IndexedBinaNode } from "../src/lib/bina-asamalari";

export interface CanonicalBriefV2 {
  id: string;
  // PRIMARY
  primaryMode: "site-process" | "installed-component" | "technical-cutaway" | "project-visual";
  primaryFocus: string;
  primaryMustShow: string[];
  primaryMustNotShow: string[];
  // SECONDARY
  secondaryMode: "site-process" | "installed-component" | "technical-cutaway" | "project-visual";
  secondaryPlacement: "overview" | "application" | "technical-detail" | "quality-control";
  secondaryFocus: string;
  secondaryMustShow: string[];
  secondaryMustNotShow: string[];
  secondaryDifference: string;
}

export const CANONICAL_BRIEFS_V2: Record<string, CanonicalBriefV2> = {
  // ==========================================
  // 1. PROJE & İZİNLER (6 Konu)
  // ==========================================
  "proje-hazirlik": {
    id: "proje-hazirlik",
    primaryMode: "project-visual",
    primaryFocus: "Tasarım koordinasyonu, mimari maket ve çizim paftaları genel görünümü",
    primaryMustShow: ["mimari fiziksel maket", "çizim paftaları üzerinde plan ve kesit geometrileri", "koordinasyon masası"],
    primaryMustNotShow: ["okunur metin", "sahte resmi mühür", "ölçü rakamları", "logo"],
    secondaryMode: "project-visual",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Metinsiz BIM çakışma tespiti ve disiplinler arası 3D koordinasyon modeli",
    secondaryMustShow: ["çakışan mekanik kanal ve statik kiriş aksı 3D modeli", "koordinasyon kesiti", "farklı disiplin renk kodları"],
    secondaryMustNotShow: ["yazılım menüleri", "okunur etiketler", "harf/rakam", "pseudo-text"],
    secondaryDifference: "Primary genel mimari maket ve pafta masasını gösterirken, secondary metinsiz 3D BIM çakışma ve disiplin koordinasyon detayını öğretir.",
  },
  "mimari-proje": {
    id: "mimari-proje",
    primaryMode: "project-visual",
    primaryFocus: "Mimari plan ve kesit geometrileri ile temiz bina kütlesi ilişkisi",
    primaryMustShow: ["mimari kat planı geometrisi", "kesit çizgileri", "mekan hacimleri", "temiz bina kütlesi"],
    primaryMustNotShow: ["okunur oda isimleri", "ölçü rakamları", "lejant yazıları", "logo"],
    secondaryMode: "project-visual",
    secondaryPlacement: "application",
    secondaryFocus: "Plan-kesit ve düşey sirkülasyon (merdiven/galeri) hacim ilişkisini anlatan teknik kesit",
    secondaryMustShow: ["bina düşey kesiti", "döşeme kotları ve merdiven boşluğu ilişkisi", "iç mekan akışı"],
    secondaryMustNotShow: ["yazı", "ölçü etiketleri", "sahte semboller"],
    secondaryDifference: "Primary plan kütle ilişkisini sunarken, secondary düşey kesitte merdiven ve galeri sirkülasyon hacimlerini detaylandırır.",
  },
  "statik-proje": {
    id: "statik-proje",
    primaryMode: "project-visual",
    primaryFocus: "Taşıyıcı sistem şeması, kolon-kiriş aksları ve 3D yapısal çerçeve modeli",
    primaryMustShow: ["3D yapısal çerçeve modeli", "kolon ve kiriş aks çizgileri", "taşıyıcı sistem şeması"],
    primaryMustNotShow: ["yazılım arayüzü (UI)", "okunur metin", "boyutlandırma etiketleri"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kolon-kiriş-döşeme yük aktarımı çerçeve düğüm noktası gerilme diyagramı",
    secondaryMustShow: ["çerçeve düğüm noktası", "moment ve kesme kuvveti yönleri", "mesnet rijitliği birleşimi"],
    secondaryMustNotShow: ["okunur formüller", "sayısal değerler", "yazılım grafikleri"],
    secondaryDifference: "Primary binanın genel 3D taşıyıcı karkasını gösterirken, secondary tek bir düğüm noktasındaki yük aktarım çerçeve davranışını öğretir.",
  },
  "tesisat-projesi": {
    id: "tesisat-projesi",
    primaryMode: "project-visual",
    primaryFocus: "Bina kesitinde mekanik tesisat boru güzergahları ve şaft koordinasyonu",
    primaryMustShow: ["mekanik tesisat şaftları", "boru güzergahı geometrisi", "mimari kesit içinde tesisat akışı"],
    primaryMustNotShow: ["okunur boru çapı yazıları", "etiketler", "sahte şema açıklamaları"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kazan dairesi ve kollektör dağıtım merkezi borulama ve vana grubu kesiti",
    secondaryMustShow: ["ana dağıtım kollektörü", "gidiş-dönüş boru grupları", "sirkülasyon pompaları ve vanalar"],
    secondaryMustNotShow: ["okunur etiketler", "basınç göstergesi yazıları", "marka"],
    secondaryDifference: "Primary binadaki düşey şaft dağılımını gösterirken, secondary ana kollektör ve mekanik santral detayını kesit olarak öğretir.",
  },
  "elektrik-projesi": {
    id: "elektrik-projesi",
    primaryMode: "project-visual",
    primaryFocus: "Elektrik tava hatları, ana dağıtım ve aydınlatma linyesi proje koordinasyonu",
    primaryMustShow: ["kablo tavası güzergah geometrisi", "elektrik şaftı yerleşimi", "dağıtım hatları akışı"],
    primaryMustNotShow: ["pseudo-text", "okunur devre numaraları", "sahte sembol lejantı"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Zayıf akım ve kuvvetli akım şaft ayrımı ve kat pano besleme detayı",
    secondaryMustShow: ["kat dağıtım panosu", "zayıf akım ve kuvvetli akım tepsileri", "şaft duvar geçişi yangın durdurucu"],
    secondaryMustNotShow: ["yazı", "amper değerleri", "marka logoları"],
    secondaryDifference: "Primary tavan tava güzergahını gösterirken, secondary şaft içindeki zayıf akım-kuvvetli akım ayrımı ve yangın durdurucu detayı öğretir.",
  },
  "yapi-ruhsati": {
    id: "yapi-ruhsati",
    primaryMode: "project-visual",
    primaryFocus: "Onaylı proje setleri ve inşaata başlama hazırlığı bağlamı",
    primaryMustShow: ["rulo proje paftaları", "şantiye baret ve koordinasyon bağlamı", "inşaat başlangıç hazırlığı"],
    primaryMustNotShow: ["sahte belediye evrakı", "sahte mühür", "okunur imza/yazı"],
    secondaryMode: "site-process",
    secondaryPlacement: "overview",
    secondaryFocus: "Şantiye sahasında parsel köşe kazıkları ve onaylı plankote aplikasyon kontrolü",
    secondaryMustShow: ["total station ile köşe aplikasyonu", "ahşap aplikasyon kazıkları", "parsel sınır şeridi"],
    secondaryMustNotShow: ["sahte resmi evrak", "yazı", "harf/rakam"],
    secondaryDifference: "Primary ofis proje setlerini gösterirken, secondary ruhsat sonrası sahada yapılan ilk parsel köşe aplikasyonunu öğretir.",
  },

  // ==========================================
  // 2. KAZI & TEMEL (13 Konu)
  // ==========================================
  "kazi-temel": {
    id: "kazi-temel",
    primaryMode: "site-process",
    primaryFocus: "Kazı platformu, iksa sistemleri ve temel hazırlığının genel saha bağlamı",
    primaryMustShow: ["açılmış temel çukuru", "paletli ekskavatör", "iksa perdesi", "şantiye güvenlik sınırı"],
    primaryMustNotShow: ["kolaj", "yazı", "ölçü etiketleri", "sahte tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Temel çukuru taban drenajı, kuyu pompası ve şev stabilitesi kesiti",
    secondaryMustShow: ["taban drenaj çakılı ve drenfleks boru", "dalgıç pompa terfi çukuru", "temel kotu altı zemin katmanı"],
    secondaryMustNotShow: ["yazı", "rakam", "oklar"],
    secondaryDifference: "Primary geniş kazı çukuru sahnesini sunarken, secondary taban suyu tahliye ve drenaj altyapı kesitini öğretir.",
  },
  "zemin-etudu": {
    id: "zemin-etudu",
    primaryMode: "site-process",
    primaryFocus: "Sondaj makinesi, karot numune sandıkları ve zemin araştırma operasyonu",
    primaryMustShow: ["arazi sondaj makinesi", "sondaj tijleri", "karot numune sandığı ve zemin karotları"],
    primaryMustNotShow: ["cihaz üzerinde okunur marka", "sahte rapor kağıtları", "yazı"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Sondaj derinliği boyunca zemin profil katmanları ve karot numune tüpü kesiti",
    secondaryMustShow: ["SPT numune alıcı tüp (split spoon)", "zemin katman tabakaları (kil, kum, çakıl, kaya)", "yer altı su seviyesi sınırı"],
    secondaryMustNotShow: ["yazı", "metre rakamları", "grafik etiketleri"],
    secondaryDifference: "Primary arazideki sondaj makinesini gösterirken, secondary yeraltı zemin profili ve numune alıcı tüp kesitini öğretir.",
  },
  "hafriyat": {
    id: "hafriyat",
    primaryMode: "site-process",
    primaryFocus: "Ekskavatörün temel çukurunda kademeli kazı yapması ve kamyon yüklemesi",
    primaryMustShow: ["ağır iş makinesi ekskavatör", "kademe şevli kazı yüzeyi", "hafriyat kamyonu", "doğal toprak katmanı"],
    primaryMustNotShow: ["oyuncak/plastik render", "yazı", "logo"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Kazı tabanında nivo kontrolü ve son 20 cm taban tesviyesi hassas kazısı",
    secondaryMustShow: ["lazer nivo veya optik nivo ile kot kontrolü", "düz kovalı tesviye ekskavatörü", "taban kot kazıkları"],
    secondaryMustNotShow: ["ölçü rakamları", "yazı", "sahte tabela"],
    secondaryDifference: "Primary kaba hafriyat yüklemesini gösterirken, secondary taban kotuna yaklaşırken yapılan hassas tesviye ve kot doğrulamasını öğretir.",
  },
  "iksa-sistemi": {
    id: "iksa-sistemi",
    primaryMode: "technical-cutaway",
    primaryFocus: "Derin kazı çukurunu tutan betonarme iksa perdesi ve zemin katmanı ilişkisi",
    primaryMustShow: ["düşey iksa perdesi", "arka zemin kütlesi", "temel kazı tabanı", "güvenli destekleme sistemi"],
    primaryMustNotShow: ["ölçü çizgileri", "yazı", "anlamsız renkli neon hatlar"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "İksa perdesinin arkasındaki zemin basıncı prizması ve yatay kuşak kirişi birleşimi",
    secondaryMustShow: ["çelik veya betonarme kuşak kirişi", "zemin itki çizgisi yönleri", "perde bağlantı detay kesiti"],
    secondaryMustNotShow: ["yazı", "rakam", "sembol etiketleri"],
    secondaryDifference: "Primary iksa perdesinin genel zemin ilişkisini sunarken, secondary yatay kuşak kirişinin perdeye aktardığı yük düğümünü öğretir.",
  },
  "fore-kazik": {
    id: "fore-kazik",
    primaryMode: "site-process",
    primaryFocus: "Döner delgi makinesi (fore kazık makinesi) ve donatı kafesi yerleşimi",
    primaryMustShow: ["büyük fore kazık delgi makinesi (rotary drilling rig)", "silindirik donatı kafesi", "şantiye zemini"],
    primaryMustNotShow: ["okunur marka", "yazı", "sahte tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Tremie borusu ile kuyu tabanından yukarıya doğru su altı beton döküm kesiti",
    secondaryMustShow: ["kuyu içindeki tremie borusu", "tabandan yükselen taze beton", "bentonit çamurunun yukarı ötelenmesi", "silindirik donatı"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary makinenin donatıyı kuyuya indirmesini gösterirken, secondary kuyu içinde tremie borusuyla betonlama dinamiğini kesit olarak öğretir.",
  },
  "ankrajli-iksa": {
    id: "ankrajli-iksa",
    primaryMode: "technical-cutaway",
    primaryFocus: "İksa perdesi yüzeyindeki çelik ankraj başlıkları ve zemine eğik uzanan kök ankrajlar",
    primaryMustShow: ["betonarme iksa yüzeyi", "çelik ankraj plakaları ve başlıkları", "zemine eğik giren ankraj halatları"],
    primaryMustNotShow: ["etiket yazıları", "oklar", "şematik metinler"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Hidrolik kriko ile öngermeli zemin ankrajı halatlarının gerilmesi ve kilitlenmesi",
    secondaryMustShow: ["hidrolik germe krikosu", "çoklu çelik halat demetleri (tendon)", "ankraj kamaları ve manometre"],
    secondaryMustNotShow: ["yazı", "ölçü rakamı", "marka logosu"],
    secondaryDifference: "Primary ankrajın zemin içindeki kesit geometrisini gösterirken, secondary sahada hidrolik krikoyla yapılan halat gerdirme operasyonunu öğretir.",
  },
  "palplans": {
    id: "palplans",
    primaryMode: "site-process",
    primaryFocus: "Kilitli çelik palplanş perdelerinin vibro-çekiç ile zemine çakılması",
    primaryMustShow: ["oluklu çelik palplanş profilleri", "birbirine kenetlenen çelik kilitler", "vibro çakıcı ekipman"],
    primaryMustNotShow: ["yazı", "ölçü", "sahte marka"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Çelik palplanş kilit birleşim kesiti (Larssen interlock) ve su geçirimsizlik dolgusu",
    secondaryMustShow: ["birbirine geçen Larssen tipi kilit geometrisi", "kilit arası sızdırmazlık mastiği", "çelik et kalınlığı kesiti"],
    secondaryMustNotShow: ["yazı", "ölçü okları", "etiket"],
    secondaryDifference: "Primary sahada palplanş çakımını gösterirken, secondary çelik kilitlerin mikro düzeydeki birbirine geçiş ve sızdırmazlık kesitini öğretir.",
  },
  "temel-turleri": {
    id: "temel-turleri",
    primaryMode: "technical-cutaway",
    primaryFocus: "Tekil sömel, sürekli temel ve radye plağın zemin üzerindeki izometrik yapısal kesiti",
    primaryMustShow: ["temel plağı geometrisi", "zemin temas yüzeyi", "kolon filizleri bağlantısı"],
    primaryMustNotShow: ["metin etiketleri", "oda isimleri", "ölçü rakamları"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Farklı temel tiplerinde zemin gerilme dağılım soğanları (stress bulb) kesiti",
    secondaryMustShow: ["temel altı basınç yayılım eğrileri", "farklı derinliklerde gerilme konsantrasyonu", "homojen zemin modeli"],
    secondaryMustNotShow: ["formül", "yazı", "sayısal değerler"],
    secondaryDifference: "Primary temel geometrilerinin fiziksel kütlelerini gösterirken, secondary temel altındaki zemin gerilme dağılımını kesit olarak öğretir.",
  },
  "radye-temel": {
    id: "radye-temel",
    primaryMode: "site-process",
    primaryFocus: "Geniş alanlı radye temel donatı ağı, sehpa demirleri ve kolon filizleri",
    primaryMustShow: ["çift kat yoğun nervürlü donatı ağı", "donatı sehpaları", "yükselen kolon filiz demirleri"],
    primaryMustNotShow: ["çizgi ikon", "yazı", "filigran"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Radye plak kesitinde alt donatı, üst donatı, pas payı takozu ve zımbalama donatısı detayı",
    secondaryMustShow: ["çift sıra donatı katmanı", "pas payı elemanı", "kolon tabanında zımbalama donatıları (stud rayı)", "grobeton yatağı"],
    secondaryMustNotShow: ["ölçü rakamları", "yazı", "lejant"],
    secondaryDifference: "Primary sahadaki geniş donatı alanını gösterirken, secondary radye plak kesitindeki zımbalama donatısı ve pas payı katman ilişkisini öğretir.",
  },
  "grobeton": {
    id: "grobeton",
    primaryMode: "site-process",
    primaryFocus: "Kazılmış temel tabanına temiz grobeton tabakasının serilmesi ve mastarlanması",
    primaryMustShow: ["düzeltilmiş zemin üzerine dökülen açık gri grobeton", "mastar ile yüzey düzleme", "temiz düz taban"],
    primaryMustNotShow: ["yazı", "ölçü", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Sıkıştırılmış blokaj taşı, kum yatağı, polietilen örtü ve grobeton katman kesiti",
    secondaryMustShow: ["en altta sıkışmış tüvenan zemin", "blokaj taş tabakası", "naylon örtü (rutubet bariyeri)", "10 cm grobeton plağı"],
    secondaryMustNotShow: ["yazı", "cm rakamları", "oklar"],
    secondaryDifference: "Primary sahadaki grobeton dökümünü gösterirken, secondary grobetonun altındaki blokaj ve buhar kesici katman kesitini öğretir.",
  },
  "temel-donati": {
    id: "temel-donati",
    primaryMode: "site-process",
    primaryFocus: "Radye temel alt ve üst donatı örgüsü, pas payı takozları ve bağ telleri",
    primaryMustShow: ["nervürlü çelik donatı ızgarası", "beton pas payı takozları", "bağ teli düğümleri"],
    primaryMustNotShow: ["ölçü oku", "yazı", "anlamsız semboller"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Temel donatı bindirme boyu (ek boyu) ve şaşırtmalı ek yerleşimi teknik detayı",
    secondaryMustShow: ["iki nervürlü donatının yan yana bindirmesi", "ek yerinde sıklaştırılmış bağ telleri", "şaşırtmalı donatı ek aksları"],
    secondaryMustNotShow: ["yazı", "rakam", "etiket"],
    secondaryDifference: "Primary sahadaki genel donatı örgüsünü gösterirken, secondary donatı bindirme boyu ve şaşırtmalı ek kurallarını kesit olarak öğretir.",
  },
  "temel-betonlama": {
    id: "temel-betonlama",
    primaryMode: "site-process",
    primaryFocus: "Mobil beton pompası bomu ile temele sürekli taze beton dökümü ve yayılması",
    primaryMustShow: ["beton pompası esnek kauçuk hortumu", "taze beton akışı", "donatı arasına dolan beton"],
    primaryMustNotShow: ["logo", "okunur yazı", "sahte tabela"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Dökülen taze betonun lazer nivo kontrolünde helikopter perdahı öncesi mastarlanması",
    secondaryMustShow: ["uzun aluminyum vibratörlü mastar", "lazer alıcılı nivo çıtası", "pürüzsüzleştirilen taze beton yüzeyi"],
    secondaryMustNotShow: ["yazı", "marka", "deforme insan"],
    secondaryDifference: "Primary pompadan beton akışını gösterirken, secondary dökülen betonun yüzey kot doğruluğu için mastarlanma aşamasını öğretir.",
  },
  "temel-su-yalitimi": {
    id: "temel-su-yalitimi",
    primaryMode: "technical-cutaway",
    primaryFocus: "Temel altı ve perde duvar dışındaki bitümlü membran yalıtım katmanının sürekliliği",
    primaryMustShow: ["temel altı yalıtım membranı", "pah detayında bükülen membran", "perde duvara tırmanan yalıtım", "koruma katmanı"],
    primaryMustNotShow: ["ürün katalog etiketi", "yazı", "ölçü"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Şalümö alevi ile bitümlü su yalıtım membranının ek yerlerinin eritilerek kaynaklanması",
    secondaryMustShow: ["şalümö hamlacı ve alev", "rulo bitümlü membran", "10 cm bindirme payında sızan sıcak bitüm çizgisi"],
    secondaryMustNotShow: ["yazı", "marka logosu", "tabela"],
    secondaryDifference: "Primary sistemin bina köşesindeki katman kesitini gösterirken, secondary sahada şalümö ile membran ek yeri kaynaklama tekniğini öğretir.",
  },

  // ==========================================
  // 3. KABA İNŞAAT (25 Konu)
  // ==========================================
  "kaba-insaat": {
    id: "kaba-insaat",
    primaryMode: "site-process",
    primaryFocus: "Betonarme iskeletin yükseldiği şantiye: kolonlar, döşeme kalıpları ve kule vinç",
    primaryMustShow: ["betonarme kolon ve perdeler", "döşeme kalıp iskeleleri", "gökyüzüne yükselen katlar", "kule vinç bomu"],
    primaryMustNotShow: ["kolaj", "yazı", "logo", "aşırı sinematik neon"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Tipik kat betonarme çerçevesi: kolon, kiriş, döşeme ve perde birleşim donatı kesiti",
    secondaryMustShow: ["kolon donatı kafesi", "kiriş gövde donatıları", "döşeme hasır ağı", "beton dökülmüş kesit geçişi"],
    secondaryMustNotShow: ["yazı", "ölçü", "çizgi sembol"],
    secondaryDifference: "Primary yükselen şantiyenin genel görünümünü sunarken, secondary karkasın içindeki donatı-kalıp-beton anatomisini kesit olarak öğretir.",
  },
  "kalip-isleri": {
    id: "kalip-isleri",
    primaryMode: "site-process",
    primaryFocus: "Endüstriyel çelik çerçeveli plywood kalıp panelleri ve teleskopik dikmeler",
    primaryMustShow: ["plywood kalıp yüzeyleri", "çelik kalıp kilitleri", "teleskopik dikme direkleri"],
    primaryMustNotShow: ["yazı", "marka", "ölçü"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kalıp paneli arkasındaki tie-rod (tayrot) mili, koni ve boru koruma kesiti",
    secondaryMustShow: ["çift taraflı kalıp paneli", "ortadan geçen tie-rod çelik mili", "plastik koruma borusu ve konisi", "kelebek somun"],
    secondaryMustNotShow: ["yazı", "rakam", "ölçü çizgisi"],
    secondaryDifference: "Primary sahadaki kalıp kurulumunu gösterirken, secondary kalıbı tutan tie-rod ve su geçirimsizlik konisi detayını öğretir.",
  },
  "kolon-kalibi": {
    id: "kolon-kalibi",
    primaryMode: "site-process",
    primaryFocus: "Düşey kolon kalıp paneli, çelik kuşaklar ve şakül ayar payandaları",
    primaryMustShow: ["düşey kalıp panelleri", "kolon kelepçe ve kuşakları", "çapraz ayar payandaları"],
    primaryMustNotShow: ["yazı", "ölçü", "logo"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "Kolon kalıbının çift yönde şakül ve şakül ipi / lazer ile düşeylik kontrolü",
    secondaryMustShow: ["kalıp köşesinde asılı ağır pirinç şakül", "şakül ipi mesafesi kontrolü", "ayar payandası krikosu"],
    secondaryMustNotShow: ["yazı", "ölçü rakamı", "etiket"],
    secondaryDifference: "Primary kalıbın montajını gösterirken, secondary kalıbın düşey eksenden sapmaması için yapılan hassas şakül ölçümünü öğretir.",
  },
  "kiris-kalibi": {
    id: "kiris-kalibi",
    primaryMode: "site-process",
    primaryFocus: "Kiriş taban ve kanat kalıpları, döşeme bağlantısı ve alt taşıyıcı iskele",
    primaryMustShow: ["U şekilli kiriş kalıp kanatları", "kalıp altı H-iskele veya dikmeler", "kolon birleşim boğazı"],
    primaryMustNotShow: ["ölçü çizgisi", "yazı", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kiriş kanadı açılma önleyici payandası ve taban ahşap H20 desteği kesiti",
    secondaryMustShow: ["kiriş taban plywood plakası", "yan kanat dikliği desteği", "ters sehim (camber) ayar krikosu"],
    secondaryMustNotShow: ["yazı", "rakam", "oklar"],
    secondaryDifference: "Primary kiriş kalıbının iskele kurgusunu gösterirken, secondary yan basıncı karşılayan payanda ve ters sehim detayını kesit olarak öğretir.",
  },
  "doseme-kalibi": {
    id: "doseme-kalibi",
    primaryMode: "site-process",
    primaryFocus: "Geniş döşeme kalıp platformu, ana ve tali ahşap H20 kirişler ve teleskopik dikmeler",
    primaryMustShow: ["sarı H20 ahşap kirişler", "düzgün döşenmiş plywood plakalar", "aşağıdaki teleskopik dikme ormanı"],
    primaryMustNotShow: ["yazı", "logo", "ölçü"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Döşeme kalıbı dört yollu başlık, ana taşıyıcı ve tali taşıyıcı ızgara kesit detayı",
    secondaryMustShow: ["dikme tepesindeki çelik 4 yollu başlık", "ana sarı H20 kiriş", "tali H20 kirişler", "üst plywood birleşimi"],
    secondaryMustNotShow: ["yazı", "cm ölçüsü", "etiket"],
    secondaryDifference: "Primary geniş kalıp platformunu gösterirken, secondary dikme başlığı ile ahşap kirişlerin kesiştiği yük aktarma düğümünü öğretir.",
  },
  "kalip-sokumu": {
    id: "kalip-sokumu",
    primaryMode: "site-process",
    primaryFocus: "Betonu prizini almış kolon veya kiriş kanat kalıbının levyeyle dikkatle sökülmesi",
    primaryMustShow: ["sertleşmiş pürüzsüz beton yüzey", "açılan kalıp paneli", "emniyetli çalışma pozisyonu"],
    primaryMustNotShow: ["yazı", "parçalanmış beton", "deforme el"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Döşeme kalıbı sökümünde güvenlik dikmelerinin (re-shore) yerinde bırakılması",
    secondaryMustShow: ["kalıbı alınmış tavan betonu", "belirli aralıklarla bırakılmış çelik güvenlik dikmeleri", "döşeme sehim koruması"],
    secondaryMustNotShow: ["yazı", "rakam", "uyarı tabelası"],
    secondaryDifference: "Primary panellerin sökülme anını gösterirken, secondary betonun yükünü taşımak için tavanda bırakılan güvenlik dikmelerini öğretir.",
  },
  "donati-isleri": {
    id: "donati-isleri",
    primaryMode: "site-process",
    primaryFocus: "Nervürlü inşaat demirlerinin sahada bağlanması ve donatı hazırlığı",
    primaryMustShow: ["inşaat demirleri demeti", "demirci kerpeteni ile bağ teli bağlama", "döşeme veya kolon donatı kurgusu"],
    primaryMustNotShow: ["yazı", "ölçü oku", "çizgi sembol"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Nervürlü donatının kanca büküm yarıçapı ve standart büküm mandrel detayı",
    secondaryMustShow: ["90 ve 135 derece bükülmüş nervürlü çelik çubuk", "iç büküm kavisi", "çeliğin çatlamamış dış yüzeyi"],
    secondaryMustNotShow: ["yazı", "çap rakamları", "açı derecesi metni"],
    secondaryDifference: "Primary sahadaki donatı bağlama sürecini gösterirken, secondary donatının doğru çapta mandrelle bükülme standardını öğretir.",
  },
  "kolon-donati": {
    id: "kolon-donati",
    primaryMode: "site-process",
    primaryFocus: "Düşey kolon donatı kafesi, boyuna donatılar ve yatay etriyeler",
    primaryMustShow: ["dik kolon donatı çubukları", "sık etriye halkaları", "filiz bindirme boyu"],
    primaryMustNotShow: ["çizgi ikon", "yazı", "ölçü"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kolon sarılma bölgesinde etriye sıklaştırması ve 135 derece deprem kancası detayı",
    secondaryMustShow: ["alt ve üst sarılma bölgesinde 10 cm aralıklı etriyeler", "135 derece içe bükülen etriye kancaları", "boyuna donatıyı kavrayan çirot"],
    secondaryMustNotShow: ["yazı", "ölçü çizgileri", "oklar"],
    secondaryDifference: "Primary kolon kafesinin tüm boyunu gösterirken, secondary sarılma bölgesindeki 135 derece kanca ve etriye sıklaştırmasını öğretir.",
  },
  "kiris-donati": {
    id: "kiris-donati",
    primaryMode: "site-process",
    primaryFocus: "Kiriş donatı sepeti, alt-üst boyuna donatılar, pilyeler ve etriyeler",
    primaryMustShow: ["kiriş donatı sepeti", "etriye dizilimi", "kolon-kiriş birleşim düğümüne giren donatılar"],
    primaryMustNotShow: ["yazı", "ölçü oku", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kolon-kiriş birleşim düğümünde kiriş donatılarının kolon içine gömülme ve kenetlenme detayı",
    secondaryMustShow: ["kolon çekirdeği içine giren kiriş üst donatısı", "90 derece aşağı bükülen gönyeli ankraj", "düğüm noktası etriyeleri"],
    secondaryMustNotShow: ["yazı", "rakam", "sembol"],
    secondaryDifference: "Primary kiriş boy donatı sepetini gösterirken, secondary kolon içine kenetlenen donatının 90 derece gönye detayını kesit olarak öğretir.",
  },
  "doseme-donati": {
    id: "doseme-donati",
    primaryMode: "site-process",
    primaryFocus: "Döşeme donatısı çift yönlü hasır ağı ve mesnet ek donatıları",
    primaryMustShow: ["döşeme kalıbı üzerindeki alt donatı ızgarası", "mesnet üst donatıları", "pas payı takozları"],
    primaryMustNotShow: ["yazı", "ölçü", "filigran"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Döşeme donatısında sehpa demirinin alt ve üst donatıyı ayırma mesafesi kesiti",
    secondaryMustShow: ["Z veya şapka biçimli çelik donatı sehpası", "alt donatı teli", "üst donatı tabakası", "aradaki rijit boşluk"],
    secondaryMustNotShow: ["yazı", "cm rakamları", "etiket"],
    secondaryDifference: "Primary sahadaki döşeme donatı alanını gösterirken, secondary iki donatı katını birbirinden ayıran donatı sehpası kesitini öğretir.",
  },
  "pas-payi": {
    id: "pas-payi",
    primaryMode: "technical-cutaway",
    primaryFocus: "Kalıp yüzeyi ile çelik donatı arasındaki beton pas payı takozunun koruyucu konumu",
    primaryMustShow: ["çelik kalıp paneli", "nervürlü çelik donatı", "aradaki plastik veya beton pas payı takozu", "temiz mesafe"],
    primaryMustNotShow: ["ölçü rakamları", "yazı", "oklar"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "Döşeme ve perde kalıbında yerleştirilmiş pas payı takozlarının sıklık kontrolü",
    secondaryMustShow: ["döşeme donatısı altına 1 metre arayla dizilmiş takozlar", "perde donatısına takılmış tekerlek tipi plastik pas payları"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "marka"],
    secondaryDifference: "Primary tek bir pas payı takozunun koruyucu kesitini gösterirken, secondary sahada perde ve döşemedeki montaj dizilim sıklığını öğretir.",
  },
  "beton-isleri": {
    id: "beton-isleri",
    primaryMode: "site-process",
    primaryFocus: "Transmikser ve mobil pompa ile taze betonun kalıba aktarılması süreci",
    primaryMustShow: ["dönen transmikser kazanı", "pompa haznesine boşalan taze beton", "şantiye sahası"],
    primaryMustNotShow: ["logo", "yazı", "sahte tabela"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "Transmikser başında slump (çökme) konisi ile taze beton kıvam deneyi",
    secondaryMustShow: ["çelik slump konisi", "koni çekildikten sonra çöken taze beton kütlesi", "ölçüm cetveli ile çökme ölçümü"],
    secondaryMustNotShow: ["okunur rakamlar", "marka logoları", "yazı"],
    secondaryDifference: "Primary sahadaki transmikser operasyonunu gösterirken, secondary transmikser başında yapılan slump kıvam deneyini öğretir.",
  },
  "beton-sinifi": {
    id: "beton-sinifi",
    primaryMode: "technical-cutaway",
    primaryFocus: "C25, C30, C35 betonun agrega gradasyonu, çimento hamuru ve yoğunluk mikro-kesiti",
    primaryMustShow: ["farklı boyutlu kırma taş agregalar", "agregaları saran çimento pastası", "boşluksuz yoğun matris kesiti"],
    primaryMustNotShow: ["C30 yazısı", "formüller", "etiketler"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "Basınç dayanım deneyi için sahada 15x15 cm küp kalıplara beton numunesi alma",
    secondaryMustShow: ["çelik küp numune kalıpları", "şişleme çubuğu ile tabaka tabaka sıkıştırma", "etiketsiz numune dizisi"],
    secondaryMustNotShow: ["yazı", "sayılar", "laboratuvar logoları"],
    secondaryDifference: "Primary beton matrisinin iç agrega dağılımını gösterirken, secondary şantiyede küp numune alma işlemini öğretir.",
  },
  "beton-dokumu": {
    id: "beton-dokumu",
    primaryMode: "site-process",
    primaryFocus: "Pompa hortumu ile döşeme veya perdeye taze beton serilmesi",
    primaryMustShow: ["kauçuk pompa ucu", "kalıba dökülen taze gri beton", "çizmeli ve baretli işçiler"],
    primaryMustNotShow: ["yazı", "sahte tabela", "kolaj"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Perde ve kolonlarda betonun aşırı yüksekten serbest düşmesini önleyen hortum uzatması",
    secondaryMustShow: ["kolon kalıbının derinliğine inen hortum", "ayrışmayı (segregasyon) önleyen kontrollü döküm", "temiz kalıp içi"],
    secondaryMustNotShow: ["yazı", "ölçü", "deforme insan"],
    secondaryDifference: "Primary döşemeye geniş beton yayılmasını gösterirken, secondary düşey elemanda segregasyonu önleyen derin döküm disiplinini öğretir.",
  },
  "vibrasyon": {
    id: "vibrasyon",
    primaryMode: "site-process",
    primaryFocus: "Taze beton içine daldırılan mekanik iğne vibratör ve hava kabarcığı çıkışı",
    primaryMustShow: ["çelik vibratör şişesi", "betona dikey daldırma", "yüzeyde parıldayan çimento şerbeti ve çıkan hava kabarcıkları"],
    primaryMustNotShow: ["yazı", "marka", "çizgi efektler"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Vibratör şişesinin etki yarıçapı ve bir önceki döküm tabakasına 10 cm saplanma kesiti",
    secondaryMustShow: ["düşey daldırılan şişe", "dairesel titreşim yayılım dalgası", "alttaki tabakayla kaynaşan beton katmanı kesiti"],
    secondaryMustNotShow: ["yazı", "cm ölçüleri", "grafik okları"],
    secondaryDifference: "Primary sahadaki vibrasyon anını gösterirken, secondary vibratörün etki yarıçapını ve iki beton tabakasını kaynaştırma kesitini öğretir.",
  },
  "kur-islemi": {
    id: "kur-islemi",
    primaryMode: "site-process",
    primaryFocus: "Sertleşen taze beton yüzeyine su püskürtme veya kimyasal kür membranı uygulaması",
    primaryMustShow: ["nemli beton yüzeyi", "su hortumu ile sulama veya püskürtme", "parlak koruyucu nem filmi"],
    primaryMustNotShow: ["yazı", "logo", "aşırı gökkuşağı efekti"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Güneş ve rüzgardan korumak için beton üzerine ıslak jüt (çuval) örtü veya jeotekstil serimi",
    secondaryMustShow: ["döşeme betonu üzerine serilmiş ıslak jüt kumaşı", "nemli örtü yüzeyi", "buharlaşmayı önleyen tam kaplama"],
    secondaryMustNotShow: ["yazı", "marka", "tabela"],
    secondaryDifference: "Primary su ile doğrudan kürlemeyi gösterirken, secondary döşemede ıslak örtü (jüt) ile nem kaybını önleme tekniğini öğretir.",
  },
  "beton-testi": {
    id: "beton-testi",
    primaryMode: "site-process",
    primaryFocus: "Laboratuvar hidrolik presinde beton küp numunesinin basınç kırılma testi",
    primaryMustShow: ["ağır hidrolik pres plakaları", "arada çatlayan 15x15 beton küp", "kırılma piramidi koniği"],
    primaryMustNotShow: ["dijital ekrandaki okunur MPa rakamları", "yazı", "laboratuvar adı"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "Sahada sertleşmiş beton yüzeyinde Schmidt test çekici (beton sklerometresi) uygulaması",
    secondaryMustShow: ["beton kolona dik tutulan çelik Schmidt çekici", "darbe ucu", "temizlenmiş pürüzsüz beton deney noktası"],
    secondaryMustNotShow: ["skala üzerindeki sayılar", "yazı", "marka"],
    secondaryDifference: "Primary pres altında küp numunenin kırılmasını gösterirken, secondary sahada tahribatsız Schmidt çekici kontrolünü öğretir.",
  },
  "duvar-orme": {
    id: "duvar-orme",
    primaryMode: "site-process",
    primaryFocus: "Şakül ve mastar ipi doğrultusunda tuğla veya gazbeton duvar örgüsü",
    primaryMustShow: ["sıralı tuğla örgüsü", "mala ile harç yayma", "gergin sarı duvarcı ipi", "düşey derzler"],
    primaryMustNotShow: ["yazı", "marka", "deforme el"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Duvarın betonarme kolona lamel (çelik ankraj sacı) ile bağlanması detayı",
    secondaryMustShow: ["betonarme kolon yüzeyi", "kolona çakılan L tipi delikli galvaniz sac", "tuğla yatay derzine gömülen sac lamel"],
    secondaryMustNotShow: ["yazı", "rakam", "oklar"],
    secondaryDifference: "Primary sahadaki duvar örgüsünü gösterirken, secondary duvarın depremde devrilmesini önleyen kolon bağlantı sacı kesitini öğretir.",
  },
  "tugla-duvar": {
    id: "tugla-duvar",
    primaryMode: "site-process",
    primaryFocus: "Düşey delikli kırmızı pişmiş kil tuğlalar ile harçlı duvar imalatı",
    primaryMustShow: ["kırmızı kil delikli tuğlalar", "düzgün harç tabakası", "şaşırtmalı derz dizilimi"],
    primaryMustNotShow: ["yazı", "logo", "ölçü"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Tuğla duvar kapı-pencere üstü prefabrik veya yerinde döküm betonarme lento kesiti",
    secondaryMustShow: ["açıklık üstündeki betonarme lento", "lento donatısı", "tuğla duvarın lentoya oturma mesafesi"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "etiket"],
    secondaryDifference: "Primary tuğla duvar örgüsünü sunarken, secondary duvar boşluğu üstündeki taşıyıcı lento detayını kesit olarak öğretir.",
  },
  "ytong-gazbeton": {
    id: "ytong-gazbeton",
    primaryMode: "site-process",
    primaryFocus: "Hafif beyaz gazbeton blokların dişli mala ve özel yapıştırıcı ile örülmesi",
    primaryMustShow: ["beyaz gazbeton bloklar", "dişli mala ile sürülen ince yapıştırıcı harç", "lastik tokmak ile terazi ayarı"],
    primaryMustNotShow: ["marka yazısı (Ytong)", "yazı", "rakam"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Gazbeton blokların el testeresi ile hassas kesimi ve kanal açma hazırlığı",
    secondaryMustShow: ["geniş dişli gazbeton testeresi", "düzgün kesilen beyaz blok", "tesisat için açılan düzgün kanal"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary ince harçlı blok örgüsünü gösterirken, secondary blokların testere ile özel boyutlandırılma ve işlenme kolaylığını öğretir.",
  },
  "briket": {
    id: "briket",
    primaryMode: "site-process",
    primaryFocus: "Gri beton briket veya bims bloklarla çevre veya bölme duvar örgüsü",
    primaryMustShow: ["boşluklu gri beton briketler", "kalın çimento harcı derzleri", "sağlam duvar örgüsü"],
    primaryMustNotShow: ["yazı", "ölçü", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Briket duvar içinde düşey donatı çubuğu ve harç doldurulan boşluk kesiti",
    secondaryMustShow: ["briket dikey boşluğundan geçen nervürlü demir", "harç ile doldurulmuş çekirdek", "donatılı kargir kesiti"],
    secondaryMustNotShow: ["yazı", "rakam", "oklar"],
    secondaryDifference: "Primary kaba briket örgüsünü gösterirken, secondary briket boşluklarına düşey donatı atılarak yapılan güçlendirme kesitini öğretir.",
  },
  "cati-iskeleti": {
    id: "cati-iskeleti",
    primaryMode: "site-process",
    primaryFocus: "Bina üstünde yükselen taşıyıcı çatı konstrüksiyonu, aşıklar ve mertekler",
    primaryMustShow: ["eğimli çatı iskeleti", "ahşap veya çelik ana makaslar", "aşık profilleri", "açık gökyüzü bağlamı"],
    primaryMustNotShow: ["yazı", "ölçü", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Çatı mahya birleşimi ve saçak ucu taşıyıcı kalkan duvar bağlantı kesiti",
    secondaryMustShow: ["mahya aşığı birleşimi", "merteklerin mahyaya oturması", "saçak damlalık ucu ve kalkan duvar ankrajı"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "etiket"],
    secondaryDifference: "Primary binanın tüm çatı iskeletini gösterirken, secondary en tepe mahya ve saçak ucu birleşim düğümünü kesit olarak öğretir.",
  },
  "ahsap-cati": {
    id: "ahsap-cati",
    primaryMode: "site-process",
    primaryFocus: "Geleneksel emprenyeli ahşap karkas çatı: makaslar, aşıklar ve mertek dizilimi",
    primaryMustShow: ["masif ahşap mertekler", "ahşap çatı makası", "çelik bağlantı plakaları ve bulonlar"],
    primaryMustNotShow: ["yazı", "marka", "ölçü"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Ahşap mertek ile betonarme hatıl arasındaki metal çelik ankraj ve zıvana detayı",
    secondaryMustShow: ["betonarme çatı hatılı", "kimyasal dübelle bağlı L çelik mesnet", "ahşap merteğin cıvatayla mesnede kilitlenmesi"],
    secondaryMustNotShow: ["yazı", "rakam", "oklar"],
    secondaryDifference: "Primary genel ahşap karkas yapısını sunarken, secondary ahşabın betonarme hatıla rüzgar emmesine karşı bağlandığı çelik mesnet detayını öğretir.",
  },
  "celik-cati": {
    id: "celik-cati",
    primaryMode: "site-process",
    primaryFocus: "Hafif çelik veya ağır çelik kafes makaslı endüstriyel çatı montajı",
    primaryMustShow: ["çelik kafes makaslar", "C veya Z aşık profilleri", "vinç ile kaldırılan çelik eleman"],
    primaryMustNotShow: ["yazı", "logo", "aşırı neon"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Çelik makas düğüm noktası guse levhası ve yüksek mukavemetli bulon birleşimi",
    secondaryMustShow: ["üçgen çelik guse plakası", "bulonlu torklu bağlantılar", "çapraz rüzgar bağlantı gergisi"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary geniş açıklıklı çelik çatı montajını gösterirken, secondary kafes kiriş düğüm noktasındaki guse levhası ve bulon kesitini öğretir.",
  },
  "teras-cati": {
    id: "teras-cati",
    primaryMode: "technical-cutaway",
    primaryFocus: "Gezilebilen ters teras çatı katmanları: betonarme döşeme, eğim betonu, yalıtım, koruma",
    primaryMustShow: ["eğim şapı", "su yalıtım membranı", "ekstrüde polistiren (XPS) ısı yalıtımı", "koruma harcı ve kaplama"],
    primaryMustNotShow: ["katman etiket yazıları", "oklar", "reklam"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Teras çatı süzgeci (parapet çıkışı veya dikey gider) ve yalıtım etek flanşı kesiti",
    secondaryMustShow: ["çift kademeli teras çatı süzgeci", "membranın süzgeç flanşına kaynaklanması", "çakıl tutucu yaprak ızgarası"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "marka"],
    secondaryDifference: "Primary çatı düzlemindeki katman sıralamasını gösterirken, secondary suyun tahliye edildiği teras süzgeci flanş yalıtım detayını öğretir.",
  },

  // ==========================================
  // 4. İNCE İŞLER (25 Konu)
  // ==========================================
  "ince-isler": {
    id: "ince-isler",
    primaryMode: "site-process",
    primaryFocus: "Kaba inşaatı bitmiş modern iç mekanda ince işler: sıva, alçıpan, şap ve doğrama montajı",
    primaryMustShow: ["duvar sıvası", "alçıpan asma tavan metal karkası", "düzgün şap zemini", "doğrama montajı"],
    primaryMustNotShow: ["kolaj", "yazı", "logo", "filigran"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "İç mekan köşe bitiş koordinasyonu: süpürgelik, zemin derzi, duvar boyası ve kapı pervazı kesişimi",
    secondaryMustShow: ["duvar-zemin birleşiminde süpürgelik", "kapı kasası ile pervaz bitişi", "kusursuz yüzey kalitesi ve boya sınırı"],
    secondaryMustNotShow: ["yazı", "ölçü", "marka logosu"],
    secondaryDifference: "Primary kaba-ince geçişindeki geniş şantiye odasını gösterirken (mevcut WebP korunur), secondary bitmiş malzemelerin köşe ve pervazda buluştuğu ince detay koordinasyonunu öğretir.",
  },
  "siva": {
    id: "siva",
    primaryMode: "site-process",
    primaryFocus: "İç mekan tuğla duvara mala ile taze harç sıva uygulaması",
    primaryMustShow: ["mala ile taze harç sıvama", "tuğla duvar yüzeyi", "mastar izleri"],
    primaryMustNotShow: ["yazı", "logo", "filigran"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Sıva katmanları ve köşe profili (ano çıtası, kaba sıva, ince sıva, mastarlı düzlem) kesiti",
    secondaryMustShow: ["tuğla alt yüzey", "çimento esaslı kaba sıva tabakası", "perlitli/ince sıva bitişi", "aluminyum köşe koruma çıtası"],
    secondaryMustNotShow: ["yazı", "ölçü rakamı", "oklar"],
    secondaryDifference: "Primary ustanın mala ile sıva uygulamasını gösterirken (mevcut WebP korunur), secondary sıva tabakalarının katman kesitini ve köşe filesi detayını öğretir.",
  },
  "ic-siva": {
    id: "ic-siva",
    primaryMode: "site-process",
    primaryFocus: "Oda içinde duvarlara makineyle püskürtülen veya elle çekilen iç mekan sıvası",
    primaryMustShow: ["iç mekan oda duvarı", "alçı veya çimento iç sıva uygulaması", "duvar mastarı ile düzeltme"],
    primaryMustNotShow: ["yazı", "ölçü", "kolaj"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "2 metrelik aluminyum mastar ve ışık huzmesi ile iç sıva yüzey düzgünsüzlük kontrolü",
    secondaryMustShow: ["duvara dayalı 2 metre uzun mastar", "mastar arkasından sızmayan ışık (sıfır boşluk)", "kusursuz düzlem"],
    secondaryMustNotShow: ["yazı", "rakam", "etiket"],
    secondaryDifference: "Primary sıvanın duvara uygulanmasını sunarken, secondary yüzeyin eğriliksiz olduğunu kanıtlayan 2m mastar kalite kontrolünü öğretir.",
  },
  "dis-siva": {
    id: "dis-siva",
    primaryMode: "site-process",
    primaryFocus: "Dış cephe iskelesinde mantolama veya tuğla üzerine fileli çimento esaslı dış cephe sıvası",
    primaryMustShow: ["cephe iskelesi", "dış duvara sürülen elyaflı sıva", "sıva içine gömülen alkaliye dayanıklı donatı filesi"],
    primaryMustNotShow: ["yazı", "marka", "tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Dış cephe sıvasında damlalık profili, pencere denizliği altı ve dilatasyon derzi kesiti",
    secondaryMustShow: ["pencere altı damlalık çıtası", "sıva filesinin köşede dönmesi", "su damlamasını sağlayan kılcal damlalık oluğu"],
    secondaryMustNotShow: ["yazı", "ölçü oku", "etiket"],
    secondaryDifference: "Primary iskelede fileli sıva serimini gösterirken, secondary cephe suyunu duvardan uzaklaştıran damlalık profil kesitini öğretir.",
  },
  "alci-siva": {
    id: "alci-siva",
    primaryMode: "site-process",
    primaryFocus: "Perlitli alçı sıvanın çelik mala ile pürüzsüz ipeksi yüzey elde edilecek şekilde perdahlanması",
    primaryMustShow: ["beyaz alçı harcı", "geniş çelik mala (kürek)", "ayna gibi düzleştirilmiş pürüzsüz beyaz duvar"],
    primaryMustNotShow: ["yazı", "torba markası", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Farklı malzeme birleşiminde (beton-tuğla geçişi) alçı sıva altına file çekme detayı",
    secondaryMustShow: ["kolon ile tuğla duvar çatlak riski çizgisi", "üzerine serilen kendinden yapışkanlı derz filesi", "alçı sıvanın çatlağı önleme kesiti"],
    secondaryMustNotShow: ["yazı", "ölçü", "oklar"],
    secondaryDifference: "Primary yüzeyin çelik mala ile perdahlanmasını sunarken, secondary beton-tuğla birleşiminde çatlamayı önleyen sıva filesi kesitini öğretir.",
  },
  "alcipan": {
    id: "alcipan",
    primaryMode: "technical-cutaway",
    primaryFocus: "Galvaniz C ve U profilleri, tavan askı çubukları ve alçıpan levhaların karkas montajı",
    primaryMustShow: ["galvaniz çelik profil karkası", "tavandan inen askı teli", "monte edilen beyaz alçıpan levhalar"],
    primaryMustNotShow: ["yazı", "vida ölçüleri", "logo"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "İki alçıpan plaka pahlı ek yeri: kağıt derz bandı, derz dolgu alçısı ve vidalama kesiti",
    secondaryMustShow: ["pahlı alçıpan kenarları", "batık vida başı", "kağıt derz bandı (paper tape)", "iki kat derz dolgu alçısı tabakası"],
    secondaryMustNotShow: ["yazı", "rakam", "oklar"],
    secondaryDifference: "Primary geniş asma tavan metal karkasını gösterirken (mevcut WebP korunur), secondary iki alçıpan levhanın derz bandı ve dolgu alçısıyla birleşme kesitini öğretir.",
  },
  "bolme-duvar": {
    id: "bolme-duvar",
    primaryMode: "site-process",
    primaryFocus: "Hafif çelik karkaslı alçıpan bölme duvar: dikmeler, ses yalıtım mineral yünü ve levhalar",
    primaryMustShow: ["düşey C profilleri", "profiller arasına yerleştirilen sarı/yeşil mineral taşyünü", "tek yüzü kapatılmış duvar"],
    primaryMustNotShow: ["yazı", "marka", "tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Bölme duvarın zemin ve tavan betonuna ses yalıtım bandı (akustik bant) ile bağlantı kesiti",
    secondaryMustShow: ["zemin betonuna vidalanan U profili", "profil altında sıkışmış kauçuk akustik bant", "çift kat alçıpan levha kesiti"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "etiket"],
    secondaryDifference: "Primary duvar içi taşyünü yerleşimini gösterirken, secondary ses köprüsünü kesen zemin/tavan akustik yalıtım bandı kesitini öğretir.",
  },
  "asma-tavan": {
    id: "asma-tavan",
    primaryMode: "site-process",
    primaryFocus: "Geniş salonda metal askı karkaslı modüler veya monolitik asma tavan montajı",
    primaryMustShow: ["lazer nivo ile yatay tavan kotu çizgisi", "askı çubukları", "ana ve tali taşıyıcı profiller", "aydınlatma boşlukları"],
    primaryMustNotShow: ["yazı", "ölçü", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Gizli ışık bandı ve asma tavan gölgelik (shadow line / z-profil) duvar birleşim kesiti",
    secondaryMustShow: ["duvar kenarında gölge derzi Z-profili", "gizli LED ışık havuzu kanalı", "alçıpan büküm profili"],
    secondaryMustNotShow: ["yazı", "oklar", "etiket"],
    secondaryDifference: "Primary geniş tavan karkas kurulumunu gösterirken, secondary modern mimarideki gölge derzli duvar birleşimi ve gizli ışık havuzu kesitini öğretir.",
  },
  "zemin-kaplamalari": {
    id: "zemin-kaplamalari",
    primaryMode: "site-process",
    primaryFocus: "Aydınlık modern iç mekanda düzgün tesviye şapı üzerine seramik ve parke zemin uygulaması",
    primaryMustShow: ["tesviye şapı zemini", "taraklı yapıştırıcı harç", "döşenen zemin kaplama elemanları", "oda perspektifi"],
    primaryMustNotShow: ["havada yüzen ürün numuneleri", "katalog kolajı", "yazı", "logo"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Betonarme döşeme, ses yalıtım şiltesi, yüzer şap ve zemin kaplaması katman kesiti",
    secondaryMustShow: ["taşıyıcı beton plak", "ayak sesi yalıtım şiltesi (şilteli yüzer şap)", "çelik hasırlı tesviye şapı", "yapıştırıcı ve üst kaplama"],
    secondaryMustNotShow: ["yazı", "cm rakamları", "etiket"],
    secondaryDifference: "Primary mekandaki döşeme işçiliğini gösterirken, secondary ses yalıtımlı yüzer şap sisteminin döşeme katman kesitini öğretir.",
  },
  "seramik-kaplama": {
    id: "seramik-kaplama",
    primaryMode: "site-process",
    primaryFocus: "Büyük ebatlı porselen seramik karoların zemin seviye takozları (tesviye klipsi) ile döşenmesi",
    primaryMustShow: ["geniş ebatlı seramik karolar", "taraklı yapıştırıcı harç", "derz aralarındaki kırmızı/mavi plastik tesviye takozları"],
    primaryMustNotShow: ["yazı", "marka", "ölçü"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Çift taraflı yapıştırıcı tarama (back-buttering) ve derz dolgusu (fugalı birleşim) kesiti",
    secondaryMustShow: ["hem zemine hem karo arkasına çekilmiş çift yönlü yapıştırıcı", "hava boşluksuz tam yapışma", "elastik derz dolgusu"],
    secondaryMustNotShow: ["yazı", "ölçü oku", "oklar"],
    secondaryDifference: "Primary yüzeydeki seviye takozlu montajı gösterirken, secondary büyük karolarda kırılmayı önleyen çift taraflı yapıştırma kesitini öğretir.",
  },
  "parke-kaplama": {
    id: "parke-kaplama",
    primaryMode: "site-process",
    primaryFocus: "Kilitli lamine veya laminat parke panellerinin kapпроntoz tokmakla birbirine geçirilmesi",
    primaryMustShow: ["ahşap dokulu parke panelleri", "altına serilmiş beyaz kapron/şilte", "kilit mekanizmasıyla birleştirme"],
    primaryMustNotShow: ["yazı", "marka", "katalog görseli"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Parkenin duvar dibinde bıraktığı 15 mm genleşme boşluğu ve süpürgelik klipsi kesiti",
    secondaryMustShow: ["duvar sıvası", "duvar ile parke arasındaki 15 mm genleşme aralığı takozu", "üzerini örten süpürgelik"],
    secondaryMustNotShow: ["yazı", "mm ölçüleri", "etiket"],
    secondaryDifference: "Primary odada parke döşenmesini gösterirken, secondary ahşabın şişip kabarmasını önleyen duvar dibi genleşme boşluğu kesitini öğretir.",
  },
  "mermer-kaplama": {
    id: "mermer-kaplama",
    primaryMode: "site-process",
    primaryFocus: "Doğal mermer veya granit plakaların harç yatağına tokmaklanarak hassas seviyelenmesi",
    primaryMustShow: ["damarlı doğal mermer levhalar", "yarı kuru harç yatağı", "lastik tokmak ve su terazisi"],
    primaryMustNotShow: ["yazı", "marka", "çizgi sembol"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Mermer merdiven basamağı: rıht, basamak plağı, damlalık pahı ve harç bağlantı kesiti",
    secondaryMustShow: ["masif mermer basamak", "düşey mermer rıht", "önde kaymaz pah/oluk detayı", "alttaki harç yatağı"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary zemin mermer döşeme sahnesini sunarken, secondary merdiven basamağındaki damlalık pahı ve rıht birleşim kesitini öğretir.",
  },
  "epoksi-kaplama": {
    id: "epoksi-kaplama",
    primaryMode: "site-process",
    primaryFocus: "Helikopterli beton zemin üzerine self-leveling epoksi kaplamanın çekçek ve kirpi rulo ile yayılması",
    primaryMustShow: ["parlak epoksi reçine tabakası", "özel çivili ayakkabılı usta", "hava kabarcığı alıcı kirpi rulo"],
    primaryMustNotShow: ["yazı", "logo", "aşırı neon efekt"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Epoksi zemin katmanları: bilyalanmış beton, epoksi astar, ara katman ve son kat poliüretan koruma kesiti",
    secondaryMustShow: ["yüzeyi pürüzlendirilmiş zemin betonu", "derin nüfuz eden astar tabakası", "kendiliğinden yayılan 2mm gövde", "son kat aşınma tabakası"],
    secondaryMustNotShow: ["yazı", "mikron rakamları", "oklar"],
    secondaryDifference: "Primary sahadaki parlak sıvı reçine serimini gösterirken, secondary beton yüzey hazırlığından son kata epoksi katman mimarisini öğretir.",
  },
  "duvar-kaplamalari": {
    id: "duvar-kaplamalari",
    primaryMode: "site-process",
    primaryFocus: "İç mekan duvarlarına dekoratif akustik ahşap panellerin veya seramik kaplamanın montajı",
    primaryMustShow: ["duvar kaplama panelleri", "alt karkas veya yapıştırıcı", "hizalama terazisi", "modern iç mekan"],
    primaryMustNotShow: ["yazı", "katalog kolajı", "marka"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Akustik ahşap duvar panelinin gizli klips ve taşyünü yalıtım karkasına geçiş kesiti",
    secondaryMustShow: ["delikli/oluklu ahşap akustik panel", "arkasında siyah akustik tül ve taşyünü", "gizli vidalı alüminyum montaj klipsi"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary genel duvar kaplama uygulamasını gösterirken, secondary arkasındaki akustik yalıtım ve gizli klipsli taşıyıcı kesiti öğretir.",
  },
  "fayans": {
    id: "fayans",
    primaryMode: "site-process",
    primaryFocus: "Banyo veya ıslak hacim duvarında su yalıtımı üstüne parlak seramik fayans döşeme",
    primaryMustShow: ["ıslak hacim duvarı", "su yalıtımlı mavi/gri zemin", "taraklı yapıştırıcı harç", "düzgün fayans dizilimi ve derz artıları"],
    primaryMustNotShow: ["yazı", "marka", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Islak hacim köşe birleşiminde pah bandı (su yalıtım elastik bandı) ve silikon derz kesiti",
    secondaryMustShow: ["iki duvarın birleştiği 90 derece köşe", "su yalıtımı altına gömülü su sızdırmaz elastik pah bandı", "fayans köşesinde antibakteriyel silikon"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary duvara fayans döşeme işçiliğini gösterirken, secondary su sızıntılarını önleyen köşe yalıtım pah bandı ve silikon kesitini öğretir.",
  },
  "boya": {
    id: "boya",
    primaryMode: "site-process",
    primaryFocus: "Astarlanmış pürüzsüz duvara rulo ile iç cephe su bazlı mat/ipek mat boya uygulaması",
    primaryMustShow: ["boya tavası ve rulo", "duvarda düzgün ıslak boya izi", "maskeleme bandı çekilmiş süpürgelik ve tavan sınırı"],
    primaryMustNotShow: ["boya tenekesi marka yazısı", "yazı", "renk kodları"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Boya öncesi yüzey hazırlığı katman kesiti: sıva, macun (2 kat saten macun), astar ve 2 kat son kat boya",
    secondaryMustShow: ["kaba alçı sıva tabakası", "ince saten macun filmi", "şeffaf astar nüfuziyeti", "iki ince son kat boya filmi"],
    secondaryMustNotShow: ["yazı", "mikron ölçüleri", "oklar"],
    secondaryDifference: "Primary ustanın rulo ile boya yapmasını gösterirken, secondary boyanın çatlamaması ve kabarmaması için alt macun ve astar katman kesitini öğretir.",
  },
  "duvar-kagidi": {
    id: "duvar-kagidi",
    primaryMode: "site-process",
    primaryFocus: "Tutkallı pürüzsüz duvara desenli duvar kağıdının hava kabarcığı alıcı spatulayla yapıştırılması",
    primaryMustShow: ["duvar kağıdı rulosu", "plastik spatula ile hava kabarcıklarını düzeltme", "desenlerin sıfır ek yeriyle birleşmesi"],
    primaryMustNotShow: ["yazı", "marka", "tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "İki duvar kağıdı şeridinin desen çakışması (desen tekrarı) ve sıfır derz bindirme kesiti",
    secondaryMustShow: ["yan yana gelen iki duvar kağıdı kenarı", "özel ek yeri yapıştırıcısı", "görünmeyen pürüzsüz kenet derzi"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary şeridin duvara yapıştırılma anını gösterirken, secondary iki desenin mikron mertebesinde çakıştığı ek yeri dikiş kesitini öğretir.",
  },
  "kapi-pencere": {
    id: "kapi-pencere",
    primaryMode: "site-process",
    primaryFocus: "Duvar boşluğuna kapı veya pencere kasasının montajı, kama ve terazi ayarı",
    primaryMustShow: ["duvar kör kasası boşluğu", "aluminyum veya ahşap kasa", "ayar kamaları ve su terazisi"],
    primaryMustNotShow: ["yazı", "marka logosu", "ölçü"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kasa ile duvar arasındaki poliüretan köpük, buhar bariyeri bandı ve mastik kesiti",
    secondaryMustShow: ["kasa profili", "duvar boşluğu", "arada genleşen montaj köpüğü", "içte buhar kesici bant", "dışta su buharı geçirgen hava bandı"],
    secondaryMustNotShow: ["yazı", "ölçü oku", "etiket"],
    secondaryDifference: "Primary kasanın duvara yerleştirilmesini gösterirken, secondary RAL standartlarına uygun 3 kademeli sızdırmazlık yalıtım bandı kesitini öğretir.",
  },
  "dis-kapi": {
    id: "dis-kapi",
    primaryMode: "installed-component",
    primaryFocus: "Binanın ana girişinde monte edilmiş sağlam çelik zırhlı dış kapı ve mermer eşik",
    primaryMustShow: ["çelik kapı kasası ve kanadı", "mermer giriş eşiği", "güvenlik kilit mekanizması", "temiz giriş holü"],
    primaryMustNotShow: ["yazı", "marka logosu", "daire numarası"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Dış kapı altı otomatik giyotin fitil ve zemin su bariyeri eşik kesiti",
    secondaryMustShow: ["kapı kanadı altındaki mekanik düşen giyotin fitil", "termal bariyerli alüminyum eşik", "hava ve rüzgar kesici contalar"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "etiket"],
    secondaryDifference: "Primary monte edilmiş dış kapıyı gösterirken, secondary kapı kapandığında zemine inen otomatik hava-ses kesici giyotin fitil kesitini öğretir.",
  },
  "ic-kapi": {
    id: "ic-kapi",
    primaryMode: "site-process",
    primaryFocus: "İç mekan oda kapısı ahşap kasasının montajı, köpükleme ve kanat takılması",
    primaryMustShow: ["ahşap kapı kasası", "menteşe montajı", "duvar boşluğunda poliüretan köpük", "oda perspektifi"],
    primaryMustNotShow: ["yazı", "marka", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Teleskopik pervazın kapı kasasına geçişi ve akustik fitil yuvası kesiti",
    secondaryMustShow: ["teleskopik ayarlı ahşap pervaz", "duvar kalınlığı tolerans yuvası", "kasa oluğuna gömülü yumuşak elastomerik fitil"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary kapı kanadının menteşeye takılmasını gösterirken, secondary duvar eğriliklerini örten teleskopik pervaz ve ses fitili kesitini öğretir.",
  },
  "pencere": {
    id: "pencere",
    primaryMode: "site-process",
    primaryFocus: "Çift veya üç camlı alüminyum/PVC pencere doğramasının cephe boşluğuna montajı",
    primaryMustShow: ["yalıtımlı pencere kasası", "üçlü yalıtım camı (Isıcam)", "cephe montaj vidaları ve terazi"],
    primaryMustNotShow: ["cam üzerindeki etiketler", "marka yazısı", "ölçü"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Pencere altı alüminyum damlalıklı denizlik, su yalıtım membranı ve ısı köprüsü kesiti",
    secondaryMustShow: ["dış alüminyum denizlik", "eğimli su damlalık burnu", "denizlik altı sızdırmazlık membranı", "iç mermer parapet"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "oklar"],
    secondaryDifference: "Primary pencerenin kasaya montajını gösterirken, secondary yağmur suyunun içeri sızmasını önleyen eğimli denizlik ve ısı köprüsü yalıtım kesitini öğretir.",
  },
  "cati-kaplamasi": {
    id: "cati-kaplamasi",
    primaryMode: "technical-cutaway",
    primaryFocus: "Eğimli çatıda kaplama katmanları: mertek, OSB levha, su yalıtım örtüsü, çıtalar ve son kat kaplama",
    primaryMustShow: ["ahşap taşıyıcı mertek", "OSB alt kaplama", "nefes alan su yalıtım örtüsü", "havalandırma çıtaları", "çatı kaplaması"],
    primaryMustNotShow: ["katman yazı etiketleri", "oklar", "reklam"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Eğimli çatı saçak havalandırma tarağı ve gizli dere yağmur oluğu kesiti",
    secondaryMustShow: ["saçak ucu havalandırma menfezi/tarağı", "asma çinko veya PVC yağmur oluğu", "damlalık sacı"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary çatı yüzeyindeki tüm katman mimarisini gösterirken, secondary çatının nefes almasını sağlayan saçak havalandırma tarağı ve dere oluğu kesitini öğretir.",
  },
  "kiremit": {
    id: "kiremit",
    primaryMode: "site-process",
    primaryFocus: "Ahşap latolar üzerine kilitli kiremitlerin (Marsilya veya Akdeniz kiremiti) dizilmesi",
    primaryMustShow: ["kırmızı killi kiremitler", "yatay ve düşey ahşap lata ızgarası", "birbirine kilitlenen kiremit kanalları"],
    primaryMustNotShow: ["yazı", "marka", "tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kiremit çatı mahya hattında kuru mahya bandı ve mahya kiremiti tespit kancası kesiti",
    secondaryMustShow: ["havalandırmalı kuru mahya rulosu", "mahya aşık çıtası", "çelik tespit kancasıyla sabitlenmiş yarım yuvarlak mahya kiremiti"],
    secondaryMustNotShow: ["yazı", "ölçü", "oklar"],
    secondaryDifference: "Primary sahadaki kiremit döşeme akışını sunarken, secondary çatının en tepe noktasında harçsız kuru mahya havalandırma kesitini öğretir.",
  },
  "membran-cati": {
    id: "membran-cati",
    primaryMode: "site-process",
    primaryFocus: "Eğimli veya düz çatıya şalümö ateşiyle arduvazlı (mineral kaplı) bitümlü membran serimi",
    primaryMustShow: ["yeşil veya kırmızı arduvaz taş kaplı membran rulosu", "şalümö alevi", "10 cm boyuna biniş çizgisi"],
    primaryMustNotShow: ["yazı", "marka", "tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Membran çatıda baca ve havalandırma borusu etrafı kurşun/baskı çıtası su yalıtım prapet dönüşü kesiti",
    secondaryMustShow: ["çatıdan çıkan dairesel baca borusu", "üste tırmanan membran eteği", "paslanmaz çelik kelepçe ve mastik dolgusu"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "etiket"],
    secondaryDifference: "Primary yüzey membran yapıştırmasını gösterirken, secondary çatı bacası veya boru geçişindeki en kritik sızdırmazlık etek kesitini öğretir.",
  },
  "metal-cati": {
    id: "metal-cati",
    primaryMode: "site-process",
    primaryFocus: "Kenet çatı alüminyum/çinko panellerinin özel elektrikli kenet sıkma makinesi ile montajı",
    primaryMustShow: ["uzun metal kenet sacları", "yükselen dik kenet hatları", "çatı eğimi ve bağlantı klipsleri"],
    primaryMustNotShow: ["yazı", "marka", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Gizli hareketli paslanmaz klips (cleat) ve çift kilitli kenet birleşim kesiti",
    secondaryMustShow: ["birbirine 360 derece sarılan çift kenet kıvrımı", "alttaki OSB'ye vidalı gizli hareketli çelik klips"],
    secondaryMustNotShow: ["yazı", "ölçü", "oklar"],
    secondaryDifference: "Primary sahadaki kenet metal çatı döşemesini gösterirken, secondary sacın genleşmesine izin veren gizli hareketli klips kesitini öğretir.",
  },

  // ==========================================
  // 5. TESİSAT İŞLERİ (11 Konu)
  // ==========================================
  "tesisat-isleri": {
    id: "tesisat-isleri",
    primaryMode: "site-process",
    primaryFocus: "Kaba inşaat sonrası koridor tavanı ve şaftlarda mekanik-elektrik tesisat hatları koordinasyonu",
    primaryMustShow: ["kablo tavaları", "temiz ve pis su boru hatları", "yangın sprinkler boruları", "düzenli askı sistemleri"],
    primaryMustNotShow: ["yazı", "kolaj", "dağınık kaos"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Tesisat ana şaftı yangın kompartıman geçişi ve yangın durdurucu harç/manşet kesiti",
    secondaryMustShow: ["betonarme döşeme şaft boşluğu", "içinden geçen plastik ve çelik borular", "şişen yangın manşeti (intumescent collar)", "yangın harcı"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary tavandaki yatay hat dağılımını gösterirken, secondary katlar arası yangın yayılmasını durduran şaft yangın yalıtım manşeti kesitini öğretir.",
  },
  "sihhi-tesisat": {
    id: "sihhi-tesisat",
    primaryMode: "site-process",
    primaryFocus: "Banyoda PPRC temiz su boruları ve sessiz PVC pis su hatlarının duvar içine gömülmesi",
    primaryMustShow: ["yeşil PPRC kaynaklı borular", "gri PVC gider boruları", "duvar kırım kanalları", "test tapaları"],
    primaryMustNotShow: ["marka yazısı", "yazı", "ölçü"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "Sıhhi tesisat kapatılmadan önce hidrostatik basınç testi: manometre ve test pompası",
    secondaryMustShow: ["manuel veya elektrikli basınç test pompası", "su dolu boru ağı", "10 bar basınca sabitlenmiş ibreli manometre"],
    secondaryMustNotShow: ["okunur rakamlar", "marka", "yazı"],
    secondaryDifference: "Primary boruların duvara montajını gösterirken, secondary borular sıvanmadan önce yapılan sızdırmazlık basınç testini öğretir.",
  },
  "temiz-su": {
    id: "temiz-su",
    primaryMode: "site-process",
    primaryFocus: "Polipropilen (PPRC) boruların pafta kaynak makinesi ile ısıtılarak birleştirilmesi",
    primaryMustShow: ["yeşil/gri PPRC borular", "ısıtıcı kaynak paftası ve kaynak makinesi", "dirsek ve manşon birleşimi"],
    primaryMustNotShow: ["yazı", "marka", "ölçü"],
    secondaryMode: "installed-component",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kollektörlü (mobil sistem) kılıflı boru temiz su dağıtım panosu",
    secondaryMustShow: ["kırmızı ve mavi kılıflı PEX borular", "pirinç gidiş-dönüş kollektörleri", "bireysel mini küresel vanalar"],
    secondaryMustNotShow: ["yazı", "daire no", "etiket"],
    secondaryDifference: "Primary PPRC boru kaynak tekniğini gösterirken, secondary her armatüre bağımsız hat çeken kılıflı kollektör sistemini öğretir.",
  },
  "pis-su": {
    id: "pis-su",
    primaryMode: "site-process",
    primaryFocus: "Atık su ve yağmur iniş hatlarında contalı PVC/PP sessiz boruların eğimle döşenmesi",
    primaryMustShow: ["kalın çaplı atık su boruları", "akış yönünde %2 eğim", "çift geçmeli contalı dirsekler", "tavan askı kelepçeleri"],
    primaryMustNotShow: ["çap rakamları", "yazı", "marka"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Lavabo altı ve yer sifonu su tutucu koku önleyici 'S' sifon kesiti",
    secondaryMustShow: ["S veya körük şekilli sifon gövdesi", "içeride biriken temiz su bariyeri", "kanalizasyon kokusunun geri tepmesini önleyen su perdesi"],
    secondaryMustNotShow: ["yazı", "ölçü", "oklar"],
    secondaryDifference: "Primary ana pis su boru eğim ve askı hattını sunarken, secondary kötü kokuları hapseden sifon içi su perdesi mekanizmasını kesit olarak öğretir.",
  },
  "elektrik-tesisati": {
    id: "elektrik-tesisati",
    primaryMode: "site-process",
    primaryFocus: "Duvar kanallarına alev yaymayan spiral boruların döşenmesi ve buat montajı",
    primaryMustShow: ["turuncu/gri alev iletmeyen spiral borular", "sıva altı yuvarlak buatlar", "anahtar-priz kasaları"],
    primaryMustNotShow: ["yazı", "ölçü", "marka"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Temel topraklama ring hattı ve galvaniz şerit topraklama pabucu birleşim kesiti",
    secondaryMustShow: ["temel betonu içine gömülen galvaniz topraklama şeridi", "donatı demirine çapraz klemensle kaynak/bağlantı", "test klemens kutusu"],
    secondaryMustNotShow: ["yazı", "rakam", "etiket"],
    secondaryDifference: "Primary oda içindeki priz-buat borulamasını gösterirken, secondary binanın tüm elektrik güvenliğini kuran temel topraklama şeridi kesitini öğretir.",
  },
  "kablolama": {
    id: "kablolama",
    primaryMode: "site-process",
    primaryFocus: "Asma tavan üstü perfore kablo tavasında halojen-free kablo demetlerinin çekilmesi",
    primaryMustShow: ["delikli galvaniz kablo tavası", "renkli faz ve nötr kablo demetleri", "kablo bağı (klips) ile düzenleme"],
    primaryMustNotShow: ["kablo üzeri okunur yazılar", "marka", "dağınıklık"],
    secondaryMode: "site-process",
    secondaryPlacement: "application",
    secondaryFocus: "Spiral boru içinden çelik susta (kılavuz tel) ile kabloların buatlara çekilme tekniği",
    secondaryMustShow: ["spiral boru ağzı", "esnek çelik susta teli ucu", "sustaya bantlanmış renkli bakır iletkenler"],
    secondaryMustNotShow: ["yazı", "etiket", "deforme el"],
    secondaryDifference: "Primary tavan tavasındaki organize kablo akışını gösterirken, secondary sıva altı borularda susta teliyle kablo çekme zanaatını öğretir.",
  },
  "pano-montaj": {
    id: "pano-montaj",
    primaryMode: "installed-component",
    primaryFocus: "Duvara monte edilmiş ana veya tali elektrik dağıtım panosu, sigortalar ve kablo düzeni",
    primaryMustShow: ["temiz metal pano kabini", "DIN rayına dizilmiş otomatik sigortalar", "kablo kanalları içinde organize renkli hatlar"],
    primaryMustNotShow: ["okunur voltaj/amper yazıları", "marka logoları", "yazı"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Kaçak akım koruma rölesi (RCD) ve aşırı gerilim parafudru bağlantı şema kesiti",
    secondaryMustShow: ["dört kutuplu kaçak akım rölesi modülü", "toprak barası", "nötr ve faz akım transformatörü halkası kesiti"],
    secondaryMustNotShow: ["yazı", "rakam", "etiket"],
    secondaryDifference: "Primary panonun sahadaki genel montaj düzenini gösterirken, secondary hayat koruma sağlayan kaçak akım rölesinin iç tetik kesitini öğretir.",
  },
  "isitma-sogutma": {
    id: "isitma-sogutma",
    primaryMode: "site-process",
    primaryFocus: "Merkezi ısıtma-soğutma kanalları, fan-coil üniteleri ve tavan montaj askıları",
    primaryMustShow: ["izoleli galvaniz hava kanalları", "asma tavana asılı fan-coil cihazı", "bakır boru hatları ve yoğuşma tavası"],
    primaryMustNotShow: ["yazı", "marka", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Hava kanalında yangın damperi (fire damper) ve eriyen lehimli sigorta mekanizması kesiti",
    secondaryMustShow: ["hava kanalı içindeki çelik klape kanadı", "72 derece eriyen termal sigorta teli", "duvar geçişi sızdırmazlık kesiti"],
    secondaryMustNotShow: ["yazı", "derece rakamları", "etiket"],
    secondaryDifference: "Primary tavan klima-havalandırma kanal ağını gösterirken, secondary yangın anında havalandırmayı kapatan yangın damperi kesitini öğretir.",
  },
  "yerden-isitma": {
    id: "yerden-isitma",
    primaryMode: "site-process",
    primaryFocus: "Modülasyonlu strafor yalıtım panelleri üzerine spiral PEX boruların döşenmesi",
    primaryMustShow: ["kabarcıklı/mantarlı siyah veya beyaz yalıtım köpüğü", "kırmızı veya şeffaf oksijen bariyerli PEX borular", "salyangoz serpantin düzeni"],
    primaryMustNotShow: ["yazı", "marka", "tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Yerden ısıtma zemin katman kesiti: şap içi boru, kenar yalıtım bandı ve zemin kaplaması",
    secondaryMustShow: ["duvar dibi elastik genleşme şeridi (kenar izolasyon bandı)", "şap içinde gömülü ısıtma borusu", "boruyu çevreleyen kalsiyum sülfat şapı"],
    secondaryMustNotShow: ["yazı", "cm rakamları", "oklar"],
    secondaryDifference: "Primary zemindeki boru serim geometrisini gösterirken, secondary duvar kenarındaki genleşme bandı ve şap kalınlığı katman kesitini öğretir.",
  },
  "klima-tesisat": {
    id: "klima-tesisat",
    primaryMode: "site-process",
    primaryFocus: "VRF/VRV klima bakır boru hattı montajı, armafleks izolasyonu ve lehim kaynağı",
    primaryMustShow: ["siyah armafleks kauçuk boru izolasyonu", "bakır boru demetleri", "azot gazı korumasında kaynak işlemi"],
    primaryMustNotShow: ["marka logosu", "yazı", "tabela"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Klima drenaj borusu ve ters koku önleyici yerçekimli kuru sifon (ball-valve trap) kesiti",
    secondaryMustShow: ["şeffaf yoğuşma drenaj borusu", "içinde yüzen bilyeli çekvalf sifon", "negatif basınçta kokuyu kesen bilye mekanizması"],
    secondaryMustNotShow: ["yazı", "ölçü", "etiket"],
    secondaryDifference: "Primary bakır boru ve izolasyon hatlarını gösterirken, secondary klimanın yoğuşma suyunun tahliyesinde koku girmesini önleyen bilyeli sifon kesitini öğretir.",
  },
  "yangin-tesisati": {
    id: "yangin-tesisati",
    primaryMode: "site-process",
    primaryFocus: "Kırmızı boyalı çelik dikişli borularla tavan yangın sprinkler sistemi kurulumu",
    primaryMustShow: ["kırmızı çelik yangın boruları", "yivli kaplin mekanik birleşimleri", "aşağı bakan pirinç sprinkler başlıkları"],
    primaryMustNotShow: ["marka yazısı", "yazı", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Yangın sprinkler başlığı cam tüpü (bulb), deflektör ve su püskürtme konisi kesiti",
    secondaryMustShow: ["pirinç dişli gövde", "kırmızı renkli ısıya duyarlı sıvı dolu cam tüp", "su saptırıcı deflektör tablası"],
    secondaryMustNotShow: ["yazı", "derece rakamları", "etiket"],
    secondaryDifference: "Primary tavandaki kırmızı yangın borulama ağını gösterirken, secondary yangın anında patlayan sprinkler cam tüpünün mikro mekanik kesitini öğretir.",
  },

  // ==========================================
  // 6. PEYZAJ & TESLİM (5 Konu)
  // ==========================================
  "peyzaj-teslim": {
    id: "peyzaj-teslim",
    primaryMode: "site-process",
    primaryFocus: "Yapımı tamamlanmış modern bina, temiz çevre düzeni, yürüyüş yolları ve yeşil alanlar",
    primaryMustShow: ["tamamlanmış çağdaş bina dış cephesi", "aydınlatma direkleri ve yaya yolları", "düzenlenmiş bahçe çimleri ve ağaçlar"],
    primaryMustNotShow: ["sahte tabela", "yazı", "insan deformasyonu", "kolaj"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "Teslim öncesi son kontrol (punch list): mühendisin daire içinde yüzey ve mekanik kontrolü",
    secondaryMustShow: ["tamamlanmış aydınlık oda", "pencere ve radyatör kontrolü", "profesyonel teslim kabul süreci"],
    secondaryMustNotShow: ["okunur kontrol listesi yazısı", "sahte evrak", "yazı"],
    secondaryDifference: "Primary binanın bitmiş dış cephe ve çevre genel görünümünü sunarken, secondary bina içinde yapılan son eksik-kusur kontrolü (punch list) anını öğretir.",
  },
  "peyzaj-ve-cevre-duzenleme": {
    id: "peyzaj-ve-cevre-duzenleme",
    primaryMode: "site-process",
    primaryFocus: "Bina çevresinde sert zemin bordür taşları ile bitkisel toprak alanının uyumlu düzenlenmesi",
    primaryMustShow: ["beton bordür taşları sınırı", "kilit parke yürüme yolu", "verimli siyah bahçe toprağı serimi"],
    primaryMustNotShow: ["yazı", "ölçü", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Açık otopark ve yaya yolu altında yağmur suyu ızgarası ve drenaj kanalı kesiti",
    secondaryMustShow: ["döküm demir ızgara", "polimer beton drenaj kanalı", "alttaki çakıllı süzülme ve boru bağlantısı"],
    secondaryMustNotShow: ["yazı", "ölçü oku", "etiket"],
    secondaryDifference: "Primary genel çevre düzenleme sahasını gösterirken, secondary yaya yollarındaki yüzey sularını toplayan lineer drenaj kanalı kesitini öğretir.",
  },
  "sert-zemin": {
    id: "sert-zemin",
    primaryMode: "site-process",
    primaryFocus: "Yaya yolunda kum yatağı üzerine beton kilit parke taşlarının tokmakla döşenmesi",
    primaryMustShow: ["düzeltilmiş kum yatağı", "birbirine kilitlenen parke taşları", "kenar bordür dayaması", "kompaktör vibrasyon tablası"],
    primaryMustNotShow: ["yazı", "ölçü", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Sert zemin katman kesiti: sıkıştırılmış alt temel, kırma taş, kum sergi ve kilit parke taşı",
    secondaryMustShow: ["doğal zemin", "tüvenan alt temel tabakası", "0-4 mm yıkanmış kum yatağı", "beton kilit taşı ve derz kumu dolgusu"],
    secondaryMustNotShow: ["yazı", "cm rakamları", "etiket"],
    secondaryDifference: "Primary sahadaki parke taşı döşeme işini gösterirken, secondary çökme ve dalgalanmayı önleyen alt temel ve sergi kumu katman kesitini öğretir.",
  },
  "bitkisel-peyzaj": {
    id: "bitkisel-peyzaj",
    primaryMode: "site-process",
    primaryFocus: "Bahçe alanında fidan dikimi, kök boğazı toprağı, damlama sulama borusu ve malç serimi",
    primaryMustShow: ["açılmış çukura dikilen fidan/ağaç", "organik malç/kabuk serimi", "damlama sulama boru hattı"],
    primaryMustNotShow: ["yazı", "ölçü", "kolaj"],
    secondaryMode: "technical-cutaway",
    secondaryPlacement: "technical-detail",
    secondaryFocus: "Ağaç dikim çukuru kesiti: kök topu, gübreli toprak, drenaj çakılı ve ahşap herek (kazık) desteği",
    secondaryMustShow: ["kök balyası (root ball)", "çukurdaki organik toprak karışımı", "ağacı rüzgardan koruyan çapraz ahşap herek gergisi", "sulama çanağı"],
    secondaryMustNotShow: ["yazı", "ölçü çizgisi", "etiket"],
    secondaryDifference: "Primary genel fidan dikimini sunarken, secondary fidanın tutunmasını sağlayan kök çukuru drenajı ve rüzgar hereği kesitini öğretir.",
  },
  "iskan-ruhsati": {
    id: "iskan-ruhsati",
    primaryMode: "project-visual",
    primaryFocus: "Tüm imalatları bitmiş, oturuma ve kabule hazır tamamlanmış kusursuz bina girişi",
    primaryMustShow: ["bitmiş bina giriş holü ve cephesi", "aydınlatılmış peyzaj", "kabul aşamasında kusursuz mimari"],
    primaryMustNotShow: ["sahte belediye belgesi", "sahte resmi mühür", "okunur yazı/imza"],
    secondaryMode: "site-process",
    secondaryPlacement: "quality-control",
    secondaryFocus: "Yetkili yapı denetim ve belediye heyetinin yangın merdiveni ve sığınakta teknik kabul denetimi",
    secondaryMustShow: ["temiz yangın kaçış merdiveni ve panik bar kapısı", "acil durum aydınlatmaları", "baretli mühendislerin teknik incelemesi"],
    secondaryMustNotShow: ["okunur resmi evrak", "yazı", "tabela"],
    secondaryDifference: "Primary teslime hazır binanın kusursuz dış/giriş mimarisini gösterirken, secondary iskânın asıl şartı olan yangın güvenlik kabul denetimini öğretir.",
  },
};

export const MASTER_NEGATIVE_PROMPT =
  "okunur yazı, bozuk yazı, anlamsız harf dizisi, ters yazı, aynalı yazı, rakam, ölçü etiketi, logo, marka, filigran, tabela, sahte mühür, pseudo-text, UI, HUD, teknik açıklama kutusu, gereksiz ok, stok görsel damgası, ürün katalog kompozisyonu, kolaj, havada yüzen parça, rastgele geometrik dekor, konuyla ilgisiz el aleti, konuyla ilgisiz kablo veya boru, oyuncak görünümü, plastik doku, aşırı neon, bozuk perspektif, deforme geometri, eksik yapı elemanı, fiziksel olarak imkansız bağlantı, tekrar eden obje, bozuk el, fazla parmak, deforme insan, gereksiz kalabalık, aşırı lens efekti, aşırı alan derinliği, aşırı glow, aşırı doygunluk.";

export function buildPrimaryPrompt(node: IndexedBinaNode, brief: CanonicalBriefV2): string {
  return [
    `KONU: ${node.plainLabel}`,
    `İÇERİK: ${node.summary}`,
    `GÖRSELİN ROLÜ: PRIMARY / HERO / CARD`,
    `GÖRSELİN AMACI: Kullanıcı bu görsele baktığında ${brief.primaryFocus.toLowerCase()} durumu ilk bakışta net anlaşılmalı.`,
    `MOD: ${brief.primaryMode}`,
    `SAHNE: Gerçekçi şantiye veya mimari bağlam. 16:9 yatay kompozisyon. Tek ana odak, kart boyutunda anlaşılır. Kolaj veya havada yüzen parça yok.`,
    `MUTLAKA GÖRÜNSÜN: ${brief.primaryMustShow.join(", ")}.`,
    `FİZİKSEL DOĞRULUK: Malzemeler, birleşimler, taşıyıcı sistemler ve montaj gerçek inşaat pratiğine uygun olsun.`,
    `KALİTE: Profesyonel mimari/inşaat görselleştirmesi. Gerçekçi malzemeler, doğal kontrollü ışık.`,
    `KESİNLİKLE OLMASIN: ${brief.primaryMustNotShow.join(", ")}, hiçbir yazı, harf, rakam, logo, marka, filigran, tabela, etiket, ölçü rakamı, pseudo-text, UI, HUD, açıklama oku.`,
  ].join("\n");
}

export function buildSecondaryPrompt(node: IndexedBinaNode, brief: CanonicalBriefV2): string {
  return [
    `KONU: ${node.plainLabel}`,
    `GÖRSELİN ROLÜ: SECONDARY / ARTICLE DETAIL`,
    `PRIMARY GÖRSELİN ÖĞRETTİĞİ: ${brief.primaryFocus}`,
    `BU İKİNCİ GÖRSELİN FARKLI AMACI: ${brief.secondaryFocus}`,
    `ÖNEMLİ: Bu görsel primary'nin yeniden kadrajlanmış veya yakınlaştırılmış kopyası OLMAYACAK. Aynı konunun tamamlayıcı ve farklı teknik detayını gösterecek.`,
    `MOD: ${brief.secondaryMode}`,
    `SAHNE: 16:9 yatay teknik detay veya kesit sahnesi.`,
    `MUTLAKA GÖRÜNSÜN: ${brief.secondaryMustShow.join(", ")}.`,
    `PRIMARY'DEN FARK: ${brief.secondaryDifference}`,
    `FİZİKSEL DOĞRULUK: Gerçekçi mühendislik ilişkisi, doğru malzeme katmanları, sıfır yapay süsleme.`,
    `KESİNLİKLE OLMASIN: ${brief.secondaryMustNotShow.join(", ")}, hiçbir yazı, harf, rakam, logo, marka, filigran, etiket, ölçü, UI, HUD, kolaj, havada yüzen obje.`,
  ].join("\n");
}

function run() {
  const allNodes = getAllIndexedBinaNodes();
  const canonicalNodes = allNodes.filter((n) => n.id !== "root");

  console.log(`Canonical düğüm sayısı: ${canonicalNodes.length}`);

  const inventory: any[] = [];

  for (const node of canonicalNodes) {
    const brief = CANONICAL_BRIEFS_V2[node.id];
    if (!brief) {
      console.warn(`Brief bulunamadı: ${node.id}`);
      continue;
    }

    const primaryPromptTr = buildPrimaryPrompt(node, brief);
    const secondaryPromptTr = buildSecondaryPrompt(node, brief);

    const primaryAltTr = `${node.plainLabel} — ${brief.primaryFocus}`;
    const secondaryAltTr = `${node.plainLabel} (Teknik Detay) — ${brief.secondaryFocus}`;

    inventory.push({
      id: node.id,
      slugPath: node.slugPath,
      label: node.plainLabel,
      summary: node.summary,
      phaseId: node.branchId,
      depth: node.depth,
      parentSlugPath: node.parentSlugPath,
      childIds: node.childIds,

      // Dosya yolları
      primaryTargetWebp: `/bina-asamalari/topics/${node.id}.webp`,
      secondaryTargetWebp: `/bina-asamalari/details/${node.id}.webp`,
      legacySvgCard: `/bina-asamalari/topics/${node.id}.svg`,

      // PRIMARY
      primaryMode: brief.primaryMode,
      primaryVisualPurpose: `Kullanıcı bu görsele baktığında ${brief.primaryFocus.toLowerCase()} durumunu net olarak anlamalı.`,
      primaryMustShow: brief.primaryMustShow,
      primaryMustNotShow: brief.primaryMustNotShow,
      primaryPromptTr,
      primaryAltTr,

      // SECONDARY
      secondaryMode: brief.secondaryMode,
      secondaryPlacement: brief.secondaryPlacement,
      secondaryVisualPurpose: `Primary görselin göstermediği teknik bilgiyi öğretmek: ${brief.secondaryFocus.toLowerCase()}`,
      secondaryMustShow: brief.secondaryMustShow,
      secondaryMustNotShow: brief.secondaryMustNotShow,
      secondaryPromptTr,
      secondaryAltTr,
      secondaryDifference: brief.secondaryDifference,

      // Ortak negatif
      negativePromptTr: MASTER_NEGATIVE_PROMPT,

      // Statü
      status: "planned",
    });
  }

  const outPath = path.resolve(process.cwd(), "bina-gorsel-envanteri.json");
  fs.writeFileSync(outPath, JSON.stringify(inventory, null, 2), "utf-8");
  console.log(`Envanter V2 başarıyla yazıldı: ${outPath} (${inventory.length} canonical kayıt)`);
}

if (process.argv[1]?.includes("build-bina-inventory")) {
  run();
}
