import type { BinaGuideSource } from "./types";

export const SOURCE_LEDGER = {
  tbdy2018: {
    title: "Türkiye Bina Deprem Yönetmeliği",
    shortCode: "TBDY 2018",
    type: "official-guide",
    url: "https://www.afad.gov.tr/turkiye-bina-deprem-yonetmeligi",
    note: "Deprem etkisi, taşıyıcı sistem davranışı ve temel tasarımı için ana teknik çerçeve.",
  },
  tdth: {
    title: "Türkiye Deprem Tehlike Haritaları İnteraktif Web Uygulaması",
    shortCode: "TDTH",
    type: "official-tool",
    url: "https://tdth.afad.gov.tr/",
    note: "Ss, S1, PGA ve deprem düzeyi girdilerinin resmi kaynağı.",
  },
  ts500: {
    title: "TS 500 Betonarme Yapıların Tasarım ve Yapım Kuralları",
    shortCode: "TS 500",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Betonarme kesit, malzeme, pas payı ve temel kararlarının ana standardı.",
  },
  tsEn206: {
    title: "TS EN 206 Beton - Özellik, Performans, İmalat ve Uygunluk",
    shortCode: "TS EN 206",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Hazır beton sınıfı, kıvam ve dayanım kabul zincirinde referans alınır.",
  },
  tsEn13670: {
    title: "TS EN 13670 Beton Yapıların Uygulanması",
    shortCode: "TS EN 13670",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Betonarme imalatın uygulama, tolerans ve kalite güvence çerçevesi.",
  },
  tsEn1536: {
    title: "TS EN 1536 Özel Geoteknik İşler - Fore Kazıklar",
    shortCode: "TS EN 1536",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Fore kazık uygulamalarında imalat ve kalite kontrol esaslarını tanımlar.",
  },
  tsEn1538: {
    title: "TS EN 1538 Özel Geoteknik İşler - Diyafram Duvarlar",
    shortCode: "TS EN 1538",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Derin kazı çevreleme sistemlerinde kalite ve imalat yaklaşımı için referans.",
  },
  imarKanunu: {
    title: "3194 sayılı İmar Kanunu",
    shortCode: "3194 sayılı İmar Kanunu",
    type: "regulation",
    url: "https://www.mevzuat.gov.tr/",
    note: "Ruhsat, yapı koşulları ve imar disiplininin ana mevzuat çatısı.",
  },
  yapiDenetim: {
    title: "4708 sayılı Yapı Denetimi Hakkında Kanun",
    shortCode: "4708 sayılı Kanun",
    type: "regulation",
    url: "https://www.mevzuat.gov.tr/",
    note: "Denetim zinciri, kontrol sorumluluğu ve uygulama izleme sistemi için referans.",
  },
  planliAlanlar: {
    title: "Planlı Alanlar İmar Yönetmeliği",
    shortCode: "Planlı Alanlar İmar Yönetmeliği",
    type: "regulation",
    url: "https://www.mevzuat.gov.tr/",
    note: "Ruhsat eki proje setleri, yapı kullanma izinleri ve mimari teslim çerçevesi için kullanılır.",
  },
  yanginYonetmeligi: {
    title: "Binaların Yangından Korunması Hakkında Yönetmelik",
    shortCode: "Yangın Yönetmeliği",
    type: "regulation",
    url: "https://www.mevzuat.gov.tr/",
    note: "Yangın tesisatı, kaçış, yangın zonları ve aktif sistem gereksinimlerinin resmi çerçevesi.",
  },
  enerjiPerformansi: {
    title: "Binalarda Enerji Performansı Yönetmeliği",
    shortCode: "BEP Yönetmeliği",
    type: "regulation",
    url: "https://www.mevzuat.gov.tr/",
    note: "Bina kabuğu ve enerji performansı kararlarında resmi mevzuat kaynağı.",
  },
  ts825: {
    title: "TS 825 Binalarda Isı Yalıtım Kuralları",
    shortCode: "TS 825",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Isı yalıtımı kalınlığı, kabuk performansı ve enerji dengesi için temel standart.",
  },
  tsEn13914: {
    title: "TS EN 13914 Sıva Tasarımı, Hazırlığı ve Uygulama Prensipleri",
    shortCode: "TS EN 13914",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "İç ve dış sıva sistemlerinde yüzey hazırlığı ve uygulama yaklaşımını çerçeveler.",
  },
  tsEn12004: {
    title: "TS EN 12004 Seramik Yapıştırıcıları",
    shortCode: "TS EN 12004",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Seramik ve karo yapıştırıcılarının performans sınıfı ve kullanım alanı için referans.",
  },
  tsEn13329: {
    title: "TS EN 13329 Laminat Zemin Kaplamaları",
    shortCode: "TS EN 13329",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Laminat zeminlerin aşınma, sınıf ve kullanım koşulları için temel referans.",
  },
  tsEn806: {
    title: "TS EN 806 Binalarda İçme ve Kullanma Suyu Tesisatı",
    shortCode: "TS EN 806",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Temiz su dağıtım sistemlerinde hijyen, basınç ve montaj yaklaşımı için referans.",
  },
  tsEn12056: {
    title: "TS EN 12056 Binalarda Cazibeli Atık Su Drenaj Sistemleri",
    shortCode: "TS EN 12056",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Pis su, havalık ve atık su eğim kararlarının tasarım çerçevesi.",
  },
  tsHd60364: {
    title: "TS HD 60364 Alçak Gerilim Elektrik Tesisleri",
    shortCode: "TS HD 60364",
    type: "standard",
    url: "https://www.tse.org.tr/",
    note: "Elektrik tesislerinde koruma, kablolama ve pano kararları için temel seri.",
  },
  afadHazard: {
    title: "AFAD Resmi Deprem ve Yapı Güvenliği Kaynakları",
    shortCode: "AFAD",
    type: "official-guide",
    url: "https://www.afad.gov.tr/",
    note: "Deprem tehlikesi, yapı güvenliği ve afet odaklı resmi açıklamalar için çatı kaynak.",
  },
} as const satisfies Record<string, BinaGuideSource>;

export const BRANCH_SOURCE_LEDGER = {
  "proje-hazirlik": [
    SOURCE_LEDGER.planliAlanlar,
    SOURCE_LEDGER.imarKanunu,
    SOURCE_LEDGER.yapiDenetim,
    SOURCE_LEDGER.tbdy2018,
    SOURCE_LEDGER.ts500,
  ],
  "kazi-temel": [
    SOURCE_LEDGER.tbdy2018,
    SOURCE_LEDGER.ts500,
    SOURCE_LEDGER.tsEn1536,
    SOURCE_LEDGER.tsEn1538,
    SOURCE_LEDGER.afadHazard,
  ],
  "kaba-insaat": [
    SOURCE_LEDGER.tbdy2018,
    SOURCE_LEDGER.ts500,
    SOURCE_LEDGER.tsEn206,
    SOURCE_LEDGER.tsEn13670,
  ],
  "ince-isler": [
    SOURCE_LEDGER.ts825,
    SOURCE_LEDGER.enerjiPerformansi,
    SOURCE_LEDGER.tsEn13914,
    SOURCE_LEDGER.tsEn12004,
    SOURCE_LEDGER.tsEn13329,
  ],
  "tesisat-isleri": [
    SOURCE_LEDGER.tsEn806,
    SOURCE_LEDGER.tsEn12056,
    SOURCE_LEDGER.tsHd60364,
    SOURCE_LEDGER.yanginYonetmeligi,
    SOURCE_LEDGER.ts825,
  ],
  "peyzaj-teslim": [
    SOURCE_LEDGER.planliAlanlar,
    SOURCE_LEDGER.imarKanunu,
    SOURCE_LEDGER.yapiDenetim,
    SOURCE_LEDGER.yanginYonetmeligi,
  ],
} as const satisfies Record<string, readonly BinaGuideSource[]>;
